# Generated by Django 2.2.8 on 2020-05-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_assist_datahub', '0001_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitlementcard',
            name='household',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='household',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='cash_plan',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='entitlement',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='household',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='target_population',
        ),
        migrations.RemoveField(
            model_name='targetpopulation',
            name='households',
        ),
        migrations.DeleteModel(
            name='CashPlan',
        ),
        migrations.DeleteModel(
            name='EntitlementCard',
        ),
        migrations.DeleteModel(
            name='Household',
        ),
        migrations.DeleteModel(
            name='Individual',
        ),
        migrations.DeleteModel(
            name='PaymentEntitlement',
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='TargetPopulation',
        ),
    ]
