# Generated by Django 3.2.25 on 2024-07-10 14:23
from decimal import Decimal

from django.db import migrations, models


def migrate_payments_delivered_quantity(apps, schema_editor):
    Payment = apps.get_model("payment", "Payment")

    not_distributed_payments = Payment.objects.filter(status="Not Distributed", delivered_quantity__isnull=True)
    for payment in not_distributed_payments:
        payment.delivered_quantity = Decimal(0)
        payment.delivered_quantity_usd = Decimal(0)

    Payment.objects.bulk_update(not_distributed_payments, ["delivered_quantity", "delivered_quantity_usd"])


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0137_migration"),
    ]

    operations = [
        migrations.RunPython(migrate_payments_delivered_quantity, migrations.RunPython.noop),
    ]
