PAYMENT_PLAN_SENT_FOR_APPROVAL = "payment.plan.sent_for_approval"
PAYMENT_PLAN_APPROVED = "payment.plan.approved"
PAYMENT_PLAN_AUTHORIZED = "payment.plan.authorized"
PAYMENT_PLAN_RELEASED = "payment.plan.released"

PDU_ONLINE_EDIT_SENT_FOR_APPROVAL = "pdu.online_edit.sent_for_approval"
PDU_ONLINE_EDIT_APPROVED = "pdu.online_edit.approved"
PDU_ONLINE_EDIT_SENT_BACK = "pdu.online_edit.sent_back"

RENDERED_EMAIL_SENT = "email.rendered.sent"

PAYMENT_PLAN_ACTION_TO_BITCASTER_EVENT = {
    "SEND_FOR_APPROVAL": PAYMENT_PLAN_SENT_FOR_APPROVAL,
    "APPROVE": PAYMENT_PLAN_APPROVED,
    "AUTHORIZE": PAYMENT_PLAN_AUTHORIZED,
    "REVIEW": PAYMENT_PLAN_RELEASED,
}

PDU_ONLINE_EDIT_ACTION_TO_BITCASTER_EVENT = {
    "SEND_FOR_APPROVAL": PDU_ONLINE_EDIT_SENT_FOR_APPROVAL,
    "APPROVE": PDU_ONLINE_EDIT_APPROVED,
    "SEND_BACK": PDU_ONLINE_EDIT_SENT_BACK,
}
