SPECTACULAR_SETTINGS = {
    "TITLE": "HOPE API",
    "DESCRIPTION": "HOPE REST AOI Swagger Documentation",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": True,
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
    "ENUM_ADD_EXPLICIT_BLANK_NULL_CHOICE": False,
}
