from hct_mis_api.config.env import env
from hct_mis_api.config.settings import ENV

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")

EMAIL_BACKEND = env("EMAIL_BACKEND")
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS")

MAILJET_API_KEY = env("MAILJET_API_KEY")
MAILJET_SECRET_KEY = env("MAILJET_SECRET_KEY")
CATCH_ALL_EMAIL = env.list("CATCH_ALL_EMAIL")
DEFAULT_EMAIL_DISPLAY = env("DEFAULT_EMAIL_DISPLAY")
DEFAULT_EMAIL = env("DEFAULT_EMAIL")

if ENV != "prod":
    EMAIL_SUBJECT_PREFIX = f"{ENV}"
else:
    EMAIL_SUBJECT_PREFIX = ""

ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 7
