# Generated by Django 3.2.25 on 2024-09-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodic_data_update', '0006_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicdataupdatetemplate',
            name='filters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
