---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kpi-media-pvc
  labels:
    app: {{ include "kobo.labels.app" . }}
    component: kpi
    chart: {{ include "kobo.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: "{{ .Values.global.storageClass }}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
