from hct_mis_api.apps.core.field_attributes.fields_types import (
    _DELIVERY_MECHANISM_DATA,
    _INDIVIDUAL,
    TYPE_DATE,
    TYPE_STRING,
    Scope,
)
from hct_mis_api.apps.core.field_attributes.lookup_functions import (
    get_debit_card_issuer,
    get_debit_card_number,
)
from hct_mis_api.apps.payment.delivery_mechanisms import DeliveryMechanismChoices

PAYMENT_CHANNEL_FIELDS_ATTRIBUTES = [
    {
        "id": "22085a8d-205d-42a9-b5b3-951b51f11915",
        "type": TYPE_STRING,
        "name": "account_holder_name",  # TODO MB bank account info
        "lookup": "account_holder_name",
        "label": {"English(EN)": "Account holder name"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "account_holder_name_i_c",
        "scope": [Scope.XLSX, Scope.KOBO_IMPORT],
    },
    {
        "id": "e9d964b9-aa85-4a0f-b1eb-4755bdad7592",
        "type": TYPE_STRING,
        "name": "bank_branch_name",  # TODO MB bank account info
        "lookup": "bank_branch_name",
        "label": {"English(EN)": "Bank branch name"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "bank_branch_name_i_c",
        "scope": [Scope.XLSX, Scope.KOBO_IMPORT],
    },
    {
        "id": "e5766962-1455-4ebc-8fad-fc89cdde792b",
        "type": TYPE_STRING,
        "name": "bank_name",  # TODO MB bank account info
        "lookup": "bank_name",
        "required": False,
        "label": {"English(EN)": "Bank name"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "bank_name_i_c",
        "scope": [Scope.XLSX],
    },
    {
        "id": "3d6a45f3-d3f7-48a0-801b-7a98c0da517a",
        "type": TYPE_STRING,
        "name": "bank_account_number",  # TODO MB bank account info
        "lookup": "bank_account_number",
        "required": False,
        "label": {"English(EN)": "Bank account number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "bank_account_number_i_c",
        "scope": [Scope.XLSX],
    },
    {
        "id": "72e79eec-0c10-42d9-9c25-86162232a389",
        "type": TYPE_STRING,
        "name": "debit_card_issuer",  # TODO MB bank account info
        "lookup": "debit_card_issuer",
        "required": False,
        "label": {"English(EN)": "Debit Card Issuer"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "debit_card_issuer_i_c",
        "scope": [Scope.XLSX],
        "lookup_function": get_debit_card_issuer,
    },
    {
        "id": "4a2ae111-3450-41a4-8d26-5eb20f4e233c",
        "type": TYPE_STRING,
        "name": "debit_card_number",  # TODO MB bank account info
        "lookup": "debit_card_number",
        "required": False,
        "label": {"English(EN)": "Debit card number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "debit_card_number_i_c",
        "scope": [Scope.XLSX],
        "lookup_function": get_debit_card_number,
    },
    {
        "id": "4a2ae111-3450-41a4-8d26-5eb20f4e233c",
        "type": TYPE_STRING,
        "name": "payment_delivery_phone_no",  # TODO MB this an Individual Field
        "lookup": "payment_delivery_phone_no",
        "required": False,
        "label": {"English(EN)": "Payment delivery phone number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "payment_delivery_phone_no_i_c",
        "scope": [Scope.XLSX, Scope.INDIVIDUAL_UPDATE, Scope.TARGETING],
    },
    {
        "id": "584c47fa-de3f-40a5-9889-251c7720c660",
        "type": TYPE_STRING,
        "name": "card_number_atm_card",
        "lookup": "card_number_atm_card",
        "required": False,
        "label": {"English(EN)": "Card number (ATM card)"},
        "hint": "",
        "choices": [],
        "associated_with": _DELIVERY_MECHANISM_DATA,
        "required_for_payment": True,
        "unique_for_payment": True,
        "delivery_mechanisms": [DeliveryMechanismChoices.DELIVERY_TYPE_ATM_CARD],
        "xlsx_field": "card_number_atm_card_i_c",
        "scope": [Scope.XLSX, Scope.DELIVERY_MECHANISM, Scope.INDIVIDUAL_UPDATE],
    },
    {
        "id": "996d501d-35a3-4884-85a1-2ced5262a1f3",
        "type": TYPE_DATE,
        "name": "card_expiry_date_atm_card",
        "lookup": "card_expiry_date_atm_card",
        "required": False,
        "label": {"English(EN)": "Card expiry date (ATM card)"},
        "hint": "",
        "choices": [],
        "associated_with": _DELIVERY_MECHANISM_DATA,
        "required_for_payment": True,
        "unique_for_payment": True,
        "delivery_mechanisms": [DeliveryMechanismChoices.DELIVERY_TYPE_ATM_CARD],
        "xlsx_field": "card_expiry_date_atm_card_i_c",
        "scope": [Scope.XLSX, Scope.DELIVERY_MECHANISM, Scope.INDIVIDUAL_UPDATE],
    },
    {
        "id": "91560be8-be92-4aa0-bcf5-c53e42daef76",
        "type": TYPE_STRING,
        "name": "name_of_cardholder_atm_card",
        "lookup": "name_of_cardholder_atm_card",
        "required": False,
        "label": {"English(EN)": "Name of cardholder (ATM card)"},
        "hint": "",
        "choices": [],
        "associated_with": _DELIVERY_MECHANISM_DATA,
        "required_for_payment": True,
        "unique_for_payment": True,
        "delivery_mechanisms": [DeliveryMechanismChoices.DELIVERY_TYPE_ATM_CARD],
        "xlsx_field": "name_of_cardholder_atm_card_i_c",
        "scope": [Scope.XLSX, Scope.DELIVERY_MECHANISM, Scope.INDIVIDUAL_UPDATE],
    },
]
