from hct_mis_api.apps.core.field_attributes.fields_types import (
    _DELIVERY_MECHANISM_DATA,
    _INDIVIDUAL,
    TYPE_DATE,
    TYPE_STRING,
    Scope,
)
from hct_mis_api.apps.core.field_attributes.lookup_functions import (
    get_debit_card_issuer,
    get_debit_card_number,
)
from hct_mis_api.apps.payment.delivery_mechanisms import DeliveryMechanismChoices

PAYMENT_CHANNEL_FIELDS_ATTRIBUTES = [
    {
        "id": "22085a8d-205d-42a9-b5b3-951b51f11915",
        "type": TYPE_STRING,
        "name": "account_holder_name",
        "lookup": "account_holder_name",
        "label": {"English(EN)": "Account holder name"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "account_holder_name_i_c",
        "scope": [Scope.XLSX, Scope.KOBO_IMPORT],
    },
    {
        "id": "e9d964b9-aa85-4a0f-b1eb-4755bdad7592",
        "type": TYPE_STRING,
        "name": "bank_branch_name",
        "lookup": "bank_branch_name",
        "label": {"English(EN)": "Bank branch name"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "bank_branch_name_i_c",
        "scope": [Scope.XLSX, Scope.KOBO_IMPORT],
    },
    {
        "id": "e5766962-1455-4ebc-8fad-fc89cdde792b",
        "type": TYPE_STRING,
        "name": "bank_name",
        "lookup": "bank_name",
        "required": False,
        "label": {"English(EN)": "Bank name"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "bank_name_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE],
    },
    {
        "id": "3d6a45f3-d3f7-48a0-801b-7a98c0da517a",
        "type": TYPE_STRING,
        "name": "bank_account_number",
        "lookup": "bank_account_number",
        "required": False,
        "label": {"English(EN)": "Bank account number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "bank_account_number_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE],
    },
    {
        "id": "72e79eec-0c10-42d9-9c25-86162232a389",
        "type": TYPE_STRING,
        "name": "debit_card_issuer",
        "lookup": "debit_card_issuer",
        "required": False,
        "label": {"English(EN)": "Debit Card Issuer"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "debit_card_issuer_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE],
        "lookup_function": get_debit_card_issuer,
    },
    {
        "id": "4a2ae111-3450-41a4-8d26-5eb20f4e233c",
        "type": TYPE_STRING,
        "name": "debit_card_number",
        "lookup": "debit_card_number",
        "required": False,
        "label": {"English(EN)": "Debit card number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "debit_card_number_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE],
        "lookup_function": get_debit_card_number,
    },
    {
        "id": "4a2ae111-3450-41a4-8d26-5eb20f4e233c",
        "type": TYPE_STRING,
        "name": "payment_delivery_phone_no",
        "lookup": "payment_delivery_phone_no",
        "required": False,
        "label": {"English(EN)": "Payment delivery phone number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "payment_delivery_phone_no_i_c",
        "scope": [Scope.XLSX, Scope.INDIVIDUAL_UPDATE, Scope.TARGETING, Scope.XLSX_PEOPLE],
    },
    {
        "id": "584c47fa-de3f-40a5-9889-251c7720c660",
        "type": TYPE_STRING,
        "name": "card_number_atm_card",
        "lookup": "card_number_atm_card",
        "required": False,
        "label": {"English(EN)": "Card number (ATM card)"},
        "hint": "",
        "choices": [],
        "associated_with": _DELIVERY_MECHANISM_DATA,
        "required_for_payment": True,
        "unique_for_payment": True,
        "delivery_mechanisms": [DeliveryMechanismChoices.DELIVERY_TYPE_ATM_CARD],
        "xlsx_field": "card_number_atm_card_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE, Scope.DELIVERY_MECHANISM],
    },
    {
        "id": "996d501d-35a3-4884-85a1-2ced5262a1f3",
        "type": TYPE_DATE,
        "name": "card_expiry_date_atm_card",
        "lookup": "card_expiry_date_atm_card",
        "required": False,
        "label": {"English(EN)": "Card expiry date (ATM card)"},
        "hint": "",
        "choices": [],
        "associated_with": _DELIVERY_MECHANISM_DATA,
        "required_for_payment": True,
        "unique_for_payment": True,
        "delivery_mechanisms": [DeliveryMechanismChoices.DELIVERY_TYPE_ATM_CARD],
        "xlsx_field": "card_expiry_date_atm_card_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE, Scope.DELIVERY_MECHANISM],
    },
    {
        "id": "91560be8-be92-4aa0-bcf5-c53e42daef76",
        "type": TYPE_STRING,
        "name": "name_of_cardholder_atm_card",
        "lookup": "name_of_cardholder_atm_card",
        "required": False,
        "label": {"English(EN)": "Name of cardholder (ATM card)"},
        "hint": "",
        "choices": [],
        "associated_with": _DELIVERY_MECHANISM_DATA,
        "required_for_payment": True,
        "unique_for_payment": True,
        "delivery_mechanisms": [DeliveryMechanismChoices.DELIVERY_TYPE_ATM_CARD],
        "xlsx_field": "name_of_cardholder_atm_card_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE, Scope.DELIVERY_MECHANISM],
    },
    {
        "id": "216feefb-9fda-4aee-bb75-1028d7ff83f9",
        "type": TYPE_STRING,
        "name": "card_number_deposit_to_card",
        "lookup": "card_number_deposit_to_card",
        "required": False,
        "label": {"English(EN)": "Card Number (Deposit to Card)"},
        "hint": "",
        "choices": [],
        "associated_with": _DELIVERY_MECHANISM_DATA,
        "required_for_payment": True,
        "unique_for_payment": True,
        "delivery_mechanisms": [DeliveryMechanismChoices.DELIVERY_TYPE_DEPOSIT_TO_CARD],
        "xlsx_field": "card_number_deposit_to_card_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE, Scope.DELIVERY_MECHANISM],
    },
    {
        "id": "a51dd5f3-9785-4720-884c-1ce9fccf335e",
        "type": TYPE_STRING,
        "name": "delivery_phone_number_mobile_money",
        "lookup": "delivery_phone_number_mobile_money",
        "required": False,
        "label": {"English(EN)": "Delivery Phone Number (Mobile Money)"},
        "hint": "",
        "choices": [],
        "associated_with": _DELIVERY_MECHANISM_DATA,
        "required_for_payment": True,
        "unique_for_payment": True,
        "delivery_mechanisms": [DeliveryMechanismChoices.DELIVERY_TYPE_MOBILE_MONEY],
        "xlsx_field": "delivery_phone_number_mobile_money_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE, Scope.DELIVERY_MECHANISM],
    },
    {
        "id": "c50c3b71-0509-468b-a123-55e582e1012e",
        "type": TYPE_STRING,
        "name": "provider_mobile_money",
        "lookup": "provider_mobile_money",
        "required": False,
        "label": {"English(EN)": "Provider (Mobile Money)"},
        "hint": "",
        "choices": [],
        "associated_with": _DELIVERY_MECHANISM_DATA,
        "required_for_payment": True,
        "unique_for_payment": True,
        "delivery_mechanisms": [DeliveryMechanismChoices.DELIVERY_TYPE_MOBILE_MONEY],
        "xlsx_field": "provider_mobile_money_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE, Scope.DELIVERY_MECHANISM],
    },
    {
        "id": "45f7b6aa-f190-406e-aaec-44ea96fc5ab6",
        "type": TYPE_STRING,
        "name": "bank_name_transfer_to_account",
        "lookup": "bank_name_transfer_to_account",
        "required": False,
        "label": {"English(EN)": "Bank Name (Transfer to Account)"},
        "hint": "",
        "choices": [],
        "associated_with": _DELIVERY_MECHANISM_DATA,
        "required_for_payment": True,
        "unique_for_payment": False,
        "delivery_mechanisms": [DeliveryMechanismChoices.DELIVERY_TYPE_TRANSFER_TO_ACCOUNT],
        "xlsx_field": "bank_name_transfer_to_account_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE, Scope.DELIVERY_MECHANISM],
    },
    {
        "id": "4a49196e-a931-44c2-801c-91d3a89d269c",
        "type": TYPE_STRING,
        "name": "bank_account_number_transfer_to_account",
        "lookup": "bank_account_number_transfer_to_account",
        "required": False,
        "label": {"English(EN)": "Bank Account Number (Transfer to Account)"},
        "hint": "",
        "choices": [],
        "associated_with": _DELIVERY_MECHANISM_DATA,
        "required_for_payment": True,
        "unique_for_payment": True,
        "delivery_mechanisms": [DeliveryMechanismChoices.DELIVERY_TYPE_TRANSFER_TO_ACCOUNT],
        "xlsx_field": "bank_account_number_transfer_to_account_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE, Scope.DELIVERY_MECHANISM],
    },
    {
        "id": "be0a5e78-7cb5-401e-8b96-3a4bac26967f",
        "type": TYPE_STRING,
        "name": "mobile_phone_number_cash_over_the_counter",
        "lookup": "mobile_phone_number_cash_over_the_counter",
        "required": False,
        "label": {"English(EN)": "Mobile Phone Number (Cash Over the Counter)"},
        "hint": "",
        "choices": [],
        "associated_with": _DELIVERY_MECHANISM_DATA,
        "required_for_payment": True,
        "unique_for_payment": False,
        "delivery_mechanisms": [DeliveryMechanismChoices.DELIVERY_TYPE_CASH_OVER_THE_COUNTER],
        "xlsx_field": "mobile_phone_number_cash_over_the_counter_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE, Scope.DELIVERY_MECHANISM],
    },
    {
        "id": "52d1044c-8bf7-4526-985d-541cf1850c30",
        "type": TYPE_STRING,
        "name": "wallet_name_transfer_to_digital_wallet",
        "lookup": "wallet_name_transfer_to_digital_wallet",
        "label": {"English(EN)": "Wallet Name"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _DELIVERY_MECHANISM_DATA,
        "required_for_payment": False,
        "unique_for_payment": False,
        "delivery_mechanisms": [DeliveryMechanismChoices.DELIVERY_TYPE_TRANSFER_TO_DIGITAL_WALLET],
        "xlsx_field": "wallet_name_transfer_to_digital_wallet_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE, Scope.DELIVERY_MECHANISM],
    },
    {
        "id": "af08e8a7-890a-4467-a989-3a2173e4de2e",
        "type": TYPE_STRING,
        "name": "blockchain_name_transfer_to_digital_wallet",
        "lookup": "blockchain_name_transfer_to_digital_wallet",
        "label": {"English(EN)": "Blockchain Name"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _DELIVERY_MECHANISM_DATA,
        "required_for_payment": True,
        "unique_for_payment": True,
        "delivery_mechanisms": [DeliveryMechanismChoices.DELIVERY_TYPE_TRANSFER_TO_DIGITAL_WALLET],
        "xlsx_field": "blockchain_name_transfer_to_digital_wallet_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE, Scope.DELIVERY_MECHANISM],
    },
    {
        "id": "15d35efa-8f36-4a40-b9ed-a7812a665e01",
        "type": TYPE_STRING,
        "name": "wallet_address_transfer_to_digital_wallet",
        "lookup": "wallet_address_transfer_to_digital_wallet",
        "label": {"English(EN)": "Wallet Address"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _DELIVERY_MECHANISM_DATA,
        "required_for_payment": True,
        "unique_for_payment": True,
        "delivery_mechanisms": [DeliveryMechanismChoices.DELIVERY_TYPE_TRANSFER_TO_DIGITAL_WALLET],
        "xlsx_field": "wallet_address_transfer_to_digital_wallet_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE, Scope.DELIVERY_MECHANISM],
    },
]
