from hct_mis_api.apps.core.attributes_qet_queries import (
    age_to_birth_date_query,
    get_birth_certificate_document_number_query,
    get_birth_certificate_issuer_query,
    get_drivers_license_document_number_query,
    get_drivers_licensee_issuer_query,
    get_electoral_card_document_number_query,
    get_electoral_card_issuer_query,
    get_national_id_document_number_query,
    get_national_id_issuer_query,
    get_national_passport_document_number_query,
    get_national_passport_issuer_query,
    get_other_document_number_query,
    get_other_issuer_query,
    get_scope_id_issuer_query,
    get_scope_id_number_query,
    get_tax_id_document_number_query,
    get_tax_id_issuer_query,
    get_unhcr_id_issuer_query,
    get_unhcr_id_number_query,
)
from hct_mis_api.apps.core.countries import Countries
from hct_mis_api.apps.core.currencies import CURRENCY_CHOICES
from hct_mis_api.apps.core.field_attributes.fields_types import (
    _INDIVIDUAL,
    TYPE_BOOL,
    TYPE_DATE,
    TYPE_GEOPOINT,
    TYPE_IMAGE,
    TYPE_INTEGER,
    TYPE_LIST_OF_IDS,
    TYPE_SELECT_MANY,
    TYPE_SELECT_ONE,
    TYPE_STRING,
    Scope,
)
from hct_mis_api.apps.core.field_attributes.lookup_functions import (
    get_birth_certificate_issuer,
    get_birth_certificate_no,
    get_debit_card_issuer,
    get_debit_card_number,
    get_drivers_license_issuer,
    get_drivers_license_no,
    get_electoral_card_issuer,
    get_electoral_card_no,
    get_national_id_issuer,
    get_national_id_no,
    get_national_passport_issuer,
    get_national_passport_no,
    get_other_id_issuer,
    get_other_id_no,
    get_scope_id_issuer,
    get_scope_id_no,
    get_tax_id_issuer,
    get_tax_id_no,
    get_unhcr_id_issuer,
    get_unhcr_id_no,
)
from hct_mis_api.apps.core.languages import Languages
from hct_mis_api.apps.geo.models import Area, Country
from hct_mis_api.apps.household.models import (
    BLANK,
    DATA_SHARING_CHOICES,
    DISABILITY_CHOICES,
    MARITAL_STATUS_CHOICE,
    OBSERVED_DISABILITY_CHOICE,
    ORG_ENUMERATOR_CHOICES,
    REGISTRATION_METHOD_CHOICES,
    RELATIONSHIP_CHOICE,
    RESIDENCE_STATUS_CHOICE,
    SEVERITY_OF_DISABILITY_CHOICES,
    SEX_CHOICE,
    WORK_STATUS_CHOICE,
)

PEOPLE_FIELDS_ATTRIBUTES = [
    {
        "id": "bec7a6b9-476d-48a8-8822-e24ae023df42",
        "type": TYPE_INTEGER,
        "name": "index_id",
        "lookup": "index_id",
        "required": True,
        "label": {"English(EN)": "Index ID"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_index_id",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "4a054660-ca29-4ccc-9223-3a0ed64c0488",
        "type": TYPE_STRING,
        "name": "full_name",
        "lookup": "full_name",
        "required": True,
        "label": {"English(EN)": "Full name"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_full_name_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "b927edd1-0291-4a27-8dec-1adbd0c466ee",
        "type": TYPE_STRING,
        "name": "given_name",
        "lookup": "given_name",
        "required": False,
        "label": {"English(EN)": "Given name"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_given_name_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "cd7ff6f4-f1c5-4fc7-87f7-1ed4b5073bd2",
        "type": TYPE_STRING,
        "name": "middle_name",
        "lookup": "middle_name",
        "required": False,
        "label": {"English(EN)": "Middle name(s)"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_middle_name_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "e74f9c38-9976-44d3-82a4-6b2664b11da1",
        "type": TYPE_STRING,
        "name": "family_name",
        "lookup": "family_name",
        "required": False,
        "label": {"English(EN)": "Family name"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_family_name_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "eccc7005-d8b0-4573-a0af-222bbec305d4",
        "type": TYPE_SELECT_ONE,
        "name": "sex",
        "lookup": "sex",
        "required": True,
        "label": {"English(EN)": "Gender"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in SEX_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_gender_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "4dbfc94b-f139-4fb5-9a01-7178a774ca62",
        "type": TYPE_DATE,
        "name": "birth_date",
        "lookup": "birth_date",
        "required": True,
        "label": {"English(EN)": "Birth date"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_birth_date_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "79a5e22d-4c58-4884-b62c-cb03ec26aeba",
        "type": TYPE_BOOL,
        "name": "estimated_birth_date",
        "lookup": "estimated_birth_date",
        "required": True,
        "label": {"English(EN)": "Estimated birth date?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_estimated_birth_date_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "5136c014-2b85-43b5-ba1c-753a8b574bcf",
        "type": TYPE_IMAGE,
        "name": "photo",
        "lookup": "photo",
        "required": False,
        "label": {"English(EN)": "Individual's photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_photo_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "9f026563-2280-4541-9650-d099c4bba903",
        "type": TYPE_STRING,
        "name": "address",
        "lookup": "address",
        "required": False,
        "label": {"English(EN)": "Address"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_address_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "ea0adf6f-61cc-44b4-bca6-16980e1a591c",
        "type": TYPE_SELECT_ONE,
        "name": "country_origin",
        "lookup": "country_origin__iso_code3",
        "required": False,
        "label": {"English(EN)": "Country of Origin"},
        "hint": "country origin",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_country_origin_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "40456b87-2620-48c3-af13-19c2de31a655",
        "type": TYPE_SELECT_ONE,
        "name": "country",
        "lookup": "country__iso_code3",
        "required": True,
        "label": {"English(EN)": "Country of registration"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_country_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "b85054fb-0dce-4ac4-84ce-4c84f9cb5179",
        "type": TYPE_STRING,
        "name": "zip_code",
        "lookup": "zip_code",
        "required": False,
        "label": {"English(EN)": "Zip code"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_zip_code_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "c53ea58b-e7cf-4bf3-82d0-dec41f66ef3a",
        "type": TYPE_SELECT_ONE,
        "name": "admin1",
        "lookup": "admin1__p_code",
        "required": False,
        "label": {"English(EN)": "Social worker resides in which ${admin1_i_c}?"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Area.get_admin_areas_as_choices(1, *args, **kwargs),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_admin1_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "67ac9b44-cda7-42ee-ae47-640a30306d84",
        "type": TYPE_SELECT_ONE,
        "name": "admin2",
        "lookup": "admin2__p_code",
        "required": False,
        "label": {"English(EN)": "Social worker resides in which ${admin2_i_c}?"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Area.get_admin_areas_as_choices(2, *args, **kwargs),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_admin2_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "b124a9f1-a01e-4145-857a-931bdb6cd84d",
        "type": TYPE_SELECT_ONE,
        "name": "admin3",
        "lookup": "admin3__p_code",
        "required": False,
        "label": {"English(EN)": "Social worker resides in which ${admin3_i_c}?"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Area.get_admin_areas_as_choices(3, *args, **kwargs),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_admin3_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "722511ed-2f47-4e78-b963-56fc22ca5e71",
        "type": TYPE_SELECT_ONE,
        "name": "admin4",
        "lookup": "admin4__p_code",
        "required": False,
        "label": {"English(EN)": "Social worker resides in which ${admin4_i_c}?"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Area.get_admin_areas_as_choices(4, *args, **kwargs),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_admin4_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "f6a4dfb5-711c-4498-b286-cc4524abb778",
        "type": TYPE_SELECT_ONE,
        "name": "residence_status",
        "lookup": "residence_status",
        "required": False,
        "label": {"English(EN)": "Residence status"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in RESIDENCE_STATUS_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_residence_status_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "feeb6dc8-79e3-4278-abd3-0f7bf2f95000",
        "type": TYPE_BOOL,
        "name": "consent",
        "lookup": "consent",
        "required": False,
        "label": {"English(EN)": "Do you consent?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_consent_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "268e653a-2bb8-4570-aeea-72aa2f0c3f23",
        "type": TYPE_IMAGE,
        "name": "consent_sign",
        "lookup": "consent_sign",
        "required": False,
        "label": {"English(EN)": "Do you consent?"},
        "hint": "Ask the social worker to sign or do an X as acknowledgement",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_consent_sign_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "d2d62a29-096c-41f2-be34-ce97ce1222eb",
        "type": TYPE_GEOPOINT,
        "name": "geopoint",
        "lookup": "geopoint",
        "required": False,
        "label": {"English(EN)": "Geolocation"},
        "hint": "latitude and longitude of social worker",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_hh_geopoint_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "b8e02ee5-fb35-4e4d-b1f8-62a0b75f5995",
        "type": TYPE_STRING,
        "name": "unhcr_id",
        "lookup": "unhcr_id",
        "required": False,
        "label": {"English(EN)": "UNHCR Case ID"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_unhcr_id_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "7899b38c-545a-4ddb-b659-58f7bc6e0ceb",
        "type": TYPE_BOOL,
        "name": "returnee",
        "lookup": "returnee",
        "required": False,
        "label": {"English(EN)": "Is this a returnee household?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_returnee_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "6b0c970a-6731-4449-afe1-02f101b7a74c",
        "type": TYPE_SELECT_ONE,
        "name": "registration_method",
        "lookup": "registration_method",
        "required": False,
        "label": {"English(EN)": "Method of collection (e.g. HH survey, Community, etc.)"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in REGISTRATION_METHOD_CHOICES],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_registration_method_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "a351a328-a67d-4c5b-bf60-2cbcc89a6a60",
        "type": TYPE_SELECT_ONE,
        "name": "currency",
        "lookup": "currency",
        "required": False,
        "label": {"English(EN)": "Which currency will be used for financial questions?"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": currency_name}, "value": code}
            for code, currency_name in CURRENCY_CHOICES
            if code != BLANK
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_currency_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "627cad46-6e08-4a18-b9ff-cf487ec4365a",
        "type": TYPE_STRING,
        "name": "village",
        "lookup": "village",
        "required": False,
        "label": {"English(EN)": "Village"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_village_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "17350903-0692-4214-809d-dc0a3c6b2338",
        "type": TYPE_STRING,
        "name": "deviceid",
        "lookup": "deviceid",
        "required": False,
        "label": {"English(EN)": "Device ID"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_deviceid",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "0ed7caaf-f80c-41d9-9394-32b766a090bb",
        "type": TYPE_STRING,
        "name": "name_enumerator",
        "lookup": "name_enumerator",
        "required": False,
        "label": {"English(EN)": "Name of the enumerator"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_name_enumerator_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "97a4db27-0b48-4e49-b2ef-cb70c889bd6c",
        "type": TYPE_SELECT_ONE,
        "name": "org_enumerator",
        "lookup": "org_enumerator",
        "required": False,
        "label": {"English(EN)": "Organization of the enumerator"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in ORG_ENUMERATOR_CHOICES],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_org_enumerator_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "28533a41-1b09-4a02-b2cd-48515bf4f02e",
        "type": TYPE_SELECT_MANY,
        "name": "consent_sharing",
        "lookup": "consent_sharing",
        "required": False,
        "label": {"English(EN)": "Which organizations may we share your information with?"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in DATA_SHARING_CHOICES],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_consent_sharing_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "2acfc04b-087c-4417-b859-00e940fcb9cf",
        "type": TYPE_STRING,
        "name": "org_name_enumerator",
        "lookup": "org_name_enumerator",
        "required": False,
        "label": {"English(EN)": "Name of partner organization"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_org_name_enumerator_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "bedc9e8f-6435-4ebf-8416-89e0b9d1f065",
        "type": TYPE_INTEGER,
        "name": "age",
        "lookup": "age",
        "label": {"English(EN)": "Age (calculated)"},
        "hint": "",
        "required": False,
        "get_query": age_to_birth_date_query,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_age",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "ef12def0-6268-47ab-970b-3b05c7f6b286",
        "type": TYPE_BOOL,
        "name": "fchild_hoh",
        "lookup": "fchild_hoh",
        "required": False,
        "label": {"English(EN)": "Child is female and head of household"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_fchild_hoh_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "2a50facb-9ae2-46da-8d75-717bdd766b2c",
        "type": TYPE_BOOL,
        "name": "child_hoh",
        "lookup": "child_hoh",
        "required": False,
        "label": {"English(EN)": "Child is head of household"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_child_hoh_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "e85f5bd8-3ff4-49a5-aa56-039611229679",
        "type": TYPE_SELECT_ONE,
        "name": "relationship",
        "lookup": "relationship",
        "required": True,
        "label": {"English(EN)": "Relationship to head of household"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in RELATIONSHIP_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_relationship_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "9a8ed133-39e7-4a69-911c-829622d2e3f3",
        "type": TYPE_SELECT_ONE,
        "name": "marital_status",
        "lookup": "marital_status",
        "required": False,
        "label": {"English(EN)": "Marital status"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in MARITAL_STATUS_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_marital_status_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "a0c4f10f-c193-4544-9c35-8989759679f4",
        "type": TYPE_STRING,
        "name": "phone_no",
        "lookup": "phone_no",
        "required": False,
        "label": {"English(EN)": "Phone number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_phone_no_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "6c0cd14c-6022-44f1-9122-3bea7d7d65be",
        "type": TYPE_STRING,
        "name": "who_answers_phone",
        "lookup": "who_answers_phone",
        "required": False,
        "label": {"English(EN)": "Who answers this phone?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_who_answers_phone_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "481393f3-5518-4d0b-a17c-7b16b7008db4",
        "type": TYPE_STRING,
        "name": "phone_no_alternative",
        "lookup": "phone_no_alternative",
        "required": False,
        "label": {"English(EN)": "Alternative phone number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_phone_no_alternative_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "d2ff92da-4602-45f5-8dd0-80c1ed176545",
        "type": TYPE_STRING,
        "name": "who_answers_alt_phone",
        "lookup": "who_answers_alt_phone",
        "required": False,
        "label": {"English(EN)": "Who answers this (alt) phone?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_who_answers_alt_phone_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "e68dd5aa-4cfb-4e75-967a-39393650c04d",
        "type": TYPE_STRING,
        "name": "birth_certificate_no",
        "lookup": "birth_certificate_no",
        "required": False,
        "label": {"English(EN)": "Birth certificate number"},
        "hint": "",
        "choices": [],
        "get_query": get_birth_certificate_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_birth_certificate_no_i_c",
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_birth_certificate_no,
    },
    {
        "id": "8942a42b-8146-40d0-909d-062c6378bee5",
        "type": TYPE_SELECT_ONE,
        "name": "birth_certificate_issuer",
        "lookup": "birth_certificate_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of birth certificate"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "get_query": get_birth_certificate_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_birth_certificate_issuer_i_c",
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_birth_certificate_issuer,
    },
    {
        "id": "8f19b57b-0b70-4d5a-9fe6-2879a9d4ad23",
        "type": TYPE_IMAGE,
        "name": "birth_certificate_photo",
        "lookup": "birth_certificate_photo",
        "required": False,
        "label": {"English(EN)": "Birth certificate photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_birth_certificate_photo_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "01a34f7a-c2fa-474c-ba94-8775b3d577d6",
        "type": TYPE_STRING,
        "name": "tax_id_no",
        "lookup": "tax_id_no",
        "required": False,
        "label": {"English(EN)": "Tax identification number"},
        "hint": "",
        "choices": [],
        "get_query": get_tax_id_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_tax_id_no_i_c",
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_tax_id_no,
    },
    {
        "id": "2f0d7153-1307-41ec-b6cf-f2f846137390",
        "type": TYPE_SELECT_ONE,
        "name": "tax_id_issuer",
        "lookup": "tax_id_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of tax identification"},
        "hint": "",
        "choices": Countries.get_choices(output_code="alpha3"),
        "get_query": get_tax_id_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_tax_id_issuer_i_c",
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_tax_id_issuer,
    },
    {
        "id": "2628dddf-74ef-4e31-8628-a912ed6173a6",
        "type": TYPE_IMAGE,
        "name": "tax_id_photo",
        "lookup": "tax_id_photo",
        "required": False,
        "label": {"English(EN)": "Tax identification photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_tax_id_photo_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "14b57405-5efc-4e8a-bd33-75b1413e6de8",
        "type": TYPE_STRING,
        "name": "drivers_license_no",
        "lookup": "drivers_license_no",
        "required": False,
        "label": {"English(EN)": "Driver's license number"},
        "hint": "",
        "choices": [],
        "get_query": get_drivers_license_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_drivers_license_no_i_c",
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_drivers_license_no,
    },
    {
        "id": "3b488b06-8669-4768-afb2-ed5c60f0a596",
        "type": TYPE_SELECT_ONE,
        "name": "drivers_license_issuer",
        "lookup": "drivers_license_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of driver's license"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "get_query": get_drivers_licensee_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_drivers_license_issuer_i_c",
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_drivers_license_issuer,
    },
    {
        "id": "6492b0a8-1d31-43d4-8b57-3879e15ec096",
        "type": TYPE_IMAGE,
        "name": "drivers_license_photo",
        "lookup": "drivers_license_photo",
        "required": False,
        "label": {"English(EN)": "Driver's license photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_drivers_license_photo_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "3359ce84-860d-473d-95aa-ab81ce2aaefb",
        "type": TYPE_STRING,
        "name": "electoral_card_no",
        "lookup": "electoral_card_no",
        "required": False,
        "label": {"English(EN)": "Electoral card number"},
        "hint": "",
        "choices": [],
        "get_query": get_electoral_card_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_electoral_card_no_i_c",
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_electoral_card_no,
    },
    {
        "id": "606cc5e3-c61b-40e8-8609-712e597c0146",
        "type": TYPE_SELECT_ONE,
        "name": "electoral_card_issuer",
        "lookup": "electoral_card_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of electoral card"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "get_query": get_electoral_card_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_electoral_card_issuer_i_c",
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_electoral_card_issuer,
    },
    {
        "id": "9d9779f9-4c56-470f-900c-cd56b39b47ef",
        "type": TYPE_IMAGE,
        "name": "electoral_card_photo",
        "lookup": "electoral_card_photo",
        "required": False,
        "label": {"English(EN)": "Electoral card photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_electoral_card_photo_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "e806e2a5-ba29-429e-917c-891f5589b286",
        "type": TYPE_STRING,
        "name": "unhcr_id_no",
        "lookup": "unhcr_id_no",
        "required": False,
        "label": {"English(EN)": "UNHCR ID number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_unhcr_id_no_i_c",
        "get_query": get_unhcr_id_number_query,
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_unhcr_id_no,
    },
    {
        "id": "6f2d1c86-9acd-4976-9652-30ceb2c726cf",
        "type": TYPE_SELECT_ONE,
        "name": "unhcr_id_issuer",
        "lookup": "unhcr_id_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing entity of UNHCR ID"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_unhcr_id_issuer_i_c",
        "get_query": get_unhcr_id_issuer_query,
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_unhcr_id_issuer,
    },
    {
        "id": "c8535c3f-86ab-4aea-9130-e9b7e791d5eb",
        "type": TYPE_IMAGE,
        "name": "unhcr_id_photo",
        "lookup": "unhcr_id_photo",
        "required": False,
        "label": {"English(EN)": "UNHCR ID photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_unhcr_id_photo_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "87585455-45c0-46ac-b755-9c5f1a4ec84b",
        "type": TYPE_STRING,
        "name": "national_passport",
        "lookup": "national_passport",
        "required": False,
        "label": {"English(EN)": "National passport number"},
        "hint": "",
        "choices": [],
        "get_query": get_national_passport_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_national_passport_no_i_c",
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_national_passport_no,
    },
    {
        "id": "c74631e3-6992-44d8-9a99-ed620b9b304e",
        "type": TYPE_SELECT_ONE,
        "name": "national_passport_issuer",
        "lookup": "national_passport_issuer",
        "get_query": get_national_passport_issuer_query,
        "required": False,
        "label": {"English(EN)": "Issuing country of national passport"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_national_passport_issuer_i_c",
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_national_passport_issuer,
    },
    {
        "id": "55d7b2c2-9645-4619-97da-60a0887c45dc",
        "type": TYPE_IMAGE,
        "name": "national_passport_photo",
        "lookup": "national_passport_photo",
        "required": False,
        "label": {"English(EN)": "National passport photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_national_passport_photo_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "631d5583-6f05-43ec-a80b-eaec7fd53f80",
        "type": TYPE_STRING,
        "name": "national_id_no",
        "lookup": "national_id_no",
        "required": False,
        "label": {"English(EN)": "National ID number"},
        "hint": "",
        "choices": [],
        "get_query": get_national_id_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_national_id_no_i_c",
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_national_id_no,
    },
    {
        "id": "3498fee1-3da7-4411-9c3d-8717e3ae9cff",
        "type": TYPE_SELECT_ONE,
        "name": "national_id_issuer",
        "lookup": "national_id_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of national ID"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "get_query": get_national_id_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_national_id_issuer_i_c",
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_national_id_issuer,
    },
    {
        "id": "f628b4f1-26f2-4b0a-9849-233421b77126",
        "type": TYPE_IMAGE,
        "name": "national_id_photo",
        "lookup": "national_id_photo",
        "required": False,
        "label": {"English(EN)": "National ID photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_national_id_photo_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "bcd4a480-765c-4434-bfba-8d1bcef08dbb",
        "type": TYPE_STRING,
        "name": "scope_id_no",
        "lookup": "scope_id_no",
        "required": False,
        "label": {"English(EN)": "WFP Scope ID number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_scope_id_no_i_c",
        "get_query": get_scope_id_number_query,
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_scope_id_no,
    },
    {
        "id": "195440fd-b687-4800-87fc-247ebfd44811",
        "type": TYPE_SELECT_ONE,
        "name": "scope_id_issuer",
        "lookup": "scope_id_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing entity of SCOPE ID"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_scope_id_issuer_i_c",
        "get_query": get_scope_id_issuer_query,
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_scope_id_issuer,
    },
    {
        "id": "623e9bc5-f6c1-4610-9cb1-a823c11457b5",
        "type": TYPE_IMAGE,
        "name": "scope_id_photo",
        "lookup": "scope_id_photo",
        "required": False,
        "label": {"English(EN)": "WFP Scope ID photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_scope_id_photo_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "80cf7e1a-1b29-4acd-b8c0-e8c67ce5d635",
        "type": TYPE_STRING,
        "name": "other_id_type",
        "lookup": "other_id_type",
        "required": False,
        "label": {"English(EN)": "If other type of ID, specify the type"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_other_id_type_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "3361a92a-93fc-4d36-8d19-6e80934d7975",
        "type": TYPE_STRING,
        "name": "other_id_no",
        "lookup": "other_id_no",
        "required": False,
        "label": {"English(EN)": "Other ID number"},
        "hint": "",
        "choices": [],
        "get_query": get_other_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_other_id_no_i_c",
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_other_id_no,
    },
    {
        "id": "e8fd4de6-8beb-41bb-b870-c774b54cce43",
        "type": TYPE_SELECT_ONE,
        "name": "other_id_issuer",
        "lookup": "other_id_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of other ID"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "get_query": get_other_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_other_id_issuer_i_c",
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_other_id_issuer,
    },
    {
        "id": "0e0cacc8-5b3f-48d5-bf6b-272054031892",
        "type": TYPE_IMAGE,
        "name": "other_id_photo",
        "lookup": "other_id_photo",
        "required": False,
        "label": {"English(EN)": "ID photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_other_id_photo_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "dda942d0-776e-4166-9f3f-8907a4e509f9",
        "type": TYPE_BOOL,
        "name": "pregnant",
        "lookup": "pregnant",
        "required": False,
        "label": {"English(EN)": "Is the individual pregnant?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_pregnant_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "41dc1154-5751-469b-8e49-98c8192acf0e",
        "type": TYPE_SELECT_ONE,
        "name": "work_status",
        "lookup": "work_status",
        "required": False,
        "label": {"English(EN)": "Does the individual have paid employment in the current month?"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in WORK_STATUS_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_work_status_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "b84b49c0-f55e-455d-9127-29365914c896",
        "type": TYPE_SELECT_MANY,
        "name": "observed_disability",
        "lookup": "observed_disability",
        "required": False,
        "label": {"English(EN)": "Does the individual have disability?"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in OBSERVED_DISABILITY_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_observed_disability_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "c10c1418-c89c-4069-b9fd-034f6cb8be2e",
        "type": TYPE_SELECT_ONE,
        "name": "seeing_disability",
        "lookup": "seeing_disability",
        "required": False,
        "label": {"English(EN)": "If the individual has difficulty seeing, what is the severity?"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_seeing_disability_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "504ee8a5-e715-4406-9595-662f45998ddb",
        "type": TYPE_SELECT_ONE,
        "name": "hearing_disability",
        "lookup": "hearing_disability",
        "required": False,
        "label": {"English(EN)": "If the individual has difficulty hearing, what is the severity?"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_hearing_disability_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "b5097dc9-90ed-4fcf-9a8f-1142bd54177c",
        "type": TYPE_SELECT_ONE,
        "name": "physical_disability",
        "lookup": "physical_disability",
        "required": False,
        "label": {"English(EN)": "If the individual has difficulty walking or climbing steps, what is the severity?"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_physical_disability_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "6f30fdfc-fa65-44a7-bdd4-93f31cec4038",
        "type": TYPE_SELECT_ONE,
        "name": "memory_disability",
        "lookup": "memory_disability",
        "required": False,
        "label": {
            "English(EN)": "If the individual has difficulty remembering or concentrating, what is the severity?"
        },
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_memory_disability_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "7ee8ec7e-0259-47cf-9dee-f0d027cc2179",
        "type": TYPE_SELECT_ONE,
        "name": "selfcare_disability",
        "lookup": "selfcare_disability",
        "required": False,
        "label": {"English(EN)": "Do you have difficulty (with self-care such as) washing all over or dressing"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_selfcare_disability_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "e02ec7e1-6071-4045-bfda-453759704d5a",
        "type": TYPE_SELECT_ONE,
        "name": "comms_disability",
        "lookup": "comms_disability",
        "required": False,
        "label": {"English(EN)": "If the individual has difficulty communicating, what is the severity?"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_comms_disability_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "91b31b3c-c3c9-470e-b5fd-7a610ab34aa3",
        "type": TYPE_SELECT_ONE,
        "name": "disability",
        "lookup": "disability",
        "required": False,
        "label": {"English(EN)": "Individual is disabled?"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in DISABILITY_CHOICES],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_disability_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "ed58245f-03d2-4610-bb09-a809450d3a91",
        "type": TYPE_DATE,
        "name": "first_registration_date",
        "lookup": "first_registration_date",
        "required": True,
        "label": {"English(EN)": "First individual registration date"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_first_registration_date_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "ac44e017-d7e6-48a2-8f76-c2c5eb3717ed",
        "type": TYPE_LIST_OF_IDS,
        "name": "primary_collector_id",
        "lookup": "primary_collector_id",
        "required": False,
        "label": {"English(EN)": "List of primary collectors ids, separated by a semicolon"},
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_primary_collector_id",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "316e43d4-d216-4060-adde-c09cad20a976",
        "type": TYPE_LIST_OF_IDS,
        "name": "alternate_collector_id",
        "lookup": "alternate_collector_id",
        "required": False,
        "label": {"English(EN)": "List of alternate collectors ids, separated by a semicolon"},
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_alternate_collector_id",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "8823010f-cc9e-4714-bcc3-871334fec215",
        "type": TYPE_STRING,
        "name": "email",
        "lookup": "email",
        "required": False,
        "label": {"English(EN)": "Individual email"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_email",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "ca432ff3-0872-4927-b513-a97b18b3f47d",
        "type": TYPE_SELECT_ONE,
        "name": "preferred_language",
        "lookup": "preferred_language",
        "required": False,
        "label": {"English(EN)": "Preferred language"},
        "hint": "",
        "choices": Languages.get_choices(),
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_preferred_language",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "f4197829-5a5d-485e-8b18-9b9353db020e",
        "type": TYPE_INTEGER,
        "name": "age_at_registration",
        "lookup": "age_at_registration",
        "label": {"English(EN)": "Age at registration"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_age_at_registration",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "44597fa4-a7d5-4e7c-8036-4888d6fbc090",
        "type": TYPE_STRING,
        "name": "account_holder_name",
        "lookup": "account_holder_name",
        "label": {"English(EN)": "Account holder name"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_account_holder_name_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "3283adcd-27f7-450f-bc83-e305601b2871",
        "type": TYPE_STRING,
        "name": "bank_branch_name",
        "lookup": "bank_branch_name",
        "label": {"English(EN)": "Bank branch name"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_bank_branch_name_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "84b05bc5-9757-4894-8a2b-b556b69d9f60",
        "type": TYPE_STRING,
        "name": "bank_name",
        "lookup": "bank_name",
        "required": False,
        "label": {"English(EN)": "Bank name"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_bank_name_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "1c83fac6-39ff-43ff-95c0-394c025ad79b",
        "type": TYPE_STRING,
        "name": "bank_account_number",
        "lookup": "bank_account_number",
        "required": False,
        "label": {"English(EN)": "Bank account number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_bank_account_number_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "537acf75-3437-483e-b9ab-d341a7ebc024",
        "type": TYPE_STRING,
        "name": "debit_card_issuer",
        "lookup": "debit_card_issuer",
        "required": False,
        "label": {"English(EN)": "Debit Card Issuer"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_debit_card_issuer_i_c",
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_debit_card_issuer,
    },
    {
        "id": "85f95811-a0d1-4667-b039-8d7e2416ea1b",
        "type": TYPE_STRING,
        "name": "debit_card_number",
        "lookup": "debit_card_number",
        "required": False,
        "label": {"English(EN)": "Debit card number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_debit_card_number_i_c",
        "scope": [Scope.XLSX_PEOPLE],
        "lookup_function": get_debit_card_number,
    },
    {
        "id": "c9ff67ab-92a4-48f9-8be8-44fe41425110",
        "type": TYPE_STRING,
        "name": "payment_delivery_phone_no",
        "lookup": "payment_delivery_phone_no",
        "required": False,
        "label": {"English(EN)": "Payment delivery phone number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_payment_delivery_phone_no_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "wallet_name",
        "lookup": "wallet_name",
        "label": {"English(EN)": "Wallet Name"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_wallet_name_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "blockchain_name",
        "lookup": "blockchain_name",
        "label": {"English(EN)": "Blockchain Name"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_blockchain_name_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "wallet_address",
        "lookup": "wallet_address",
        "label": {"English(EN)": "Wallet Address"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_wallet_address_i_c",
        "scope": [Scope.XLSX_PEOPLE],
    },
]
