from hct_mis_api.apps.core.currencies import CURRENCY_CHOICES
from hct_mis_api.apps.core.field_attributes.fields_types import (
    _INDIVIDUAL,
    TYPE_BOOL,
    TYPE_DATE,
    TYPE_GEOPOINT,
    TYPE_IMAGE,
    TYPE_SELECT_MANY,
    TYPE_SELECT_ONE,
    TYPE_STRING,
    Scope,
)
from hct_mis_api.apps.geo.models import Area, Country
from hct_mis_api.apps.household.models import (
    BLANK,
    DATA_SHARING_CHOICES,
    ORG_ENUMERATOR_CHOICES,
    REGISTRATION_METHOD_CHOICES,
    RESIDENCE_STATUS_CHOICE,
)

SOCIAL_WORKER_FIELDS_ATTRIBUTES = [
    {
        "id": "bec7a6b9-476d-48a8-8822-e24ae023df42",
        "type": TYPE_STRING,
        "name": "index_id",
        "lookup": "index_id",
        "required": False,
        "label": {"English(EN)": "Index ID"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_index_id",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "9f026563-2280-4541-9650-d099c4bba903",
        "type": TYPE_STRING,
        "name": "address",
        "lookup": "address",
        "required": False,
        "label": {"English(EN)": "Address"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_address_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "ea0adf6f-61cc-44b4-bca6-16980e1a591c",
        "type": TYPE_SELECT_ONE,
        "name": "country_origin",
        "lookup": "country_origin__iso_code3",
        "required": False,
        "label": {"English(EN)": "Country of Origin"},
        "hint": "country origin",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_country_origin_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "40456b87-2620-48c3-af13-19c2de31a655",
        "type": TYPE_SELECT_ONE,
        "name": "country",
        "lookup": "country__iso_code3",
        "required": True,
        "label": {"English(EN)": "Country of registration"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_country_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "b85054fb-0dce-4ac4-84ce-4c84f9cb5179",
        "type": TYPE_STRING,
        "name": "zip_code",
        "lookup": "zip_code",
        "required": False,
        "label": {"English(EN)": "Zip code"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_zip_code_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "c53ea58b-e7cf-4bf3-82d0-dec41f66ef3a",
        "type": TYPE_SELECT_ONE,
        "name": "admin1",
        "lookup": "admin1__p_code",
        "required": False,
        "label": {"English(EN)": "Social worker resides in which ${admin1_i_c}?"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Area.get_admin_areas_as_choices(1, *args, **kwargs),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_admin1_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "67ac9b44-cda7-42ee-ae47-640a30306d84",
        "type": TYPE_SELECT_ONE,
        "name": "admin2",
        "lookup": "admin2__p_code",
        "required": False,
        "label": {"English(EN)": "Social worker resides in which ${admin2_i_c}?"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Area.get_admin_areas_as_choices(2, *args, **kwargs),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_admin2_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "b124a9f1-a01e-4145-857a-931bdb6cd84d",
        "type": TYPE_SELECT_ONE,
        "name": "admin3",
        "lookup": "admin3__p_code",
        "required": False,
        "label": {"English(EN)": "Social worker resides in which ${admin3_i_c}?"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Area.get_admin_areas_as_choices(3, *args, **kwargs),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_admin3_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "722511ed-2f47-4e78-b963-56fc22ca5e71",
        "type": TYPE_SELECT_ONE,
        "name": "admin4",
        "lookup": "admin4__p_code",
        "required": False,
        "label": {"English(EN)": "Social worker resides in which ${admin4_i_c}?"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Area.get_admin_areas_as_choices(4, *args, **kwargs),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_admin4_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "f6a4dfb5-711c-4498-b286-cc4524abb778",
        "type": TYPE_SELECT_ONE,
        "name": "residence_status",
        "lookup": "residence_status",
        "required": False,
        "label": {"English(EN)": "Residence status"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in RESIDENCE_STATUS_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_residence_status_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "feeb6dc8-79e3-4278-abd3-0f7bf2f95000",
        "type": TYPE_BOOL,
        "name": "consent",
        "lookup": "consent",
        "required": False,
        "label": {"English(EN)": "Do you consent?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_consent_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "268e653a-2bb8-4570-aeea-72aa2f0c3f23",
        "type": TYPE_IMAGE,
        "name": "consent_sign",
        "lookup": "consent_sign",
        "required": False,
        "label": {"English(EN)": "Do you consent?"},
        "hint": "Ask the social worker to sign or do an X as acknowledgement",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_consent_sign_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "d2d62a29-096c-41f2-be34-ce97ce1222eb",
        "type": TYPE_GEOPOINT,
        "name": "geopoint",
        "lookup": "geopoint",
        "required": False,
        "label": {"English(EN)": "Geolocation"},
        "hint": "latitude and longitude of social worker",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_hh_geopoint_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "b8e02ee5-fb35-4e4d-b1f8-62a0b75f5995",
        "type": TYPE_STRING,
        "name": "unhcr_id",
        "lookup": "unhcr_id",
        "required": False,
        "label": {"English(EN)": "UNHCR Case ID"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_unhcr_id_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "7899b38c-545a-4ddb-b659-58f7bc6e0ceb",
        "type": TYPE_BOOL,
        "name": "returnee",
        "lookup": "returnee",
        "required": False,
        "label": {"English(EN)": "Is this a returnee household?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_returnee_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "6b0c970a-6731-4449-afe1-02f101b7a74c",
        "type": TYPE_SELECT_ONE,
        "name": "registration_method",
        "lookup": "registration_method",
        "required": False,
        "label": {"English(EN)": "Method of collection (e.g. HH survey, Community, etc.)"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in REGISTRATION_METHOD_CHOICES],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_registration_method_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "a351a328-a67d-4c5b-bf60-2cbcc89a6a60",
        "type": TYPE_SELECT_ONE,
        "name": "currency",
        "lookup": "currency",
        "required": False,
        "label": {"English(EN)": "Which currency will be used for financial questions?"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": currency_name}, "value": code}
            for code, currency_name in CURRENCY_CHOICES
            if code != BLANK
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_currency_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "627cad46-6e08-4a18-b9ff-cf487ec4365a",
        "type": TYPE_STRING,
        "name": "village",
        "lookup": "village",
        "required": False,
        "label": {"English(EN)": "Village"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_village_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "17350903-0692-4214-809d-dc0a3c6b2338",
        "type": TYPE_STRING,
        "name": "deviceid",
        "lookup": "deviceid",
        "required": False,
        "label": {"English(EN)": "Device ID"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_deviceid",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "0ed7caaf-f80c-41d9-9394-32b766a090bb",
        "type": TYPE_STRING,
        "name": "name_enumerator",
        "lookup": "name_enumerator",
        "required": False,
        "label": {"English(EN)": "Name of the enumerator"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_name_enumerator_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "97a4db27-0b48-4e49-b2ef-cb70c889bd6c",
        "type": TYPE_SELECT_ONE,
        "name": "org_enumerator",
        "lookup": "org_enumerator",
        "required": False,
        "label": {"English(EN)": "Organization of the enumerator"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in ORG_ENUMERATOR_CHOICES],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_org_enumerator_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "28533a41-1b09-4a02-b2cd-48515bf4f02e",
        "type": TYPE_SELECT_MANY,
        "name": "consent_sharing",
        "lookup": "consent_sharing",
        "required": False,
        "label": {"English(EN)": "Which organizations may we share your information with?"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in DATA_SHARING_CHOICES],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_consent_sharing_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "2acfc04b-087c-4417-b859-00e940fcb9cf",
        "type": TYPE_STRING,
        "name": "org_name_enumerator",
        "lookup": "org_name_enumerator",
        "required": False,
        "label": {"English(EN)": "Name of partner organization"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_org_name_enumerator_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
    {
        "id": "568effd8-f652-466b-8c2d-8a9ae2fa0deb",
        "type": TYPE_DATE,
        "name": "first_registration_date",
        "lookup": "first_registration_date",
        "required": True,
        "label": {"English(EN)": "First social worker registration date"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pp_first_registration_date_i_c",
        "scope": [Scope.XLSX_SOCIAL_WORKER],
    },
]
