# Generated by Django 5.2.11 on 2026-03-04 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("steficon", "0003_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rule",
            options={
                "ordering": ("id",),
                "permissions": (
                    ("process_file", "Can Process File"),
                    ("check_diff", "Can Check Diff"),
                    ("changelog", "Can Check Changelog"),
                    ("rerun_rule", "Can Rerun Rule"),
                ),
            },
        ),
    ]
