# Generated by Django 3.2.25 on 2025-02-27 11:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0015_migration'),
        ('payment', '0016_migration'),
        ('program', '0003_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('curr_async_result_id', models.CharField(blank=True, help_text='Current (active) AsyncResult is', max_length=36, null=True)),
                ('individual_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('individual_flex_fields_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('household_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('household_flex_fields_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='')),
                ('update_file', models.FileField(blank=True, null=True, upload_to='')),
                ('backup_snapshot', models.FileField(blank=True, null=True, upload_to='')),
                ('saved_logs', models.TextField(blank=True, default='', null=True)),
                ('unicef_ids', models.TextField(blank=True, null=True)),
                ('delivery_mechanisms', models.ManyToManyField(blank=True, to='payment.DeliveryMechanism')),
                ('document_types', models.ManyToManyField(blank=True, to='household.DocumentType')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
