# Generated by Django 3.2.25 on 2025-02-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_update_script', '0001_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universalupdate',
            name='update_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
