# Generated by Django 3.2.25 on 2025-02-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_update_script', '0002_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='universalupdate',
            name='unicef_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
