# Generated by Django 3.2.25 on 2025-03-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0005_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduplicationenginesimilaritypair',
            name='status_code',
            field=models.CharField(choices=[('200', 'Deduplication success'), ('404', 'No file found'), ('412', 'No face detected'), ('429', 'Multiple faces detected'), ('500', 'Generic error')], max_length=20),
        ),
    ]
