# Generated by Django 2.2.8 on 2020-08-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0007_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdataimport',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registrationdataimport',
            name='status',
            field=models.CharField(choices=[('IN_REVIEW', 'In Review'), ('MERGED', 'Merged'), ('MERGING', 'Merging'), ('IMPORTING', 'Importing'), ('DEDUPLICATION_FAILED', 'Deduplication Failed'), ('DEDUPLICATION', 'Deduplication')], default='IN_REVIEW', max_length=255),
        ),
    ]
