# Generated by Django 2.2.16 on 2021-02-16 13:11

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0010_migration'),
        ('steficon', '0002_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdataimport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='registrationdataimport',
            name='datahub_id',
            field=models.UUIDField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataimport',
            name='import_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='registrationdataimport',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationdataimport',
            name='number_of_households',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='registrationdataimport',
            name='number_of_individuals',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='registrationdataimport',
            name='status',
            field=models.CharField(choices=[('IN_REVIEW', 'In Review'), ('MERGED', 'Merged'), ('MERGING', 'Merging'), ('IMPORTING', 'Importing'), ('DEDUPLICATION_FAILED', 'Deduplication Failed'), ('DEDUPLICATION', 'Deduplication')], db_index=True, default='IN_REVIEW', max_length=255),
        ),
        migrations.AlterField(
            model_name='registrationdataimport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
