# Generated by Django 3.2.15 on 2023-01-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0023_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdataimport',
            name='data_source',
            field=models.CharField(choices=[('XLS', 'Excel'), ('KOBO', 'KoBo'), ('DIIA', 'DIIA'), ('FLEX_REGISTRATION', 'Flex Registration'), ('API', 'Flex API'), ('EDOPOMOGA', 'eDopomoga')], max_length=255),
        ),
    ]
