import copy
import logging
from functools import reduce
from typing import Any, Dict, Iterable, List, Optional, Set

from hct_mis_api.apps.core.attributes_qet_queries import (
    age_to_birth_date_query,
    get_birth_certificate_document_number_query,
    get_birth_certificate_issuer_query,
    get_drivers_license_document_number_query,
    get_drivers_licensee_issuer_query,
    get_electoral_card_document_number_query,
    get_electoral_card_issuer_query,
    get_has_bank_account_number_query,
    get_has_phone_number_query,
    get_has_tax_id_query,
    get_national_id_document_number_query,
    get_national_id_issuer_query,
    get_national_passport_document_number_query,
    get_national_passport_issuer_query,
    get_other_document_number_query,
    get_other_issuer_query,
    get_role_query,
    get_scope_id_issuer_query,
    get_scope_id_number_query,
    get_tax_id_document_number_query,
    get_tax_id_issuer_query,
    get_unhcr_id_issuer_query,
    get_unhcr_id_number_query,
    registration_data_import_query,
)
from hct_mis_api.apps.core.countries import Countries
from hct_mis_api.apps.core.currencies import CURRENCY_CHOICES
from hct_mis_api.apps.core.field_attributes.fields_types import (
    _DELIVERY_MECHANISM_DATA,
    _HOUSEHOLD,
    _INDIVIDUAL,
    TEMPLATE_HOH,
    TEMPLATE_HOUSEHOLD,
    TEMPLATE_INDIVIDUAL,
    TEMPLATE_MAPPING_NORMAL,
    TEMPLATE_MAPPING_PEOPLE,
    TYPE_BOOL,
    TYPE_DATE,
    TYPE_GEOPOINT,
    TYPE_ID,
    TYPE_IMAGE,
    TYPE_INTEGER,
    TYPE_LIST_OF_IDS,
    TYPE_SELECT_MANY,
    TYPE_SELECT_ONE,
    TYPE_STRING,
    Scope,
)
from hct_mis_api.apps.core.field_attributes.lookup_functions import (
    get_birth_certificate_issuer,
    get_birth_certificate_no,
    get_drivers_license_issuer,
    get_drivers_license_no,
    get_electoral_card_issuer,
    get_electoral_card_no,
    get_national_id_issuer,
    get_national_id_no,
    get_national_passport_issuer,
    get_national_passport_no,
    get_other_id_issuer,
    get_other_id_no,
    get_scope_id_issuer,
    get_scope_id_no,
    get_tax_id_issuer,
    get_tax_id_no,
    get_unhcr_id_issuer,
    get_unhcr_id_no,
)
from hct_mis_api.apps.core.field_attributes.payment_channel_fields_attributes import (
    PAYMENT_CHANNEL_FIELDS_ATTRIBUTES,
)
from hct_mis_api.apps.core.languages import Languages
from hct_mis_api.apps.geo.models import Area, Country
from hct_mis_api.apps.household.models import (
    BLANK,
    DATA_SHARING_CHOICES,
    DISABILITY_CHOICES,
    MARITAL_STATUS_CHOICE,
    OBSERVED_DISABILITY_CHOICE,
    ORG_ENUMERATOR_CHOICES,
    REGISTRATION_METHOD_CHOICES,
    RELATIONSHIP_CHOICE,
    RESIDENCE_STATUS_CHOICE,
    ROLE_CHOICE,
    SEVERITY_OF_DISABILITY_CHOICES,
    SEX_CHOICE,
    WORK_STATUS_CHOICE,
)
from hct_mis_api.apps.registration_data.models import (
    COLLECT_TYPES,
    RegistrationDataImport,
)

logger = logging.getLogger(__name__)

# about "snapshot_field"
# if it's the same field that can connect with "associated_with" and "lookup"
# like individual.full_name or household.size <-- no needed any "snapshot_field" info
# but for "account_holder_name" it gets from  "bank_account_info__account_holder_name"
# or for field "debit_card_issuer" used individual.full_name and in "snapshot_field" it's "full_name"

CORE_FIELDS_ATTRIBUTES = [
    {
        "id": "a1741e3c-0e24-4a60-8d2f-463943abaebb",
        "type": TYPE_INTEGER,
        "name": "age",
        "lookup": "age",
        "label": {"English(EN)": "Age (calculated)"},
        "hint": "",
        "required": False,
        "get_query": age_to_birth_date_query,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "age",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
    },
    {
        "id": "3c2473d6-1e81-4025-86c7-e8036dd92f4b",
        "type": TYPE_SELECT_ONE,
        "name": "residence_status",
        "lookup": "residence_status",
        "required": False,
        "label": {"English(EN)": "Residence status"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in RESIDENCE_STATUS_CHOICE],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "residence_status_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "e47bafa7-0b86-4be9-a07f-d3fc7ac698cf",
        "type": TYPE_BOOL,
        "name": "consent",
        "lookup": "consent",
        "required": False,
        "label": {"English(EN)": "Do you consent?"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "consent_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "9480fc0d-1b88-45b0-9056-6a6fe0ebe509",
        "type": TYPE_IMAGE,
        "name": "consent_sign",
        "lookup": "consent_sign",
        "required": False,
        "label": {"English(EN)": "Do you consent?"},
        "hint": f"Ask the {TEMPLATE_HOH} to sign or do an X as acknowledgement",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "consent_sign_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "e44efed6-47d6-4f60-bcf6-b1d2ffc4d7d1",
        "type": TYPE_SELECT_ONE,
        "name": "country_origin",
        "lookup": "country_origin__iso_code3",
        "required": False,
        "label": {"English(EN)": "Country of Origin"},
        "hint": "country origin",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "country_origin_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX_PEOPLE],
        "snapshot_field": "country_origin_id__iso_code3",
    },
    {
        "id": "aa79985c-b616-453c-9884-0666252c3070",
        "type": TYPE_SELECT_ONE,
        "name": "country",
        "lookup": "country__iso_code3",
        "required": True,
        "label": {"English(EN)": "Country of registration"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "country_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX_PEOPLE],
        "snapshot_field": "country_id__iso_code3",
    },
    {
        "id": "59685cec-69bf-4abe-81b4-70b8f05b89f3",
        "type": TYPE_STRING,
        "name": "address",
        "lookup": "address",
        "required": False,
        "label": {"English(EN)": "Address"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "address_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "3b107048-1f31-42bf-85a1-4fb76adb2804",
        "type": TYPE_STRING,
        "name": "zip_code",
        "lookup": "zip_code",
        "required": False,
        "label": {"English(EN)": "Zip code"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "zip_code_h_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE],
    },
    {
        "id": "c53ea58b-e7cf-4bf3-82d0-dec41f66ef3a",
        "type": TYPE_SELECT_ONE,
        "name": "admin1",
        "lookup": "admin1__p_code",
        "required": False,
        "label": {"English(EN)": f"{TEMPLATE_HOUSEHOLD} resides in which admin1?"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Area.get_admin_areas_as_choices(1, *args, **kwargs),
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "admin1_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "snapshot_field": "admin1_id__p_code",
    },
    {
        "id": "e4eb6632-8204-44ed-b39c-fe791ded9246",
        "type": TYPE_SELECT_ONE,
        "name": "admin2",
        "lookup": "admin2__p_code",
        "required": False,
        "label": {"English(EN)": f"{TEMPLATE_HOUSEHOLD} resides in which admin2?"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Area.get_admin_areas_as_choices(2, *args, **kwargs),
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "admin2_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "snapshot_field": "admin2_id__p_code",
    },
    {
        "id": "92e425a7-db22-4026-8602-96c51471dfff",
        "type": TYPE_SELECT_ONE,
        "name": "admin3",
        "lookup": "admin3__p_code",
        "required": False,
        "label": {"English(EN)": f"{TEMPLATE_HOUSEHOLD} resides in which admin3?"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Area.get_admin_areas_as_choices(3, *args, **kwargs),
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "admin3_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.XLSX_PEOPLE],
        "snapshot_field": "admin3_id__p_code",
    },
    {
        "id": "717620df-b804-4398-b789-e56aa7a3da5e",
        "type": TYPE_SELECT_ONE,
        "name": "admin4",
        "lookup": "admin4__p_code",
        "required": False,
        "label": {"English(EN)": f"{TEMPLATE_HOUSEHOLD} resides in which admin4?"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Area.get_admin_areas_as_choices(4, *args, **kwargs),
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "admin4_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.XLSX_PEOPLE],
        "snapshot_field": "admin4_id__p_code",
    },
    {
        "id": "13a9d8b0-f278-47c2-9b1b-b06579b0ab35",
        "type": TYPE_GEOPOINT,
        "name": "geopoint",
        "lookup": "geopoint",
        "required": False,
        "label": {"English(EN)": "Geolocation"},
        "hint": f"latitude and longitude of {TEMPLATE_HOUSEHOLD}",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "hh_geopoint_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
    },
    {
        "id": "5b32bad5-ff7c-4e6b-af7e-a0287fe91ea2",
        "type": TYPE_STRING,
        "name": "unhcr_id",
        "lookup": "unhcr_id",
        "required": False,
        "label": {"English(EN)": "UNHCR Case ID"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "unhcr_id_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "5f530642-b889-4130-bf1a-5fac1b17cf09",
        "type": TYPE_BOOL,
        "name": "returnee",
        "lookup": "returnee",
        "required": False,
        "label": {"English(EN)": f"Is this a returnee {TEMPLATE_HOUSEHOLD}?"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "returnee_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "d668ae31-12cf-418e-8f7f-4c6398d82ffd",
        "type": TYPE_INTEGER,
        "name": "size",
        "lookup": "size",
        "required": False,
        "label": {"English(EN)": f"What is the {TEMPLATE_HOUSEHOLD} size?"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "size_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "ee54d921-e11d-46a2-8a1f-3ebf17485dd6",
        "type": TYPE_BOOL,
        "name": "fchild_hoh",
        "lookup": "fchild_hoh",
        "required": False,
        "label": {"English(EN)": f"Child is female and {TEMPLATE_HOH}"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "fchild_hoh_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "f9d16bda-4823-425d-b30e-ce35030bc5c0",
        "type": TYPE_BOOL,
        "name": "child_hoh",
        "lookup": "child_hoh",
        "required": False,
        "label": {"English(EN)": f"Child is {TEMPLATE_HOH}"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "child_hoh_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "8d9df01a-ce7c-4e78-b8ec-6f3eec8f30ce",
        "type": TYPE_SELECT_ONE,
        "name": "relationship",
        "lookup": "relationship",
        "required": True,
        "label": {"English(EN)": f"Relationship to {TEMPLATE_HOH}"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in RELATIONSHIP_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "relationship_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "36ab3421-6e7a-40d1-b816-ea5cbdcc0b6a",
        "type": TYPE_STRING,
        "name": "full_name",
        "lookup": "full_name",
        "required": True,
        "label": {"English(EN)": "Full name"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "full_name_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "b1f90314-b8b8-4bcb-9265-9d48d1fce5a4",
        "type": TYPE_STRING,
        "name": "given_name",
        "lookup": "given_name",
        "required": False,
        "label": {"English(EN)": "Given name"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "given_name_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "6f603107-bd88-4a8d-97cc-748a7238358d",
        "type": TYPE_STRING,
        "name": "middle_name",
        "lookup": "middle_name",
        "required": False,
        "label": {"English(EN)": "Middle name(s)"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "middle_name_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "3f74dd36-bfd2-4c84-bfc7-21f7adbff7f0",
        "type": TYPE_STRING,
        "name": "family_name",
        "lookup": "family_name",
        "required": False,
        "label": {"English(EN)": "Family name"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "family_name_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "da726870-dfc9-48dc-aba9-b9138b611c74",
        "type": TYPE_SELECT_ONE,
        "name": "sex",
        "lookup": "sex",
        "required": True,
        "label": {"English(EN)": "Gender"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in SEX_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "gender_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "416b0119-2d89-4517-819d-e563d2eb428c",
        "type": TYPE_DATE,
        "name": "birth_date",
        "lookup": "birth_date",
        "required": True,
        "label": {"English(EN)": "Birth date"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "birth_date_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "5e2c2a7c-9651-4c07-873c-f594ae18a56a",
        "type": TYPE_BOOL,
        "name": "estimated_birth_date",
        "lookup": "estimated_birth_date",
        "required": True,
        "label": {"English(EN)": "Estimated birth date?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "estimated_birth_date_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "84827966-17e5-407a-9424-1350c7ec3b64",
        "type": TYPE_IMAGE,
        "name": "photo",
        "lookup": "photo",
        "required": False,
        "label": {"English(EN)": f"{TEMPLATE_INDIVIDUAL}'s photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "photo_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
    },
    {
        "id": "35ede8c4-877e-40dc-a93a-0a9a3bc511dc",
        "type": TYPE_SELECT_ONE,
        "name": "marital_status",
        "lookup": "marital_status",
        "required": False,
        "label": {"English(EN)": "Marital status"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in MARITAL_STATUS_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "marital_status_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "01c1ae70-d8f8-4451-96c5-09afb4ff3057",
        "type": TYPE_STRING,
        "name": "phone_no",
        "lookup": "phone_no",
        "required": False,
        "label": {"English(EN)": "Phone number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "phone_no_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "8e10289e-235a-4af5-a745-8c3082b820f5",
        "type": TYPE_STRING,
        "name": "who_answers_phone",
        "lookup": "who_answers_phone",
        "required": False,
        "label": {"English(EN)": "Who answers this phone?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "who_answers_phone_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "f7609980-95c4-4b18-82dc-132a04ce7d65",
        "type": TYPE_STRING,
        "name": "phone_no_alternative",
        "lookup": "phone_no_alternative",
        "required": False,
        "label": {"English(EN)": "Alternative phone number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "phone_no_alternative_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "2448dbfe-e746-4aea-9e74-e635a3195dc5",
        "type": TYPE_STRING,
        "name": "who_answers_alt_phone",
        "lookup": "who_answers_alt_phone",
        "required": False,
        "label": {"English(EN)": "Who answers this (alt) phone?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "who_answers_alt_phone_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "e991e0e2-d6be-4abd-b3bc-9122091ca96e",
        "type": TYPE_SELECT_ONE,
        "name": "registration_method",
        "lookup": "registration_method",
        "required": False,
        "label": {"English(EN)": "Method of collection (e.g. HH survey, Community, etc.)"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in REGISTRATION_METHOD_CHOICES],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "registration_method_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "d9eea60c-5747-4d26-9f4b-f99a2165e913",
        "type": TYPE_SELECT_ONE,
        "name": "collect_individual_data",
        "lookup": "collect_individual_data",
        "required": False,
        "label": {"English(EN)": f"Will you be collecting all member {TEMPLATE_INDIVIDUAL} data?"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in COLLECT_TYPES],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "collect_individual_data_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX],
    },
    {
        "id": "1c2e3c42-8b32-4198-bd4f-06a61e2ecf0e",
        "type": TYPE_SELECT_ONE,
        "name": "currency",
        "lookup": "currency",
        "required": False,
        "label": {"English(EN)": "Which currency will be used for financial questions?"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": currency_name}, "value": code}
            for code, currency_name in CURRENCY_CHOICES
            if code != BLANK
        ],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "currency_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "f1d0c0c1-53d7-422a-be3d-b3588ee0ff58",
        "type": TYPE_STRING,
        "name": "birth_certificate_no",
        "lookup": "birth_certificate_no",
        "required": False,
        "label": {"English(EN)": "Birth certificate number"},
        "hint": "",
        "choices": [],
        "get_query": get_birth_certificate_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "birth_certificate_no_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_birth_certificate_no,
        # for document, it's gets from ["documents"][type][field]
        "snapshot_field": "documents__birth_certificate__document_number",
    },
    {
        "id": "0d8bc4b6-c2c7-4b8b-ab64-cd2e80b70717",
        "type": TYPE_SELECT_ONE,
        "name": "birth_certificate_issuer",
        "lookup": "birth_certificate_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of birth certificate"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "get_query": get_birth_certificate_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "birth_certificate_issuer_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_birth_certificate_issuer,
        "snapshot_field": "documents__birth_certificate__country",
    },
    {
        "id": "12ceb917-8942-4cb6-a9d0-6a97a097258a",
        "type": TYPE_IMAGE,
        "name": "birth_certificate_photo",
        "lookup": "birth_certificate_photo",
        "required": False,
        "label": {"English(EN)": "Birth certificate photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "birth_certificate_photo_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "snapshot_field": "documents__birth_certificate__photo",
    },
    {
        "id": "03520f48-4918-4f7a-988d-f24476e16fc4",
        "type": TYPE_STRING,
        "name": "tax_id_no",
        "lookup": "tax_id_no",
        "required": False,
        "label": {"English(EN)": "Tax identification number"},
        "hint": "",
        "choices": [],
        "get_query": get_tax_id_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "tax_id_no_i_c",
        "scope": [Scope.XLSX, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_tax_id_no,
        "snapshot_field": "documents__tax_id__document_number",
    },
    {
        "id": "762cb2a8-b05a-47dc-81da-c71e4b1fd68f",
        "type": TYPE_SELECT_ONE,
        "name": "tax_id_issuer",
        "lookup": "tax_id_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of tax identification"},
        "hint": "",
        "choices": Countries.get_choices(output_code="alpha3"),
        "get_query": get_tax_id_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "tax_id_issuer_i_c",
        "scope": [Scope.XLSX, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_tax_id_issuer,
        "snapshot_field": "documents__tax_id__country",
    },
    {
        "id": "d0e84bc0-9ac5-4c5b-bbdc-0644f5349d53",
        "type": TYPE_IMAGE,
        "name": "tax_id_photo",
        "lookup": "tax_id_photo",
        "required": False,
        "label": {"English(EN)": "Tax identification photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "tax_id_photo_i_c",
        "scope": [Scope.XLSX, Scope.XLSX_PEOPLE],
        "snapshot_field": "documents__tax_id__photo",
    },
    {
        "id": "34a9519f-9c42-4910-b097-157ec8e6e31f",
        "type": TYPE_STRING,
        "name": "drivers_license_no",
        "lookup": "drivers_license_no",
        "required": False,
        "label": {"English(EN)": "Driver's license number"},
        "hint": "",
        "choices": [],
        "get_query": get_drivers_license_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "drivers_license_no_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_drivers_license_no,
        "snapshot_field": "documents__drivers_license__document_number",
    },
    {
        "id": "00b95153-976e-4653-b9a8-843d513df873",
        "type": TYPE_SELECT_ONE,
        "name": "drivers_license_issuer",
        "lookup": "drivers_license_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of driver's license"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "get_query": get_drivers_licensee_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "drivers_license_issuer_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_drivers_license_issuer,
        "snapshot_field": "documents__drivers_license__country",
    },
    {
        "id": "7e6a41c5-0fbd-4f99-98ba-2c6a7da8dbe4",
        "type": TYPE_IMAGE,
        "name": "drivers_license_photo",
        "lookup": "drivers_license_photo",
        "required": False,
        "label": {"English(EN)": "Driver's license photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "drivers_license_photo_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "snapshot_field": "documents__drivers_license__photo",
    },
    {
        "id": "225832fc-c61b-4100-aac9-352d272d15fd",
        "type": TYPE_STRING,
        "name": "electoral_card_no",
        "lookup": "electoral_card_no",
        "required": False,
        "label": {"English(EN)": "Electoral card number"},
        "hint": "",
        "choices": [],
        "get_query": get_electoral_card_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "electoral_card_no_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_electoral_card_no,
        "snapshot_field": "documents__electoral_card__document_number",
    },
    {
        "id": "acca5a63-538a-47d1-b343-da22a86783b0",
        "type": TYPE_SELECT_ONE,
        "name": "electoral_card_issuer",
        "lookup": "electoral_card_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of electoral card"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "get_query": get_electoral_card_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "electoral_card_issuer_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_electoral_card_issuer,
        "snapshot_field": "documents__electoral_card__country",
    },
    {
        "id": "ffb6a487-a806-47d6-a12f-fe3c6c516976",
        "type": TYPE_IMAGE,
        "name": "electoral_card_photo",
        "lookup": "electoral_card_photo",
        "required": False,
        "label": {"English(EN)": "Electoral card photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "electoral_card_photo_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "snapshot_field": "documents__electoral_card__photo",
    },
    {
        "id": "1c7f6c85-1621-48f1-88f3-a172d69aa316",
        "type": TYPE_STRING,
        "name": "unhcr_id_no",
        "lookup": "unhcr_id_no",
        "required": False,
        "label": {"English(EN)": "UNHCR ID number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "unhcr_id_no_i_c",
        "get_query": get_unhcr_id_number_query,
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_unhcr_id_no,
        # "snapshot_field":  # TODO: this one is not added in snapshot
    },
    {
        "id": "801bdd67-d27d-4afa-9d23-823e1c8d1313",
        "type": TYPE_SELECT_ONE,
        "name": "unhcr_id_issuer",
        "lookup": "unhcr_id_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing entity of UNHCR ID"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "unhcr_id_issuer_i_c",
        "get_query": get_unhcr_id_issuer_query,
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_unhcr_id_issuer,
        # "snapshot_field":  # TODO: this one is not added in snapshot
    },
    {
        "id": "2f9ca147-afde-4311-9d61-e906a8ef2334",
        "type": TYPE_IMAGE,
        "name": "unhcr_id_photo",
        "lookup": "unhcr_id_photo",
        "required": False,
        "label": {"English(EN)": "UNHCR ID photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "unhcr_id_photo_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        # "snapshot_field":  # TODO: this one is not added in snapshot
    },
    {
        "id": "4e836832-2cf2-4073-80eb-21316eaf7277",
        "type": TYPE_STRING,
        "name": "national_passport",
        "lookup": "national_passport",
        "required": False,
        "label": {"English(EN)": "National passport number"},
        "hint": "",
        "choices": [],
        "get_query": get_national_passport_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "national_passport_no_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_national_passport_no,
        "snapshot_field": "documents__national_passport__document_number",
    },
    {
        "id": "3da62c17-66ee-4c08-adbf-74402f31dce2",
        "type": TYPE_SELECT_ONE,
        "name": "national_passport_issuer",
        "lookup": "national_passport_issuer",
        "get_query": get_national_passport_issuer_query,
        "required": False,
        "label": {"English(EN)": "Issuing country of national passport"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "national_passport_issuer_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_national_passport_issuer,
        "snapshot_field": "documents__national_passport__country",
    },
    {
        "id": "234a1b5b-7900-4f67-86a9-5fcaede3d09d",
        "type": TYPE_IMAGE,
        "name": "national_passport_photo",
        "lookup": "national_passport_photo",
        "required": False,
        "label": {"English(EN)": "National passport photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "national_passport_photo_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "snapshot_field": "documents__national_passport__photo",
    },
    {
        "id": "eff20a18-4336-4273-bbb8-ed0e9a94ebbb",
        "type": TYPE_STRING,
        "name": "national_id_no",
        "lookup": "national_id_no",
        "required": False,
        "label": {"English(EN)": "National ID number"},
        "hint": "",
        "choices": [],
        "get_query": get_national_id_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "national_id_no_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_national_id_no,
        "snapshot_field": "documents__national_id__document_number",
    },
    {
        "id": "2bd255a7-1273-4a52-930f-6660573b2743",
        "type": TYPE_SELECT_ONE,
        "name": "national_id_issuer",
        "lookup": "national_id_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of national ID"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "get_query": get_national_id_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "national_id_issuer_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_national_id_issuer,
        "snapshot_field": "documents__national_id__country",
    },
    {
        "id": "d43304d9-91e4-4317-9356-f7066b898b16",
        "type": TYPE_IMAGE,
        "name": "national_id_photo",
        "lookup": "national_id_photo",
        "required": False,
        "label": {"English(EN)": "National ID photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "national_id_photo_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "snapshot_field": "documents__national_id__photo",
    },
    {
        "id": "201c91d2-8f89-46c9-ba5a-db7130140402",
        "type": TYPE_STRING,
        "name": "scope_id_no",
        "lookup": "scope_id_no",
        "required": False,
        "label": {"English(EN)": "WFP Scope ID number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "scope_id_no_i_c",
        "get_query": get_scope_id_number_query,
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_scope_id_no,
        # "snapshot_field":  # TODO: this one is not added in snapshot
    },
    {
        "id": "638a6383-6e87-4c4f-842c-6c5433599267",
        "type": TYPE_SELECT_ONE,
        "name": "scope_id_issuer",
        "lookup": "scope_id_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing entity of SCOPE ID"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "scope_id_issuer_i_c",
        "get_query": get_scope_id_issuer_query,
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_scope_id_issuer,
        # "snapshot_field":  # TODO: this one is not added in snapshot
    },
    {
        "id": "4aa3d595-131a-48df-8752-ec171eabe3be",
        "type": TYPE_IMAGE,
        "name": "scope_id_photo",
        "lookup": "scope_id_photo",
        "required": False,
        "label": {"English(EN)": "WFP Scope ID photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "scope_id_photo_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        # "snapshot_field":  # TODO: this one is not added in snapshot
    },
    {
        "id": "3bf6105f-87d0-479b-bf92-7f90af4d8462",
        "type": TYPE_STRING,
        "name": "other_id_type",
        "lookup": "other_id_type",
        "required": False,
        "label": {"English(EN)": "If other type of ID, specify the type"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "other_id_type_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        # "snapshot_field":  # TODO: this one is not added in snapshot
    },
    {
        "id": "556e14af-9901-47f3-bf2c-20b4c721e8f7",
        "type": TYPE_STRING,
        "name": "other_id_no",
        "lookup": "other_id_no",
        "required": False,
        "label": {"English(EN)": "Other ID number"},
        "hint": "",
        "choices": [],
        "get_query": get_other_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "other_id_no_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_other_id_no,
        "snapshot_field": "documents__other_id__document_number",
    },
    {
        "id": "cd181a09-f4c5-4a47-8713-25bdc4a64058",
        "type": TYPE_SELECT_ONE,
        "name": "other_id_issuer",
        "lookup": "other_id_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of other ID"},
        "hint": "",
        "_choices": lambda *args, **kwargs: Country.get_choices(),
        "choices": [],
        "get_query": get_other_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "other_id_issuer_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "lookup_function": get_other_id_issuer,
        "snapshot_field": "documents__other_id__country",
    },
    {
        "id": "d4279a74-377f-4f74-baf2-e1ebd001ec5c",
        "type": TYPE_IMAGE,
        "name": "other_id_photo",
        "lookup": "other_id_photo",
        "required": False,
        "label": {"English(EN)": "ID photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "other_id_photo_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
        "snapshot_field": "documents__other_id__photo",
    },
    {
        "id": "07f7005f-e70d-409b-9dee-4c3414aba40b",
        "type": TYPE_INTEGER,
        "name": "female_age_group_0_5_count",
        "lookup": "female_age_group_0_5_count",
        "required": False,
        "label": {"English(EN)": "Females Age 0 - 5"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_0_5_age_group_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "6b993af8-4a5d-4a08-a444-8ade115c39ad",
        "type": TYPE_INTEGER,
        "name": "female_age_group_6_11_count",
        "lookup": "female_age_group_6_11_count",
        "required": False,
        "label": {"English(EN)": "Females Age 6 - 11"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_6_11_age_group_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "71ce16b5-4e49-48fa-818c-0bd2eba079eb",
        "type": TYPE_INTEGER,
        "name": "female_age_group_12_17_count",
        "lookup": "female_age_group_12_17_count",
        "required": False,
        "label": {"English(EN)": "Females Age 12 - 17"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_12_17_age_group_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "1af02ab4-469b-4de1-a71a-7d51cc86224b",
        "type": TYPE_INTEGER,
        "name": "female_age_group_18_59_count",
        "lookup": "female_age_group_18_59_count",
        "required": False,
        "label": {"English(EN)": "Females Age 18 - 59"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_18_59_age_group_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "4009ca04-1ffd-48eb-a41f-64ddb439cc8d",
        "type": TYPE_INTEGER,
        "name": "female_age_group_60_count",
        "lookup": "female_age_group_60_count",
        "required": False,
        "label": {"English(EN)": "Females Age 60 +"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_60_age_group_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "18fd9429-400f-4fce-b72f-035d2afca201",
        "type": TYPE_INTEGER,
        "name": "pregnant_count",
        "lookup": "pregnant_count",
        "required": False,
        "label": {"English(EN)": "Pregnant count"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "pregnant_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "57233f1b-93c3-4fd4-a885-92c512c5e32a",
        "type": TYPE_INTEGER,
        "name": "male_age_group_0_5_count",
        "lookup": "male_age_group_0_5_count",
        "required": False,
        "label": {"English(EN)": "Males Age 0 - 5"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_0_5_age_group_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "11e2a938-e93a-4c18-8eca-7e61355d7476",
        "type": TYPE_INTEGER,
        "name": "male_age_group_6_11_count",
        "lookup": "male_age_group_6_11_count",
        "required": False,
        "label": {"English(EN)": "Males Age 6 - 11"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_6_11_age_group_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "bf28628e-0f6a-46e8-9587-3b0c17977006",
        "type": TYPE_INTEGER,
        "name": "male_age_group_12_17_count",
        "lookup": "male_age_group_12_17_count",
        "required": False,
        "label": {"English(EN)": "Males Age 12 - 17"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_12_17_age_group_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "e76cd764-1466-49c3-92da-5a558069c472",
        "type": TYPE_INTEGER,
        "name": "male_age_group_18_59_count",
        "lookup": "male_age_group_18_59_count",
        "required": False,
        "label": {"English(EN)": "Males Age 18 - 59"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_18_59_age_group_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "988ebe6d-8782-4bc1-95a0-eeb692980847",
        "type": TYPE_INTEGER,
        "name": "male_age_group_60_count",
        "lookup": "male_age_group_60_count",
        "required": False,
        "label": {"English(EN)": "Males Age 60 +"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_60_age_group_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "4f59aca6-5900-40c0-a1e4-47c331a90a6f",
        "type": TYPE_INTEGER,
        "name": "female_age_group_0_5_disabled_count",
        "lookup": "female_age_group_0_5_disabled_count",
        "required": False,
        "label": {"English(EN)": "Females age 0 - 5 with disability"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_0_5_disability_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "10e33d7b-b3c4-4383-a4f0-6eba00a15e9c",
        "type": TYPE_INTEGER,
        "name": "female_age_group_6_11_disabled_count",
        "lookup": "female_age_group_6_11_disabled_count",
        "required": False,
        "label": {"English(EN)": "Females age 6 - 11 with disability"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_6_11_disability_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "623a6fd6-d863-40cc-a4d1-964f739747be",
        "type": TYPE_INTEGER,
        "name": "female_age_group_12_17_disabled_count",
        "lookup": "female_age_group_12_17_disabled_count",
        "required": False,
        "label": {"English(EN)": "Females age 12 - 17 with disability"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_12_17_disability_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "c99df741-4559-4166-a49c-05d69ba8a4fa",
        "type": TYPE_INTEGER,
        "name": "female_age_group_18_59_disabled_count",
        "lookup": "female_age_group_18_59_disabled_count",
        "required": False,
        "label": {"English(EN)": "Females Age 18 - 59 with disability"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_18_59_disability_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "f21d61f2-923e-46b8-aefc-b623cb0026ca",
        "type": TYPE_INTEGER,
        "name": "female_age_group_60_disabled_count",
        "lookup": "female_age_group_60_disabled_count",
        "required": False,
        "label": {"English(EN)": "Female members with Disability age 60 +"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_60_disability_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "d3b82576-1bba-44fa-9d5a-db04e71bb35b",
        "type": TYPE_INTEGER,
        "name": "male_age_group_0_5_disabled_count",
        "lookup": "male_age_group_0_5_disabled_count",
        "required": False,
        "label": {"English(EN)": "Males age 0 - 5 with disability"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_0_5_disability_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "78340f8f-86ab-464a-8e19-ce3d6feec5d6",
        "type": TYPE_INTEGER,
        "name": "male_age_group_6_11_disabled_count",
        "lookup": "male_age_group_6_11_disabled_count",
        "required": False,
        "label": {"English(EN)": "Males age 6 - 11 with disability"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_6_11_disability_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "519140f7-1a9e-4115-b736-2b09dbc6f036",
        "type": TYPE_INTEGER,
        "name": "male_age_group_12_17_disabled_count",
        "lookup": "male_age_group_12_17_disabled_count",
        "required": False,
        "label": {"English(EN)": "Males age 12 - 17 with disability"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_12_17_disability_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "9c6e1d87-0768-4db7-b925-41da8b5c7988",
        "type": TYPE_INTEGER,
        "name": "male_age_group_18_59_disabled_count",
        "lookup": "male_age_group_18_59_disabled_count",
        "required": False,
        "label": {"English(EN)": "Males Age 18 - 59 with disability"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_18_59_disability_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "c07da769-b7c4-4e4f-aefa-1a20bb24d8b2",
        "type": TYPE_INTEGER,
        "name": "male_age_group_60_disabled_count",
        "lookup": "male_age_group_60_disabled_count",
        "required": False,
        "label": {"English(EN)": "Male members with Disability age 60 +"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_60_disability_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE],
    },
    {
        "id": "b2593385-5a81-452e-ae9a-28292e35714b",
        "type": TYPE_BOOL,
        "name": "pregnant",
        "lookup": "pregnant",
        "required": False,
        "label": {"English(EN)": f"Is the {TEMPLATE_INDIVIDUAL} pregnant?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pregnant_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "dca6748f-7831-4fa1-b5c8-e708a456656b",
        "type": TYPE_SELECT_ONE,
        "name": "work_status",
        "lookup": "work_status",
        "required": False,
        "label": {"English(EN)": f"Does the {TEMPLATE_INDIVIDUAL} have paid employment in the current month?"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in WORK_STATUS_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "work_status_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "21cd9a35-b080-4f60-97da-6ec6918a49c0",
        "type": TYPE_SELECT_MANY,
        "name": "observed_disability",
        "lookup": "observed_disability",
        "required": False,
        "label": {"English(EN)": f"Does the {TEMPLATE_INDIVIDUAL} have disability?"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in OBSERVED_DISABILITY_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "observed_disability_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "244ec9ae-5eb8-4b80-9416-91024a3f32d7",
        "type": TYPE_SELECT_ONE,
        "name": "seeing_disability",
        "lookup": "seeing_disability",
        "required": False,
        "label": {"English(EN)": f"If the {TEMPLATE_INDIVIDUAL} has difficulty seeing, what is the severity?"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "seeing_disability_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "bef35c02-1fe7-4f6b-a0af-8282ec31de89",
        "type": TYPE_SELECT_ONE,
        "name": "hearing_disability",
        "lookup": "hearing_disability",
        "required": False,
        "label": {"English(EN)": f"If the {TEMPLATE_INDIVIDUAL} has difficulty hearing, what is the severity?"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "hearing_disability_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "b7346b1f-23ea-47a8-b2ec-c176c62cdb5b",
        "type": TYPE_SELECT_ONE,
        "name": "physical_disability",
        "lookup": "physical_disability",
        "required": False,
        "label": {
            "English(EN)": f"If the {TEMPLATE_INDIVIDUAL} has difficulty walking or climbing steps, what is the severity?"
        },
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "physical_disability_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "0f24c374-4428-43ef-b162-86dc1b14e39d",
        "type": TYPE_SELECT_ONE,
        "name": "memory_disability",
        "lookup": "memory_disability",
        "required": False,
        "label": {
            "English(EN)": f"If the {TEMPLATE_INDIVIDUAL} has difficulty remembering or concentrating, what is the severity?"
        },
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "memory_disability_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "59508af1-07d0-4e20-ac3d-f241bef319c1",
        "type": TYPE_SELECT_ONE,
        "name": "selfcare_disability",
        "lookup": "selfcare_disability",
        "required": False,
        "label": {"English(EN)": "Do you have difficulty (with self-care such as) washing all over or dressing"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "selfcare_disability_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "78311be2-fb3f-443c-aac6-c0e7197af20d",
        "type": TYPE_SELECT_ONE,
        "name": "comms_disability",
        "lookup": "comms_disability",
        "required": False,
        "label": {"English(EN)": f"If the {TEMPLATE_INDIVIDUAL} has difficulty communicating, what is the severity?"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "comms_disability_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "9fbd2b6f-6713-445c-a7bb-e1efc398b20d",
        "type": TYPE_BOOL,
        "name": "fchild_hoh",
        "lookup": "fchild_hoh",
        "required": False,
        "label": {"English(EN)": f"Female child headed {TEMPLATE_HOUSEHOLD}"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "fchild_hoh_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT],
    },
    {
        "id": "e92810b2-c6f1-480c-95a9-4f736a1f48bf",
        "type": TYPE_BOOL,
        "name": "child_hoh",
        "lookup": "child_hoh",
        "required": False,
        "label": {"English(EN)": f"Child headed {TEMPLATE_HOUSEHOLD}"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "child_hoh_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT],
    },
    {
        "id": "62692d6a-c054-418b-803a-e34393cbc1b0",
        "type": TYPE_STRING,
        "name": "village",
        "lookup": "village",
        "required": False,
        "label": {"English(EN)": "Village"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "village_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "c640fe45-368f-4206-afae-09700a495db3",
        "type": TYPE_STRING,
        "name": "deviceid",
        "lookup": "deviceid",
        "required": False,
        "label": {"English(EN)": "Device ID"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "deviceid",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
    },
    {
        "id": "8f379d33-c5fd-4344-ba2b-73e136aba13a",
        "type": TYPE_STRING,
        "name": "name_enumerator",
        "lookup": "name_enumerator",
        "required": False,
        "label": {"English(EN)": "Name of the enumerator"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "name_enumerator_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "201e9a88-fb7d-4ba4-afec-66aba748fe55",
        "type": TYPE_SELECT_ONE,
        "name": "org_enumerator",
        "lookup": "org_enumerator",
        "required": False,
        "label": {"English(EN)": "Organization of the enumerator"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in ORG_ENUMERATOR_CHOICES],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "org_enumerator_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "0858371e-4e5c-402e-9cda-b767eb2d337c",
        "type": TYPE_SELECT_MANY,
        "name": "consent_sharing",
        "lookup": "consent_sharing",
        "required": False,
        "label": {"English(EN)": "Which organizations may we share your information with?"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in DATA_SHARING_CHOICES],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "consent_sharing_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
    },
    {
        "id": "27bd4ef2-442d-4b49-976c-063df050b3ae",
        "type": TYPE_STRING,
        "name": "org_name_enumerator",
        "lookup": "org_name_enumerator",
        "required": False,
        "label": {"English(EN)": "Name of partner organization"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "org_name_enumerator_h_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.HOUSEHOLD_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "69dbc5f2-039f-4671-b39f-a63d96475cab",
        "type": TYPE_SELECT_ONE,
        "name": "disability",
        "lookup": "disability",
        "required": False,
        "label": {"English(EN)": f"{TEMPLATE_INDIVIDUAL} is disabled?"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in DISABILITY_CHOICES],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "disability_i_c",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "6536a987-a50e-453b-9517-57c1dccd1340",
        "type": TYPE_DATE,
        "name": "first_registration_date",
        "lookup": "first_registration_date",
        "required": True,
        "label": {"English(EN)": f"First {TEMPLATE_INDIVIDUAL} registration date"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "first_registration_date_i_c",
        "scope": [Scope.GLOBAL, Scope.XLSX, Scope.TARGETING, Scope.XLSX_PEOPLE],
    },
    {
        "id": "2fe6d876-388f-45d9-b497-eb2f8af923e8",
        "type": TYPE_DATE,
        "name": "first_registration_date",
        "lookup": "first_registration_date",
        "required": True,
        "label": {"English(EN)": f"First {TEMPLATE_HOUSEHOLD} registration date"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "first_registration_date_h_c",
        "scope": [Scope.GLOBAL, Scope.XLSX, Scope.TARGETING],
    },
    {
        "id": "c8da2910-4348-47ab-a82e-725b4cebc332",
        "type": TYPE_INTEGER,
        "name": "number_of_children",
        "lookup": "children_count",
        "label": {"English(EN)": f"What is the number of children in the {TEMPLATE_HOUSEHOLD}?"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "number_of_children",
        "scope": [Scope.TARGETING],
    },
    {
        "id": "bc18c462-bd75-4607-b75d-b7111a658453",
        "type": TYPE_BOOL,
        "name": "has_phone_number",
        "lookup": "has_phone_number",
        "get_query": get_has_phone_number_query,
        "label": {"English(EN)": "Has phone number?"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "has_phone_number",
        "scope": [Scope.TARGETING],
        # "snapshot_field":  # TODO: this one is not added in snapshot
    },
    {
        "id": "f4032e4f-00a9-4ed9-bff4-4e47d2f7b4be",
        "type": TYPE_BOOL,
        "name": "has_tax_id_number",
        "lookup": "has_tax_id_number",
        "get_query": get_has_tax_id_query,
        "label": {"English(EN)": "Has tax ID number?"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "has_tax_ID_number",
        "scope": [Scope.TARGETING],
        # "snapshot_field":  # TODO: this one is not added in snapshot
    },
    {
        "id": "6b97e9a3-38bb-49a3-9637-65f05d5b8ea4",
        "type": TYPE_BOOL,
        "name": "has_the_bank_account_number",
        "lookup": "has_the_bank_account_number",
        "get_query": get_has_bank_account_number_query,
        "label": {"English(EN)": "Has the bank account number?"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "has_the_bank_account_number",
        "scope": [Scope.TARGETING],
        # "snapshot_field":  # TODO: this one is not added in snapshot
    },
    {
        "id": "0bf5fad3-8f4f-4528-85f7-57e8a84a2a43",
        "type": TYPE_SELECT_ONE,
        "name": "role",
        "lookup": "role",
        "required": True,
        "label": {"English(EN)": "Role"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in ROLE_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "role_i_c",
        "get_query": get_role_query,
        "scope": [Scope.TARGETING, Scope.KOBO_IMPORT, Scope.INDIVIDUAL_UPDATE],
        "snapshot_field": "roles__role__individual__id",  # TODO: add method for get role from snapshot
    },
    {
        "id": "a1662e94-5d8b-46a7-8c9a-7c72b280f497",
        "type": TYPE_SELECT_MANY,
        "name": "registration_data_import",
        "lookup": "registration_data_import__pk",
        "get_query": registration_data_import_query,
        "required": False,
        "label": {"English(EN)": "Registration Data Import"},
        "hint": "",
        "_choices": lambda *args, **kwargs: RegistrationDataImport.get_choices(*args, **kwargs),
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "registration_data_import",
        "scope": [Scope.TARGETING, Scope.XLSX_PEOPLE],
    },
    {
        "id": "e4aa9cdf-2c9e-4e22-9928-2b63a6ea4ef0",
        "type": TYPE_SELECT_MANY,
        "name": "registration_data_import",
        "lookup": "registration_data_import__pk",
        "get_query": registration_data_import_query,
        "required": False,
        "label": {"English(EN)": "Registration Data Import"},
        "hint": "",
        "_choices": lambda *args, **kwargs: RegistrationDataImport.get_choices(*args, **kwargs),
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "registration_data_import",
        "scope": [Scope.TARGETING],
    },
    {
        "id": "df2b2588-68af-4dea-89ab-c5a53a5764be",
        "type": TYPE_STRING,
        "name": "household_unicef_id",
        "lookup": "unicef_id",
        "required": False,
        "label": {"English(EN)": f"{TEMPLATE_HOUSEHOLD} unicef id"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "unicef_id_h_c",
        "scope": [Scope.INDIVIDUAL_XLSX_UPDATE],
    },
    {
        "id": "bb9bcb76-c9e4-4e83-8b9a-6c8bb35cb84c",
        "type": TYPE_STRING,
        "name": "individual_unicef_id",
        "lookup": "unicef_id",
        "required": False,
        "label": {"English(EN)": f"{TEMPLATE_INDIVIDUAL} unicef id"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "unicef_id_i_c",
        "scope": [Scope.INDIVIDUAL_XLSX_UPDATE],
    },
    {
        "id": "e48a4e26-6552-4e15-855f-9ea4d5268c84",
        "type": TYPE_SELECT_ONE,
        "name": "admin_area_title",
        "lookup": "admin_area__p_code",
        "required": False,
        "label": {"English(EN)": f"{TEMPLATE_HOUSEHOLD} resides in which admin area?"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "admin_area_h_c",
        "scope": [Scope.HOUSEHOLD_UPDATE],
        "snapshot_field": "admin_area_id__p_code",
    },
    {
        "id": "9da8c56a-3c65-47d9-8149-699761842ce4",
        "type": TYPE_STRING,
        "name": "start",
        "lookup": "start",
        "required": True,
        "label": {"English(EN)": "Data collection start date"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "start",
        "scope": [Scope.KOBO_IMPORT],
    },
    {
        "id": "06e4c4a0-28d2-4530-be24-92623a5b48b0",
        "type": TYPE_STRING,
        "name": "end",
        "lookup": "end",
        "required": True,
        "label": {"English(EN)": "Data collection end date"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "end",
        "scope": [Scope.KOBO_IMPORT],
        # "snapshot_field":  # TODO: this one is not added in snapshot
    },
    {
        "id": "16e68909-54f4-47cb-ab06-066d13e85134",
        "type": TYPE_LIST_OF_IDS,
        "name": "primary_collector_id",
        "lookup": "primary_collector_id",
        "required": False,
        "label": {"English(EN)": "List of primary collectors ids, separated by a semicolon"},
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "primary_collector_id",
        "custom_cast_value": Countries.get_country_value,
        "scope": [Scope.COLLECTOR, Scope.XLSX_PEOPLE],
        "snapshot_field": "primary_collector__id",
    },
    {
        "id": "d7f41696-94e5-4e0c-ab1b-20ff27c25364",
        "type": TYPE_LIST_OF_IDS,
        "name": "alternate_collector_id",
        "lookup": "alternate_collector_id",
        "required": False,
        "label": {"English(EN)": "List of alternate collectors ids, separated by a semicolon"},
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "alternate_collector_id",
        "custom_cast_value": Countries.get_country_value,
        "scope": [Scope.COLLECTOR, Scope.XLSX_PEOPLE],
        "snapshot_field": "alternate_collector__id",
    },
    {
        "id": "746b3d2d-19c5-4b91-ad37-d230e1d33eb5",
        "type": TYPE_ID,
        "name": "household_id",
        "lookup": "household_id",
        "required": False,
        "label": {"English(EN)": f"{TEMPLATE_HOUSEHOLD} ID"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "household_id",
        "scope": [Scope.HOUSEHOLD_ID],
    },
    {
        "id": "1079bfd0-fc51-41ab-aa10-667e6b2034b9",
        "type": TYPE_ID,
        "name": "household_id",
        "lookup": "household_id",
        "required": False,
        "label": {"English(EN)": f"{TEMPLATE_HOUSEHOLD} ID"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "household_id",
        "scope": [Scope.HOUSEHOLD_ID],
    },
    {
        "id": "519af6bf-3e8c-4899-a4f4-360ce55648e0",
        "type": TYPE_STRING,
        "name": "email",
        "lookup": "email",
        "required": False,
        "label": {"English(EN)": f"{TEMPLATE_INDIVIDUAL} email"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "email",
        "scope": [Scope.XLSX, Scope.INDIVIDUAL_UPDATE, Scope.INDIVIDUAL_XLSX_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "e2b8dd27-f861-4c54-9651-677636918c47",
        "type": TYPE_SELECT_ONE,
        "name": "preferred_language",
        "lookup": "preferred_language",
        "required": False,
        "label": {"English(EN)": "Preferred language"},
        "hint": "",
        "choices": Languages.get_choices(),
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "preferred_language",
        "scope": [Scope.XLSX, Scope.INDIVIDUAL_UPDATE, Scope.XLSX_PEOPLE],
    },
    {
        "id": "32fcdace-6e72-48ac-9ce8-469e552cfafe",
        "type": TYPE_INTEGER,
        "name": "age_at_registration",
        "lookup": "age_at_registration",
        "label": {"English(EN)": "Age at registration"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "age_at_registration",
        "scope": [Scope.GLOBAL, Scope.TARGETING, Scope.KOBO_IMPORT, Scope.XLSX_PEOPLE],
    },
    {
        # just using specifically for people import for mapping collector and beneficiary
        "id": "bec7a6b9-476d-48a8-8822-e24ae023df42",
        "type": TYPE_INTEGER,
        "name": "index_id",
        "lookup": "index_id",
        "required": True,
        "label": {"English(EN)": "Index ID"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "index_id",
        "scope": [Scope.XLSX_PEOPLE],
    },
    {
        "id": "15b7b623-0dee-4212-a32a-a6d6f6877b4e",
        "type": TYPE_STRING,
        "name": "wallet_name",
        "lookup": "wallet_name",
        "label": {"English(EN)": "Wallet Name"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "wallet_name_i_c",
        "scope": [Scope.XLSX, Scope.INDIVIDUAL_UPDATE],
    },
    {
        "id": "0010bc3e-0a4a-452b-a776-2cc4b760a0fd",
        "type": TYPE_STRING,
        "name": "blockchain_name",
        "lookup": "blockchain_name",
        "label": {"English(EN)": "Blockchain Name"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "blockchain_name_i_c",
        "scope": [Scope.XLSX, Scope.INDIVIDUAL_UPDATE],
    },
    {
        "id": "15d35efa-8f36-4a40-b9ed-a7812a665e01",
        "type": TYPE_STRING,
        "name": "wallet_address",
        "lookup": "wallet_address",
        "label": {"English(EN)": "Wallet Address"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "wallet_address_i_c",
        "scope": [Scope.XLSX, Scope.INDIVIDUAL_UPDATE],
    },
    {
        "id": "8ef6fd85-032f-42cf-8f1f-3398f88316af",
        "type": TYPE_STRING,
        "name": "program_registration_id",
        "lookup": "program_registration_id",
        "label": {"English(EN)": "Program registration id"},
        "hint": "",
        "required": False,
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "program_registration_id_h_c",
        "scope": [Scope.KOBO_IMPORT],
    },
] + PAYMENT_CHANNEL_FIELDS_ATTRIBUTES


def get_core_fields_attributes() -> List[Dict[str, Any]]:
    from hct_mis_api.apps.payment.models import DeliveryMechanism

    return CORE_FIELDS_ATTRIBUTES + DeliveryMechanism.get_all_core_fields_definitions()


class FieldFactory(list):
    def __init__(
        self, fields: Optional[Any] = None, scopes: Optional[Set[Scope]] = None, *args: Any, **kwargs: Any
    ) -> None:
        super().__init__(*args, **kwargs)
        self.scopes: Set = scopes or set()
        self.all_fields = copy.deepcopy(get_core_fields_attributes())
        if fields:
            self.extend(copy.deepcopy(fields))

    def extend(self, __iterable: Iterable[dict]) -> None:
        items = list(__iterable)
        for item in items:
            if item not in self:
                self._fill_label_template(item)
        super().extend(items)

    def append(self, attr: dict) -> None:
        self._fill_label_template(attr)
        super().append(attr)

    def _fill_label_template(self, field: dict, language: str = "English(EN)") -> Optional[str]:
        label_with_template = field["label"].get(language)
        if not label_with_template:
            return None
        mapping_dict = TEMPLATE_MAPPING_NORMAL if Scope.XLSX_PEOPLE not in self.scopes else TEMPLATE_MAPPING_PEOPLE
        for mapping in mapping_dict.items():
            label_with_template = label_with_template.replace(mapping[0], mapping[1])
        field["label"][language] = label_with_template
        return label_with_template

    @classmethod
    def from_scopes(cls, scopes: list[Scope]) -> "FieldFactory":
        factory = cls()
        all_fields = copy.deepcopy(factory.all_fields)
        factory.scopes.update(scopes)
        factory.extend(filter(lambda field: any(True for scope in scopes if scope in field["scope"]), all_fields))
        if Scope.XLSX_PEOPLE in scopes:
            for field_attr in factory:
                field_attr["xlsx_field"] = "pp_" + field_attr["xlsx_field"].replace("_h_c", "_i_c")
        return factory

    @classmethod
    def from_only_scopes(cls, scopes: list[Scope]) -> "FieldFactory":
        factory = cls()
        all_fields = copy.deepcopy(factory.all_fields)
        factory.scopes.update(scopes)
        factory.extend(filter(lambda field: all(scope in field["scope"] for scope in scopes), all_fields))
        if Scope.XLSX_PEOPLE in scopes:
            for field_attr in factory:
                field_attr["xlsx_field"] = "pp_" + field_attr["xlsx_field"].replace("_h_c", "_i_c")
        return factory

    @classmethod
    def from_scope(cls, scope: Scope) -> "FieldFactory":
        factory = cls()
        all_fields = copy.deepcopy(factory.all_fields)
        factory.scopes.add(scope)
        factory.extend(filter(lambda field: scope in field["scope"], all_fields))
        if scope == Scope.XLSX_PEOPLE:
            for field_attr in factory:
                field_attr["xlsx_field"] = "pp_" + field_attr["xlsx_field"].replace("_h_c", "_i_c")
        return factory

    @classmethod
    def not_from_scope(cls, scope: Scope) -> "FieldFactory":
        factory = cls()
        all_fields = copy.deepcopy(factory.all_fields)
        factory.extend(filter(lambda field: scope not in field["scope"], all_fields))
        factory.scopes.add(scope)
        return factory

    def and_scope(self, scope: Scope) -> "FieldFactory":
        factory = FieldFactory(self, self.scopes)

        if scope not in self.scopes:
            all_fields = copy.deepcopy(factory.all_fields)
            factory.scopes.add(scope)
            factory.extend(filter(lambda field: scope in field["scope"], all_fields))
        return factory

    def filtered_by_types(self, types: List) -> "FieldFactory":
        factory = FieldFactory(scopes=self.scopes)

        for item in self:
            if item.get("type") in types:
                factory.append(item)
        return factory

    def associated_with_individual(self) -> "FieldFactory":
        return self._associated_with([_INDIVIDUAL])

    def associated_with_individual_with_delivery_mechanism_data(self) -> "FieldFactory":
        return self._associated_with([_INDIVIDUAL, _DELIVERY_MECHANISM_DATA])

    def associated_with_household(self) -> "FieldFactory":
        return self._associated_with([_HOUSEHOLD])

    def _associated_with(self, associated_with: List[str]) -> "FieldFactory":
        factory = FieldFactory(scopes=self.scopes)
        for item in self:
            if item.get("associated_with") in associated_with:
                factory.append(item)
        return factory

    def to_dict_by(self, attr: str) -> Dict:
        return reduce(lambda pre, curr: {**pre, curr[attr]: curr}, self, {})

    def to_choices(self) -> List[Any]:
        return [(x["name"], x["label"]["English(EN)"]) for x in self]

    def apply_business_area(
        self,
        business_area_slug: Optional[str] = None,
        program_id: Optional[str] = None,
    ) -> "FieldFactory":
        factory = FieldFactory(self, self.scopes)
        for field in factory:
            choices = field.get("_choices")
            if callable(choices):
                field["choices"] = choices(business_area_slug=business_area_slug, program_id=program_id)
        return factory

    @classmethod
    def get_all_core_fields_choices(cls) -> List:
        factory = cls()
        factory.extend(factory.all_fields)
        return factory.to_choices()
