# Generated by Django 2.2.16 on 2021-04-15 20:18

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import model_utils.fields
import multiselectfield.db.fields
import phonenumber_field.modelfields
import sorl.thumbnail.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportData',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('file', models.FileField(upload_to='')),
                ('data_type', models.CharField(choices=[('XLSX', 'XLSX File'), ('JSON', 'JSON File')], default='XLSX', max_length=4)),
                ('number_of_households', models.PositiveIntegerField()),
                ('number_of_individuals', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportedAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'unique_together': {('country', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ImportedHousehold',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('consent_sign', sorl.thumbnail.fields.ImageField(blank=True, upload_to='', validators=[django.core.validators.validate_image_file_extension])),
                ('consent', models.NullBooleanField()),
                ('consent_sharing', multiselectfield.db.fields.MultiSelectField(choices=[('', 'None'), ('UNICEF', 'UNICEF'), ('HUMANITARIAN_PARTNER', 'Humanitarian partners'), ('PRIVATE_PARTNER', 'Private partners'), ('GOVERNMENT_PARTNER', 'Government partners')], default='', max_length=63)),
                ('residence_status', models.CharField(choices=[('', 'None'), ('IDP', 'Displaced  |  Internally Displaced People'), ('REFUGEE', 'Displaced  |  Refugee / Asylum Seeker'), ('OTHERS_OF_CONCERN', 'Displaced  |  Others of Concern'), ('HOST', 'Non-displaced  |   Host'), ('NON_HOST', 'Non-displaced  |   Non-host')], max_length=255)),
                ('country_origin', django_countries.fields.CountryField(max_length=2)),
                ('size', models.PositiveIntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('admin1', models.CharField(blank=True, default='', max_length=255)),
                ('admin1_title', models.CharField(blank=True, default='', max_length=255)),
                ('admin2', models.CharField(blank=True, default='', max_length=255)),
                ('admin2_title', models.CharField(blank=True, default='', max_length=255)),
                ('geopoint', django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326)),
                ('female_age_group_0_5_count', models.PositiveIntegerField(default=None, null=True)),
                ('female_age_group_6_11_count', models.PositiveIntegerField(default=None, null=True)),
                ('female_age_group_12_17_count', models.PositiveIntegerField(default=None, null=True)),
                ('female_age_group_18_59_count', models.PositiveIntegerField(default=None, null=True)),
                ('female_age_group_60_count', models.PositiveIntegerField(default=None, null=True)),
                ('pregnant_count', models.PositiveIntegerField(default=None, null=True)),
                ('male_age_group_0_5_count', models.PositiveIntegerField(default=None, null=True)),
                ('male_age_group_6_11_count', models.PositiveIntegerField(default=None, null=True)),
                ('male_age_group_12_17_count', models.PositiveIntegerField(default=None, null=True)),
                ('male_age_group_18_59_count', models.PositiveIntegerField(default=None, null=True)),
                ('male_age_group_60_count', models.PositiveIntegerField(default=None, null=True)),
                ('female_age_group_0_5_disabled_count', models.PositiveIntegerField(default=None, null=True)),
                ('female_age_group_6_11_disabled_count', models.PositiveIntegerField(default=None, null=True)),
                ('female_age_group_12_17_disabled_count', models.PositiveIntegerField(default=None, null=True)),
                ('female_age_group_18_59_disabled_count', models.PositiveIntegerField(default=None, null=True)),
                ('female_age_group_60_disabled_count', models.PositiveIntegerField(default=None, null=True)),
                ('male_age_group_0_5_disabled_count', models.PositiveIntegerField(default=None, null=True)),
                ('male_age_group_6_11_disabled_count', models.PositiveIntegerField(default=None, null=True)),
                ('male_age_group_12_17_disabled_count', models.PositiveIntegerField(default=None, null=True)),
                ('male_age_group_18_59_disabled_count', models.PositiveIntegerField(default=None, null=True)),
                ('male_age_group_60_disabled_count', models.PositiveIntegerField(default=None, null=True)),
                ('fchild_hoh', models.NullBooleanField()),
                ('child_hoh', models.NullBooleanField()),
                ('first_registration_date', models.DateTimeField()),
                ('last_registration_date', models.DateTimeField()),
                ('returnee', models.NullBooleanField()),
                ('flex_fields', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('deviceid', models.CharField(blank=True, max_length=250)),
                ('name_enumerator', models.CharField(blank=True, default='', max_length=250)),
                ('org_enumerator', models.CharField(blank=True, choices=[('', 'None'), ('UNICEF', 'UNICEF'), ('PARTNER', 'Partner')], default='', max_length=250)),
                ('org_name_enumerator', models.CharField(blank=True, default='', max_length=250)),
                ('village', models.CharField(blank=True, default='', max_length=250)),
                ('registration_method', models.CharField(choices=[('', 'None'), ('HH_REGISTRATION', 'Household Registration'), ('COMMUNITY', 'Community-level Registration')], default='', max_length=250)),
                ('collect_individual_data', models.CharField(choices=[('', 'None'), ('1', 'Yes'), ('0', 'No')], default='', max_length=250)),
                ('currency', models.CharField(choices=[('', 'None'), ('AED', 'United Arab Emirates dirham'), ('AFN', 'Afghan afghani'), ('ALL', 'Albanian lek'), ('AMD', 'Armenian dram'), ('ANG', 'Netherlands Antillean guilder'), ('AOA', 'Angolan kwanza'), ('ARS', 'Argentine peso'), ('AUD', 'Australian dollar'), ('AWG', 'Aruban florin'), ('AZN', 'Azerbaijani manat'), ('BAM', 'Bosnia and Herzegovina convertible mark'), ('BBD', 'Barbados dollar'), ('BDT', 'Bangladeshi taka'), ('BGN', 'Bulgarian lev'), ('BHD', 'Bahraini dinar'), ('BIF', 'Burundian franc'), ('BMD', 'Bermudian dollar'), ('BND', 'Brunei dollar'), ('BOB', 'Boliviano'), ('BOV', 'Bolivian Mvdol (funds code)'), ('BRL', 'Brazilian real'), ('BSD', 'Bahamian dollar'), ('BTN', 'Bhutanese ngultrum'), ('BWP', 'Botswana pula'), ('BYN', 'Belarusian ruble'), ('BZD', 'Belize dollar'), ('CAD', 'Canadian dollar'), ('CDF', 'Congolese franc'), ('CHF', 'Swiss franc'), ('CLP', 'Chilean peso'), ('CNY', 'Chinese yuan'), ('COP', 'Colombian peso'), ('CRC', 'Costa Rican colon'), ('CUC', 'Cuban convertible peso'), ('CUP', 'Cuban peso'), ('CVE', 'Cape Verdean escudo'), ('CZK', 'Czech koruna'), ('DJF', 'Djiboutian franc'), ('DKK', 'Danish krone'), ('DOP', 'Dominican peso'), ('DZD', 'Algerian dinar'), ('EGP', 'Egyptian pound'), ('ERN', 'Eritrean nakfa'), ('ETB', 'Ethiopian birr'), ('EUR', 'Euro'), ('FJD', 'Fiji dollar'), ('FKP', 'Falkland Islands pound'), ('GBP', 'Pound sterling'), ('GEL', 'Georgian lari'), ('GHS', 'Ghanaian cedi'), ('GIP', 'Gibraltar pound'), ('GMD', 'Gambian dalasi'), ('GNF', 'Guinean franc'), ('GTQ', 'Guatemalan quetzal'), ('GYD', 'Guyanese dollar'), ('HKD', 'Hong Kong dollar'), ('HNL', 'Honduran lempira'), ('HRK', 'Croatian kuna'), ('HTG', 'Haitian gourde'), ('HUF', 'Hungarian forint'), ('IDR', 'Indonesian rupiah'), ('ILS', 'Israeli new shekel'), ('INR', 'Indian rupee'), ('IQD', 'Iraqi dinar'), ('IRR', 'Iranian rial'), ('ISK', 'Icelandic króna'), ('JMD', 'Jamaican dollar'), ('JOD', 'Jordanian dinar'), ('JPY', 'Japanese yen'), ('KES', 'Kenyan shilling'), ('KGS', 'Kyrgyzstani som'), ('KHR', 'Cambodian riel'), ('KMF', 'Comoro franc'), ('KPW', 'North Korean won'), ('KRW', 'South Korean won'), ('KWD', 'Kuwaiti dinar'), ('KYD', 'Cayman Islands dollar'), ('KZT', 'Kazakhstani tenge'), ('LAK', 'Lao kip'), ('LBP', 'Lebanese pound'), ('LKR', 'Sri Lankan rupee'), ('LRD', 'Liberian dollar'), ('LSL', 'Lesotho loti'), ('LYD', 'Libyan dinar'), ('MAD', 'Moroccan dirham'), ('MDL', 'Moldovan leu'), ('MGA', 'Malagasy ariary'), ('MKD', 'Macedonian denar'), ('MMK', 'Myanmar kyat'), ('MNT', 'Mongolian tögrög'), ('MOP', 'Macanese pataca'), ('MRU', 'Mauritanian ouguiya'), ('MUR', 'Mauritian rupee'), ('MVR', 'Maldivian rufiyaa'), ('MWK', 'Malawian kwacha'), ('MXN', 'Mexican peso'), ('MYR', 'Malaysian ringgit'), ('MZN', 'Mozambican metical'), ('NAD', 'Namibian dollar'), ('NGN', 'Nigerian naira'), ('NIO', 'Nicaraguan córdoba'), ('NOK', 'Norwegian krone'), ('NPR', 'Nepalese rupee'), ('NZD', 'New Zealand dollar'), ('OMR', 'Omani rial'), ('PAB', 'Panamanian balboa'), ('PEN', 'Peruvian sol'), ('PGK', 'Papua New Guinean kina'), ('PHP', 'Philippine peso'), ('PKR', 'Pakistani rupee'), ('PLN', 'Polish złoty'), ('PYG', 'Paraguayan guaraní'), ('QAR', 'Qatari riyal'), ('RON', 'Romanian leu'), ('RSD', 'Serbian dinar'), ('RUB', 'Russian ruble'), ('RWF', 'Rwandan franc'), ('SAR', 'Saudi riyal'), ('SBD', 'Solomon Islands dollar'), ('SCR', 'Seychelles rupee'), ('SDG', 'Sudanese pound'), ('SEK', 'Swedish krona/kronor'), ('SGD', 'Singapore dollar'), ('SHP', 'Saint Helena pound'), ('SLL', 'Sierra Leonean leone'), ('SOS', 'Somali shilling'), ('SRD', 'Surinamese dollar'), ('SSP', 'South Sudanese pound'), ('STN', 'São Tomé and Príncipe dobra'), ('SVC', 'Salvadoran colón'), ('SYP', 'Syrian pound'), ('SZL', 'Swazi lilangeni'), ('THB', 'Thai baht'), ('TJS', 'Tajikistani somoni'), ('TMT', 'Turkmenistan manat'), ('TND', 'Tunisian dinar'), ('TOP', 'Tongan paʻanga'), ('TRY', 'Turkish lira'), ('TTD', 'Trinidad and Tobago dollar'), ('TWD', 'New Taiwan dollar'), ('TZS', 'Tanzanian shilling'), ('UAH', 'Ukrainian hryvnia'), ('UGX', 'Ugandan shilling'), ('USD', 'United States dollar'), ('UYU', 'Uruguayan peso'), ('UYW', 'Unidad previsional[14]'), ('UZS', 'Uzbekistan som'), ('VES', 'Venezuelan bolívar soberano'), ('VND', 'Vietnamese đồng'), ('VUV', 'Vanuatu vatu'), ('WST', 'Samoan tala'), ('XAF', 'CFA franc BEAC'), ('XAG', 'Silver (one troy ounce)'), ('XAU', 'Gold (one troy ounce)'), ('XCD', 'East Caribbean dollar'), ('XOF', 'CFA franc BCEAO'), ('XPF', 'CFP franc (franc Pacifique)'), ('YER', 'Yemeni rial'), ('ZAR', 'South African rand'), ('ZMW', 'Zambian kwacha'), ('ZWL', 'Zimbabwean dollar')], default='', max_length=250)),
                ('unhcr_id', models.CharField(blank=True, default='', max_length=250)),
                ('kobo_submission_uuid', models.UUIDField(default=None, null=True)),
                ('kobo_asset_id', models.CharField(blank=True, default='', max_length=150)),
                ('kobo_submission_time', models.DateTimeField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportedIndividual',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('individual_id', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('full_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255)])),
                ('given_name', models.CharField(blank=True, default='', max_length=85)),
                ('middle_name', models.CharField(blank=True, default='', max_length=85)),
                ('family_name', models.CharField(blank=True, default='', max_length=85)),
                ('relationship', models.CharField(blank=True, choices=[('UNKNOWN', 'Unknown'), ('NON_BENEFICIARY', 'Not a Family Member. Can only act as a recipient.'), ('HEAD', 'Head of household (self)'), ('SON_DAUGHTER', 'Son / Daughter'), ('WIFE_HUSBAND', 'Wife / Husband'), ('BROTHER_SISTER', 'Brother / Sister'), ('MOTHER_FATHER', 'Mother / Father'), ('AUNT_UNCLE', 'Aunt / Uncle'), ('GRANDMOTHER_GRANDFATHER', 'Grandmother / Grandfather'), ('MOTHERINLAW_FATHERINLAW', 'Mother-in-law / Father-in-law'), ('DAUGHTERINLAW_SONINLAW', 'Daughter-in-law / Son-in-law'), ('SISTERINLAW_BROTHERINLAW', 'Sister-in-law / Brother-in-law'), ('GRANDDAUGHER_GRANDSON', 'Granddaughter / Grandson'), ('NEPHEW_NIECE', 'Nephew / Niece'), ('COUSIN', 'Cousin')], default='', max_length=255)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=255)),
                ('birth_date', models.DateField()),
                ('estimated_birth_date', models.BooleanField(default=False)),
                ('marital_status', models.CharField(choices=[('', 'None'), ('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated')], max_length=255)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None)),
                ('phone_no_alternative', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None)),
                ('disability', models.BooleanField(default=False)),
                ('work_status', models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No'), ('NOT_PROVIDED', 'Not provided')], default='NOT_PROVIDED', max_length=20)),
                ('first_registration_date', models.DateField()),
                ('last_registration_date', models.DateField()),
                ('deduplication_batch_status', models.CharField(blank=True, choices=[('SIMILAR_IN_BATCH', 'Similar in batch'), ('DUPLICATE_IN_BATCH', 'Duplicate in batch'), ('UNIQUE_IN_BATCH', 'Unique in batch'), ('NOT_PROCESSED', 'Not Processed')], default='UNIQUE_IN_BATCH', max_length=50)),
                ('deduplication_golden_record_status', models.CharField(blank=True, choices=[('UNIQUE', 'Unique'), ('DUPLICATE', 'Duplicate'), ('NEEDS_ADJUDICATION', 'Needs Adjudication'), ('NOT_PROCESSED', 'Not Processed')], default='UNIQUE', max_length=50)),
                ('deduplication_batch_results', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('deduplication_golden_record_results', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('flex_fields', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('pregnant', models.NullBooleanField()),
                ('observed_disability', multiselectfield.db.fields.MultiSelectField(choices=[('NONE', 'None'), ('SEEING', 'Difficulty seeing (even if wearing glasses)'), ('HEARING', 'Difficulty hearing (even if using a hearing aid)'), ('WALKING', 'Difficulty walking or climbing steps'), ('MEMORY', 'Difficulty remembering or concentrating'), ('SELF_CARE', 'Difficulty with self care (washing, dressing)'), ('COMMUNICATING', 'Difficulty communicating (e.g understanding or being understood)')], max_length=58)),
                ('seeing_disability', models.CharField(blank=True, choices=[('', 'None'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50)),
                ('hearing_disability', models.CharField(blank=True, choices=[('', 'None'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50)),
                ('physical_disability', models.CharField(blank=True, choices=[('', 'None'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50)),
                ('memory_disability', models.CharField(blank=True, choices=[('', 'None'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50)),
                ('selfcare_disability', models.CharField(blank=True, choices=[('', 'None'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50)),
                ('comms_disability', models.CharField(blank=True, choices=[('', 'None'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50)),
                ('who_answers_phone', models.CharField(blank=True, max_length=150)),
                ('who_answers_alt_phone', models.CharField(blank=True, max_length=150)),
                ('household', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='registration_datahub.ImportedHousehold')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KoboImportedSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_submission_uuid', models.UUIDField()),
                ('kobo_asset_id', models.CharField(max_length=150)),
                ('kobo_submission_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationDataImportDatahub',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('hct_id', models.UUIDField(db_index=True, null=True)),
                ('import_done', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('STARTED', 'Started'), ('DONE', 'Done')], default='NOT_STARTED', max_length=15)),
                ('business_area_slug', models.CharField(blank=True, max_length=250)),
                ('import_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_data_import', to='registration_datahub.ImportData')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ImportedIndividualIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=255)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='registration_datahub.ImportedAgency')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='registration_datahub.ImportedIndividual')),
            ],
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='registration_data_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='registration_datahub.RegistrationDataImportDatahub'),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='head_of_household',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration_datahub.ImportedIndividual'),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='registration_data_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='registration_datahub.RegistrationDataImportDatahub'),
        ),
        migrations.CreateModel(
            name='ImportedDocumentType',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('label', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('DRIVERS_LICENSE', "Driver's License"), ('NATIONAL_ID', 'National ID'), ('NATIONAL_PASSPORT', 'National Passport'), ('ELECTORAL_CARD', 'Electoral Card'), ('OTHER', 'Other')], max_length=50)),
            ],
            options={
                'unique_together': {('country', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ImportedDocument',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('document_number', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registration_datahub.ImportedIndividual')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registration_datahub.ImportedDocumentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentValidator',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('regex', models.CharField(default='.*', max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validators', to='registration_datahub.ImportedDocumentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportedIndividualRoleInHousehold',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('role', models.CharField(blank=True, choices=[('PRIMARY', 'Primary collector'), ('ALTERNATE', 'Alternate collector'), ('NO_ROLE', 'None')], max_length=255)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals_and_roles', to='registration_datahub.ImportedHousehold')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households_and_roles', to='registration_datahub.ImportedIndividual')),
            ],
            options={
                'unique_together': {('role', 'household')},
            },
        ),
    ]
