# Generated by Django 3.2.19 on 2023-06-08 20:07

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models, transaction
import django.db.migrations.operations.special
import django.db.models.deletion
import django_countries.fields
import model_utils.fields
import multiselectfield.db.fields
import phonenumber_field.modelfields
import sorl.thumbnail.fields
import uuid

from django.db.models import F
from django.db.models.functions import Concat

from hct_mis_api.apps.core.field_attributes.fields_types import TYPE_DECIMAL
from hct_mis_api.apps.core.utils import fix_flex_type_fields, serialize_flex_attributes
from hct_mis_api.apps.household.models import IDENTIFICATION_TYPE_CHOICE
from hct_mis_api.apps.utils.phone import calculate_phone_numbers_validity

def remove_duplicates(apps, schema_editor):
    ImportedDocument = apps.get_model(
        "registration_datahub", "ImportedDocument"
    )

    master_qs_docs = ImportedDocument.objects.annotate(
        concat_id_doc_num=Concat(
            F("type__id"),
            F("document_number"),
            output_field=models.CharField(),
        ),
    ).distinct("concat_id_doc_num")

    for master in master_qs_docs:
        ImportedDocument.objects.filter(
            type=master.type, document_number=master.document_number
        ).exclude(pk=master.pk).delete()

def remove_duplicates_2nd(apps, schema_editor):
    ImportedDocumentType = apps.get_model(
        "registration_datahub", "ImportedDocumentType"
    )

    master_qs_types = ImportedDocumentType.objects.annotate(
        concat_country_type=F("type")).distinct("concat_country_type")

    for master in master_qs_types:
        ImportedDocumentType.objects.filter(type=master.type).exclude(pk=master.pk).delete()


def set_document_types(apps, schema_editor):
    choices = {
        "Driving License": "DRIVERS_LICENSE",
        "Birth Certificate": "BIRTH_CERTIFICATE",
        "National ID": "NATIONAL_ID",
        "National Passport": "NATIONAL_PASSPORT",
    }
    ImportedDocumentType = apps.get_model(
        "registration_datahub", "ImportedDocumentType"
    )
    imported_doc_types = ImportedDocumentType.objects.all()
    for obj in imported_doc_types:
        obj.type = choices.get(obj.label)
        obj.save()

def cast_flex_field_values(apps, schema_editor):
    pass


def empty_reverse(apps, schema_editor):
    pass

def round_muac(apps, schema_editor):
    ImportedIndividual = apps.get_model("registration_datahub", "ImportedIndividual")
    individuals_with_muac = ImportedIndividual.objects.filter(flex_fields__muac_i_f__isnull=False)

    for individual in individuals_with_muac:
        individual.flex_fields["muac_i_f"] = "{:.2f}".format(float(individual.flex_fields["muac_i_f"]))

    ImportedIndividual.objects.bulk_update(individuals_with_muac, ("flex_fields",), 1000)

def fix_fields_individuals(apps, schema_editor):
    ImportedIndividual = apps.get_model("registration_datahub", "ImportedIndividual")
    individuals = ImportedIndividual.objects.all()

    all_flex_fields = serialize_flex_attributes().get("individuals", {})
    if all_flex_fields and individuals:
        decimal_flex_fields = [key for key, value in all_flex_fields.items() if value["type"] == TYPE_DECIMAL]

        individuals = fix_flex_type_fields(individuals, decimal_flex_fields)
        ImportedIndividual.objects.bulk_update(individuals, ("flex_fields",), 1000)


def fix_fields_households(apps, schema_editor):
    ImportedHousehold = apps.get_model("registration_datahub", "ImportedHousehold")
    households = ImportedHousehold.objects.all()

    all_flex_fields = serialize_flex_attributes().get("households", {})
    if all_flex_fields and households:
        decimal_flex_fields = [key for key, value in all_flex_fields.items() if value["type"] == TYPE_DECIMAL]

        households = fix_flex_type_fields(households, decimal_flex_fields)
        ImportedHousehold.objects.bulk_update(households, ("flex_fields",), 1000)

def migrate_doc_type(apps, schema_editor):
    ImportedDocument = apps.get_model('registration_datahub', 'ImportedDocument')
    ImportedDocumentType = apps.get_model('registration_datahub', 'ImportedDocumentType')

    countries = ImportedDocumentType.objects.order_by('country').values_list('country', flat=True).distinct()

    for country in countries:
        ImportedDocument.objects.filter(type__country=country).update(country=country)

    tostay = countries.first()
    if tostay:
        for code, _ in IDENTIFICATION_TYPE_CHOICE:
            new_type, _ = ImportedDocumentType.objects.get_or_create(type=code, country=tostay)
            ImportedDocument.objects.filter(type__type=code).update(type=new_type)
        ImportedDocumentType.objects.exclude(country=tostay).delete()

@transaction.atomic
def update_each_phone_numbers_validity(apps, schema_editor):
    ImportedIndividual = apps.get_model("registration_datahub", "ImportedIndividual")
    for individual in ImportedIndividual.objects.only(
        "phone_no", "phone_no_alternative", "phone_no_valid", "phone_no_alternative_valid"
    ).iterator():
        individual = calculate_phone_numbers_validity(individual)
        individual.save(update_fields=["phone_no_valid", "phone_no_alternative_valid"])

def populate_partner_and_country(apps, schema_editor):
    IndividualIdentity = apps.get_model("registration_datahub", "ImportedIndividualIdentity")

    for identity in IndividualIdentity.objects.prefetch_related("agency").all():
        identity.partner = identity.agency.type
        identity.country = identity.agency.country
        identity.save(update_fields=("partner", "country"))

class Migration(migrations.Migration):

    replaces = [('registration_datahub', '0001_migration'), ('registration_datahub', '0002_migration'), ('registration_datahub', '0003_migration'), ('registration_datahub', '0004_migration'), ('registration_datahub', '0005_migration'), ('registration_datahub', '0006_migration'), ('registration_datahub', '0007_migration'), ('registration_datahub', '0008_migration'), ('registration_datahub', '0009_migration'), ('registration_datahub', '0010_migration'), ('registration_datahub', '0011_migration'), ('registration_datahub', '0012_migration'), ('registration_datahub', '0013_migration'), ('registration_datahub', '0014_migration'), ('registration_datahub', '0015_migration'), ('registration_datahub', '0016_migration'), ('registration_datahub', '0017_migration'), ('registration_datahub', '0018_migration'), ('registration_datahub', '0019_migration'), ('registration_datahub', '0020_migration'), ('registration_datahub', '0021_migration'), ('registration_datahub', '0022_migration'), ('registration_datahub', '0023_migration'), ('registration_datahub', '0024_migration'), ('registration_datahub', '0025_migration'), ('registration_datahub', '0026_migration'), ('registration_datahub', '0027_migration'), ('registration_datahub', '0028_migration'), ('registration_datahub', '0029_migration'), ('registration_datahub', '0030_migration'), ('registration_datahub', '0031_migration'), ('registration_datahub', '0032_migration'), ('registration_datahub', '0033_migration'), ('registration_datahub', '0034_migration'), ('registration_datahub', '0035_migration'), ('registration_datahub', '0036_migration'), ('registration_datahub', '0037_migration'), ('registration_datahub', '0038_migration'), ('registration_datahub', '0039_migration'), ('registration_datahub', '0040_migration'), ('registration_datahub', '0041_migration'), ('registration_datahub', '0042_migration'), ('registration_datahub', '0043_migration'), ('registration_datahub', '0044_migration'), ('registration_datahub', '0045_migration'), ('registration_datahub', '0046_migration'), ('registration_datahub', '0047_migration'), ('registration_datahub', '0048_migration'), ('registration_datahub', '0049_migration'), ('registration_datahub', '0050_migration'), ('registration_datahub', '0051_migration'), ('registration_datahub', '0052_migration'), ('registration_datahub', '0053_migration'), ('registration_datahub', '0054_migration'), ('registration_datahub', '0055_migration'), ('registration_datahub', '0056_migration'), ('registration_datahub', '0057_migration'), ('registration_datahub', '0058_migration'), ('registration_datahub', '0059_migration'), ('registration_datahub', '0060_migration'), ('registration_datahub', '0061_migration'), ('registration_datahub', '0062_migration'), ('registration_datahub', '0063_migration'), ('registration_datahub', '0064_migration'), ('registration_datahub', '0065_migration'), ('registration_datahub', '0066_migration'), ('registration_datahub', '0067_migration'), ('registration_datahub', '0068_migration'), ('registration_datahub', '0069_migration'), ('registration_datahub', '0070_migration'), ('registration_datahub', '0071_migration'), ('registration_datahub', '0072_migration'), ('registration_datahub', '0073_migration'), ('registration_datahub', '0074_migration'), ('registration_datahub', '0075_migration'), ('registration_datahub', '0076_migration'), ('registration_datahub', '0077_migration'), ('registration_datahub', '0078_migration'), ('registration_datahub', '0079_migration'), ('registration_datahub', '0080_migration'), ('registration_datahub', '0081_migration'), ('registration_datahub', '0082_migration'), ('registration_datahub', '0083_migration'), ('registration_datahub', '0084_migration'), ('registration_datahub', '0085_migration'), ('registration_datahub', '0086_migration'), ('registration_datahub', '0087_migration'), ('registration_datahub', '0088_migration')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImportData',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xlsx_file', models.FileField(upload_to='')),
                ('number_of_households', models.PositiveIntegerField()),
                ('number_of_individuals', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportedDocumentType',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportedHousehold',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent', sorl.thumbnail.fields.ImageField(upload_to='', validators=[django.core.validators.validate_image_file_extension])),
                ('residence_status', models.CharField(choices=[('REFUGEE', 'Refugee'), ('MIGRANT', 'Migrant'), ('CITIZEN', 'Citizen'), ('IDP', 'IDP'), ('OTHER', 'Other')], max_length=255)),
                ('country_origin', django_countries.fields.CountryField(max_length=2)),
                ('size', models.PositiveIntegerField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('admin1', models.CharField(blank=True, max_length=255)),
                ('admin2', models.CharField(blank=True, max_length=255)),
                ('geopoint', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('female_age_group_0_5_count', models.PositiveIntegerField(default=0)),
                ('female_age_group_6_11_count', models.PositiveIntegerField(default=0)),
                ('female_age_group_12_17_count', models.PositiveIntegerField(default=0)),
                ('female_adults_count', models.PositiveIntegerField(default=0)),
                ('pregnant_count', models.PositiveIntegerField(default=0)),
                ('male_age_group_0_5_count', models.PositiveIntegerField(default=0)),
                ('male_age_group_6_11_count', models.PositiveIntegerField(default=0)),
                ('male_age_group_12_17_count', models.PositiveIntegerField(default=0)),
                ('male_adults_count', models.PositiveIntegerField(default=0)),
                ('female_age_group_0_5_disabled_count', models.PositiveIntegerField(default=0)),
                ('female_age_group_6_11_disabled_count', models.PositiveIntegerField(default=0)),
                ('female_age_group_12_17_disabled_count', models.PositiveIntegerField(default=0)),
                ('female_adults_disabled_count', models.PositiveIntegerField(default=0)),
                ('male_age_group_0_5_disabled_count', models.PositiveIntegerField(default=0)),
                ('male_age_group_6_11_disabled_count', models.PositiveIntegerField(default=0)),
                ('male_age_group_12_17_disabled_count', models.PositiveIntegerField(default=0)),
                ('male_adults_disabled_count', models.PositiveIntegerField(default=0)),
                ('registration_date', models.DateField(null=True)),
                ('returnee', models.BooleanField(default=False, null=True)),
                ('flex_fields', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportedIndividual',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('individual_id', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('full_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255)])),
                ('given_name', models.CharField(blank=True, max_length=85)),
                ('middle_name', models.CharField(blank=True, max_length=85)),
                ('family_name', models.CharField(blank=True, max_length=85)),
                ('relationship', models.CharField(blank=True, choices=[('NON_BENEFICIARY', 'Not a Family Member. Can only act as a recipient.'), ('HEAD', 'Head of household (self)'), ('SON_DAUGHTER', 'Son / Daughter'), ('WIFE_HUSBAND', 'Wife / Husband'), ('BROTHER_SISTER', 'Brother / Sister'), ('MOTHER_FATHER', 'Mother / Father'), ('AUNT_UNCLE', 'Aunt / Uncle'), ('GRANDMOTHER_GRANDFATHER', 'Grandmother / Grandfather'), ('MOTHERINLAW_FATHERINLAW', 'Mother-in-law / Father-in-law'), ('DAUGHTERINLAW_SONINLAW', 'Daughter-in-law / Son-in-law'), ('SISTERINLAW_BROTHERINLAW', 'Sister-in-law / Brother-in-law'), ('GRANDDAUGHER_GRANDSON', 'Granddaughter / Grandson'), ('NEPHEW_NIECE', 'Nephew / Niece'), ('COUSIN', 'Cousin')], max_length=255)),
                ('role', models.CharField(blank=True, choices=[('PRIMARY', 'Primary collector'), ('ALTERNATE', 'Alternate collector'), ('NO_ROLE', 'None')], max_length=255)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=255)),
                ('birth_date', models.DateField()),
                ('estimated_birth_date', models.BooleanField(default=False, null=True)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'Married'), ('WIDOW', 'Widow'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated')], max_length=255)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('phone_no_alternative', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('disability', models.BooleanField(default=False)),
                ('flex_fields', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='registration_datahub.importedhousehold')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationDataImportDatahub',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('hct_id', models.UUIDField(null=True)),
                ('import_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_data_import', to='registration_datahub.importdata')),
                ('import_done', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportedIndividualIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=255)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='registration_datahub.agency')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='registration_datahub.importedindividual')),
            ],
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='registration_data_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='registration_datahub.registrationdataimportdatahub'),
        ),
        migrations.CreateModel(
            name='ImportedHouseholdIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=255)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households_identities', to='registration_datahub.agency')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='registration_datahub.importedhousehold')),
            ],
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='head_of_household',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration_datahub.importedindividual'),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='registration_data_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='registration_datahub.registrationdataimportdatahub'),
        ),
        migrations.CreateModel(
            name='ImportedDocument',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registration_datahub.importedindividual')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registration_datahub.importeddocumenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentValidator',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regex', models.CharField(default='.*', max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validators', to='registration_datahub.importeddocumenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='admin1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='admin2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='geopoint',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='registration_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='returnee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='estimated_birth_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='family_name',
            field=models.CharField(blank=True, default='', max_length=85),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='given_name',
            field=models.CharField(blank=True, default='', max_length=85),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=85),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='phone_no_alternative',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='relationship',
            field=models.CharField(blank=True, choices=[('NON_BENEFICIARY', 'Not a Family Member. Can only act as a recipient.'), ('HEAD', 'Head of household (self)'), ('SON_DAUGHTER', 'Son / Daughter'), ('WIFE_HUSBAND', 'Wife / Husband'), ('BROTHER_SISTER', 'Brother / Sister'), ('MOTHER_FATHER', 'Mother / Father'), ('AUNT_UNCLE', 'Aunt / Uncle'), ('GRANDMOTHER_GRANDFATHER', 'Grandmother / Grandfather'), ('MOTHERINLAW_FATHERINLAW', 'Mother-in-law / Father-in-law'), ('DAUGHTERINLAW_SONINLAW', 'Daughter-in-law / Son-in-law'), ('SISTERINLAW_BROTHERINLAW', 'Sister-in-law / Brother-in-law'), ('GRANDDAUGHER_GRANDSON', 'Granddaughter / Grandson'), ('NEPHEW_NIECE', 'Nephew / Niece'), ('COUSIN', 'Cousin')], default='', max_length=255),
        ),
        migrations.RunPython(remove_duplicates, migrations.RunPython.noop),
        migrations.AddField(
            model_name='importeddocumenttype',
            name='type',
            field=models.CharField(blank=True, choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('DRIVERS_LICENSE', "Driver's License"), ('NATIONAL_ID', 'National ID'), ('NATIONAL_PASSPORT', 'National Passport'), ('ELECTORAL_CARD', 'Electoral Card'), ('OTHER', 'Other')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.RunPython(set_document_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='importeddocumenttype',
            name='type',
            field=models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('DRIVERS_LICENSE', "Driver's License"), ('NATIONAL_ID', 'National ID'), ('NATIONAL_PASSPORT', 'National Passport'), ('ELECTORAL_CARD', 'Electoral Card'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.RunPython(remove_duplicates_2nd, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='importeddocumenttype',
            unique_together={('country', 'type')},
        ),
        migrations.RenameModel(
            old_name='Agency',
            new_name='ImportedAgency',
        ),
        migrations.RenameField(
            model_name='importdata',
            old_name='xlsx_file',
            new_name='file',
        ),
        migrations.AddField(
            model_name='importdata',
            name='data_type',
            field=models.CharField(choices=[('XLSX', 'XLSX File'), ('JSON', 'JSON File')], default='XLSX', max_length=4),
        ),
        migrations.AlterField(
            model_name='registrationdataimportdatahub',
            name='import_done',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('STARTED', 'Started'), ('DONE', 'Done')], default='NOT_STARTED', max_length=15),
        ),
        migrations.AddField(
            model_name='registrationdataimportdatahub',
            name='business_area_slug',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='work_status',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No'), ('NOT_PROVIDED', 'Not provided')], default='NOT_PROVIDED', max_length=20),
        ),
        migrations.RemoveField(
            model_name='importedhousehold',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='first_registration_date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='last_registration_date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='first_registration_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 14, 13, 43, 16, 947)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='last_registration_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 14, 13, 43, 21, 163324)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='importeddocument',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='importedindividual',
            name='role',
        ),
        migrations.CreateModel(
            name='ImportedIndividualRoleInHousehold',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('role', models.CharField(blank=True, choices=[('PRIMARY', 'Primary collector'), ('ALTERNATE', 'Alternate collector'), ('NO_ROLE', 'None')], max_length=255)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals_and_roles', to='registration_datahub.importedhousehold')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households_and_roles', to='registration_datahub.importedindividual')),
            ],
            options={
                'unique_together': {('role', 'household')},
            },
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='registration_datahub.importedhousehold'),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='deduplication_batch_results',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='deduplication_golden_record_results',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='deduplication_batch_status',
            field=models.CharField(blank=True, choices=[('SIMILAR_IN_BATCH', 'Similar in batch'), ('DUPLICATE_IN_BATCH', 'Duplicate in batch'), ('UNIQUE_IN_BATCH', 'Unique in batch'), ('NOT_PROCESSED', 'Not Processed')], default='UNIQUE_IN_BATCH', max_length=50),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='deduplication_golden_record_status',
            field=models.CharField(blank=True, choices=[('UNIQUE', 'Unique'), ('DUPLICATE', 'Duplicate'), ('NEEDS_ADJUDICATION', 'Needs Adjudication'), ('NOT_PROCESSED', 'Not Processed')], default='UNIQUE', max_length=50),
        ),
        migrations.RemoveField(
            model_name='importedhousehold',
            name='consent',
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='consent_sign',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='deviceid',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='observed_disability',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NONE', 'None'), ('SEEING', 'Difficulty seeing (even if wearing glasses)'), ('HEARING', 'Difficulty hearing (even if using a hearing aid)'), ('WALKING', 'Difficulty walking or climbing steps'), ('MEMORY', 'Difficulty remembering or concentrating'), ('SELF_CARE', 'Difficulty with self care (washing, dressing)'), ('COMMUNICATING', 'Difficulty communicating (e.g understanding or being understood)')], default='NONE', max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='who_answers_alt_phone',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='who_answers_phone',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='residence_status',
            field=models.CharField(choices=[('IDP', 'Displaced  |  Internally Displaced People'), ('REFUGEE', 'Displaced  |  Refugee / Asylum Seeker'), ('OTHERS_OF_CONCERN', 'Displaced  |  Others of Concern'), ('HOST', 'Non-displaced  |   Host'), ('NON_HOST', 'Non-displaced  |   Non-host')], max_length=255),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated')], max_length=255),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated')], max_length=255),
        ),
        migrations.AlterModelOptions(
            name='registrationdataimportdatahub',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='relationship',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'Unknown'), ('NON_BENEFICIARY', 'Not a Family Member. Can only act as a recipient.'), ('HEAD', 'Head of household (self)'), ('SON_DAUGHTER', 'Son / Daughter'), ('WIFE_HUSBAND', 'Wife / Husband'), ('BROTHER_SISTER', 'Brother / Sister'), ('MOTHER_FATHER', 'Mother / Father'), ('AUNT_UNCLE', 'Aunt / Uncle'), ('GRANDMOTHER_GRANDFATHER', 'Grandmother / Grandfather'), ('MOTHERINLAW_FATHERINLAW', 'Mother-in-law / Father-in-law'), ('DAUGHTERINLAW_SONINLAW', 'Daughter-in-law / Son-in-law'), ('SISTERINLAW_BROTHERINLAW', 'Sister-in-law / Brother-in-law'), ('GRANDDAUGHER_GRANDSON', 'Granddaughter / Grandson'), ('NEPHEW_NIECE', 'Nephew / Niece'), ('COUSIN', 'Cousin')], default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='importedhousehold',
            name='female_adults_count',
        ),
        migrations.RemoveField(
            model_name='importedhousehold',
            name='female_adults_disabled_count',
        ),
        migrations.RemoveField(
            model_name='importedhousehold',
            name='male_adults_count',
        ),
        migrations.RemoveField(
            model_name='importedhousehold',
            name='male_adults_disabled_count',
        ),
        migrations.AddField(
            model_name='importedagency',
            name='country',
            field=django_countries.fields.CountryField(default='AF', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='currency',
            field=models.CharField(choices=[('', 'None'), ('AED', 'United Arab Emirates dirham'), ('AFN', 'Afghan afghani'), ('ALL', 'Albanian lek'), ('AMD', 'Armenian dram'), ('ANG', 'Netherlands Antillean guilder'), ('AOA', 'Angolan kwanza'), ('ARS', 'Argentine peso'), ('AUD', 'Australian dollar'), ('AWG', 'Aruban florin'), ('AZN', 'Azerbaijani manat'), ('BAM', 'Bosnia and Herzegovina convertible mark'), ('BBD', 'Barbados dollar'), ('BDT', 'Bangladeshi taka'), ('BGN', 'Bulgarian lev'), ('BHD', 'Bahraini dinar'), ('BIF', 'Burundian franc'), ('BMD', 'Bermudian dollar'), ('BND', 'Brunei dollar'), ('BOB', 'Boliviano'), ('BOV', 'Bolivian Mvdol (funds code)'), ('BRL', 'Brazilian real'), ('BSD', 'Bahamian dollar'), ('BTN', 'Bhutanese ngultrum'), ('BWP', 'Botswana pula'), ('BYN', 'Belarusian ruble'), ('BZD', 'Belize dollar'), ('CAD', 'Canadian dollar'), ('CDF', 'Congolese franc'), ('CHF', 'Swiss franc'), ('CLP', 'Chilean peso'), ('CNY', 'Chinese yuan'), ('COP', 'Colombian peso'), ('CRC', 'Costa Rican colon'), ('CUC', 'Cuban convertible peso'), ('CUP', 'Cuban peso'), ('CVE', 'Cape Verdean escudo'), ('CZK', 'Czech koruna'), ('DJF', 'Djiboutian franc'), ('DKK', 'Danish krone'), ('DOP', 'Dominican peso'), ('DZD', 'Algerian dinar'), ('EGP', 'Egyptian pound'), ('ERN', 'Eritrean nakfa'), ('ETB', 'Ethiopian birr'), ('EUR', 'Euro'), ('FJD', 'Fiji dollar'), ('FKP', 'Falkland Islands pound'), ('GBP', 'Pound sterling'), ('GEL', 'Georgian lari'), ('GHS', 'Ghanaian cedi'), ('GIP', 'Gibraltar pound'), ('GMD', 'Gambian dalasi'), ('GNF', 'Guinean franc'), ('GTQ', 'Guatemalan quetzal'), ('GYD', 'Guyanese dollar'), ('HKD', 'Hong Kong dollar'), ('HNL', 'Honduran lempira'), ('HRK', 'Croatian kuna'), ('HTG', 'Haitian gourde'), ('HUF', 'Hungarian forint'), ('IDR', 'Indonesian rupiah'), ('ILS', 'Israeli new shekel'), ('INR', 'Indian rupee'), ('IQD', 'Iraqi dinar'), ('IRR', 'Iranian rial'), ('ISK', 'Icelandic króna'), ('JMD', 'Jamaican dollar'), ('JOD', 'Jordanian dinar'), ('JPY', 'Japanese yen'), ('KES', 'Kenyan shilling'), ('KGS', 'Kyrgyzstani som'), ('KHR', 'Cambodian riel'), ('KMF', 'Comoro franc'), ('KPW', 'North Korean won'), ('KRW', 'South Korean won'), ('KWD', 'Kuwaiti dinar'), ('KYD', 'Cayman Islands dollar'), ('KZT', 'Kazakhstani tenge'), ('LAK', 'Lao kip'), ('LBP', 'Lebanese pound'), ('LKR', 'Sri Lankan rupee'), ('LRD', 'Liberian dollar'), ('LSL', 'Lesotho loti'), ('LYD', 'Libyan dinar'), ('MAD', 'Moroccan dirham'), ('MDL', 'Moldovan leu'), ('MGA', 'Malagasy ariary'), ('MKD', 'Macedonian denar'), ('MMK', 'Myanmar kyat'), ('MNT', 'Mongolian tögrög'), ('MOP', 'Macanese pataca'), ('MRU', 'Mauritanian ouguiya'), ('MUR', 'Mauritian rupee'), ('MVR', 'Maldivian rufiyaa'), ('MWK', 'Malawian kwacha'), ('MXN', 'Mexican peso'), ('MYR', 'Malaysian ringgit'), ('MZN', 'Mozambican metical'), ('NAD', 'Namibian dollar'), ('NGN', 'Nigerian naira'), ('NIO', 'Nicaraguan córdoba'), ('NOK', 'Norwegian krone'), ('NPR', 'Nepalese rupee'), ('NZD', 'New Zealand dollar'), ('OMR', 'Omani rial'), ('PAB', 'Panamanian balboa'), ('PEN', 'Peruvian sol'), ('PGK', 'Papua New Guinean kina'), ('PHP', 'Philippine peso'), ('PKR', 'Pakistani rupee'), ('PLN', 'Polish złoty'), ('PYG', 'Paraguayan guaraní'), ('QAR', 'Qatari riyal'), ('RON', 'Romanian leu'), ('RSD', 'Serbian dinar'), ('RUB', 'Russian ruble'), ('RWF', 'Rwandan franc'), ('SAR', 'Saudi riyal'), ('SBD', 'Solomon Islands dollar'), ('SCR', 'Seychelles rupee'), ('SDG', 'Sudanese pound'), ('SEK', 'Swedish krona/kronor'), ('SGD', 'Singapore dollar'), ('SHP', 'Saint Helena pound'), ('SLL', 'Sierra Leonean leone'), ('SOS', 'Somali shilling'), ('SRD', 'Surinamese dollar'), ('SSP', 'South Sudanese pound'), ('STN', 'São Tomé and Príncipe dobra'), ('SVC', 'Salvadoran colón'), ('SYP', 'Syrian pound'), ('SZL', 'Swazi lilangeni'), ('THB', 'Thai baht'), ('TJS', 'Tajikistani somoni'), ('TMT', 'Turkmenistan manat'), ('TND', 'Tunisian dinar'), ('TOP', 'Tongan paʻanga'), ('TRY', 'Turkish lira'), ('TTD', 'Trinidad and Tobago dollar'), ('TWD', 'New Taiwan dollar'), ('TZS', 'Tanzanian shilling'), ('UAH', 'Ukrainian hryvnia'), ('UGX', 'Ugandan shilling'), ('USD', 'United States dollar'), ('UYU', 'Uruguayan peso'), ('UYW', 'Unidad previsional[14]'), ('UZS', 'Uzbekistan som'), ('VES', 'Venezuelan bolívar soberano'), ('VND', 'Vietnamese đồng'), ('VUV', 'Vanuatu vatu'), ('WST', 'Samoan tala'), ('XAF', 'CFA franc BEAC'), ('XAG', 'Silver (one troy ounce)'), ('XAU', 'Gold (one troy ounce)'), ('XCD', 'East Caribbean dollar'), ('XOF', 'CFA franc BCEAO'), ('XPF', 'CFP franc (franc Pacifique)'), ('YER', 'Yemeni rial'), ('ZAR', 'South African rand'), ('ZMW', 'Zambian kwacha'), ('ZWL', 'Zimbabwean dollar')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='female_age_group_18_59_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='female_age_group_18_59_disabled_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='female_age_group_60_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='female_age_group_60_disabled_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='male_age_group_18_59_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='male_age_group_18_59_disabled_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='male_age_group_60_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='male_age_group_60_disabled_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='registration_method',
            field=models.CharField(choices=[('', 'None'), ('HH_REGISTRATION', 'Household Registration'), ('COMMUNITY', 'Community-level Registration')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='unhcr_id',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='importeddocumenttype',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='consent_sharing',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', 'None'), ('UNICEF', 'UNICEF'), ('HUMANITARIAN_PARTNER', 'Humanitarian partners'), ('PRIVATE_PARTNER', 'Private partners'), ('GOVERNMENT_PARTNER', 'Government partners')], default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='female_age_group_0_5_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='female_age_group_0_5_disabled_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='female_age_group_12_17_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='female_age_group_12_17_disabled_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='female_age_group_6_11_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='female_age_group_6_11_disabled_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='male_age_group_0_5_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='male_age_group_0_5_disabled_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='male_age_group_12_17_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='male_age_group_12_17_disabled_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='male_age_group_6_11_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='male_age_group_6_11_disabled_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='name_enumerator',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='org_enumerator',
            field=models.CharField(blank=True, choices=[('', 'None'), ('UNICEF', 'UNICEF'), ('PARTNER', 'Partner')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='org_name_enumerator',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='pregnant_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='residence_status',
            field=models.CharField(choices=[('', 'None'), ('IDP', 'Displaced  |  Internally Displaced People'), ('REFUGEE', 'Displaced  |  Refugee / Asylum Seeker'), ('OTHERS_OF_CONCERN', 'Displaced  |  Others of Concern'), ('HOST', 'Non-displaced  |   Host'), ('NON_HOST', 'Non-displaced  |   Non-host')], max_length=255),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='returnee',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='village',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='comms_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='hearing_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='marital_status',
            field=models.CharField(choices=[('', 'None'), ('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated')], max_length=255),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='memory_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='physical_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='seeing_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='selfcare_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='importedagency',
            unique_together={('country', 'type')},
        ),
        migrations.CreateModel(
            name='KoboImportedSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_submission_uuid', models.UUIDField()),
                ('kobo_asset_id', models.CharField(max_length=150)),
                ('kobo_submission_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='kobo_asset_id',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='kobo_submission_uuid',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='collect_individual_data',
            field=models.CharField(choices=[('', 'None'), ('1', 'Yes'), ('0', 'No')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='child_hoh',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='consent',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='fchild_hoh',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='returnee',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='pregnant',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='ImportedHouseholdIdentity',
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='kobo_submission_time',
            field=models.DateTimeField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='documentvalidator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='documentvalidator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='importeddocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='importeddocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='importeddocumenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='importeddocumenttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='registrationdataimportdatahub',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='registrationdataimportdatahub',
            name='hct_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataimportdatahub',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='admin1_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='admin2_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(cast_flex_field_values, empty_reverse),
        migrations.RunPython(round_muac, empty_reverse),
        migrations.AlterField(
            model_name='importedindividual',
            name='disability',
            field=models.CharField(choices=[('disabled', 'disabled'), ('not disabled', 'not disabled')], default='not disabled', max_length=20),
        ),
        migrations.AlterField(
            model_name='importeddocumenttype',
            name='country',
            field=django_countries.fields.CountryField(default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='koboimportedsubmission',
            name='registration_data_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration_datahub.registrationdataimportdatahub'),
        ),
        migrations.AddField(
            model_name='koboimportedsubmission',
            name='imported_household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration_datahub.importedhousehold'),
        ),
        migrations.AddField(
            model_name='koboimportedsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='koboimportedsubmission',
            name='amended',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='female_age_group_0_5_count',
            new_name='female_age_group_0_4_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='female_age_group_0_5_disabled_count',
            new_name='female_age_group_0_4_disabled_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='female_age_group_12_17_count',
            new_name='female_age_group_13_17_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='female_age_group_12_17_disabled_count',
            new_name='female_age_group_13_17_disabled_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='female_age_group_6_11_count',
            new_name='female_age_group_5_12_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='female_age_group_6_11_disabled_count',
            new_name='female_age_group_5_12_disabled_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='male_age_group_0_5_count',
            new_name='male_age_group_0_4_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='male_age_group_0_5_disabled_count',
            new_name='male_age_group_0_4_disabled_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='male_age_group_12_17_count',
            new_name='male_age_group_13_17_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='male_age_group_12_17_disabled_count',
            new_name='male_age_group_13_17_disabled_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='male_age_group_6_11_count',
            new_name='male_age_group_5_12_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='male_age_group_6_11_disabled_count',
            new_name='male_age_group_5_12_disabled_count',
        ),
        migrations.RunPython(fix_fields_individuals, migrations.RunPython.noop),
        migrations.RunPython(fix_fields_households, migrations.RunPython.noop),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='female_age_group_0_4_count',
            new_name='female_age_group_0_5_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='female_age_group_0_4_disabled_count',
            new_name='female_age_group_0_5_disabled_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='female_age_group_13_17_count',
            new_name='female_age_group_12_17_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='female_age_group_13_17_disabled_count',
            new_name='female_age_group_12_17_disabled_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='female_age_group_5_12_count',
            new_name='female_age_group_6_11_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='female_age_group_5_12_disabled_count',
            new_name='female_age_group_6_11_disabled_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='male_age_group_0_4_count',
            new_name='male_age_group_0_5_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='male_age_group_0_4_disabled_count',
            new_name='male_age_group_0_5_disabled_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='male_age_group_13_17_count',
            new_name='male_age_group_12_17_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='male_age_group_13_17_disabled_count',
            new_name='male_age_group_12_17_disabled_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='male_age_group_5_12_count',
            new_name='male_age_group_6_11_count',
        ),
        migrations.RenameField(
            model_name='importedhousehold',
            old_name='male_age_group_5_12_disabled_count',
            new_name='male_age_group_6_11_disabled_count',
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='kobo_asset_id',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='row_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='row_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='KoboImportData',
            fields=[
                ('importdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration_datahub.importdata')),
                ('kobo_asset_id', models.CharField(max_length=100)),
                ('only_active_submissions', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('registration_datahub.importdata',),
        ),
        migrations.AddField(
            model_name='importdata',
            name='business_area_slug',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='importdata',
            name='created_by_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='importdata',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importdata',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('ERROR', 'Error'), ('VALIDATION_ERROR', 'Validation Error')], default='FINISHED', max_length=20),
        ),
        migrations.AddField(
            model_name='importdata',
            name='validation_errors',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='number_of_households',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='number_of_individuals',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='importedagency',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='flex_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='deduplication_batch_results',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='deduplication_golden_record_results',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='flex_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='importedindividualidentity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='koboimportedsubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='importeddocumenttype',
            name='type',
            field=models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('DRIVERS_LICENSE', "Driver's License"), ('ELECTORAL_CARD', 'Electoral Card'), ('NATIONAL_ID', 'National ID'), ('NATIONAL_PASSPORT', 'National Passport'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='consent_sharing',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', 'None'), ('GOVERNMENT_PARTNER', 'Government partners'), ('HUMANITARIAN_PARTNER', 'Humanitarian partners'), ('PRIVATE_PARTNER', 'Private partners'), ('UNICEF', 'UNICEF')], default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='org_enumerator',
            field=models.CharField(blank=True, choices=[('', 'None'), ('PARTNER', 'Partner'), ('UNICEF', 'UNICEF')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='registration_method',
            field=models.CharField(choices=[('', 'None'), ('COMMUNITY', 'Community-level Registration'), ('HH_REGISTRATION', 'Household Registration')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='comms_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all'), ('SOME_DIFFICULTY', 'Some difficulty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='deduplication_golden_record_status',
            field=models.CharField(blank=True, choices=[('DUPLICATE', 'Duplicate'), ('NEEDS_ADJUDICATION', 'Needs Adjudication'), ('NOT_PROCESSED', 'Not Processed'), ('UNIQUE', 'Unique')], default='UNIQUE', max_length=50),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='hearing_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all'), ('SOME_DIFFICULTY', 'Some difficulty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='marital_status',
            field=models.CharField(choices=[('', 'None'), ('DIVORCED', 'Divorced'), ('MARRIED', 'Married'), ('SEPARATED', 'Separated'), ('SINGLE', 'Single'), ('WIDOWED', 'Widowed')], max_length=255),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='memory_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all'), ('SOME_DIFFICULTY', 'Some difficulty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='physical_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all'), ('SOME_DIFFICULTY', 'Some difficulty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='relationship',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'Unknown'), ('AUNT_UNCLE', 'Aunt / Uncle'), ('BROTHER_SISTER', 'Brother / Sister'), ('COUSIN', 'Cousin'), ('DAUGHTERINLAW_SONINLAW', 'Daughter-in-law / Son-in-law'), ('GRANDDAUGHER_GRANDSON', 'Granddaughter / Grandson'), ('GRANDMOTHER_GRANDFATHER', 'Grandmother / Grandfather'), ('HEAD', 'Head of household (self)'), ('MOTHER_FATHER', 'Mother / Father'), ('MOTHERINLAW_FATHERINLAW', 'Mother-in-law / Father-in-law'), ('NEPHEW_NIECE', 'Nephew / Niece'), ('NON_BENEFICIARY', 'Not a Family Member. Can only act as a recipient.'), ('SISTERINLAW_BROTHERINLAW', 'Sister-in-law / Brother-in-law'), ('SON_DAUGHTER', 'Son / Daughter'), ('WIFE_HUSBAND', 'Wife / Husband')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='seeing_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all'), ('SOME_DIFFICULTY', 'Some difficulty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='selfcare_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all'), ('SOME_DIFFICULTY', 'Some difficulty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='importedindividualroleinhousehold',
            name='role',
            field=models.CharField(blank=True, choices=[('NO_ROLE', 'None'), ('ALTERNATE', 'Alternate collector'), ('PRIMARY', 'Primary collector')], max_length=255),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('storage', models.BinaryField(blank=True, null=True)),
                ('ignored', models.BooleanField(blank=True, db_index=True, default=False, null=True)),
                ('source_id', models.IntegerField(db_index=True)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('registration_data_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='registration_datahub.registrationdataimportdatahub')),
            ],
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='flex_registrations_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_households', to='registration_datahub.record'),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='data_type',
            field=models.CharField(choices=[('XLSX', 'XLSX File'), ('JSON', 'JSON File'), ('FLEX', 'Flex Registration')], default='XLSX', max_length=4),
        ),
        migrations.AlterField(
            model_name='importeddocumenttype',
            name='type',
            field=models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('DRIVERS_LICENSE', "Driver's License"), ('ELECTORAL_CARD', 'Electoral Card'), ('NATIONAL_ID', 'National ID'), ('NATIONAL_PASSPORT', 'National Passport'), ('TAX_ID', 'Tax Number Identification'), ('RESIDENCE_PERMIT_NO', "Foreigner's Residence Permit"), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='disability_certificate_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='relationship',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'Unknown'), ('AUNT_UNCLE', 'Aunt / Uncle'), ('BROTHER_SISTER', 'Brother / Sister'), ('COUSIN', 'Cousin'), ('DAUGHTERINLAW_SONINLAW', 'Daughter-in-law / Son-in-law'), ('GRANDDAUGHER_GRANDSON', 'Granddaughter / Grandson'), ('GRANDMOTHER_GRANDFATHER', 'Grandmother / Grandfather'), ('HEAD', 'Head of household (self)'), ('MOTHER_FATHER', 'Mother / Father'), ('MOTHERINLAW_FATHERINLAW', 'Mother-in-law / Father-in-law'), ('NEPHEW_NIECE', 'Nephew / Niece'), ('NON_BENEFICIARY', 'Not a Family Member. Can only act as a recipient.'), ('OTHER', 'Other'), ('SISTERINLAW_BROTHERINLAW', 'Sister-in-law / Brother-in-law'), ('SON_DAUGHTER', 'Son / Daughter'), ('WIFE_HUSBAND', 'Wife / Husband')], default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ImportedBankAccountInfo',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=64)),
                ('debit_card_number', models.CharField(blank=True, default='', max_length=255)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_info', to='registration_datahub.importedindividual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS individuals_num ON registration_datahub_record((data->'individuals_num'));",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS collectors_num ON registration_datahub_record((data->'collectors_num'));",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS head ON registration_datahub_record((data->'head'));",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS valid_phones ON registration_datahub_record((data->'valid_phones'));",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS birth_certificate ON registration_datahub_record((data->'birth_certificate'));",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS disability_certificate_match ON registration_datahub_record((data->'disability_certificate_match'));",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS collector_bank_account ON registration_datahub_record((data->'collector_bank_account'));",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS valid_payment ON registration_datahub_record((data->'valid_payment'));",
        ),
        migrations.AddField(
            model_name='record',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(blank=True, choices=[('TO_IMPORT', 'To import'), ('IMPORTED', 'Imported'), ('ERROR', 'Error')], max_length=16, null=True),
        ),
        migrations.AlterModelOptions(
            name='importedindividualidentity',
            options={'verbose_name_plural': 'Imported Individual Identities'},
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='mis_unicef_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='mis_unicef_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importeddocument',
            name='doc_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='diia_rec_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='deduplication_batch_results',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='address',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='record',
            name='counters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='files',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='index1',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='index2',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='index3',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='unique_field',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='deduplication_batch_results',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='data_type',
            field=models.CharField(choices=[('XLSX', 'XLSX File'), ('JSON', 'JSON File'), ('FLEX', 'Flex Registration'), ('DIIA', 'DIIA')], default='XLSX', max_length=4),
        ),
        migrations.CreateModel(
            name='DiiaIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('individual_id', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=85, null=True)),
                ('first_name', models.CharField(blank=True, max_length=85, null=True)),
                ('second_name', models.CharField(blank=True, max_length=85, null=True)),
                ('relationship', models.CharField(blank=True, choices=[(None, 'Unknown'), ('HEAD', 'Head of household (self)'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('HUSBAND', 'Husband'), ('WIFE', 'Wife')], max_length=255, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=255, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=64, null=True)),
                ('birth_doc', models.CharField(blank=True, max_length=128, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('', 'None'), ('DIVORCED', 'Divorced'), ('MARRIED', 'Married'), ('SEPARATED', 'Separated'), ('SINGLE', 'Single'), ('WIDOWED', 'Widowed')], max_length=255, null=True)),
                ('disability', models.CharField(blank=True, choices=[('True', 'disabled'), ('False', 'not disabled')], default='not disabled', max_length=20, null=True)),
                ('iban', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_type', models.CharField(blank=True, max_length=128, null=True)),
                ('doc_serie', models.CharField(blank=True, max_length=64, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=64, null=True)),
                ('doc_issue_date', models.CharField(blank=True, max_length=64, null=True)),
                ('imported_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diia_individuals', to='registration_datahub.importedindividual')),
                ('registration_data_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diia_individuals', to='registration_datahub.registrationdataimportdatahub')),
            ],
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='deduplication_golden_record_status',
            field=models.CharField(blank=True, choices=[('DUPLICATE', 'Duplicate'), ('NEEDS_ADJUDICATION', 'Needs Adjudication'), ('NOT_PROCESSED', 'Not Processed'), ('POSTPONE', 'Postpone'), ('UNIQUE', 'Unique')], default='UNIQUE', max_length=50),
        ),
        migrations.CreateModel(
            name='DiiaHousehold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('vpo_doc', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.validate_image_file_extension])),
                ('vpo_doc_id', models.CharField(blank=True, max_length=128, null=True)),
                ('vpo_doc_date', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('consent', models.BooleanField(null=True)),
                ('source_data', models.TextField(blank=True, default='', null=True)),
                ('imported_household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diia_households', to='registration_datahub.importedhousehold')),
                ('registration_data_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diia_households', to='registration_datahub.registrationdataimportdatahub')),
                ('status', models.CharField(blank=True, choices=[(None, 'To import'), ('IMPORTED', 'Imported'), ('ERROR', 'Error'), ('TAX_ID_ERROR', 'Tax ID Error')], max_length=16, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='registrationdataimportdatahub',
            options={'ordering': ('name',), 'permissions': (['api_upload', 'Can upload'],)},
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='collect_individual_data',
            field=models.CharField(choices=[('', 'Unknown'), ('2', 'Partial individuals collected'), ('1', 'Full individual collected'), ('0', 'No individual data')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='registrationdataimportdatahub',
            name='import_done',
            field=models.CharField(choices=[('LOADING', 'Loading'), ('NOT_STARTED', 'Not Started'), ('STARTED', 'Started'), ('DONE', 'Done')], default='NOT_STARTED', max_length=15),
        ),
        migrations.AddField(
            model_name='importeddocument',
            name='country',
            field=django_countries.fields.CountryField(default='U', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='importeddocumenttype',
            unique_together=set(),
        ),
        migrations.RunPython(migrate_doc_type, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='importeddocumenttype',
            name='country',
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='phone_no_alternative_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='phone_no_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(update_each_phone_numbers_validity, migrations.RunPython.noop),
        migrations.AddField(
            model_name='importedindividualidentity',
            name='country',
            field=django_countries.fields.CountryField(default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='importedindividualidentity',
            name='partner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(populate_partner_and_country, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='importedindividualidentity',
            name='agency',
        ),
        migrations.DeleteModel(
            name='ImportedAgency',
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('aa', 'Afar'), ('ab', 'Abkhazian'), ('af', 'Afrikaans'), ('ak', 'Akan'), ('sq', 'Albanian'), ('am', 'Amharic'), ('ar', 'Arabic'), ('an', 'Aragonese'), ('hy', 'Armenian'), ('as', 'Assamese'), ('av', 'Avaric'), ('ae', 'Avestan'), ('ay', 'Aymara'), ('az', 'Azerbaijani'), ('ba', 'Bashkir'), ('bm', 'Bambara'), ('eu', 'Basque'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('bh', 'Bihari languages'), ('bi', 'Bislama'), ('bs', 'Bosnian'), ('br', 'Breton'), ('bg', 'Bulgarian'), ('my', 'Burmese'), ('ca', 'Catalan; Valencian'), ('ch', 'Chamorro'), ('ce', 'Chechen'), ('zh', 'Chinese'), ('cu', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'), ('cv', 'Chuvash'), ('kw', 'Cornish'), ('co', 'Corsican'), ('cr', 'Cree'), ('cs', 'Czech'), ('da', 'Danish'), ('dv', 'Divehi; Dhivehi; Maldivian'), ('nl', 'Dutch; Flemish'), ('dz', 'Dzongkha'), ('en', 'English'), ('eo', 'Esperanto'), ('et', 'Estonian'), ('ee', 'Ewe'), ('fo', 'Faroese'), ('fj', 'Fijian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Western Frisian'), ('ff', 'Fulah'), ('ka', 'Georgian'), ('de', 'German'), ('gd', 'Gaelic; Scottish Gaelic'), ('ga', 'Irish'), ('gl', 'Galician'), ('gv', 'Manx'), ('el', 'Greek, Modern (1453-)'), ('gn', 'Guarani'), ('gu', 'Gujarati'), ('ht', 'Haitian; Haitian Creole'), ('ha', 'Hausa'), ('he', 'Hebrew'), ('hz', 'Herero'), ('hi', 'Hindi'), ('ho', 'Hiri Motu'), ('hr', 'Croatian'), ('hu', 'Hungarian'), ('ig', 'Igbo'), ('is', 'Icelandic'), ('io', 'Ido'), ('ii', 'Sichuan Yi; Nuosu'), ('iu', 'Inuktitut'), ('ie', 'Interlingue; Occidental'), ('ia', 'Interlingua (International Auxiliary Language Association)'), ('id', 'Indonesian'), ('ik', 'Inupiaq'), ('it', 'Italian'), ('jv', 'Javanese'), ('ja', 'Japanese'), ('kl', 'Kalaallisut; Greenlandic'), ('kn', 'Kannada'), ('ks', 'Kashmiri'), ('kr', 'Kanuri'), ('kk', 'Kazakh'), ('km', 'Central Khmer'), ('ki', 'Kikuyu; Gikuyu'), ('rw', 'Kinyarwanda'), ('ky', 'Kirghiz; Kyrgyz'), ('kv', 'Komi'), ('kg', 'Kongo'), ('ko', 'Korean'), ('kj', 'Kuanyama; Kwanyama'), ('ku', 'Kurdish'), ('lo', 'Lao'), ('la', 'Latin'), ('lv', 'Latvian'), ('li', 'Limburgan; Limburger; Limburgish'), ('ln', 'Lingala'), ('lt', 'Lithuanian'), ('lb', 'Luxembourgish; Letzeburgesch'), ('lu', 'Luba-Katanga'), ('lg', 'Ganda'), ('mk', 'Macedonian'), ('mh', 'Marshallese'), ('ml', 'Malayalam'), ('mi', 'Maori'), ('mr', 'Marathi'), ('ms', 'Malay'), ('mg', 'Malagasy'), ('mt', 'Maltese'), ('mn', 'Mongolian'), ('na', 'Nauru'), ('nv', 'Navajo; Navaho'), ('nr', 'Ndebele, South; South Ndebele'), ('nd', 'Ndebele, North; North Ndebele'), ('ng', 'Ndonga'), ('ne', 'Nepali'), ('nn', 'Norwegian Nynorsk; Nynorsk, Norwegian'), ('nb', 'Bokmål, Norwegian; Norwegian Bokmål'), ('no', 'Norwegian'), ('ny', 'Chichewa; Chewa; Nyanja'), ('oc', 'Occitan (post 1500)'), ('oj', 'Ojibwa'), ('or', 'Oriya'), ('om', 'Oromo'), ('os', 'Ossetian; Ossetic'), ('pa', 'Panjabi; Punjabi'), ('fa', 'Persian'), ('pi', 'Pali'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ps', 'Pushto; Pashto'), ('qu', 'Quechua'), ('rm', 'Romansh'), ('ro', 'Romanian; Moldavian; Moldovan'), ('rn', 'Rundi'), ('ru', 'Russian'), ('sg', 'Sango'), ('sa', 'Sanskrit'), ('si', 'Sinhala; Sinhalese'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('se', 'Northern Sami'), ('sm', 'Samoan'), ('sn', 'Shona'), ('sd', 'Sindhi'), ('so', 'Somali'), ('st', 'Sotho, Southern'), ('es', 'Spanish; Castilian'), ('sc', 'Sardinian'), ('sr', 'Serbian'), ('ss', 'Swati'), ('su', 'Sundanese'), ('sw', 'Swahili'), ('sv', 'Swedish'), ('ty', 'Tahitian'), ('ta', 'Tamil'), ('tt', 'Tatar'), ('te', 'Telugu'), ('tg', 'Tajik'), ('tl', 'Tagalog'), ('th', 'Thai'), ('bo', 'Tibetan'), ('ti', 'Tigrinya'), ('to', 'Tonga (Tonga Islands)'), ('tn', 'Tswana'), ('ts', 'Tsonga'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tw', 'Twi'), ('ug', 'Uighur; Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('ve', 'Venda'), ('vi', 'Vietnamese'), ('vo', 'Volapük'), ('cy', 'Welsh'), ('wa', 'Walloon'), ('wo', 'Wolof'), ('xh', 'Xhosa'), ('yi', 'Yiddish'), ('yo', 'Yoruba'), ('za', 'Zhuang; Chuang'), ('zu', 'Zulu')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='admin3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='admin3_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='admin4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='admin4_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='admin_area',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='admin_area_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
