# Generated by Django 2.2.8 on 2020-02-25 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0002_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedindividual',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationdataimportdatahub',
            name='imported_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
