# Generated by Django 2.2.8 on 2020-05-02 12:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0002_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedhousehold',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='admin1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='admin2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='geopoint',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='registration_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='returnee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='estimated_birth_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='family_name',
            field=models.CharField(blank=True, default='', max_length=85),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='given_name',
            field=models.CharField(blank=True, default='', max_length=85),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=85),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='phone_no_alternative',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='relationship',
            field=models.CharField(blank=True, choices=[('NON_BENEFICIARY', 'Not a Family Member. Can only act as a recipient.'), ('HEAD', 'Head of household (self)'), ('SON_DAUGHTER', 'Son / Daughter'), ('WIFE_HUSBAND', 'Wife / Husband'), ('BROTHER_SISTER', 'Brother / Sister'), ('MOTHER_FATHER', 'Mother / Father'), ('AUNT_UNCLE', 'Aunt / Uncle'), ('GRANDMOTHER_GRANDFATHER', 'Grandmother / Grandfather'), ('MOTHERINLAW_FATHERINLAW', 'Mother-in-law / Father-in-law'), ('DAUGHTERINLAW_SONINLAW', 'Daughter-in-law / Son-in-law'), ('SISTERINLAW_BROTHERINLAW', 'Sister-in-law / Brother-in-law'), ('GRANDDAUGHER_GRANDSON', 'Granddaughter / Grandson'), ('NEPHEW_NIECE', 'Nephew / Niece'), ('COUSIN', 'Cousin')], default='', max_length=255),
        ),
    ]
