# Generated by Django 2.2.8 on 2020-05-12 13:01

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Concat


def remove_duplicates(apps, schema_editor):
    ImportedDocument = apps.get_model(
        "registration_datahub", "ImportedDocument"
    )

    master_qs_docs = ImportedDocument.objects.annotate(
        concat_id_doc_num=Concat(
            F("type__id"),
            F("document_number"),
            output_field=models.CharField(),
        ),
    ).distinct("concat_id_doc_num")

    for master in master_qs_docs:
        ImportedDocument.objects.filter(
            type=master.type, document_number=master.document_number
        ).exclude(pk=master.pk).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("registration_datahub", "0003_migration"),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
    ]
