# Generated by Django 2.2.8 on 2020-05-12 13:01

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Concat


def remove_duplicates(apps, schema_editor):
    ImportedDocumentType = apps.get_model(
        "registration_datahub", "ImportedDocumentType"
    )

    master_qs_types = ImportedDocumentType.objects.annotate(
        concat_country_type=Concat(
            F("country"), F("type"), output_field=models.CharField(),
        ),
    ).distinct("concat_country_type")

    for master in master_qs_types:
        ImportedDocumentType.objects.filter(
            country=master.country, type=master.type
        ).exclude(pk=master.pk).delete()


def set_document_types(apps, schema_editor):
    choices = {
        "Driving License": "DRIVERS_LICENSE",
        "Birth Certificate": "BIRTH_CERTIFICATE",
        "National ID": "NATIONAL_ID",
        "National Passport": "NATIONAL_PASSPORT",
    }
    ImportedDocumentType = apps.get_model(
        "registration_datahub", "ImportedDocumentType"
    )
    imported_doc_types = ImportedDocumentType.objects.all()
    for obj in imported_doc_types:
        obj.type = choices.get(obj.label)
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("registration_datahub", "0004_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="importeddocumenttype",
            name="type",
            field=models.CharField(
                choices=[
                    ("BIRTH_CERTIFICATE", "Birth Certificate"),
                    ("DRIVERS_LICENSE", "Driver's License"),
                    ("NATIONAL_ID", "National ID"),
                    ("NATIONAL_PASSPORT", "National Passport"),
                    ("ELECTORAL_CARD", "Electoral Card"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                blank=True,
                default="",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_document_types),
        migrations.AlterField(
            model_name="importeddocumenttype",
            name="type",
            field=models.CharField(
                choices=[
                    ("BIRTH_CERTIFICATE", "Birth Certificate"),
                    ("DRIVERS_LICENSE", "Driver's License"),
                    ("NATIONAL_ID", "National ID"),
                    ("NATIONAL_PASSPORT", "National Passport"),
                    ("ELECTORAL_CARD", "Electoral Card"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.RunPython(remove_duplicates),
    ]
