# Generated by Django 2.2.8 on 2020-03-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0005_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedindividual',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=255),
        ),
    ]
