# Generated by Django 2.2.8 on 2020-05-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0006_migration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agency',
            new_name='ImportedAgency',
        ),
    ]
