# Generated by Django 2.2.8 on 2020-07-14 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0011_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importedhousehold',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='first_registration_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 14, 13, 43, 3, 630869)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='last_registration_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 14, 13, 43, 10, 2224)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='first_registration_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 14, 13, 43, 16, 947)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importedindividual',
            name='last_registration_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 14, 13, 43, 21, 163324)),
            preserve_default=False,
        ),
    ]
