# Generated by Django 2.2.8 on 2020-07-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0012_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importeddocumenttype',
            name='country',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='country',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='country_origin',
            field=models.CharField(max_length=3),
        ),
    ]
