# Generated by Django 2.2.8 on 2020-08-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0015_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedindividual',
            name='possible_duplicate_flag',
            field=models.BooleanField(default=False),
        ),
    ]
