# Generated by Django 2.2.8 on 2020-08-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0017_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdataimportdatahub',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
