# Generated by Django 2.2.8 on 2020-04-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0018_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedindividual',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=255),
        ),
    ]
