# Generated by Django 2.2.8 on 2020-09-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0022_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedindividual',
            name='pregnant',
            field=models.BooleanField(default=False),
        ),
    ]
