# Generated by Django 2.2.16 on 2020-12-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0027_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedindividual',
            name='comms_disability',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='hearing_disability',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='memory_disability',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='physical_disability',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='seeing_disability',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='selfcare_disability',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
    ]
