# Generated by Django 2.2.16 on 2020-12-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0030_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboImportedSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_submission_uuid', models.UUIDField()),
                ('kobo_asset_id', models.CharField(max_length=150)),
                ('submission_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='kobo_asset_id',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='kobo_submission_uuid',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
