# Generated by Django 2.2.16 on 2021-01-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0033_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='koboimportedsubmission',
            old_name='submission_time',
            new_name='kobo_submission_time',
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='kobo_submission_time',
            field=models.DateTimeField(blank=True, max_length=150, null=True),
        ),
    ]
