# Generated by Django 2.2.16 on 2021-02-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0035_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedhousehold',
            name='admin1_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='admin2_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
