# Generated by Django 2.2.16 on 2021-08-06 11:59

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0039_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importeddocumenttype',
            name='country',
            field=django_countries.fields.CountryField(default='U', max_length=2),
        ),
    ]
