# Generated by Django 3.2 on 2022-02-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0049_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedagency',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='importedhousehold',
            name='flex_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='deduplication_batch_results',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='deduplication_golden_record_results',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='importedindividual',
            name='flex_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='importedindividualidentity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='koboimportedsubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
