# Generated by Django 3.2.12 on 2022-03-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0051_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('storage', models.BinaryField(blank=True, null=True)),
                ('ignored', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
