# Generated by Django 3.2.12 on 2022-04-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0054_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedhousehold',
            name='flex_registrations_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_households', to='registration_datahub.record'),
        ),
        migrations.AddField(
            model_name='record',
            name='registration_data_import',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='registration_datahub.registrationdataimportdatahub'),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='data_type',
            field=models.CharField(choices=[('XLSX', 'XLSX File'), ('JSON', 'JSON File'), ('FLEX', 'Flex Registration')], default='XLSX', max_length=4),
        ),
        migrations.AlterField(
            model_name='importeddocumenttype',
            name='type',
            field=models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('DRIVERS_LICENSE', "Driver's License"), ('ELECTORAL_CARD', 'Electoral Card'), ('NATIONAL_ID', 'National ID'), ('NATIONAL_PASSPORT', 'National Passport'), ('TAX_ID', 'Tax Number Identification'), ('RESIDENCE_PERMIT_NO', "Foreigner's Residence Permit"), ('OTHER', 'Other')], max_length=50),
        ),
    ]
