# Generated by Django 3.2.12 on 2022-04-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0060_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importedindividualidentity',
            options={'verbose_name_plural': 'Imported Individual Identities'},
        ),
        migrations.AlterField(
            model_name='record',
            name='ignored',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
    ]
