# Generated by Django 3.2.12 on 2022-04-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0061_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='files',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
