# Generated by Django 3.2.13 on 2022-05-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0064_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedindividual',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
