# Generated by Django 3.2.12 on 2022-05-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0064_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeddocument',
            name='doc_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='importedhousehold',
            name='diia_rec_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
