# Generated by Django 3.2.13 on 2022-06-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0065_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='diiahousehold',
            name='source_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='diiahousehold',
            name='address',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
