# Generated by Django 3.2.13 on 2022-06-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0067_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedhousehold',
            name='address',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
