# Generated by Django 3.2.13 on 2022-06-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0068_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='counters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='files',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='index1',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='index2',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='index3',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='unique_field',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
