# Generated by Django 3.2.13 on 2022-06-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0070_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diiahousehold',
            name='source_data',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='diiahousehold',
            name='vpo_doc_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='diiaindividual',
            name='birth_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='diiaindividual',
            name='doc_issue_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
