# Generated by Django 3.2.13 on 2022-06-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0071_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diiahousehold',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='diiahousehold',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='diiaindividual',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='diiaindividual',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='diiahousehold',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diiaindividual',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
