# Generated by Django 3.2.13 on 2022-06-14 14:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0072_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiiaIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('individual_id', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=85, null=True)),
                ('first_name', models.CharField(blank=True, max_length=85, null=True)),
                ('second_name', models.CharField(blank=True, max_length=85, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('UNKNOWN', 'Unknown'), ('AUNT_UNCLE', 'Aunt / Uncle'), ('BROTHER_SISTER', 'Brother / Sister'), ('COUSIN', 'Cousin'), ('DAUGHTERINLAW_SONINLAW', 'Daughter-in-law / Son-in-law'), ('GRANDDAUGHER_GRANDSON', 'Granddaughter / Grandson'), ('GRANDMOTHER_GRANDFATHER', 'Grandmother / Grandfather'), ('HEAD', 'Head of household (self)'), ('MOTHER_FATHER', 'Mother / Father'), ('MOTHERINLAW_FATHERINLAW', 'Mother-in-law / Father-in-law'), ('NEPHEW_NIECE', 'Nephew / Niece'), ('NON_BENEFICIARY', 'Not a Family Member. Can only act as a recipient.'), ('OTHER', 'Other'), ('SISTERINLAW_BROTHERINLAW', 'Sister-in-law / Brother-in-law'), ('SON_DAUGHTER', 'Son / Daughter'), ('WIFE_HUSBAND', 'Wife / Husband')], max_length=255, null=True)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=255, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=64, null=True)),
                ('birth_doc', models.CharField(blank=True, max_length=128, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('', 'None'), ('DIVORCED', 'Divorced'), ('MARRIED', 'Married'), ('SEPARATED', 'Separated'), ('SINGLE', 'Single'), ('WIDOWED', 'Widowed')], max_length=255, null=True)),
                ('disability', models.CharField(blank=True, choices=[('disabled', 'disabled'), ('not disabled', 'not disabled')], default='not disabled', max_length=20, null=True)),
                ('iban', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_type', models.CharField(blank=True, max_length=128, null=True)),
                ('doc_serie', models.CharField(blank=True, max_length=64, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=64, null=True)),
                ('doc_issue_date', models.CharField(blank=True, max_length=64, null=True)),
                ('imported_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diia_individuals', to='registration_datahub.importedindividual')),
                ('registration_data_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diia_individuals', to='registration_datahub.registrationdataimportdatahub')),
            ],
        ),
        migrations.CreateModel(
            name='DiiaHousehold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('vpo_doc', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.validate_image_file_extension])),
                ('vpo_doc_id', models.CharField(blank=True, max_length=128, null=True)),
                ('vpo_doc_date', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('consent', models.BooleanField(null=True)),
                ('source_data', models.TextField(blank=True, default='', null=True)),
                ('imported_household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diia_households', to='registration_datahub.importedhousehold')),
                ('registration_data_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diia_households', to='registration_datahub.registrationdataimportdatahub')),
            ],
        ),
    ]
