# Generated by Django 3.2.13 on 2022-06-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0073_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='diiahousehold',
            name='status',
            field=models.CharField(blank=True, choices=[(None, 'To import'), ('IMPORTED', 'Imported'), ('ERROR', 'Error')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='diiaindividual',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='data_type',
            field=models.CharField(choices=[('XLSX', 'XLSX File'), ('JSON', 'JSON File'), ('FLEX', 'Flex Registration'), ('DIIA', 'DIIA')], default='XLSX', max_length=4),
        ),
    ]
