# Generated by Django 3.2.13 on 2022-06-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0074_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diiaindividual',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=255, null=True),
        ),
    ]
