# Generated by Django 3.2.13 on 2022-06-21 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0075_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diiahousehold',
            name='imported_household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diia_households', to='registration_datahub.importedhousehold'),
        ),
        migrations.AlterField(
            model_name='diiahousehold',
            name='registration_data_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diia_households', to='registration_datahub.registrationdataimportdatahub'),
        ),
        migrations.AlterField(
            model_name='diiaindividual',
            name='imported_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diia_individuals', to='registration_datahub.importedindividual'),
        ),
        migrations.AlterField(
            model_name='diiaindividual',
            name='registration_data_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diia_individuals', to='registration_datahub.registrationdataimportdatahub'),
        ),
    ]
