# Generated by Django 3.2.15 on 2022-11-16 16:44

from django.db import migrations, models
import django.db.models.deletion
import hct_mis_api.apps.payment.models_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0079_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedPaymentChannelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('individual', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration_datahub.importedindividual')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedPaymentChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_mechanism_id', models.CharField(max_length=128)),
                ('is_fallback', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_payment_channels', to='registration_datahub.importedindividual')),
                ('payment_channel_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration_datahub.importedpaymentchanneldata')),
            ],
            bases=(hct_mis_api.apps.payment.models_mixins.DeliveryDataMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='importedpaymentchannel',
            constraint=models.UniqueConstraint(fields=('individual', 'delivery_mechanism_id'), name='unique imported_individual_delivery_mechanism_id'),
        ),
    ]
