# Generated by Django 3.2.15 on 2022-10-03 17:56

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0079_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeddocument',
            name='country',
            field=django_countries.fields.CountryField(default='U', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='importeddocumenttype',
            unique_together=set(),
        ),
    ]
