# Generated by Django 3.2.15 on 2023-02-27 18:08
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('registration_datahub', '0090_migration'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='record',
                    name='registration',
                    field=models.IntegerField(db_index=True),
                ),
            ],
            database_operations=[
                AddIndexConcurrently(
                    model_name="record",
                    index=models.Index(
                        fields=["registration"], name="registration_datahub_record_registration_5edac906"
                    )
                ),
            ]
        )
    ]
