# Generated by Django 3.2.18 on 2023-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0097_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedhousehold',
            name='enumerator_rec_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
