# Generated by Django 3.2.18 on 2023-05-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0098_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeddocument',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='importeddocument',
            name='issuance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
