# Generated by Django 3.2.20 on 2023-07-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0100_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedindividual',
            name='age_at_registration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
