# Generated by Django 3.2.20 on 2023-09-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_migration'),
        ('registration_datahub', '0102_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedhousehold',
            name='data_collecting_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imported_households', to='core.datacollectingtype'),
        ),
    ]
