<<<<<<< HEAD
# Generated by Django 3.2.25 on 2024-04-23 17:25

from django.db import migrations, models
import django.db.models.deletion
import hct_mis_api.apps.payment.models_mixins
import model_utils.fields
import uuid


class Migration(migrations.Migration):

=======
# Generated by Django 3.2.23 on 2024-02-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
>>>>>>> origin/develop
    dependencies = [
        ('registration_datahub', '0110_migration'),
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='importdata',
            name='delivery_mechanisms_validation_errors',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('ERROR', 'Error'), ('VALIDATION_ERROR', 'Validation Error'), ('DELIVERY_MECHANISMS_VALIDATION_ERROR', 'Delivery Mechanisms Validation Error')], default='FINISHED', max_length=40),
        ),
        migrations.CreateModel(
            name='ImportedDeliveryMechanismData',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('delivery_mechanism', models.CharField(choices=[('Cardless cash withdrawal', 'Cardless cash withdrawal'), ('Cash', 'Cash'), ('Cash by FSP', 'Cash by FSP'), ('Cheque', 'Cheque'), ('Deposit to Card', 'Deposit to Card'), ('Mobile Money', 'Mobile Money'), ('Pre-paid card', 'Pre-paid card'), ('Referral', 'Referral'), ('Transfer', 'Transfer'), ('Transfer to Account', 'Transfer to Account'), ('Voucher', 'Voucher'), ('ATM Card', 'ATM Card'), ('Cash over the counter', 'Cash over the counter')], max_length=255, verbose_name='Delivery Mechanism')),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(default=dict)),
                ('unique_key', models.CharField(blank=True, editable=False, max_length=256, null=True, unique=True)),
                ('individual', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_mechanisms_data', to='registration_datahub.importedindividual')),
            ],
            options={
                'abstract': False,
            },
            bases=(hct_mis_api.apps.payment.models_mixins.DeliveryDataMixin, models.Model),
=======
            model_name='importedhousehold',
            name='program_registration_id',
            field=models.CharField(blank=True, max_length=50, null=True),
>>>>>>> origin/develop
        ),
    ]
