github_checks:
  annotations: false

coverage:
  status:
    project:
      default:
        threshold: 5%
    patch:
      default:
        target: 95%
  ignore:
    - "**/forms.py"
    - "*/selenium_tests/**"
    - "*/tests/**"
    - "*/migrations/*"
    - "*/apps.py"
    - "*/admin/*.py"
    - "*/payment_admin.py"
    - "**/aurora.py"
    - "src/hct_mis_api/one_time_scripts/*"
    - "src/hct_mis_api/libs/*"
    - "src/hct_mis_api/settings/*"
    - "src/hct_mis_api/settings.py"
    - "src/hct_mis_api/conftest.py"
    - "src/hct_mis_api/config/settings.py"
    - "src/hct_mis_api/apps/core/management/commands/*"
    - "src/hct_mis_api/apps/payment/models/cash_assist.py"
    - "pragma: no cover"
    - "pragma: no-cover"
    - "def __repr__"
    - "raise AssertionError"
    - "raise NotImplementedError"
    - "except ImportError"
    - "if __name__ == .__main__."
    - "if TYPE_CHECKING"
    - "^\\s*(import\\s.+|from\\s+.+import\\s+.+)"
    - "logger.exception(e)"