[mypy]
python_version = 3.14
show_error_codes = true
exclude = migrations|venv|snapshots|__pypackages__|build|uv-cache
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

strict = true
ignore_missing_imports = true
follow_imports = normal
mypy_path = stubs

disable_error_code = var-annotated, attr-defined, misc, union-attr, type-arg, no-any-return

[mypy.plugins.django-stubs]
django_settings_module = hope.config.settings
