# Generated by Django 2.2.16 on 2021-09-16 11:48

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.citext
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('original_id', models.UUIDField(blank=True, null=True)),
                ('name', django.contrib.postgres.fields.citext.CICharField(db_index=True, max_length=255)),
                ('short_name', django.contrib.postgres.fields.citext.CICharField(db_index=True, max_length=255)),
                ('iso_code2', models.CharField(max_length=2, unique=True)),
                ('iso_code3', models.CharField(max_length=3, unique=True)),
                ('iso_num', models.CharField(max_length=4, unique=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='geo.Country', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AreaType',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('original_id', models.UUIDField(blank=True, null=True)),
                ('name', django.contrib.postgres.fields.citext.CICharField(db_index=True, max_length=255)),
                ('area_level', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateTimeField(auto_now_add=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Country')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.AreaType', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'Area Types',
                'unique_together': {('country', 'area_level', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('original_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('p_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='P Code')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('valid_from', models.DateTimeField(auto_now_add=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('area_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.AreaType')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Area', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'unique_together': {('area_type', 'name')},
            },
        ),
    ]
