# Generated by Django 2.2.16 on 2021-09-16 09:26

from django.db import migrations

from hct_mis_api.apps.geo.utils import initialise_countries


def initialise_geo(apps, schema_editor):
    initialise_countries()


def rebuild(apps, schema_editor):
    from hct_mis_api.apps.geo.models import Country
    Country.objects.rebuild()


def empty_reverse(apps, schema_editor):
    Country = apps.get_model("geo", "Country")
    Country.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0001_migration")
    ]

    operations = [
        migrations.RunPython(initialise_geo, empty_reverse),
        migrations.RunPython(rebuild, empty_reverse),
    ]
