# Generated by Django 3.2.25 on 2024-07-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_migration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='area',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(condition=models.Q(('p_code', ''), _negated=True), fields=('p_code',), name='unique_area_p_code_not_blank'),
        ),
    ]
