# Generated by Django 3.2.25 on 2025-01-22 18:59
from django.conf import settings
from django.db import migrations
from django.db.models import Count, Q
from django.utils import timezone
from mptt import register

from hope.apps.account.models import Role
from hope.apps.account.permissions import DEFAULT_PERMISSIONS_LIST_FOR_IS_UNICEF_PARTNER

BATCH_SIZE = 1000
BATCH_SIZE_SMALL = 20


def create_constant_objects(apps, schema_editor):
    """Create constant objects for the migration. This is necessary for tests but already present on all the environments."""
    Role = apps.get_model("account", "Role")
    Partner = apps.get_model("account", "Partner")
    register(Partner)

    Role.objects.get_or_create(
        name="Role with all permissions",
        defaults={
            "is_visible_on_ui": False,
            "is_available_for_partner": True,
            "permissions": [],
        },
    )
    Partner.objects.get_or_create(name="UNICEF")


def migrate_user_roles(apps, schema_editor):
    """Handle migration of user roles.

    UserRole model was replaced with RoleAssignment model, which includes a program field.
    After model update, existing UserRoles would have program=null, granting users access to all programs by default.
    This migration will fetch the programs for specific Business Areas from UserRole
    and create RoleAssignment entries for each program to preserve the original access.
    """
    RoleAssignment = apps.get_model("account", "RoleAssignment")
    ProgramPartnerThrough = apps.get_model("program", "ProgramPartnerThrough")

    expiration_time = timezone.now()

    # do not change UserRoles for Global as it can stay with program=None
    user_roles = (
        RoleAssignment.objects.filter(user__isnull=False, program__isnull=True)
        .exclude(business_area__slug="global")
        .select_related("user__partner", "business_area")
    )

    program_access_mapping = {
        (partner_id, business_area_id): list(
            ProgramPartnerThrough.objects.filter(
                partner_id=partner_id, program__business_area_id=business_area_id
            ).values_list("program_id", flat=True)
        )
        for partner_id, business_area_id in user_roles.values_list("user__partner_id", "business_area_id").distinct()
    }
    user_roles_ids = list(user_roles.values_list("id", flat=True))
    user_roles_count = len(user_roles_ids)

    for batch_start in range(0, user_roles_count, BATCH_SIZE):
        new_assignments = []
        updated_roles = []
        batch_end = batch_start + BATCH_SIZE
        batched_user_roles_ids = user_roles_ids[batch_start:batch_end]
        batched_user_roles = list(
            RoleAssignment.objects.filter(id__in=batched_user_roles_ids).select_related(
                "user",
                "user__partner",
                "business_area",
            )
        )
        for user_role in batched_user_roles:
            user = user_role.user
            partner = user.partner
            business_area = user_role.business_area

            programs = program_access_mapping.get((partner.id, business_area.id), []) if partner else []

            if programs:
                user_role.program_id = programs[0]
                updated_roles.append(user_role)
                new_assignments.extend(
                    RoleAssignment(
                        user=user,
                        partner=None,
                        role=user_role.role,
                        business_area=business_area,
                        program_id=program,
                        expiry_date=user_role.expiry_date,
                    )
                    for program in programs[1:]
                )
            else:
                # If user has no partner
                # or their partner does not have access to any program in the UserRole's Business Area,
                # make the user role inactive.
                # In another case, the user would gain access to all programs.
                user_role.expiry_date = expiration_time
                updated_roles.append(user_role)

        if updated_roles:
            RoleAssignment.objects.bulk_update(updated_roles, ["program", "expiry_date"])
        if new_assignments:
            RoleAssignment.objects.bulk_create(new_assignments)


def migrate_partner_roles_and_access(apps, schema_editor):
    """Handle migration of partner roles and access.

    ProgramPartnerThrough and BusinessAreaPartnerThrough models need to be migrated into RoleAssignment model.
    For each combination of role in the BusinessAreaPartnerThrough and a program in the ProgramPartnerThrough,
    that partner has access to within the BA of the role -> the RoleAssignment entry needs to be created.

    Additionally, area access defined on areas filed in ProgramPartnerThrough needs to be moved to
    AdminAreaLimitedTo model and the logic needs changing - create records in the AdminAreaLimitedTo only
    if this is NOT a full-area-access - so if there are area limits applied.
    """
    RoleAssignment = apps.get_model("account", "RoleAssignment")
    ProgramPartnerThrough = apps.get_model("program", "ProgramPartnerThrough")
    BusinessAreaPartnerThrough = apps.get_model("core", "BusinessAreaPartnerThrough")
    AdminAreaLimitedTo = apps.get_model("account", "AdminAreaLimitedTo")
    Partner = apps.get_model("account", "Partner")
    register(Partner)

    # do not create RoleAssignments for partners that are parents or UNICEF
    partner_roles = BusinessAreaPartnerThrough.objects.exclude(
        Q(partner_id__in=Partner.objects.filter(parent__isnull=False).values_list("parent_id", flat=True))
        | Q(partner__name="UNICEF")
    ).select_related("partner", "business_area")

    program_access_mapping = {
        (partner_id, business_area_id): list(
            ProgramPartnerThrough.objects.filter(
                partner_id=partner_id, program__business_area_id=business_area_id
            ).values_list("program_id", flat=True)
        )
        for partner_id, business_area_id in partner_roles.values_list("partner_id", "business_area_id").distinct()
    }

    partner_roles_ids = list(partner_roles.values_list("id", flat=True))
    partner_roles_count = len(partner_roles_ids)

    for batch_start in range(0, partner_roles_count, BATCH_SIZE):
        new_assignments = []
        batch_end = batch_start + BATCH_SIZE
        batched_partner_roles_ids = partner_roles_ids[batch_start:batch_end]
        batched_partner_roles = list(
            BusinessAreaPartnerThrough.objects.filter(id__in=batched_partner_roles_ids)
            .select_related("partner", "business_area")
            .prefetch_related("roles")
        )

        for partner_role in batched_partner_roles:
            partner = partner_role.partner
            business_area = partner_role.business_area
            roles = partner_role.roles.exclude(name="Role with all permissions")
            # in case some existing Partner on any env has "Role with all permissions" -
            # which is not allowed for Partners anymore

            programs = program_access_mapping.get((partner.id, business_area.id), [])

            # Create RoleAssignments only if the partner has access to any program in the Business Area
            # of the BusinessAreaPartnerThrough
            if programs:
                partner.allowed_business_areas.add(business_area)
                new_assignments.extend(
                    RoleAssignment(
                        user=None, partner=partner, role=role, business_area=business_area, program_id=program
                    )
                    for role in roles
                    for program in programs
                )

        if new_assignments:
            RoleAssignment.objects.bulk_create(new_assignments)

    # area limits - only for non-full-area-access; do not create records for partners that are parents
    area_access = ProgramPartnerThrough.objects.filter(full_area_access=False).exclude(
        partner_id__in=Partner.objects.filter(parent__isnull=False).values_list("parent_id", flat=True)
    )

    area_access_ids = list(area_access.values_list("id", flat=True))
    area_access_count = len(area_access_ids)

    for batch_start in range(0, area_access_count, BATCH_SIZE_SMALL):
        new_area_limits = []
        new_area_limit_through = []
        batch_end = batch_start + BATCH_SIZE_SMALL

        batched_area_access_ids = area_access_ids[batch_start:batch_end]
        batched_area_access = list(
            ProgramPartnerThrough.objects.filter(id__in=batched_area_access_ids)
            .select_related("partner", "program")
            .prefetch_related("areas")
        )

        for access in batched_area_access:
            new_area_limits.append(AdminAreaLimitedTo(partner=access.partner, program=access.program))

        if new_area_limits:
            AdminAreaLimitedTo.objects.bulk_create(new_area_limits)

            for new_area_limit, areas in zip(
                new_area_limits, [access.areas.all() for access in batched_area_access], strict=True
            ):
                for area in areas:
                    new_area_limit_through.append(
                        AdminAreaLimitedTo.areas.through(adminarealimitedto_id=new_area_limit.id, area_id=area.id)
                    )
            if new_area_limit_through:
                AdminAreaLimitedTo.areas.through.objects.bulk_create(new_area_limit_through)


def migrate_unicef_partners(apps, schema_editor):
    """Handle migration of UNICEF partner into UNICEF HQ and UNICEF Partners per BusinessArea.

    UNICEF partner will become parent Partner for UNICEF HQ and UNICEF Partners per BusinessArea.
    UNICEF HQ will hold "Role with all permissions" for all Business Areas (with program=None so whole BA access)
    UNICEF Partners per BusinessArea will hold role with permissions specified in DEFAULT_PERMISSIONS_IS_UNICEF_PARTNER
    within the Business Area specific for them. Within this BA they will have access to all programs.

    Users currently assigned to UNICEF partner will be assigned to UNICEF HQ and UNICEF Partners per BusinessArea based on their roles.
    If user holds roles in multiple Business Areas, they will be assigned to UNICEF HQ.
    """
    RoleAssignment = apps.get_model("account", "RoleAssignment")
    Partner = apps.get_model("account", "Partner")
    BusinessArea = apps.get_model("core", "BusinessArea")
    User = apps.get_model("account", "User")
    register(Partner)

    new_assignments = []

    unicef_partner = Partner.objects.filter(name="UNICEF").first()

    # update Role with all permissions with is_available_for_partner=False
    role_with_all_permissions = Role.objects.get(name="Role with all permissions")
    role_with_all_permissions.is_available_for_partner = False
    role_with_all_permissions.save()

    role_for_unicef_subpartners, _ = Role.objects.get_or_create(
        name="Role for UNICEF Partners",
        is_visible_on_ui=False,
        is_available_for_partner=False,
        defaults={"permissions": DEFAULT_PERMISSIONS_LIST_FOR_IS_UNICEF_PARTNER},
    )
    role_for_unicef_subpartners.refresh_from_db()

    unicef_hq, _ = Partner.objects.get_or_create(name=settings.UNICEF_HQ_PARTNER)
    unicef_hq.allowed_business_areas.set(BusinessArea.objects.all())

    for business_area in BusinessArea.objects.exclude(slug="global"):
        unicef_subpartner, _ = Partner.objects.get_or_create(name=f"UNICEF Partner for {business_area.slug}")
        unicef_subpartner.allowed_business_areas.add(business_area)

        new_assignments.append(
            RoleAssignment(
                user=None,
                partner=unicef_subpartner,
                role_id=role_for_unicef_subpartners.id,
                business_area=business_area,
                program=None,
            )
        )

        new_assignments.append(
            RoleAssignment(
                user=None,
                partner=unicef_hq,
                role_id=role_with_all_permissions.id,
                business_area=business_area,
                program=None,
            )
        )

    if new_assignments:
        RoleAssignment.objects.bulk_create(new_assignments)

    # handle UNICEF users

    # UNICEF users with no roles or role only in GLOBAL will be assigned to default empty partner
    empty_partner, _ = Partner.objects.get_or_create(name=settings.DEFAULT_EMPTY_PARTNER)
    User.objects.filter(partner=unicef_partner).annotate(
        ba_count=Count("role_assignments__business_area", distinct=True)
    ).filter(Q(ba_count=0) | Q(ba_count=1, role_assignments__business_area__slug="global")).update(
        partner=empty_partner
    )

    # UNICEF users with roles in single Business Area will be assigned to UNICEF Sub-partner for that Business Area
    unicef_users_in_single_ba = (
        User.objects.filter(partner=unicef_partner)
        .annotate(ba_count=Count("role_assignments__business_area", distinct=True))
        .filter(Q(ba_count=1) | (Q(role_assignments__business_area__slug="global") & Q(ba_count=2)))
    )

    unicef_subpartners = {
        ba.slug: Partner.objects.get(name=f"UNICEF Partner for {ba.slug}")
        for ba in BusinessArea.objects.exclude(slug="global")
    }
    for ba in (
        RoleAssignment.objects.filter(user__in=unicef_users_in_single_ba)
        .exclude(business_area__slug="global")
        .values_list("business_area__slug", flat=True)
        .distinct()
    ):
        unicef_users = unicef_users_in_single_ba.filter(role_assignments__business_area__slug=ba)
        unicef_users.update(partner=unicef_subpartners[ba])

    unicef_subpartners_ids = [unicef_subpartner.id for unicef_subpartner in unicef_subpartners.values()]
    Partner.objects.filter(id__in=[unicef_hq.id, *unicef_subpartners_ids]).update(parent=unicef_partner)

    # UNICEF users with roles in multiple Business Areas will be assigned to UNICEF HQ
    User.objects.filter(partner=unicef_partner).annotate(
        ba_count=Count("role_assignments__business_area", distinct=True)
    ).filter(ba_count__gt=1).update(partner=unicef_hq)


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0010_migration"),
    ]

    operations = [
        migrations.RunPython(create_constant_objects, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(migrate_user_roles, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(migrate_partner_roles_and_access, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(migrate_unicef_partners, reverse_code=migrations.RunPython.noop),
    ]
