# Generated by Django 5.2.6 on 2025-09-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # ensure CREATE COLLATION can run outside transaction

    dependencies = [
        ("account", "0017_migration"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE COLLATION IF NOT EXISTS "und-ci-det"
            (provider = icu, locale = 'und-u-ks-level2', deterministic = true);
            """,
            """
            DROP COLLATION IF EXISTS "und-ci-det";
            """,
        ),
        migrations.AlterField(
            model_name="partner",
            name="name",
            field=models.CharField(db_collation="und-ci-det", max_length=100, unique=True),
        ),
    ]