# Generated by Django 5.2.6 on 2025-11-17 01:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0019_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("can_load_from_ad", "Can load users from ActiveDirectory"),
                    ("can_sync_with_ad", "Can synchronise user with ActiveDirectory"),
                    ("can_create_kobo_user", "Can create users in Kobo"),
                    ("can_import_from_kobo", "Can import and sync users from Kobo"),
                    ("can_upload_to_kobo", "Can upload CSV file to Kobo"),
                    ("can_debug", "Can access debug information"),
                    ("can_inspect", "Can inspect objects"),
                    ("quick_links", "Can see quick links in admin"),
                    ("restrict_help_desk", "Limit fields to be editable for help desk"),
                    ("can_reindex_programs", "Can reindex programs"),
                    (
                        "can_add_business_area_to_partner",
                        "Can add business area to partner",
                    ),
                    ("can_change_allowed_partners", "Can change allowed partners"),
                    ("can_change_area_limits", "Can change area limits"),
                    ("can_import_fixture", "Can import fixture"),
                    ("can_edit_user_roles", "Can edit user role assignments"),
                )
            },
        ),
    ]
