# Generated by Django 5.2.8 on 2025-12-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0021_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ad_uuid",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
