# Generated by Django 5.2.8 on 2025-12-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0022_migration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="ad_uuid",
            new_name="azure_id",
        ),
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
