# Generated by Django 5.2 on 2026-08-21

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0032_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(blank=True, null=True),
        ),
    ]
