# Generated by Django 5.2.15 on 2026-09-07

from django.db import migrations, models

import hope.apps.account.fields
import hope.apps.account.permissions


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0033_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=hope.apps.account.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=hope.apps.account.permissions.Permissions.choices,
                    max_length=255,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
