apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hope.fullname" . }}-backend-release
  labels:
    {{- include "hope.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-backend-release
          command: ["/bin/sh"]
          args: ["-c", "python3 /code/manage.py upgrade"]
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          envFrom:
          - secretRef:
              name: {{ include "hope.fullname" . }}-job-backend
          - configMapRef:
              name: {{ include "hope.fullname" . }}-backend
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      restartPolicy: Never
  backoffLimit: 20
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hope.fullname" . }}-backend-init
  labels:
    {{- include "hope.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-backend-release
          command: ["/bin/sh"]
          {{- if .Values.global.init }}
          args: ["-c", "python3 /code/manage.py upgrade"]
          {{- else }}
          args: ["-c", "python3 /code/manage.py upgrade"]
          {{- end }}
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          envFrom:
          - secretRef:
              name: {{ include "hope.fullname" . }}-backend
          - configMapRef:
              name: {{ include "hope.fullname" . }}-backend
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      restartPolicy: Never
  backoffLimit: 20

