# Generated by Django 3.2.25 on 2025-07-14 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("targeting", "0004_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetingcriteriarule",
            name="payment_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="payment.paymentplan",
                null=True,
            ),
        ),
    ]
