# Generated by Django 5.2.6 on 2025-10-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("targeting", "0007_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targetingcollectorblockrulefilter",
            name="arguments",
            field=models.JSONField(
                help_text="\n            Array of arguments\n        "
            ),
        ),
        migrations.AlterField(
            model_name="targetingcriteriarulefilter",
            name="arguments",
            field=models.JSONField(
                help_text="\n                Array of arguments\n                "
            ),
        ),
        migrations.AlterField(
            model_name="targetingindividualblockrulefilter",
            name="arguments",
            field=models.JSONField(
                help_text="\n                Array of arguments\n                "
            ),
        ),
    ]
