# Generated by Django 5.2.6 on 2025-10-31 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("targeting", "0007_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="targetingcollectorrulefilterblock",
            name="targeting_criteria_rule",
        ),
        migrations.DeleteModel(
            name="TargetingCollectorBlockRuleFilter",
        ),
        migrations.DeleteModel(
            name="TargetingCollectorRuleFilterBlock",
        ),
    ]
