# Generated by Django 5.2.11 on 2026-03-04 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("targeting", "0009_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="targetingcriteriarule",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="targetingcriteriarulefilter",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="targetingindividualblockrulefilter",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="targetingindividualrulefilterblock",
            options={"ordering": ("id",)},
        ),
    ]
