# Generated by Django 5.2.11 on 2026-03-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("targeting", "0010_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetingcriteriarule",
            name="alternative_colectors_ids",
            field=models.TextField(blank=True, help_text="Use Alternative colectors for those IDs"),
        ),
    ]
