# Generated by Django 3.2.19 on 2023-06-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexibleattributechoice',
            name='admin',
        ),
        migrations.AddField(
            model_name='businessarea',
            name='rapid_pro_host',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='businessarea',
            name='has_data_sharing_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessarea',
            name='rapid_pro_api_key',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterModelOptions(
            name='flexibleattributechoice',
            options={'ordering': ('name',)},
        ),
    ]
