# Generated by Django 3.2.19 on 2023-07-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_migration_squashed_0067_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessarea',
            old_name='rapid_pro_api_key',
            new_name='rapid_pro_payment_verification_token',
        ),
        migrations.AddField(
            model_name='businessarea',
            name='rapid_pro_messages_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='businessarea',
            name='rapid_pro_survey_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
