# Generated by Django 2.2.8 on 2020-03-03 14:00

import django.db.models.deletion
import targeting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0002_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetpopulation',
            name='num_individuals_household',
        ),
        migrations.AlterField(
            model_name='targetpopulation',
            name='last_edited_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetpopulation',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('FINALIZED', 'Finalized')], default=targeting.models.TargetStatus('In Progress'), max_length=256),
        ),
        migrations.CreateModel(
            name='TargetFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_group', models.CharField(max_length=256)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=2)),
                ('age_min', models.IntegerField(max_length=256, null=True)),
                ('age_max', models.IntegerField(max_length=256, null=True)),
                ('school_distance_min', models.IntegerField(max_length=256, null=True)),
                ('school_distance_max', models.IntegerField(max_length=256, null=True)),
                ('num_individuals_min', models.IntegerField(max_length=256, null=True)),
                ('num_individuals_max', models.IntegerField(max_length=256, null=True)),
                ('target_population',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_filters',
                                   to='targeting.TargetPopulation')),
            ],
        ),
    ]
