# Generated by Django 2.2.8 on 2020-02-28 11:02

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
import django.db.models.deletion
import targeting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0002_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetpopulation',
            name='last_edited_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetpopulation',
            name='num_individuals_household',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default=targeting.models.get_serialized_range, validators=[django.contrib.postgres.validators.RangeMinValueValidator(1), django.contrib.postgres.validators.RangeMaxValueValidator(50000)]),
        ),
        migrations.AlterField(
            model_name='targetpopulation',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('FINALIZED', 'Finalized')], default=targeting.models.TargetStatus('In Progress'), max_length=256),
        ),
        migrations.CreateModel(
            name='TargetFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_group', models.CharField(max_length=256)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=2)),
                ('age', models.IntegerField()),
                ('school_distance_min', models.IntegerField()),
                ('school_distance_max', models.IntegerField()),
                ('num_individuals_household_min', models.IntegerField()),
                ('num_individuals_household_max', models.IntegerField()),
                ('target_population', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_filters', to='targeting.TargetPopulation')),
            ],
        ),
    ]
