# Generated by Django 2.2.8 on 2020-03-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0003_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetpopulation',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
