# Generated by Django 2.2.8 on 2020-05-12 14:14

from django.db import migrations

def set_business_area(apps, schema_editor):
    BusinessArea = apps.get_model("core", "BusinessArea")
    afghanistan = BusinessArea.objects.filter(slug="afghanistan").first()
    if afghanistan is None:
        return
    TargetPopulation = apps.get_model("targeting", "TargetPopulation")
    TargetPopulation.objects.filter(business_area__isnull=True).update(
        business_area=afghanistan
    )

class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0005_migration'),
    ]

    operations = [
        migrations.RunPython(set_business_area),
    ]
