# Generated by Django 2.2.8 on 2020-03-23 09:54

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0005_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetpopulation',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='targetpopulation',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='targetpopulation',
            name='lft',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='targetpopulation',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='targeting.TargetPopulation', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='targetpopulation',
            name='rght',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='targetpopulation',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
        ),
    ]
