# Generated by Django 2.2.8 on 2020-03-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0006_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterAttrType',
        ),
        migrations.AlterField(
            model_name='targetingcriteriarulefilter',
            name='comparision_method',
            field=models.CharField(choices=[('EQUALS', 'Equals'), ('NOT_EQUALS', 'Not Equals'), ('CONTAINS', 'Contains'), ('NOT_CONTAINS', 'Does not contain'), ('RANGE', 'In between <>'), ('NOT_IN_RANGE', 'Not in between <>'), ('GREATER_THAN', 'Greater than'), ('LESS_THAN', 'Less than')], max_length=20),
        ),
        migrations.DeleteModel(
            name='TargetRule',
        ),
    ]
