# Generated by Django 2.2.8 on 2020-06-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0006_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetpopulation',
            name='sent_to_datahub',
            field=models.BooleanField(default=False, help_text='\n            Flag set when TP is processed by airflow task\n            '),
        ),
    ]
