# Generated by Django 2.2.8 on 2020-03-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0007_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetpopulation',
            name='_total_family_size',
        ),
        migrations.RemoveField(
            model_name='targetpopulation',
            name='_total_households',
        ),
        migrations.AlterField(
            model_name='householdselection',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='household.Household'),
        ),
        migrations.AlterField(
            model_name='householdselection',
            name='target_population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='targeting.TargetPopulation'),
        ),
    ]
