# Generated by Django 2.2.8 on 2020-04-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("targeting", "0008_migration"),
    ]

    def migrate_target_population_statuses(apps, schema):
        TargetPopulation = apps.get_model("targeting", "TargetPopulation")
        TargetPopulation.objects.filter(
            status="TargetStatus.IN_PROGRESS"
        ).update(status="DRAFT")
        TargetPopulation.objects.filter(status="TargetStatus.FINALIZED").update(
            status="FINALIZED"
        )

    operations = [migrations.RunPython(migrate_target_population_statuses)]
