# Generated by Django 2.2.16 on 2021-01-21 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0013_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targetpopulation',
            options={'verbose_name': 'Target Population'},
        ),
    ]
