# Generated by Django 2.2.16 on 2021-11-05 14:48

from django.db import migrations, models


def move_from_approved_to_locked(apps, schema_editor):
    TargetPopulation = apps.get_model('targeting', 'TargetPopulation')
    TargetPopulation.objects.filter(status="APPROVED").update(status="LOCKED")


def revert_change_status(apps, schema_editor):
    TargetPopulation = apps.get_model('targeting', 'TargetPopulation')
    TargetPopulation.objects.filter(status="LOCKED").update(status="APPROVED")


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0024_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetpopulation',
            name='approved_by',
        ),
        migrations.AlterField(
            model_name='targetpopulation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Open'), ('LOCKED', 'Locked'), ('FINALIZED', 'Sent')],
                                   db_index=True, default='DRAFT', max_length=256),
        ),
        migrations.RunPython(move_from_approved_to_locked, revert_change_status),
    ]
