# Generated by Django 2.2.16 on 2022-01-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0027_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetpopulation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Open'), ('LOCKED', 'Locked'), ('STEFICON_WAIT', 'Waiting for Rule Engine'), ('STEFICON_RUN', 'Rule Engine Running'), ('STEFICON_COMPLETED', 'Rule Engine Completed'), ('STEFICON_ERROR', 'Rule Engine Errored'), ('PROCESSING', 'Processing'), ('READY_FOR_CASH_ASSIST', 'Ready for cash assist')], db_index=True, default='DRAFT', max_length=256),
        ),
        migrations.AlterField(
            model_name='targetpopulation',
            name='steficon_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_populations', to='steficon.RuleCommit'),
        ),
    ]
