# Generated by Django 2.2.16 on 2022-01-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0028_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetpopulation',
            name='steficon_rule',
        ),
    ]
