# Generated by Django 3.2 on 2022-02-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0030_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetingcriteriarulefilter',
            name='arguments',
            field=models.JSONField(help_text='\n            Array of arguments\n            '),
        ),
        migrations.AlterField(
            model_name='targetingindividualblockrulefilter',
            name='arguments',
            field=models.JSONField(help_text='\n            Array of arguments\n            '),
        ),
    ]
