# Generated by Django 3.2.13 on 2022-05-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0031_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetpopulation',
            name='criteria_fit_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetpopulation',
            name='criteria_fit_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
