# Generated by Django 3.2.13 on 2022-08-23 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("targeting", "0032_migration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="targetpopulation",
            old_name="candidate_list_targeting_criteria",
            new_name="targeting_criteria",
        ),
        migrations.RenameField(
            model_name="targetpopulation",
            old_name="final_list_total_households",
            new_name="total_households_count",
        ),
        migrations.RenameField(
            model_name="targetpopulation",
            old_name="final_list_total_individuals",
            new_name="total_individuals_count",
        ),
        migrations.RemoveField(
            model_name="householdselection",
            name="final",
        ),
        migrations.RemoveField(
            model_name="targetpopulation",
            name="candidate_list_total_households",
        ),
        migrations.RemoveField(
            model_name="targetpopulation",
            name="candidate_list_total_individuals",
        ),
        migrations.RemoveField(
            model_name="targetpopulation",
            name="final_list_targeting_criteria",
        ),
        migrations.RemoveField(
            model_name="targetpopulation",
            name="selection_computation_metadata",
        ),
        migrations.AddField(
            model_name="targetpopulation",
            name="adult_female_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="targetpopulation",
            name="adult_male_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="targetpopulation",
            name="build_status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("BUILDING", "Building"), ("FAILED", "Failed"), ("OK", "Ok")],
                db_index=True,
                default="PENDING",
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name="targetpopulation",
            name="built_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="targetpopulation",
            name="child_female_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="targetpopulation",
            name="child_male_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="householdselection",
            name="vulnerability_score",
            field=models.DecimalField(
                blank=True, decimal_places=3, help_text="Written by Steficon", max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="targetpopulation",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="changed_target_populations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="targetpopulation",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("LOCKED", "Locked"),
                    ("STEFICON_WAIT", "Waiting for Rule Engine"),
                    ("STEFICON_RUN", "Rule Engine Running"),
                    ("STEFICON_COMPLETED", "Rule Engine Completed"),
                    ("STEFICON_ERROR", "Rule Engine Errored"),
                    ("PROCESSING", "Processing"),
                    ("READY_FOR_CASH_ASSIST", "Ready for cash assist"),
                ],
                db_index=True,
                default="OPEN",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name='householdselection',
            name='vulnerability_score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=3, help_text='Written by Steficon',
                                      max_digits=6, null=True),
        ),
    ]
