# Generated by Django 3.2.13 on 2022-08-23 13:35

from django.db import migrations, models
import django.db.models.deletion


def update_status(apps, schema_editor):
    TargetPopulation = apps.get_model("targeting", "TargetPopulation")
    TargetPopulation.objects.filter(status="DRAFT").update(status="OPEN")


def reverse_update_status(apps, schema_editor):
    TargetPopulation = apps.get_model("targeting", "TargetPopulation")
    TargetPopulation.objects.filter(status="OPEN").update(status="DRAFT")


class Migration(migrations.Migration):

    dependencies = [
        ("targeting", "0033_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targetpopulation",
            name="targeting_criteria",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="target_population",
                to="targeting.targetingcriteria",
            ),
        ),
        migrations.RunPython(update_status, reverse_update_status),
    ]
