# Generated by Django 3.2.13 on 2022-08-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targeting", "0035_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targetpopulation",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("LOCKED", "Locked"),
                    ("STEFICON_WAIT", "Waiting for Rule Engine"),
                    ("STEFICON_RUN", "Rule Engine Running"),
                    ("STEFICON_COMPLETED", "Rule Engine Completed"),
                    ("STEFICON_ERROR", "Rule Engine Errored"),
                    ("PROCESSING", "Processing"),
                    ("READY", "Ready"),
                    ("READY_FOR_CASH_ASSIST", "Ready for cash assist"),
                    ("READY_FOR_PAYMENT_MODULE", "Ready for payment module"),
                    ("ASSIGNED", "Assigned"),
                ],
                db_index=True,
                default="OPEN",
                max_length=256,
            ),
        ),
    ]
