# Generated by Django 3.2.15 on 2022-09-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0036_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetpopulation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('STEFICON_WAIT', 'Waiting for Rule Engine'), ('STEFICON_RUN', 'Rule Engine Running'), ('STEFICON_COMPLETED', 'Rule Engine Completed'), ('STEFICON_ERROR', 'Rule Engine Errored'), ('PROCESSING', 'Processing'), ('READY_FOR_CASH_ASSIST', 'Ready for cash assist'), ('READY_FOR_PAYMENT_MODULE', 'Ready for payment module'), ('ASSIGNED', 'Assigned')], db_index=True, default='OPEN', max_length=256),
        ),
    ]
