# Generated by Django 3.2.25 on 2024-03-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0043_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetingcriteria',
            name='household_ids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='targetingcriteria',
            name='individual_ids',
            field=models.TextField(blank=True),
        ),
    ]
