# Generated by Django 3.2.25 on 2024-08-13 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0046_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetingcriteriarulefilter',
            name='round_number',
        ),
    ]
