# Generated by Django 2.2.16 on 2020-10-28 14:29

from django.db import migrations, models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('deprecated', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[['jinja2', 'Jinja2'], ['internal', 'internal'], ['python', 'Python']], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
