# Generated by Django 2.2.8 on 2020-06-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('jinja', 'Jinja'), ('internal', 'internal'), ('lua', 'Lua')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rule',
            name='target',
            field=models.CharField(default='vulnerability_score1', max_length=100),
        ),
    ]
