# Generated by Django 2.2.16 on 2021-02-04 12:28

import concurrency.fields
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steficon', '0002_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rule',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rule',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='definition',
            field=models.TextField(blank=True, default='score.value=0'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='language',
            field=models.CharField(choices=[['python', 'Python'], ['jinja2', 'Jinja2'], ['internal', 'internal']], default='python', max_length=10),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='RuleCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField()),
                ('affected_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('previous_state', django.contrib.postgres.fields.jsonb.JSONField(editable=False, help_text='The record before change')),
                ('new_state', django.contrib.postgres.fields.jsonb.JSONField(editable=False, help_text='The record after apply changes')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='steficon.Rule')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rule (History)',
                'verbose_name_plural': 'Rules (History)',
                'ordering': ('-timestamp',),
                'get_latest_by': 'timestamp',
            },
        ),
    ]
