# Generated by Django 2.2.8 on 2020-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20200602_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='language',
            field=models.CharField(choices=[['jinja2', 'Jinja2'], ['internal', 'internal'], ['python', 'Python']], max_length=10),
        ),
    ]
