# Generated by Django 2.2.16 on 2021-02-12 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steficon', '0004_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulecommit',
            old_name='new_state',
            new_name='after',
        ),
        migrations.RenameField(
            model_name='rulecommit',
            old_name='previous_state',
            new_name='before',
        ),
    ]
