# Generated by Django 2.2.16 on 2022-01-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steficon', '0007_empty_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='id',
        ),
        migrations.AddField(
            model_name='rule',
            name='code',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
