# Generated by Django 2.2.16 on 2022-01-15 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("steficon", "0008_reset_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="code",
        ),
        migrations.AddField(
            model_name="rule",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
            preserve_default=False,
        ),
    ]
