# Generated by Django 3.2 on 2022-02-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steficon', '0013_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='rule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rulecommit',
            name='after',
            field=models.JSONField(editable=False, help_text='The record after apply changes'),
        ),
        migrations.AlterField(
            model_name='rulecommit',
            name='before',
            field=models.JSONField(editable=False, help_text='The record before change'),
        ),
        migrations.AlterField(
            model_name='rulecommit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
