# Generated by Django 3.2.12 on 2022-03-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steficon', '0015_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulecommit',
            options={'get_latest_by': '-version', 'ordering': ('-version',), 'verbose_name': 'RuleCommit', 'verbose_name_plural': 'Rule Commits'},
        ),
        migrations.AlterField(
            model_name='rulecommit',
            name='after',
            field=models.JSONField(default=dict, editable=False, help_text='The record after apply changes'),
        ),
        migrations.AlterField(
            model_name='rulecommit',
            name='before',
            field=models.JSONField(default=dict, editable=False, help_text='The record before change'),
        ),
    ]
