from typing import Any, Callable, TypeVar

F = TypeVar("F", bound=Callable[..., Any])

def button(**kwargs: Any) -> Callable[[F], F]: ...
def link(**kwargs: Any) -> Callable[[F], F]: ...
def view(**kwargs: Any) -> Callable[[F], F]: ...
def choice(**kwargs: Any) -> Callable[[F], F]: ...
