# Generated by Django 3.2.25 on 2025-01-15 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0001_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={
                "ordering": ("name",),
                "permissions": (("import_areas", "Can import areas"),),
                "verbose_name_plural": "Areas",
            },
        ),
    ]
