# Generated by Django 3.2.25 on 2024-11-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_migration"),
        ("api", "0001_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="valid_for",
            field=models.ManyToManyField(to="core.BusinessArea"),
        ),
        migrations.AddField(
            model_name="apilogentry",
            name="token",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="api.apitoken"),
        ),
    ]
