# Generated by Django 5.2.8 on 2025-12-17 13:52

from django.db import migrations, models

import hope.apps.account.fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="grants",
            field=hope.apps.account.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("API_READ_ONLY", "API_READ_ONLY"),
                        ("API_RDI_UPLOAD", "API_RDI_UPLOAD"),
                        ("API_RDI_CREATE", "API_RDI_CREATE"),
                        ("API_PROGRAM_CREATE", "API_PROGRAM_CREATE"),
                        ("API_GENERIC_IMPORT", "API_GENERIC_IMPORT"),
                    ],
                    max_length=255,
                ),
                size=None,
            ),
        ),
    ]
