# Generated by Django 5.2.12 on 2026-04-14 21:18

from django.db import migrations, models

import hope.apps.account.fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apitoken",
            options={"ordering": ("id",), "permissions": (("resend_token_email", "Can resend an email with token"),)},
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="grants",
            field=hope.apps.account.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("API_READ_ONLY", "API_READ_ONLY"),
                        ("API_RDI_UPLOAD", "API_RDI_UPLOAD"),
                        ("API_RDI_CREATE", "API_RDI_CREATE"),
                        ("API_PROGRAM_CREATE", "API_PROGRAM_CREATE"),
                        ("API_BENEFICIARY_TICKET_CREATE", "API_BENEFICIARY_TICKET_CREATE"),
                        ("API_GENERIC_IMPORT", "API_GENERIC_IMPORT"),
                    ],
                    max_length=255,
                ),
                size=None,
            ),
        ),
    ]
