# Generated by Django 5.2.12 on 2026-04-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apitoken",
            options={
                "ordering": ("id",),
                "permissions": (
                    ("resend_token_email", "Can resend an email with token"),
                ),
            },
        ),
    ]
