# Generated by Django 5.2.14 on 2026-06-17 14:58

from django.db import migrations, models

import hope.apps.account.fields
import hope.models.grant


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="grants",
            field=hope.apps.account.fields.ChoiceArrayField(
                base_field=models.CharField(choices=hope.models.grant.Grant.choices, max_length=255),
                size=None,
            ),
        ),
    ]
