# Generated by Django 5.2.14 on 2026-06-05 16:45

from django.db import migrations, models

import hope.apps.account.fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="grants",
            field=hope.apps.account.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("API_READ_ONLY", "API_READ_ONLY"),
                        ("API_RDI_UPLOAD", "API_RDI_UPLOAD"),
                        ("API_RDI_CREATE", "API_RDI_CREATE"),
                        ("API_PROGRAM_CREATE", "API_PROGRAM_CREATE"),
                        (
                            "API_BENEFICIARY_TICKET_CREATE",
                            "API_BENEFICIARY_TICKET_CREATE",
                        ),
                        ("API_GENERIC_IMPORT", "API_GENERIC_IMPORT"),
                        ("API_VISION_PP_CREATE", "API_VISION_PP_CREATE"),
                    ],
                    max_length=255,
                ),
                size=None,
            ),
        ),
    ]
