# Generated by Django 3.2.25 on 2025-01-16 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration_data", "0002_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrationdataimport",
            options={
                "permissions": (("rerun_rdi", "Can Rerun RDI"),),
                "verbose_name": "Registration data import",
            },
        ),
    ]
