# Generated by Django 5.2.8 on 2025-12-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration_data", "0009_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationdataimport",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("XLS", "Excel"),
                    ("KOBO", "KoBo"),
                    ("FLEX_REGISTRATION", "Flex Registration"),
                    ("API", "Flex API"),
                    ("EDOPOMOGA", "eDopomoga"),
                    ("PROGRAM_POPULATION", "Programme Population"),
                    ("ENROLL_FROM_PROGRAM", "Enroll From Programme"),
                    ("GENERIC_IMPORT", "Generic Import Service"),
                ],
                max_length=255,
            ),
        ),
    ]
