# Generated by Django 5.2.13 on 2026-05-20 10:38

from django.conf import settings
from django.db import migrations, models

import hope.models.deduplication_engine_similarity_pair


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_migration"),
        ("program", "0018_migration"),
        ("registration_data", "0014_migration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationdataimport",
            name="country_workspace_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="deduplicationenginesimilaritypair",
            name="status_code",
            field=models.CharField(
                choices=hope.models.deduplication_engine_similarity_pair.DeduplicationEngineSimilarityPair.StatusCode._status_code_choices,
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationdataimport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("country_workspace_id__isnull", False)),
                fields=("country_workspace_id",),
                name="unique_rdi_country_workspace_id",
            ),
        ),
    ]
