# Generated by Django 5.2.13 on 2026-05-07 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_migration"),
        ("program", "0018_migration"),
        ("registration_data", "0014_migration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationdataimport",
            name="country_workspace_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="deduplicationenginesimilaritypair",
            name="status_code",
            field=models.CharField(
                choices=[
                    ("200", "Deduplication success"),
                    ("404", "No file found"),
                    ("412", "No face detected"),
                    ("416", "Face below confidence"),
                    ("418", "Image quality below threshold"),
                    ("429", "Multiple faces detected"),
                    ("500", "Generic error"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationdataimport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("country_workspace_id__isnull", False)),
                fields=("country_workspace_id",),
                name="unique_rdi_country_workspace_id",
            ),
        ),
    ]
