# Generated by Django 5.2.14 on 2026-06-02 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0044_migration"),
        ("program", "0018_migration"),
        ("registration_data", "0015_migration"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DeduplicationEngineSimilarityPair",
            new_name="BiometricDedupeSimilarityPair",
        ),
        migrations.AlterModelOptions(
            name="registrationdataimport",
            options={
                "ordering": ("id",),
                "permissions": (
                    ("rerun_rdi", "Can Rerun RDI"),
                    ("delete_rdi", "Can Delete RDI"),
                    ("delete_merged_rdi", "Can Delete Merged RDI"),
                ),
                "verbose_name": "Registration data import",
            },
        ),
        migrations.RemoveField(
            model_name="registrationdataimport",
            name="deduplication_engine_status",
        ),
    ]
