# Generated by Django 5.2.15 on 2026-07-28 09:00

from django.db import migrations, models

import hope.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("registration_data", "0016_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importdata",
            name="file",
            field=models.FileField(
                blank=True, max_length=255, null=True, upload_to=hope.models.utils.UniqueUploadPath("import_data")
            ),
        ),
    ]
