# Generated by Django 3.2.19 on 2023-06-09 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0002_migration_squashed_0020_migration'),
        ('core', '0002_migration_squashed_0006_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.IntegerField(choices=[(1, 'Processing'), (2, 'Generated'), (3, 'Failed')], default=1)),
                ('report_type', models.IntegerField(choices=[(1, 'Individuals'), (2, 'Households'), (3, 'Cash Plan Verification'), (4, 'Payments'), (5, 'Payment verification'), (6, 'Cash Plan'), (7, 'Programme'), (8, 'Individuals & Payment')])),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('business_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.businessarea')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='program.program')),
                ('admin_area', models.ManyToManyField(blank=True, related_name='reports', to='core.AdminArea')),
                ('number_of_records', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['-created_at', 'report_type', 'status', 'created_by'],
            },
        ),
    ]
