# Generated by Django 2.2.16 on 2021-01-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_migration"),
        ("reporting", "0001_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="admin_area",
        ),
        migrations.AddField(
            model_name="report",
            name="admin_area",
            field=models.ManyToManyField(blank=True, related_name="reports", to="core.AdminArea"),
        ),
    ]
