# Generated by Django 2.2.16 on 2021-09-27 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_migration'),
        ('reporting', '0007_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardreport',
            name='admin_area_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_reports', to='geo.Area'),
        ),
        migrations.AddField(
            model_name='report',
            name='admin_area_new',
            field=models.ManyToManyField(blank=True, related_name='reports', to='geo.Area'),
        ),
    ]
