from hope.apps.core.tasks_schedules import TASKS_SCHEDULES
from hope.config.env import env

CELERY_BROKER_URL = env("CELERY_BROKER_URL")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND")
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 360 * 60
CELERY_BEAT_SCHEDULE = TASKS_SCHEDULES
CELERY_TASK_REVOKED_QUEUE = "queue_hope_revoked"
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_BEAT_SCHEDULER = "hope.apps.core.models.CustomDatabaseScheduler"
CELERY_TASK_IGNORE_RESULT = False
CELERY_BOOST_FLOWER = env("FLOWER_ADDRESS")
