from hope.apps.core.celery_queues import CELERY_QUEUE_DEFAULT, CELERY_QUEUE_PERIODIC
from hope.apps.core.tasks_schedules import TASKS_SCHEDULES
from hope.config.env import env

CELERY_BROKER_VISIBILITY_TIMEOUT = max(env("CELERY_BROKER_VISIBILITY_TIMEOUT"), 8 * 60 * 60)
CELERY_BROKER_URL = env("CELERY_BROKER_URL")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND")
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 360 * 60
CELERY_BEAT_SCHEDULE = TASKS_SCHEDULES
CELERY_TASK_REVOKED_QUEUE = "queue_hope_revoked"
CELERY_TASK_DEFAULT_QUEUE = CELERY_QUEUE_DEFAULT
CELERY_TASK_PERIODIC_QUEUE = CELERY_QUEUE_PERIODIC
CELERY_BEAT_SCHEDULER = "hope.apps.core.models.CustomDatabaseScheduler"
CELERY_TASK_IGNORE_RESULT = False
CELERY_BOOST_FLOWER = env("FLOWER_ADDRESS")
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "visibility_timeout": CELERY_BROKER_VISIBILITY_TIMEOUT,
}
