from hope.config.env import env

VISION_API_URL = env("VISION_API_URL")
VISION_CLIENT_ID = env("VISION_CLIENT_ID")
VISION_CLIENT_SECRET = env("VISION_CLIENT_SECRET")
VISION_TOKEN_GRANT_TYPE = env("VISION_TOKEN_GRANT_TYPE")
VISION_DEFAULT_TIMEOUT = env("VISION_DEFAULT_TIMEOUT")
