# Generated by Django 2.2.8 on 2020-02-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0001_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdataimport',
            name='datahub_id',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataimport',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationdataimport',
            name='status',
            field=models.CharField(choices=[('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('MERGED', 'Merged'), ('MERGING', 'Merging')], max_length=255),
        ),
    ]
