# Generated by Django 2.2.8 on 2020-05-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0001_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdataimport',
            name='status',
            field=models.CharField(choices=[('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('MERGED', 'Merged'), ('MERGING', 'Merging'), ('IMPORTING', 'Importing')], default='IN_REVIEW', max_length=255),
        ),
    ]
