# Generated by Django 2.2.8 on 2020-04-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_migration'),
        ('registration_data', '0003_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdataimport',
            name='business_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BusinessArea'),
        ),
    ]
