# Generated by Django 2.2.16 on 2021-01-21 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0008_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationdataimport',
            options={'verbose_name': 'Registration data import'},
        ),
    ]
