# Generated by Django 2.2.16 on 2021-01-08 15:52

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0008_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdataimport',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
    ]
