# Generated by Django 2.2.16 on 2021-09-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0015_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdataimport',
            name='screen_beneficiary',
            field=models.BooleanField(default=False),
        ),
    ]
