# Generated by Django 2.2.16 on 2021-09-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0017_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdataimport',
            name='status',
            field=models.CharField(choices=[('IN_REVIEW', 'In Review'), ('MERGED', 'Merged'), ('MERGING', 'Merging'), ('IMPORTING', 'Importing'), ('DEDUPLICATION_FAILED', 'Deduplication Failed'), ('DEDUPLICATION', 'Deduplication'), ('REFUSED', 'Refused import'), ('IMPORT_ERROR', 'Import Error'), ('MERGE_ERROR', 'Merge Error')], db_index=True, default='IN_REVIEW', max_length=255),
        ),
    ]
