# Generated by Django 3.2.18 on 2023-05-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0026_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdataimport',
            name='status',
            field=models.CharField(choices=[('LOADING', 'Loading'), ('DEDUPLICATION', 'Deduplication'), ('DEDUPLICATION_FAILED', 'Deduplication Failed'), ('IMPORT_SCHEDULED', 'Import Scheduled'), ('IMPORTING', 'Importing'), ('IMPORT_ERROR', 'Import Error'), ('IN_REVIEW', 'In Review'), ('MERGE_SCHEDULED', 'Merge Scheduled'), ('MERGED', 'Merged'), ('MERGING', 'Merging'), ('MERGE_ERROR', 'Merge Error'), ('REFUSED', 'Refused import'), ('ABORTED', 'Aborted')], db_index=True, default='IN_REVIEW', max_length=255),
        ),
    ]
