# Generated by Django 3.2.19 on 2023-06-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0026_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdataimport',
            name='program_id',
            field=models.UUIDField(db_index=True, default='939ff91b-7f89-4e3c-9519-26ed62f51718'),
            preserve_default=False,
        ),
    ]
