# Generated by Django 3.2.19 on 2023-07-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0038_migration'),
        ('registration_data', '0027_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdataimport',
            name='programs',
            field=models.ManyToManyField(related_name='registration_data_imports', to='program.Program'),
        ),
    ]
