# Generated by Django 3.2.25 on 2024-04-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0033_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdataimport',
            name='import_data',
        ),
    ]
