# Generated by Django 3.2.25 on 2024-05-26 18:38

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import model_utils.fields
import multiselectfield.db.fields
import phonenumber_field.modelfields
import sorl.thumbnail.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0034_migration'),
    ]

    operations = [

    ]
