# Generated by Django 3.2.23 on 2024-01-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0037_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdataimport',
            name='allow_delivery_mechanisms_validation_errors',
            field=models.BooleanField(default=False),
        ),
    ]


for g in GrievanceTicket.objects.all():
    print(g.created_at, g.updated_at)