# Generated by Django 3.2.25 on 2024-04-23 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0038_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koboimportedsubmission',
            name='imported_household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration_data.importedhousehold'),
        ),
    ]
