# Generated by Django 3.2.25 on 2025-08-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("universal_update_script", "0003_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="universalupdate",
            name="celery_tasks_results_ids",
            field=models.JSONField(
                blank=True, default=dict, help_text="Current (active) AsyncResult ids for celery tasks."
            ),
        ),
        migrations.RemoveField(
            model_name="universalupdate",
            name="curr_async_result_id",
        ),
    ]
