# Generated by Django 5.2.11 on 2026-03-04 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("universal_update_script", "0004_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="universalupdate",
            options={
                "ordering": ("id",),
                "permissions": [
                    ("can_run_universal_update", "Can run universal update"),
                    (
                        "can_generate_universal_update_template",
                        "Can generate universal update template",
                    ),
                ],
            },
        ),
    ]
