# Generated by Django 5.2.17 on 2026-09-09 12:24

from django.db import migrations, models

import hope.apps.core.upload_paths


class Migration(migrations.Migration):
    dependencies = [
        ("universal_update_script", "0006_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="universalupdate",
            name="backup_snapshot",
            field=models.FileField(
                blank=True,
                help_text="Backup Snapshot File, contains data before update. File updated on each start of update process.",
                max_length=255,
                null=True,
                upload_to=hope.apps.core.upload_paths.upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="universalupdate",
            name="template_file",
            field=models.FileField(
                blank=True,
                help_text="Generated Template XLSX File, contains columns for data to be updated. Contains also rows for unicef_ids to be updated",
                max_length=255,
                null=True,
                upload_to=hope.apps.core.upload_paths.upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="universalupdate",
            name="update_file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded File, contains data to be updated. After clicking a button to update, data will be updated",
                max_length=255,
                null=True,
                upload_to=hope.apps.core.upload_paths.upload_path,
            ),
        ),
    ]
