# Generated by Django 3.2 on 2022-02-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0003_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='changes',
            field=models.JSONField(null=True, verbose_name='change message'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
