# Generated by Django 3.2.19 on 2023-07-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0006_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='program',
        ),
    ]
