# Generated by Django 2.2.8 on 2020-06-30 13:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_datahub', '0001_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downpayment',
            name='business_area',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='downpayment',
            name='consumer_fc_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='downpayment',
            name='currency_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='downpayment',
            name='down_payment_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='downpayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=5, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))]),
        ),
        migrations.AlterField(
            model_name='downpayment',
            name='total_down_payment_amount_local',
            field=models.DecimalField(decimal_places=2, max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='downpayment',
            name='total_down_payment_amount_usd',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='downpayment',
            name='vendor_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fundscommitment',
            name='business_area',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='fundscommitment',
            name='commitment_amount_local',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='fundscommitment',
            name='commitment_amount_usd',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='fundscommitment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=5, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))]),
        ),
        migrations.AlterField(
            model_name='fundscommitment',
            name='funds_commitment_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fundscommitment',
            name='total_open_amount_local',
            field=models.DecimalField(decimal_places=2, max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='fundscommitment',
            name='total_open_amount_usd',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='fundscommitment',
            name='vendor_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
