# Generated by Django 2.2.16 on 2020-12-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_datahub', '0008_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownPayment',
        ),
    ]
