# Generated by Django 2.2.16 on 2021-06-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_datahub', '0014_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='downpayment',
            name='new_business_area_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='fundscommitment',
            name='new_business_area_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
