# Generated by Django 5.2.17 on 2026-09-09 12:24

from django.db import migrations, models

import hope.apps.core.upload_paths


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0009_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="sample_file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=hope.apps.core.upload_paths.upload_path,
            ),
        ),
    ]
