# Generated by Django 5.2.17 on 2026-09-23 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accountability", "0009_migration"),
        ("program", "0021_disable_biometric_dedup_for_non_cw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="program.program",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages",
                to="program.program",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="surveys",
                to="program.program",
            ),
        ),
    ]
