import logging
from datetime import datetime
from functools import reduce

from django.core.exceptions import ValidationError
from django.db.models import Q

from hct_mis_api.apps.core.attributes_qet_queries import (
    age_to_birth_date_query,
    get_birth_certificate_document_number_query,
    get_birth_certificate_issuer_query,
    get_drivers_license_document_number_query,
    get_drivers_licensee_issuer_query,
    get_electoral_card_document_number_query,
    get_electoral_card_issuer_query,
    get_national_id_document_number_query,
    get_national_id_issuer_query,
    get_national_passport_document_number_query,
    get_national_passport_issuer_query,
    get_other_document_number_query,
    get_other_issuer_query,
    get_role_query,
    get_scope_id_issuer,
    get_scope_id_number,
    get_unhcr_id_issuer,
    get_unhcr_id_number,
)
from hct_mis_api.apps.core.countries import Countries
from hct_mis_api.apps.core.currencies import CURRENCY_CHOICES
from hct_mis_api.apps.core.models import AdminArea, BusinessArea
from hct_mis_api.apps.core.utils import LazyEvalMethodsDict, admin_area1_query
from hct_mis_api.apps.household.models import (
    BLANK,
    DATA_SHARING_CHOICES,
    DISABILITY_CHOICES,
    MARITAL_STATUS_CHOICE,
    OBSERVED_DISABILITY_CHOICE,
    ORG_ENUMERATOR_CHOICES,
    REGISTRATION_METHOD_CHOICES,
    RELATIONSHIP_CHOICE,
    RESIDENCE_STATUS_CHOICE,
    ROLE_CHOICE,
    SEVERITY_OF_DISABILITY_CHOICES,
    SEX_CHOICE,
    WORK_STATUS_CHOICE,
    YES_NO_CHOICE,
)

logger = logging.getLogger(__name__)

TYPE_ID = "ID"
TYPE_INTEGER = "INTEGER"
TYPE_STRING = "STRING"
TYPE_LIST_OF_IDS = "LIST_OF_IDS"
TYPE_BOOL = "BOOL"
TYPE_DATE = "DATE"
TYPE_IMAGE = "IMAGE"
TYPE_SELECT_ONE = "SELECT_ONE"
TYPE_SELECT_MANY = "SELECT_MANY"
TYPE_GEOPOINT = "GEOPOINT"
TYPE_DECIMAL = "DECIMAL"

FIELD_TYPES_TO_INTERNAL_TYPE = {
    TYPE_ID: str,
    TYPE_INTEGER: int,
    TYPE_STRING: str,
    TYPE_LIST_OF_IDS: list,
    TYPE_BOOL: bool,
    TYPE_DATE: datetime,
    TYPE_IMAGE: str,
    TYPE_SELECT_ONE: str,
    TYPE_SELECT_MANY: list,
    TYPE_GEOPOINT: str,
    TYPE_DECIMAL: str,
}

_INDIVIDUAL = "Individual"
_HOUSEHOLD = "Household"

FILTERABLE_TYPES = [TYPE_INTEGER, TYPE_STRING, TYPE_SELECT_ONE, TYPE_SELECT_MANY, TYPE_DATE, TYPE_BOOL]


def country_generic_query(comparision_method, args, lookup):
    query = Q(**{lookup: Countries.get_country_value(args[0])})
    if comparision_method == "EQUALS":
        return query
    elif comparision_method == "NOT_EQUALS":
        return ~query
    logger.error(f"Country filter query does not support {comparision_method} type")
    raise ValidationError(f"Country filter query does not support {comparision_method} type")


def country_query(comparision_method, args):
    return country_generic_query(comparision_method, args, "country")


def country_origin_query(comparision_method, args):
    return country_generic_query(comparision_method, args, "country_origin")


CORE_FIELDS_ATTRIBUTES = [
    {
        "id": "a1741e3c-0e24-4a60-8d2f-463943abaebb",
        "type": TYPE_INTEGER,
        "name": "age",
        "label": {"English(EN)": "Age (calculated)"},
        "hint": "",
        "required": False,
        "get_query": age_to_birth_date_query,
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "age",
    },
    {
        "id": "3c2473d6-1e81-4025-86c7-e8036dd92f4b",
        "type": TYPE_SELECT_ONE,
        "name": "residence_status",
        "lookup": "residence_status",
        "required": False,
        "label": {"English(EN)": "Residence status"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in RESIDENCE_STATUS_CHOICE],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "residence_status_h_c",
    },
    {
        "id": "e47bafa7-0b86-4be9-a07f-d3fc7ac698cf",
        "type": TYPE_BOOL,
        "name": "consent",
        "lookup": "consent",
        "required": False,
        "label": {"English(EN)": "Do you consent?"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "consent_h_c",
    },
    {
        "id": "9480fc0d-1b88-45b0-9056-6a6fe0ebe509",
        "type": TYPE_IMAGE,
        "name": "consent_sign",
        "lookup": "consent_sign",
        "required": False,
        "label": {"English(EN)": "Do you consent?"},
        "hint": "Ask the head of household to sign or do an X as acknowledgement",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "consent_sign_h_c",
    },
    {
        "id": "e44efed6-47d6-4f60-bcf6-b1d2ffc4d7d1",
        "type": TYPE_SELECT_ONE,
        "name": "country_origin",
        "lookup": "country_origin",
        "required": False,
        "label": {"English(EN)": "Country of Origin"},
        "hint": "country origin",
        "get_query": country_origin_query,
        "choices": Countries.get_choices(output_code="alpha3"),
        "custom_validate_choices": Countries.is_valid_country_choice,
        "custom_cast_value": Countries.get_country_value,
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "country_origin_h_c",
    },
    {
        "id": "aa79985c-b616-453c-9884-0666252c3070",
        "type": TYPE_SELECT_ONE,
        "name": "country",
        "lookup": "country",
        "required": True,
        "label": {"English(EN)": "Country of registration"},
        "hint": "",
        "get_query": country_query,
        "choices": Countries.get_choices(output_code="alpha3"),
        "custom_validate_choices": Countries.is_valid_country_choice,
        "custom_cast_value": Countries.get_country_value,
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "country_h_c",
    },
    {
        "id": "59685cec-69bf-4abe-81b4-70b8f05b89f3",
        "type": TYPE_STRING,
        "name": "address",
        "lookup": "address",
        "required": False,
        "label": {"English(EN)": "Address"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "address_h_c",
    },
    LazyEvalMethodsDict(
        {
            "id": "c53ea58b-e7cf-4bf3-82d0-dec41f66ef3a",
            "type": TYPE_SELECT_ONE,
            "name": "admin1",
            "lookup": "admin_area__p_code",
            "get_query": admin_area1_query,
            "required": False,
            "label": {"English(EN)": "Household resides in which ${admin1_h_c}?"},
            "hint": "",
            "choices": lambda: AdminArea.get_admin_areas_as_choices(1),
            "associated_with": _HOUSEHOLD,
            "xlsx_field": "admin1_h_c",
        },
        ignored_method_fields=("get_query",),
    ),
    LazyEvalMethodsDict(
        {
            "id": "e4eb6632-8204-44ed-b39c-fe791ded9246",
            "type": TYPE_SELECT_ONE,
            "name": "admin2",
            "lookup": "admin_area__p_code",
            "required": False,
            "label": {"English(EN)": "Household resides in which ${admin2_h_c}?"},
            "hint": "",
            "choices": lambda: AdminArea.get_admin_areas_as_choices(2),
            "associated_with": _HOUSEHOLD,
            "xlsx_field": "admin2_h_c",
        }
    ),
    {
        "id": "13a9d8b0-f278-47c2-9b1b-b06579b0ab35",
        "type": TYPE_GEOPOINT,
        "name": "geopoint",
        "lookup": "geopoint",
        "required": False,
        "label": {"English(EN)": "Geolocation"},
        "hint": "latitude and longitude of household",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "hh_geopoint_h_c",
    },
    {
        "id": "5b32bad5-ff7c-4e6b-af7e-a0287fe91ea2",
        "type": TYPE_STRING,
        "name": "unhcr_id",
        "lookup": "unhcr_id",
        "required": False,
        "label": {"English(EN)": "UNHCR Case ID"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "unhcr_id_h_c",
    },
    {
        "id": "5f530642-b889-4130-bf1a-5fac1b17cf09",
        "type": TYPE_BOOL,
        "name": "returnee",
        "lookup": "returnee",
        "required": False,
        "label": {"English(EN)": "Is this a returnee household?"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "returnee_h_c",
    },
    {
        "id": "d668ae31-12cf-418e-8f7f-4c6398d82ffd",
        "type": TYPE_INTEGER,
        "name": "size",
        "lookup": "size",
        "required": True,
        "label": {"English(EN)": "What is the household size?"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "size_h_c",
    },
    {
        "id": "8d9df01a-ce7c-4e78-b8ec-6f3eec8f30ce",
        "type": TYPE_SELECT_ONE,
        "name": "relationship",
        "lookup": "relationship",
        "required": True,
        "label": {"English(EN)": "Relationship to head of household"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in RELATIONSHIP_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "relationship_i_c",
    },
    {
        "id": "36ab3421-6e7a-40d1-b816-ea5cbdcc0b6a",
        "type": TYPE_STRING,
        "name": "full_name",
        "lookup": "full_name",
        "required": True,
        "label": {"English(EN)": "Full name"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "full_name_i_c",
    },
    {
        "id": "b1f90314-b8b8-4bcb-9265-9d48d1fce5a4",
        "type": TYPE_STRING,
        "name": "given_name",
        "lookup": "given_name",
        "required": False,
        "label": {"English(EN)": "Given name"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "given_name_i_c",
    },
    {
        "id": "6f603107-bd88-4a8d-97cc-748a7238358d",
        "type": TYPE_STRING,
        "name": "middle_name",
        "lookup": "middle_name",
        "required": False,
        "label": {"English(EN)": "Middle name(s)"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "middle_name_i_c",
    },
    {
        "id": "3f74dd36-bfd2-4c84-bfc7-21f7adbff7f0",
        "type": TYPE_STRING,
        "name": "family_name",
        "lookup": "family_name",
        "required": False,
        "label": {"English(EN)": "Family name"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "family_name_i_c",
    },
    {
        "id": "da726870-dfc9-48dc-aba9-b9138b611c74",
        "type": TYPE_SELECT_ONE,
        "name": "sex",
        "lookup": "sex",
        "required": True,
        "label": {"English(EN)": "Gender"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in SEX_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "gender_i_c",
    },
    {
        "id": "416b0119-2d89-4517-819d-e563d2eb428c",
        "type": TYPE_DATE,
        "name": "birth_date",
        "lookup": "birth_date",
        "required": True,
        "label": {"English(EN)": "Birth date"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "birth_date_i_c",
    },
    {
        "id": "5e2c2a7c-9651-4c07-873c-f594ae18a56a",
        "type": TYPE_BOOL,
        "name": "estimated_birth_date",
        "lookup": "estimated_birth_date",
        "required": True,
        "label": {"English(EN)": "Estimated birth date?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "estimated_birth_date_i_c",
    },
    {
        "id": "84827966-17e5-407a-9424-1350c7ec3b64",
        "type": TYPE_IMAGE,
        "name": "photo",
        "lookup": "photo",
        "required": False,
        "label": {"English(EN)": "Individual's photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "photo_i_c",
    },
    {
        "id": "35ede8c4-877e-40dc-a93a-0a9a3bc511dc",
        "type": TYPE_SELECT_ONE,
        "name": "marital_status",
        "lookup": "marital_status",
        "required": False,
        "label": {"English(EN)": "Marital status"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in MARITAL_STATUS_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "marital_status_i_c",
    },
    {
        "id": "01c1ae70-d8f8-4451-96c5-09afb4ff3057",
        "type": TYPE_STRING,
        "name": "phone_no",
        "lookup": "phone_no",
        "required": False,
        "label": {"English(EN)": "Phone number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "phone_no_i_c",
    },
    {
        "id": "8e10289e-235a-4af5-a745-8c3082b820f5",
        "type": TYPE_STRING,
        "name": "who_answers_phone",
        "lookup": "who_answers_phone",
        "required": False,
        "label": {"English(EN)": "Who answers this phone?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "who_answers_phone_i_c",
    },
    {
        "id": "f7609980-95c4-4b18-82dc-132a04ce7d65",
        "type": TYPE_STRING,
        "name": "phone_no_alternative",
        "lookup": "phone_no_alternative",
        "required": False,
        "label": {"English(EN)": "Alternative phone number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "phone_no_alternative_i_c",
    },
    {
        "id": "2448dbfe-e746-4aea-9e74-e635a3195dc5",
        "type": TYPE_STRING,
        "name": "who_answers_alt_phone",
        "lookup": "who_answers_alt_phone",
        "required": False,
        "label": {"English(EN)": "Who answers this phone?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "who_answers_alt_phone_i_c",
    },
    {
        "id": "e991e0e2-d6be-4abd-b3bc-9122091ca96e",
        "type": TYPE_SELECT_ONE,
        "name": "registration_method",
        "lookup": "registration_method",
        "required": False,
        "label": {"English(EN)": "Method of collection (e.g. HH survey, Community, etc.)"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in REGISTRATION_METHOD_CHOICES],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "registration_method_h_c",
    },
    {
        "id": "d9eea60c-5747-4d26-9f4b-f99a2165e913",
        "type": TYPE_SELECT_ONE,
        "name": "collect_individual_data",
        "lookup": "collect_individual_data",
        "required": False,
        "label": {"English(EN)": "Will you be collecting all member Individuals' data?"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in YES_NO_CHOICE],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "collect_individual_data_h_c",
    },
    {
        "id": "1c2e3c42-8b32-4198-bd4f-06a61e2ecf0e",
        "type": TYPE_SELECT_ONE,
        "name": "currency",
        "lookup": "currency",
        "required": False,
        "label": {"English(EN)": "Which currency will be used for financial questions?"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": currency_name}, "value": code}
            for code, currency_name in CURRENCY_CHOICES
            if code != BLANK
        ],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "currency_h_c",
    },
    {
        "id": "f1d0c0c1-53d7-422a-be3d-b3588ee0ff58",
        "type": TYPE_STRING,
        "name": "birth_certificate_no",
        "lookup": "birth_certificate_no",
        "required": False,
        "label": {"English(EN)": "Birth certificate number"},
        "hint": "",
        "choices": [],
        "get_query": get_birth_certificate_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "birth_certificate_no_i_c",
    },
    {
        "id": "0d8bc4b6-c2c7-4b8b-ab64-cd2e80b70717",
        "type": TYPE_SELECT_ONE,
        "name": "birth_certificate_issuer",
        "lookup": "birth_certificate_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of birth certificate"},
        "hint": "",
        "choices": Countries.get_choices(output_code="alpha3"),
        "get_query": get_birth_certificate_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "birth_certificate_issuer_i_c",
    },
    {
        "id": "12ceb917-8942-4cb6-a9d0-6a97a097258a",
        "type": TYPE_IMAGE,
        "name": "birth_certificate_photo",
        "lookup": "birth_certificate_photo",
        "required": False,
        "label": {"English(EN)": "Birth certificate photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "birth_certificate_photo_i_c",
    },
    {
        "id": "34a9519f-9c42-4910-b097-157ec8e6e31f",
        "type": TYPE_STRING,
        "name": "drivers_license_no",
        "lookup": "drivers_license_no",
        "required": False,
        "label": {"English(EN)": "Driver's license number"},
        "hint": "",
        "choices": [],
        "get_query": get_drivers_license_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "drivers_license_no_i_c",
    },
    {
        "id": "00b95153-976e-4653-b9a8-843d513df873",
        "type": TYPE_SELECT_ONE,
        "name": "drivers_license_issuer",
        "lookup": "drivers_license_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of driver's license"},
        "hint": "",
        "choices": Countries.get_choices(output_code="alpha3"),
        "get_query": get_drivers_licensee_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "drivers_license_issuer_i_c",
    },
    {
        "id": "7e6a41c5-0fbd-4f99-98ba-2c6a7da8dbe4",
        "type": TYPE_IMAGE,
        "name": "drivers_license_photo",
        "lookup": "drivers_license_photo",
        "required": False,
        "label": {"English(EN)": "Driver's license photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "drivers_license_photo_i_c",
    },
    {
        "id": "225832fc-c61b-4100-aac9-352d272d15fd",
        "type": TYPE_STRING,
        "name": "electoral_card_no",
        "lookup": "electoral_card_no",
        "required": False,
        "label": {"English(EN)": "Electoral card number"},
        "hint": "",
        "choices": [],
        "get_query": get_electoral_card_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "electoral_card_no_i_c",
    },
    {
        "id": "acca5a63-538a-47d1-b343-da22a86783b0",
        "type": TYPE_SELECT_ONE,
        "name": "electoral_card_issuer",
        "lookup": "electoral_card_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of electoral card"},
        "hint": "",
        "choices": Countries.get_choices(output_code="alpha3"),
        "get_query": get_electoral_card_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "electoral_card_issuer_i_c",
    },
    {
        "id": "ffb6a487-a806-47d6-a12f-fe3c6c516976",
        "type": TYPE_IMAGE,
        "name": "electoral_card_photo",
        "lookup": "electoral_card_photo",
        "required": False,
        "label": {"English(EN)": "Electoral card photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "electoral_card_photo_i_c",
    },
    {
        "id": "1c7f6c85-1621-48f1-88f3-a172d69aa316",
        "type": TYPE_STRING,
        "name": "unhcr_id_no",
        "lookup": "unhcr_id_no",
        "required": False,
        "label": {"English(EN)": "UNHCR ID number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "unhcr_id_no_i_c",
        "get_query": get_unhcr_id_number,
    },
    {
        "id": "801bdd67-d27d-4afa-9d23-823e1c8d1313",
        "type": TYPE_SELECT_ONE,
        "name": "unhcr_id_issuer",
        "lookup": "unhcr_id_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing entity of UNHCR ID"},
        "hint": "",
        "choices": Countries.get_choices(output_code="alpha3"),
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "unhcr_id_issuer_i_c",
        "get_query": get_unhcr_id_issuer,
    },
    {
        "id": "2f9ca147-afde-4311-9d61-e906a8ef2334",
        "type": TYPE_IMAGE,
        "name": "unhcr_id_photo",
        "lookup": "unhcr_id_photo",
        "required": False,
        "label": {"English(EN)": "UNHCR ID photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "unhcr_id_photo_i_c",
    },
    {
        "id": "4e836832-2cf2-4073-80eb-21316eaf7277",
        "type": TYPE_STRING,
        "name": "national_passport",
        "lookup": "national_passport",
        "required": False,
        "label": {"English(EN)": "National passport number"},
        "hint": "",
        "choices": [],
        "get_query": get_national_passport_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "national_passport_i_c",
    },
    {
        "id": "3da62c17-66ee-4c08-adbf-74402f31dce2",
        "type": TYPE_SELECT_ONE,
        "name": "national_passport_issuer",
        "lookup": "national_passport_issuer",
        "get_query": get_national_passport_issuer_query,
        "required": False,
        "label": {"English(EN)": "Issuing country of national passport"},
        "hint": "",
        "choices": Countries.get_choices(output_code="alpha3"),
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "national_passport_issuer_i_c",
    },
    {
        "id": "234a1b5b-7900-4f67-86a9-5fcaede3d09d",
        "type": TYPE_IMAGE,
        "name": "national_passport_photo",
        "lookup": "national_passport_photo",
        "required": False,
        "label": {"English(EN)": "National passport photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "national_passport_photo_i_c",
    },
    {
        "id": "eff20a18-4336-4273-bbb8-ed0e9a94ebbb",
        "type": TYPE_STRING,
        "name": "national_id_no",
        "lookup": "national_id_no",
        "required": False,
        "label": {"English(EN)": "National ID number"},
        "hint": "",
        "choices": [],
        "get_query": get_national_id_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "national_id_no_i_c",
    },
    {
        "id": "2bd255a7-1273-4a52-930f-6660573b2743",
        "type": TYPE_SELECT_ONE,
        "name": "national_id_issuer",
        "lookup": "national_id_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of national ID"},
        "hint": "",
        "choices": Countries.get_choices(output_code="alpha3"),
        "get_query": get_national_id_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "national_id_issuer_i_c",
    },
    {
        "id": "d43304d9-91e4-4317-9356-f7066b898b16",
        "type": TYPE_IMAGE,
        "name": "national_id_photo",
        "lookup": "national_id_photo",
        "required": False,
        "label": {"English(EN)": "National ID photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "national_id_photo_i_c",
    },
    {
        "id": "201c91d2-8f89-46c9-ba5a-db7130140402",
        "type": TYPE_STRING,
        "name": "scope_id_no",
        "lookup": "scope_id_no",
        "required": False,
        "label": {"English(EN)": "WFP Scope ID number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "scope_id_no_i_c",
        "get_query": get_scope_id_number,
    },
    {
        "id": "638a6383-6e87-4c4f-842c-6c5433599267",
        "type": TYPE_SELECT_ONE,
        "name": "scope_id_issuer",
        "lookup": "scope_id_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing entity of SCOPE ID"},
        "hint": "",
        "choices": Countries.get_choices(output_code="alpha3"),
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "scope_id_issuer_i_c",
        "get_query": get_scope_id_issuer,
    },
    {
        "id": "4aa3d595-131a-48df-8752-ec171eabe3be",
        "type": TYPE_IMAGE,
        "name": "scope_id_photo",
        "lookup": "scope_id_photo",
        "required": False,
        "label": {"English(EN)": "WFP Scope ID photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "scope_id_photo_i_c",
    },
    {
        "id": "3bf6105f-87d0-479b-bf92-7f90af4d8462",
        "type": TYPE_STRING,
        "name": "other_id_type",
        "lookup": "other_id_type",
        "required": False,
        "label": {"English(EN)": "If other type of ID, specify the type"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "other_id_type_i_c",
    },
    {
        "id": "556e14af-9901-47f3-bf2c-20b4c721e8f7",
        "type": TYPE_STRING,
        "name": "other_id_no",
        "lookup": "other_id_no",
        "required": False,
        "label": {"English(EN)": "Other ID number"},
        "hint": "",
        "choices": [],
        "get_query": get_other_document_number_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "other_id_no_i_c",
    },
    {
        "id": "cd181a09-f4c5-4a47-8713-25bdc4a64058",
        "type": TYPE_SELECT_ONE,
        "name": "other_id_issuer",
        "lookup": "other_id_issuer",
        "required": False,
        "label": {"English(EN)": "Issuing country of other ID"},
        "hint": "",
        "choices": Countries.get_choices(output_code="alpha3"),
        "get_query": get_other_issuer_query,
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "other_id_issuer_i_c",
    },
    {
        "id": "d4279a74-377f-4f74-baf2-e1ebd001ec5c",
        "type": TYPE_IMAGE,
        "name": "other_id_photo",
        "lookup": "other_id_photo",
        "required": False,
        "label": {"English(EN)": "ID photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "other_id_photo_i_c",
    },
    # {
    #     "id": "b886d636-36cd-4beb-b2f9-6ddb204532d5",
    #     "type": TYPE_INTEGER,
    #     "name": "pregnant_member",
    #     "lookup": "pregnant_member",
    #     "required": False,
    #     "label": {"English(EN)": ""},
    #     "hint": "",
    #     "choices": [],
    #     "associated_with": _HOUSEHOLD,
    #     "xlsx_field": "pregnant_member_h_c",
    # },
    {
        "id": "07f7005f-e70d-409b-9dee-4c3414aba40b",
        "type": TYPE_INTEGER,
        "name": "female_age_group_0_5_count",
        "lookup": "female_age_group_0_5_count",
        "required": False,
        "label": {"English(EN)": "Females Age 0-5"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_0_5_age_group_h_c",
    },
    {
        "id": "6b993af8-4a5d-4a08-a444-8ade115c39ad",
        "type": TYPE_INTEGER,
        "name": "female_age_group_6_11_count",
        "lookup": "female_age_group_6_11_count",
        "required": False,
        "label": {"English(EN)": "Females Age 6-11"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_6_11_age_group_h_c",
    },
    {
        "id": "71ce16b5-4e49-48fa-818c-0bd2eba079eb",
        "type": TYPE_INTEGER,
        "name": "female_age_group_12_17_count",
        "lookup": "female_age_group_12_17_count",
        "required": False,
        "label": {"English(EN)": "Females Age 12-17"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_12_17_age_group_h_c",
    },
    {
        "id": "1af02ab4-469b-4de1-a71a-7d51cc86224b",
        "type": TYPE_INTEGER,
        "name": "female_age_group_18_59_count",
        "lookup": "female_age_group_18_59_count",
        "required": False,
        "label": {"English(EN)": "Females Age 18-59"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_18_59_age_group_h_c",
    },
    {
        "id": "4009ca04-1ffd-48eb-a41f-64ddb439cc8d",
        "type": TYPE_INTEGER,
        "name": "female_age_group_60_count",
        "lookup": "female_age_group_60_count",
        "required": False,
        "label": {"English(EN)": "Females Age 60+"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_60_age_group_h_c",
    },
    {
        "id": "18fd9429-400f-4fce-b72f-035d2afca201",
        "type": TYPE_INTEGER,
        "name": "pregnant_count",
        "lookup": "pregnant_count",
        "required": False,
        "label": {"English(EN)": "Pregnant count"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "pregnant_h_c",
    },
    {
        "id": "57233f1b-93c3-4fd4-a885-92c512c5e32a",
        "type": TYPE_INTEGER,
        "name": "male_age_group_0_5_count",
        "lookup": "male_age_group_0_5_count",
        "required": False,
        "label": {"English(EN)": "Males Age 0-5"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_0_5_age_group_h_c",
    },
    {
        "id": "11e2a938-e93a-4c18-8eca-7e61355d7476",
        "type": TYPE_INTEGER,
        "name": "male_age_group_6_11_count",
        "lookup": "male_age_group_6_11_count",
        "required": False,
        "label": {"English(EN)": "Males Age 6-11"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_6_11_age_group_h_c",
    },
    {
        "id": "bf28628e-0f6a-46e8-9587-3b0c17977006",
        "type": TYPE_INTEGER,
        "name": "male_age_group_12_17_count",
        "lookup": "male_age_group_12_17_count",
        "required": False,
        "label": {"English(EN)": "Males Age 12-17"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_12_17_age_group_h_c",
    },
    {
        "id": "e76cd764-1466-49c3-92da-5a558069c472",
        "type": TYPE_INTEGER,
        "name": "male_age_group_18_59_count",
        "lookup": "male_age_group_18_59_count",
        "required": False,
        "label": {"English(EN)": "Males Age 18-59"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_18_59_age_group_h_c",
    },
    {
        "id": "988ebe6d-8782-4bc1-95a0-eeb692980847",
        "type": TYPE_INTEGER,
        "name": "male_age_group_60_count",
        "lookup": "male_age_group_60_count",
        "required": False,
        "label": {"English(EN)": "Males Age 60+"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_60_age_group_h_c",
    },
    {
        "id": "4f59aca6-5900-40c0-a1e4-47c331a90a6f",
        "type": TYPE_INTEGER,
        "name": "female_age_group_0_5_disabled_count",
        "lookup": "female_age_group_0_5_disabled_count",
        "required": False,
        "label": {"English(EN)": "Females age 0-5 with disability"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_0_5_disability_h_c",
    },
    {
        "id": "10e33d7b-b3c4-4383-a4f0-6eba00a15e9c",
        "type": TYPE_INTEGER,
        "name": "female_age_group_6_11_disabled_count",
        "lookup": "female_age_group_6_11_disabled_count",
        "required": False,
        "label": {"English(EN)": "Females age 6-11 with disability"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_6_11_disability_h_c",
    },
    {
        "id": "623a6fd6-d863-40cc-a4d1-964f739747be",
        "type": TYPE_INTEGER,
        "name": "female_age_group_12_17_disabled_count",
        "lookup": "female_age_group_12_17_disabled_count",
        "required": False,
        "label": {"English(EN)": "Females age 12-17 with disability"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_12_17_disability_h_c",
    },
    {
        "id": "c99df741-4559-4166-a49c-05d69ba8a4fa",
        "type": TYPE_INTEGER,
        "name": "female_age_group_18_59_disabled_count",
        "lookup": "female_age_group_18_59_disabled_count",
        "required": False,
        "label": {"English(EN)": "Females Age 18-59 with disability"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_18_59_disability_h_c",
    },
    {
        "id": "f21d61f2-923e-46b8-aefc-b623cb0026ca",
        "type": TYPE_INTEGER,
        "name": "female_age_group_60_disabled_count",
        "lookup": "female_age_group_60_disabled_count",
        "required": False,
        "label": {"English(EN)": "Female members with Disability age 60+"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "f_60_disability_h_c",
    },
    {
        "id": "d3b82576-1bba-44fa-9d5a-db04e71bb35b",
        "type": TYPE_INTEGER,
        "name": "male_age_group_0_5_disabled_count",
        "lookup": "male_age_group_0_5_disabled_count",
        "required": False,
        "label": {"English(EN)": "Males age 0-5 with disability"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_0_5_disability_h_c",
    },
    {
        "id": "78340f8f-86ab-464a-8e19-ce3d6feec5d6",
        "type": TYPE_INTEGER,
        "name": "male_age_group_6_11_disabled_count",
        "lookup": "male_age_group_6_11_disabled_count",
        "required": False,
        "label": {"English(EN)": "Males age 6-11 with disability"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_6_11_disability_h_c",
    },
    {
        "id": "519140f7-1a9e-4115-b736-2b09dbc6f036",
        "type": TYPE_INTEGER,
        "name": "male_age_group_12_17_disabled_count",
        "lookup": "male_age_group_12_17_disabled_count",
        "required": False,
        "label": {"English(EN)": "Males age 12-17 with disability"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_12_17_disability_h_c",
    },
    {
        "id": "9c6e1d87-0768-4db7-b925-41da8b5c7988",
        "type": TYPE_INTEGER,
        "name": "male_age_group_18_59_disabled_count",
        "lookup": "male_age_group_18_59_disabled_count",
        "required": False,
        "label": {"English(EN)": "Males Age 18-59 with disability"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_18_59_disability_h_c",
    },
    {
        "id": "c07da769-b7c4-4e4f-aefa-1a20bb24d8b2",
        "type": TYPE_INTEGER,
        "name": "male_age_group_60_disabled_count",
        "lookup": "male_age_group_60_disabled_count",
        "required": False,
        "label": {"English(EN)": "Male members with Disability age 60+"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "m_60_disability_h_c",
    },
    {
        "id": "b2593385-5a81-452e-ae9a-28292e35714b",
        "type": TYPE_BOOL,
        "name": "pregnant",
        "lookup": "pregnant",
        "required": False,
        "label": {"English(EN)": "Is the individual pregnant?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "pregnant_i_c",
    },
    {
        "id": "dca6748f-7831-4fa1-b5c8-e708a456656b",
        "type": TYPE_SELECT_ONE,
        "name": "work_status",
        "lookup": "work_status",
        "required": False,
        "label": {"English(EN)": "Does the individual have paid employment in the curent month?"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in WORK_STATUS_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "work_status_i_c",
    },
    {
        "id": "21cd9a35-b080-4f60-97da-6ec6918a49c0",
        "type": TYPE_SELECT_MANY,
        "name": "observed_disability",
        "lookup": "observed_disability",
        "required": False,
        "label": {"English(EN)": "Does the individual have disability?"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in OBSERVED_DISABILITY_CHOICE],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "observed_disability_i_c",
    },
    {
        "id": "244ec9ae-5eb8-4b80-9416-91024a3f32d7",
        "type": TYPE_SELECT_ONE,
        "name": "seeing_disability",
        "lookup": "seeing_disability",
        "required": False,
        "label": {"English(EN)": "If the individual has difficulty seeing, what is the severity?"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "seeing_disability_i_c",
    },
    {
        "id": "bef35c02-1fe7-4f6b-a0af-8282ec31de89",
        "type": TYPE_SELECT_ONE,
        "name": "hearing_disability",
        "lookup": "hearing_disability",
        "required": False,
        "label": {"English(EN)": "If the individual has difficulty hearing, what is the severity?"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "hearing_disability_i_c",
    },
    {
        "id": "b7346b1f-23ea-47a8-b2ec-c176c62cdb5b",
        "type": TYPE_SELECT_ONE,
        "name": "physical_disability",
        "lookup": "physical_disability",
        "required": False,
        "label": {"English(EN)": "If the individual has difficulty walking or climbing steps, what is the severity?"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "physical_disability_i_c",
    },
    {
        "id": "0f24c374-4428-43ef-b162-86dc1b14e39d",
        "type": TYPE_SELECT_ONE,
        "name": "memory_disability",
        "lookup": "memory_disability",
        "required": False,
        "label": {
            "English(EN)": "If the individual has difficulty remembering or concentrating, what is the severity?"
        },
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "memory_disability_i_c",
    },
    {
        "id": "59508af1-07d0-4e20-ac3d-f241bef319c1",
        "type": TYPE_SELECT_ONE,
        "name": "selfcare_disability",
        "lookup": "selfcare_disability",
        "required": False,
        "label": {"English(EN)": "Do you have difficulty (with self-care such as) washing all over or dressing"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "selfcare_disability_i_c",
    },
    {
        "id": "78311be2-fb3f-443c-aac6-c0e7197af20d",
        "type": TYPE_SELECT_ONE,
        "name": "comms_disability",
        "lookup": "comms_disability",
        "required": False,
        "label": {"English(EN)": "If the individual has difficulty communicating, what is the severity?"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": value} for value, label in SEVERITY_OF_DISABILITY_CHOICES
        ],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "comms_disability_i_c",
    },
    {
        "id": "9fbd2b6f-6713-445c-a7bb-e1efc398b20d",
        "type": TYPE_BOOL,
        "name": "fchild_hoh",
        "lookup": "fchild_hoh",
        "required": False,
        "label": {"English(EN)": "Female child headed household"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "fchild_hoh_h_c",
    },
    {
        "id": "e92810b2-c6f1-480c-95a9-4f736a1f48bf",
        "type": TYPE_BOOL,
        "name": "child_hoh",
        "lookup": "child_hoh",
        "required": False,
        "label": {"English(EN)": "Child headed household"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "child_hoh_h_c",
    },
    {
        "id": "62692d6a-c054-418b-803a-e34393cbc1b0",
        "type": TYPE_STRING,
        "name": "village",
        "lookup": "village",
        "required": False,
        "label": {"English(EN)": "Village"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "village_h_c",
    },
    {
        "id": "c640fe45-368f-4206-afae-09700a495db3",
        "type": TYPE_STRING,
        "name": "deviceid",
        "lookup": "deviceid",
        "required": False,
        "label": {"English(EN)": "Device ID"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "deviceid",
    },
    {
        "id": "8f379d33-c5fd-4344-ba2b-73e136aba13a",
        "type": TYPE_STRING,
        "name": "name_enumerator",
        "lookup": "name_enumerator",
        "required": False,
        "label": {"English(EN)": "Name of the enumerator"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "name_enumerator_h_c",
    },
    {
        "id": "201e9a88-fb7d-4ba4-afec-66aba748fe55",
        "type": TYPE_SELECT_ONE,
        "name": "org_enumerator",
        "lookup": "org_enumerator",
        "required": False,
        "label": {"English(EN)": "Organization of the enumerator"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in ORG_ENUMERATOR_CHOICES],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "org_enumerator_h_c",
    },
    {
        "id": "0858371e-4e5c-402e-9cda-b767eb2d337c",
        "type": TYPE_SELECT_MANY,
        "name": "consent_sharing",
        "lookup": "consent_sharing",
        "required": False,
        "label": {"English(EN)": "Which organizations may we share your information with?"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in DATA_SHARING_CHOICES],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "consent_sharing_h_c",
    },
    {
        "id": "27bd4ef2-442d-4b49-976c-063df050b3ae",
        "type": TYPE_STRING,
        "name": "org_name_enumerator",
        "lookup": "org_name_enumerator",
        "required": False,
        "label": {"English(EN)": "Name of partner organization"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "org_name_enumerator_h_c",
    },
    {
        "id": "69dbc5f2-039f-4671-b39f-a63d96475cab",
        "type": TYPE_SELECT_ONE,
        "name": "disability",
        "lookup": "disability",
        "required": False,
        "label": {"English(EN)": "Individual is disabled?"},
        "hint": "",
        "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in DISABILITY_CHOICES],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "disability_i_c",
    },
]

HOUSEHOLD_ID_FIELDS = [
    {
        "id": "746b3d2d-19c5-4b91-ad37-d230e1d33eb5",
        "type": TYPE_ID,
        "name": "household_id",
        "lookup": "household_id",
        "required": False,
        "label": {"English(EN)": "Household ID"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "household_id",
    },
    {
        "id": "1079bfd0-fc51-41ab-aa10-667e6b2034b9",
        "type": TYPE_ID,
        "name": "household_id",
        "lookup": "household_id",
        "required": False,
        "label": {"English(EN)": "Household ID"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "household_id",
    },
]

COLLECTORS_FIELDS = {
    "primary_collector_id": {
        "type": TYPE_LIST_OF_IDS,
        "name": "primary_collector_id",
        "required": True,
        "label": {"English(EN)": "List of primary collectors ids, separated by a semicolon"},
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "primary_collector_id",
        "custom_cast_value": Countries.get_country_value,
    },
    "alternate_collector_id": {
        "type": TYPE_LIST_OF_IDS,
        "name": "alternate_collector_id",
        "required": True,
        "label": {"English(EN)": "List of alternate collectors ids, separated by a semicolon"},
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "alternate_collector_id",
        "custom_cast_value": Countries.get_country_value,
    },
}

FIELDS_EXCLUDED_FROM_RDI = {
    "business_area": LazyEvalMethodsDict(
        {
            "type": TYPE_SELECT_ONE,
            "name": "business_area",
            "lookup": "business_area",
            "required": False,
            "label": {"English(EN)": "Business Area"},
            "hint": "",
            "choices": lambda: BusinessArea.get_business_areas_as_choices(),
            "associated_with": _INDIVIDUAL,
            "xlsx_field": "business_area",
        }
    ),
}

KOBO_ONLY_HOUSEHOLD_FIELDS = {
    "start": {
        "id": "9da8c56a-3c65-47d9-8149-699761842ce4",
        "type": TYPE_STRING,
        "name": "start",
        "lookup": "start",
        "required": True,
        "label": {"English(EN)": "Data collection start date"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "start",
    },
    "end": {
        "id": "06e4c4a0-28d2-4530-be24-92623a5b48b0",
        "type": TYPE_STRING,
        "name": "end",
        "lookup": "end",
        "required": True,
        "label": {"English(EN)": "Data collection end date"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "end",
    },
}

ROLE_FIELD = {
    "id": "0bf5fad3-8f4f-4528-85f7-57e8a84a2a43",
    "type": TYPE_SELECT_ONE,
    "name": "role",
    "lookup": "role",
    "required": True,
    "label": {"English(EN)": "Role"},
    "hint": "",
    "choices": [{"label": {"English(EN)": label}, "value": value} for value, label in ROLE_CHOICE],
    "associated_with": _INDIVIDUAL,
    "xlsx_field": "role_i_c",
    "get_query": get_role_query,
}
KOBO_ONLY_INDIVIDUAL_FIELDS = {
    "role_i_c": ROLE_FIELD,
}

XLSX_ONLY_FIELDS = [
    {
        "id": "6536a987-a50e-453b-9517-57c1dccd1340",
        "type": TYPE_DATE,
        "name": "first_registration_date",
        "lookup": "first_registration_date",
        "required": True,
        "label": {"English(EN)": "First individual registration date"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
        "xlsx_field": "first_registration_date_i_c",
    },
    {
        "id": "2fe6d876-388f-45d9-b497-eb2f8af923e8",
        "type": TYPE_DATE,
        "name": "first_registration_date",
        "lookup": "first_registration_date",
        "required": True,
        "label": {"English(EN)": "First household registration date"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
        "xlsx_field": "first_registration_date_h_c",
    },
]


def _reduce_core_field_attr(old, new):
    old[new.get("name")] = new
    return old


def core_fields_to_separated_dict(append_household_id=True, append_xlsx=True):
    result_dict = {
        "individuals": {},
        "households": {},
    }

    core_fields_attrs = CORE_FIELDS_ATTRIBUTES

    if append_household_id is True:
        core_fields_attrs = HOUSEHOLD_ID_FIELDS + CORE_FIELDS_ATTRIBUTES

    if append_xlsx is True:
        core_fields_attrs += XLSX_ONLY_FIELDS

    for field in core_fields_attrs:
        associated_key = field["associated_with"].lower() + "s"
        result_dict[associated_key][field["xlsx_field"]] = field

    return result_dict


TARGETING_CORE_FIELDS = CORE_FIELDS_ATTRIBUTES + XLSX_ONLY_FIELDS + [ROLE_FIELD]
FILTERABLE_CORE_FIELDS_ATTRIBUTES = [x for x in CORE_FIELDS_ATTRIBUTES if x.get("type") in FILTERABLE_TYPES]

CORE_FIELDS_ATTRIBUTES_DICTIONARY = reduce(_reduce_core_field_attr, TARGETING_CORE_FIELDS, {})

CORE_FIELDS_SEPARATED_WITH_NAME_AS_KEY = core_fields_to_separated_dict()
