from functools import reduce

from core.utils import age_to_dob_query
from household.models import Household

TYPE_INTEGER = "INTEGER"
TYPE_STRING = "STRING"
TYPE_DATE = "DATE"
TYPE_IMAGE = "IMAGE"
TYPE_SELECT_ONE = "SELECT_ONE"
TYPE_SELECT_MANY = "SELECT_MANY"
TYPE_GEOPOINT = "SELECT_MANY"
_INDIVIDUAL = "Individual"
_HOUSEHOLD = "Household"

CALCULATED_FIELDS = ("age",)

CORE_FIELDS_ATTRIBUTES = [
    {
        "id": "a1741e3c-0e24-4a60-8d2f-463943abaebb",
        "type": TYPE_INTEGER,
        "name": "age",
        "label": {"English(EN)": "Age (calculated)"},
        "hint": "",
        "required": False,
        "get_query": age_to_dob_query,
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "d6aa9669-ae82-4e3c-adfe-79b5d95d0754",
        "type": TYPE_INTEGER,
        "lookup": "size",
        "name": "Size",
        "label": {"English(EN)": "What is the household size?"},
        "hint": "",
        "required": True,
        "choices": [],
        "associated_with": _HOUSEHOLD,
    },
    {
        "id": "3c2473d6-1e81-4025-86c7-e8036dd92f4b",
        "type": TYPE_SELECT_ONE,
        "name": "residence_status",
        "lookup": "residence_status",
        "required": True,
        "label": {"English(EN)": "Residence status"},
        "hint": "",
        "choices": [
            {"label": {"English(EN)": label}, "value": str(value),}
            for value, label in Household.RESIDENCE_STATUS_CHOICE
        ],
        "associated_with": _HOUSEHOLD,
    },
    {
        "id": "",
        "type": TYPE_SELECT_ONE,
        "name": "consent",
        "lookup": "consent",
        "required": True,
        "label": {"English(EN)": "Do you consent?"},
        "hint": "image of consent",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_SELECT_ONE,
        "name": "country_origin",
        "lookup": "country_origin",
        "required": False,
        "label": {"English(EN)": "Country origin"},
        "hint": "country origin",
        "choices": [],
        "associated_with": _HOUSEHOLD,
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "address",
        "lookup": "address",
        "required": False,
        "label": {"English(EN)": "Address"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
    },
    {
        "id": "",
        "type": TYPE_SELECT_ONE,
        "name": "admin1",
        "lookup": "admin1",
        "required": False,
        "label": {
            "English(EN)": "Household resides in (Select administrative level 1)"
        },
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
    },
    {
        "id": "",
        "type": TYPE_SELECT_ONE,
        "name": "admin2",
        "lookup": "admin2",
        "required": False,
        "label": {
            "English(EN)": "Household resides in (Select administrative level 2)"
        },
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
    },
    {
        "id": "",
        "type": TYPE_GEOPOINT,
        "name": "geopoint",
        "lookup": "geopoint",
        "required": False,
        "label": {"English(EN)": "Household Geopoint"},
        "hint": "latitude and longitude of household",
        "choices": [],
        "associated_with": _HOUSEHOLD,
    },
    {
        "id": "",
        "type": TYPE_GEOPOINT,
        "name": "geopoint",
        "lookup": "geopoint",
        "required": False,
        "label": {"English(EN)": "Household Geopoint"},
        "hint": "latitude and longitude of household",
        "choices": [],
        "associated_with": _HOUSEHOLD,
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "unhcr_id",
        "lookup": "unhcr_id",
        "required": False,
        "label": {"English(EN)": "UNHCR Case ID"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "unhcr_id",
        "lookup": "unhcr_id",
        "required": False,
        "label": {"English(EN)": "UNHCR Case ID"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
    },
    {
        "id": "",
        "type": TYPE_SELECT_ONE,
        "name": "returnee",
        "lookup": "returnee",
        "required": False,
        "label": {"English(EN)": "Is this a returnee household?"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
    },
    {
        "id": "",
        "type": TYPE_INTEGER,
        "name": "size",
        "lookup": "size",
        "required": False,
        "label": {"English(EN)": "What is the household size?"},
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
    },
    {
        "id": "",
        "type": TYPE_SELECT_ONE,
        "name": "relationship",
        "lookup": "relationship",
        "required": True,
        "label": {"English(EN)": "Relationship to Head of Household"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_SELECT_ONE,
        "name": "role",
        "lookup": "role",
        "required": False,
        "label": {"English(EN)": "Role"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "full_name",
        "lookup": "full_name",
        "required": True,
        "label": {"English(EN)": "Full Name"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "given_name",
        "lookup": "given_name",
        "required": False,
        "label": {"English(EN)": "Given Name"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "middle_name",
        "lookup": "middle_name",
        "required": False,
        "label": {"English(EN)": "Middle Names"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "family_name",
        "lookup": "family_name",
        "required": False,
        "label": {"English(EN)": "Family Name"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_SELECT_ONE,
        "name": "sex",
        "lookup": "sex",
        "required": True,
        "label": {"English(EN)": "Sex"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_DATE,
        "name": "birth_date",
        "lookup": "birth_date",
        "required": True,
        "label": {"English(EN)": "Birth Date"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_DATE,
        "name": "estimated_birth_date",
        "lookup": "estimated_birth_date",
        "required": True,
        "label": {"English(EN)": "Estimated Birth Date?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_IMAGE,
        "name": "photo",
        "lookup": "photo",
        "required": True,
        "label": {"English(EN)": "Photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_SELECT_ONE,
        "name": "marital_status",
        "lookup": "marital_status",
        "required": True,
        "label": {"English(EN)": "Marital Status"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_SELECT_ONE,
        "name": "marital_status",
        "lookup": "marital_status",
        "required": False,
        "label": {"English(EN)": "Marital Status"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_INTEGER,
        "name": "phone_no",
        "lookup": "phone_no",
        "required": False,
        "label": {"English(EN)": "Phone number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_INTEGER,
        "name": "phone_no_alternative",
        "lookup": "phone_no_alternative",
        "required": False,
        "label": {"English(EN)": "Alternative phone number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_SELECT_MANY,
        "name": "id_type",
        "lookup": "id_type",
        "required": False,
        "label": {
            "English(EN)": "What type of identification document is provided?"
        },
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "birth_certificate_no",
        "lookup": "birth_certificate_no",
        "required": False,
        "label": {"English(EN)": "Birth certificate number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": None,
        "name": "birth_certificate_photo",
        "lookup": "birth_certificate_photo",
        "required": False,
        "label": {"English(EN)": "Birth certificate photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "drivers_license_no",
        "lookup": "drivers_license_no",
        "required": False,
        "label": {"English(EN)": "Driver's license number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": None,
        "name": "drivers_license_photo",
        "lookup": "drivers_license_photo",
        "required": False,
        "label": {"English(EN)": "Driver's license photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "electoral_card_no",
        "lookup": "electoral_card_no",
        "required": False,
        "label": {"English(EN)": "Electoral card number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": None,
        "name": "electoral_card_photo",
        "lookup": "electoral_card_photo",
        "required": False,
        "label": {"English(EN)": "Electoral card photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "unhcr_id_no",
        "lookup": "unhcr_id_no",
        "required": False,
        "label": {"English(EN)": "UNHCR ID number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": None,
        "name": "unhcr_id_photo",
        "lookup": "unhcr_id_photo",
        "required": False,
        "label": {"English(EN)": "UNHCR ID photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "national_passport",
        "lookup": "national_passport",
        "required": False,
        "label": {"English(EN)": "National passport number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": None,
        "name": "national_passport_photo",
        "lookup": "national_passport_photo",
        "required": False,
        "label": {"English(EN)": "National passport photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "scope_id_no",
        "lookup": "scope_id_no",
        "required": False,
        "label": {"English(EN)": "WFP Scope ID number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": None,
        "name": "scope_id_photo",
        "lookup": "scope_id_photo",
        "required": False,
        "label": {"English(EN)": "WFP Scope ID photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "other_id_type",
        "lookup": "other_id_type",
        "required": False,
        "label": {"English(EN)": "If other type of ID, specify the type"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_STRING,
        "name": "other_id_no",
        "lookup": "other_id_no",
        "required": False,
        "label": {"English(EN)": "ID number"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": None,
        "name": "other_id_photo",
        "lookup": "other_id_photo",
        "required": False,
        "label": {"English(EN)": "ID photo"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_SELECT_ONE,
        "name": "work_status",
        "lookup": "work_status",
        "required": False,
        "label": {"English(EN)": "Does the individual  work?"},
        "hint": "",
        "choices": [],
        "associated_with": _INDIVIDUAL,
    },
    {
        "id": "",
        "type": TYPE_INTEGER,
        "name": "pregnant_member",
        "lookup": "pregnant_member",
        "required": True,
        "label": {
            "English(EN)": "How many pregnant women are there in the Household?"
        },
        "hint": "",
        "choices": [],
        "associated_with": _HOUSEHOLD,
    },
]


def _reduce_core_field_attr(old, new):
    old[new.get("name")] = new
    return old


def _core_fields_to_separated_dict():
    result_dict = {
        "individuals": {},
        "households": {},
    }
    for field in CORE_FIELDS_ATTRIBUTES:
        associated_key = field["associated_with"].lower() + "s"
        result_dict[associated_key][field["name"]] = field

    return result_dict


CORE_FIELDS_ATTRIBUTES_DICTIONARY = reduce(
    _reduce_core_field_attr, CORE_FIELDS_ATTRIBUTES, {}
)

CORE_FIELDS_SEPARATED_WITH_NAME_AS_KEY = _core_fields_to_separated_dict()
