# Generated by Django 2.2.8 on 2020-01-28 15:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='FlexibleField',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('required', models.BooleanField()),
                ('relevant', models.TextField(blank=True)),
                ('calculation', models.TextField(blank=True)),
                ('constraint_message', models.TextField(blank=True)),
                ('default', models.TextField(blank=True)),
                ('label', django.contrib.postgres.fields.jsonb.JSONField()),
                ('hint', django.contrib.postgres.fields.jsonb.JSONField()),
                ('choice_filter', models.TextField(blank=True)),
                ('repeat_count', models.CharField(blank=True, max_length=255)),
                ('read_only', models.BooleanField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
