# Generated by Django 2.2.8 on 2020-01-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessarea',
            name='kobo_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
