# Generated by Django 2.2.8 on 2020-07-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessarea',
            name='rapid_pro_api_key',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
