# Generated by Django 2.2.8 on 2020-10-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexibleattributechoice',
            options={'ordering': ('name',)},
        ),
    ]
