# Generated by Django 2.2.8 on 2020-04-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_migration'),
        ('household', '0016_migration'),
        ('core', '0007_migration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='AdminArea',
        ),
        migrations.AlterModelOptions(
            name='adminareatype',
            options={'ordering': ['name'], 'verbose_name': 'AdminAreaType type'},
        ),
    ]
