# Generated by Django 2.2.8 on 2020-04-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_migration'),
        ('household', '0020_migration'),
        ('core', '0009_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminArea',
        ),
    ]
