# Generated by Django 2.2.8 on 2020-04-23 16:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminArea',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('admin_area_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.AdminAreaType')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.AdminArea', verbose_name='Parent')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('title', 'admin_area_type')},
            },
        ),
    ]
