# Generated by Django 2.2.16 on 2021-02-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xlsxkobotemplate',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SUCCESSFUL', 'Successful'), ('UNSUCCESSFUL', 'Unsuccessful'), ('PROCESSING', 'Processing')], max_length=200),
        ),
    ]
