# Generated by Django 2.2.16 on 2021-02-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexibleattributegroup',
            name='removed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
