# Generated by Django 2.2.16 on 2021-03-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexibleattribute',
            name='type',
            field=models.CharField(choices=[('STRING', 'String'), ('IMAGE', 'Image'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('SELECT_ONE', 'Select One'), ('SELECT_MANY', 'Select Many'), ('DATE', 'Date'), ('GEOPOINT', 'Geopoint')], max_length=16),
        ),
    ]
