# Generated by Django 2.2.16 on 2021-06-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessarea',
            name='is_split',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessarea',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.BusinessArea'),
        ),
    ]
