# Generated by Django 2.2.16 on 2021-06-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminarealevel',
            name='area_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='adminarea',
            name='p_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='P Code'),
        ),
        migrations.AlterUniqueTogether(
            name='adminarealevel',
            unique_together={('area_code', 'admin_level')},
        ),
        migrations.RemoveField(
            model_name='adminarealevel',
            name='business_area',
        ),
    ]
