# Generated by Django 2.2.16 on 2021-06-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminarealevel',
            name='datamart_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
