# Generated by Django 2.2.16 on 2021-06-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminarealevel',
            name='real_admin_level',
        ),
        migrations.AddField(
            model_name='adminarealevel',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminarealevel',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
    ]
