# Generated by Django 2.2.16 on 2021-06-14 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminarealevel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AdminAreaLevel'),
        ),
    ]
