# Generated by Django 2.2.16 on 2021-06-17 08:48

from django.db import migrations
def empty_reverse(apps, schema_editor):
    pass
def remove_duplicates(apps, schema_editor):
    AdminAreaLevel = apps.get_model("core", "AdminAreaLevel")
    levels_without_ids = AdminAreaLevel.objects.filter(datamart_id__isnull=True)
    for level in levels_without_ids:
        new_datamart_id = level.admin_level
        duplicated = AdminAreaLevel.objects.filter(datamart_id=new_datamart_id)
        duplicated.delete()
        level.datamart_id=new_datamart_id
        level.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_migration'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates,empty_reverse),
    ]
