# Generated by Django 2.2.16 on 2021-07-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminarea',
            options={'ordering': ['title'], 'permissions': (('import_from_csv', 'Import AdminAreas from CSV file'), ('load_from_datamart', 'Load data from Datamart'))},
        ),
        migrations.AlterModelOptions(
            name='adminarealevel',
            options={'ordering': ['name'], 'permissions': (('load_from_datamart', 'Load data from Datamart'), ('can_sync_with_ad', 'Can synchronise user with ActiveDirectory'), ('can_upload_to_kobo', 'Can upload users to Kobo')), 'verbose_name': 'Admin Area Level'},
        ),
        migrations.AlterModelOptions(
            name='businessarea',
            options={'ordering': ['name'], 'permissions': (('can_split', 'Can split BusinessArea'),)},
        ),
        migrations.AlterField(
            model_name='adminarealevel',
            name='business_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_area_level', to='core.BusinessArea'),
        ),
    ]
