# Generated by Django 2.2.16 on 2021-07-14 14:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessarea',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
