# Generated by Django 2.2.16 on 2021-09-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessarea',
            name='screen_beneficiary',
            field=models.BooleanField(default=False),
        ),
    ]
