# Generated by Django 3.2.13 on 2022-08-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessarea",
            name="is_payment_plan_applicable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="businessarea",
            name="approval_number_required",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="businessarea",
            name="authorization_number_required",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="businessarea",
            name="finance_review_number_required",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="businessarea",
            name="approval_number_required",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="businessarea",
            name="authorization_number_required",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="businessarea",
            name="finance_review_number_required",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
