# Generated by Django 3.2.15 on 2022-10-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_migration'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='flexibleattributegroup',
            managers=[
            ],
        ),
    ]
