# Generated by Django 3.2.15 on 2023-01-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessarea',
            name='is_using_payment_module',
            field=models.BooleanField(default=False),
        ),
    ]
