# Generated by Django 3.2.24 on 2024-02-16 05:13

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    replaces = [('core', '0068_migration'), ('core', '0069_migration'), ('core', '0070_migration'), ('core', '0071_migration'), ('core', '0072_migration'), ('core', '0073_migration'), ('core', '0074_migration'), ('core', '0075_migration'), ('core', '0076_migration')]

    dependencies = [
        ('core', '0065_migration_squashed_0067_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessarea',
            old_name='rapid_pro_api_key',
            new_name='rapid_pro_payment_verification_token',
        ),
        migrations.AddField(
            model_name='businessarea',
            name='rapid_pro_messages_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='businessarea',
            name='rapid_pro_survey_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='MigrationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_running', models.BooleanField()),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Migration Status',
            },
        ),
        migrations.CreateModel(
            name='DataCollectingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('compatible_types', models.ManyToManyField(blank=True, to='core.DataCollectingType')),
                ('active', models.BooleanField(default=True)),
                ('individual_filters_available', models.BooleanField(default=False)),
                ('limit_to', models.ManyToManyField(blank=True, related_name='data_collecting_types', to='core.BusinessArea')),
                ('household_filters_available', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=32)),
                ('recalculate_composition', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='datacollectingtype',
            constraint=models.UniqueConstraint(fields=('label', 'code'), name='unique_label_code_data_collecting_type'),
        ),
        migrations.AlterField(
            model_name='datacollectingtype',
            name='compatible_types',
            field=models.ManyToManyField(blank=True, to='core.DataCollectingType'),
        ),
        migrations.AddField(
            model_name='datacollectingtype',
            name='deprecated',
            field=models.BooleanField(default=False, help_text='Cannot be used in new programs, totally hidden in UI, only admin have access'),
        ),
        migrations.AddField(
            model_name='datacollectingtype',
            name='type',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('SOCIAL', 'Social Workers')], max_length=32, null=True),
        ),
        migrations.AlterModelOptions(
            name='datacollectingtype',
            options={'ordering': ('-weight',)},
        ),
        migrations.AddField(
            model_name='datacollectingtype',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
