<<<<<<< HEAD
# Generated by Django 3.2.25 on 2024-08-19 15:45

from django.db import migrations, models
=======
# Generated by Django 3.2.25 on 2024-07-17 10:18

from django.db import migrations
>>>>>>> origin


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_migration'),
    ]

    operations = [
<<<<<<< HEAD
        migrations.AlterField(
            model_name='periodicfielddata',
            name='subtype',
            field=models.CharField(choices=[('DATE', 'Date'), ('DECIMAL', 'Number'), ('STRING', 'Text'), ('BOOL', 'Boolean (true/false)')], max_length=16),
        ),
=======
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION program_cycle_business_area_seq() RETURNS trigger 
                    LANGUAGE plpgsql
                    AS $$
                    BEGIN
                        EXECUTE format('CREATE SEQUENCE IF NOT EXISTS program_cycle_business_area_seq_%s', translate(NEW.id::text, '-', '_'));
                        RETURN NEW;
                    END
                    $$;
                """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER program_cycle_business_area_seq AFTER INSERT ON core_businessarea FOR EACH ROW EXECUTE PROCEDURE program_cycle_business_area_seq();
                """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION program_cycle_business_area_for_old_ba(id text)
                    RETURNS text 
                    LANGUAGE plpgsql
                    AS $$
                    BEGIN
                        EXECUTE format('CREATE SEQUENCE IF NOT EXISTS program_cycle_business_area_seq_%s', translate(id::text, '-', '_'));
                        RETURN id;
                    END;
                    $$;
                    SELECT id, program_cycle_business_area_for_old_ba(id::text) AS result FROM core_businessarea;
                """,
        )
>>>>>>> origin
    ]
