# Generated by Django 3.2.25 on 2025-03-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0021_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverymechanismdata",
            name="delivery_mechanism",
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="exclude_household_error",
            field=models.TextField(
                blank=True,
                help_text="Exclusion reason (Targeting level) [sys]",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="excluded_ids",
            field=models.TextField(blank=True, help_text="Targeting level exclusion IDs", null=True),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="exclusion_reason",
            field=models.TextField(blank=True, help_text="Exclusion reason (Targeting level)", null=True),
        ),
    ]
