# Generated by Django 3.2.25 on 2025-04-09 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0018_migration"),
        ("payment", "0025_migration"),
    ]

    operations = [
        migrations.DeleteModel(  # Django doesn't support Rename for proxy models
            name="PendingDeliveryMechanismData",
        ),
        migrations.RenameModel(
            old_name="DeliveryMechanismData",
            new_name="Account",
        ),
        migrations.CreateModel(
            name="PendingAccount",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
                "verbose_name": "Imported Account",
                "verbose_name_plural": "Imported Accounts",
            },
            bases=("payment.account",),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payment.accounttype",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="individual",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="household.individual",
            ),
        ),
    ]
