# Generated by Django 3.2.25 on 2025-06-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0030_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialinstitution",
            name="swift_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
