# Generated by Django 3.2.25 on 2025-08-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0039_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Exchange Rate [sys]",
                max_digits=15,
                null=True,
            ),
        ),
    ]
