# Generated by Django 3.2.25 on 2025-08-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0040_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="signature_hash",
            field=models.CharField(blank=True, editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name="payment",
            name="signature_hash",
            field=models.CharField(blank=True, editable=False, max_length=256),
        ),
    ]
