# Generated by Django 5.2.6 on 2025-10-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0047_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineExchangeRates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "rates",
                    models.JSONField(default=dict, help_text="Offline Exchange Rates"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="paymentplan",
            name="exchange_rate_assigned_offline",
            field=models.BooleanField(default=False, help_text="Exchange Rate assigned offline [sys]"),
        ),
        migrations.AddField(
            model_name="paymentplan",
            name="use_offline_exchange_rate",
            field=models.BooleanField(default=False, help_text="Use Offline Exchange Rate [sys]"),
        ),
    ]
