# Generated by Django 5.2.8 on 2026-01-08 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_migration"),
        ("household", "0029_migration"),
        ("payment", "0048_migration"),
        ("program", "0014_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="collector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collector_payments",
                to="household.individual",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="head_of_household",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="household.individual",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="household",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="household.household"),
        ),
    ]
