# Generated by Django 5.2.11 on 2026-02-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0051_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="sent_to_fsp_date",
            field=models.DateTimeField(
                blank=True, help_text="Sent to FSP on date", null=True
            ),
        ),
    ]
