# Generated by Django 5.2.11 on 2026-03-04 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0054_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="accounttype",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="deliverymechanismconfig",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="financialinstitution",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="financialinstitutionmapping",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="financialserviceprovider",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="financialserviceproviderxlsxtemplate",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="fspnamemapping",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="fspxlsxtemplateperdeliverymechanism",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="paymenthouseholdsnapshot",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="paymentplansplit",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="paymentplansplitpayments",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="paymentverification",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="paymentverificationsummary",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="westernunioninvoice",
            options={
                "ordering": ("id",),
                "verbose_name": "Western Union Invoice",
                "verbose_name_plural": "Western Union Invoices",
            },
        ),
        migrations.AlterModelOptions(
            name="westernunioninvoicepayment",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="westernunionpaymentplanreport",
            options={
                "ordering": ("id",),
                "verbose_name": "Western Union Payment Plan Report",
                "verbose_name_plural": "Western Union Payment Plan Reports",
            },
        ),
    ]
