# Generated by Django 5.2.12 on 2026-03-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0056_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="collector_type",
            field=models.CharField(
                choices=[
                    ("ALTERNATE", "Alternate collector"),
                    ("PRIMARY", "Primary collector"),
                ],
                default="PRIMARY",
                help_text="Collector type using for payment, by default is Primary",
                max_length=120,
            ),
        ),
    ]
