# Generated by Django 5.2.13 on 2026-05-12 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0066_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="source_payment_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Source Payment Plan (applicable for follow-up and top-up Payment Plans)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_plans",
                to="payment.paymentplan",
            ),
        ),
    ]
