# Generated by Django 5.2.13 on 2026-05-18 12:20

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields

import hope.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_migration"),
        ("payment", "0067_migration"),
        ("program", "0019_migration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUpInstruction",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "unicef_id",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                (
                    "background_action_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("XLSX_EXPORTING", "Exporting XLSX"),
                            (
                                "XLSX_IMPORTING_RECONCILIATION",
                                "Importing Reconciliation from XLSX",
                            ),
                            ("XLSX_EXPORT_ERROR", "Error while exporting XLSX"),
                            ("XLSX_IMPORT_ERROR", "Error while importing XLSX"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "business_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.businessarea",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_follow_up_instructions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "export_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Export File",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.filetemp",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="follow_up_instructions",
                        to="program.program",
                    ),
                ),
                (
                    "reconciliation_import_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reconciliation Import File",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.filetemp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Follow Up Instruction",
                "verbose_name_plural": "Follow Up Instructions",
                "ordering": ["created_at"],
            },
            bases=(models.Model, hope.models.utils.AdminUrlMixin),
        ),
        migrations.AddField(
            model_name="paymentplan",
            name="follow_up_instruction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_plans",
                to="payment.followupinstruction",
            ),
        ),
    ]
