# Generated by Django 5.2.14 on 2026-05-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0071_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Regular"),
                    ("TOP_UP", "Top Up"),
                    ("FOLLOW_UP", "Follow Up"),
                    ("TOP_UP_AMENDMENT", "Top Up Amendment"),
                ],
                db_index=True,
                default="REGULAR",
                help_text="Payment Plan type [sys]",
                max_length=20,
            ),
        ),
    ]
