# Generated by Django 5.2.15 on 2026-07-22

from django.db import migrations, models

import hope.models.payment_plan


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0072_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="background_action_status",
            field=models.CharField(
                blank=True,
                choices=hope.models.payment_plan.PaymentPlan.BackgroundActionStatus.get_choices,
                db_index=True,
                default=None,
                help_text="Background Action Status for celery task [sys]",
                max_length=50,
                null=True,
            ),
        ),
    ]
