# Generated by Django 5.2.15 on 2026-08-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0072_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="wallet_qr_photo",
            field=models.ImageField(blank=True, help_text="Photo of the wallet QR code", upload_to=""),
        ),
    ]
