# Generated by Django 5.2.16 on 2026-08-26 12:57

from django.db import migrations


def rename_vision_workflow_permission(apps, schema_editor):
    permission_model = apps.get_model("auth", "Permission")
    permission_model.objects.using(schema_editor.connection.alias).filter(
        content_type__app_label="payment",
        content_type__model="paymentplan",
        codename="pm_send_payment_plan",
    ).update(
        codename="pm_manage_vision_workflow",
        name="Can manage Payment Plan Vision workflow",
    )


def restore_vision_workflow_permission_name(apps, schema_editor):
    permission_model = apps.get_model("auth", "Permission")
    permission_model.objects.using(schema_editor.connection.alias).filter(
        content_type__app_label="payment",
        content_type__model="paymentplan",
        codename="pm_manage_vision_workflow",
    ).update(
        codename="pm_send_payment_plan",
        name="Can send payment plan to Vision",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0073_migration"),
    ]

    operations = [
        migrations.RunPython(
            rename_vision_workflow_permission,
            reverse_code=restore_vision_workflow_permission_name,
        ),
        migrations.AlterModelOptions(
            name="paymentplan",
            options={
                "ordering": ["created_at"],
                "permissions": (
                    (
                        "recalculate_exchange_rate",
                        "Can recalculate USD values based on exchange rate",
                    ),
                    (
                        "restart_preparing_payment_plan",
                        "Can restart Preparing Payment Plans",
                    ),
                    (
                        "restart_exporting_template_for_entitlement",
                        "Can restart Exporting Template for Entitlements",
                    ),
                    (
                        "restart_exporting_payment_plan_list",
                        "Can restart Exporting Payment Plans",
                    ),
                    (
                        "restart_importing_reconciliation_xlsx_file",
                        "Can restart Importing Reconciliation XLSX File",
                    ),
                    (
                        "pm_sync_payment_plan_with_pg",
                        "Can sync payment plan with payment gateway",
                    ),
                    (
                        "pm_manage_vision_workflow",
                        "Can manage Payment Plan Vision workflow",
                    ),
                    (
                        "download_payment_instruction",
                        "Can download payment instruction from payment gateway",
                    ),
                ),
                "verbose_name": "Payment Plan",
            },
        ),
    ]
