# Generated by Django 5.2.17 on 2026-09-11 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0076_migration"),
        ("program", "0020_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="program",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="program.program"),
        ),
        migrations.CreateModel(
            name="TargetPopulation",
            fields=[],
            options={
                "verbose_name": "Target Population",
                "verbose_name_plural": "Target Populations",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("payment.paymentplan",),
        ),
    ]
