# Generated by Django 5.2.17 on 2026-09-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0077_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentplangroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("LOCKED", "Locked"),
                    ("IN_APPROVAL", "In Approval"),
                    ("IN_AUTHORIZATION", "In Authorization"),
                    ("IN_REVIEW", "In Review"),
                    ("ACCEPTED", "Accepted"),
                    ("ABORTED", "Aborted"),
                    ("FINISHED", "Finished"),
                    ("READY_FOR_CLOSURE", "Ready for Closure"),
                    ("CLOSED", "Closed"),
                ],
                db_index=True,
                default="OPEN",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="paymentplangroup",
            name="status_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
