# Generated by Django 5.2.17 on 2026-10-02 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0077_migration"),
        ("program", "0021_disable_biometric_dedup_for_non_cw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="program",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="program.program"),
        ),
    ]
