# Generated by Django 5.2.17 on 2026-09-11 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0077_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetPopulation",
            fields=[],
            options={
                "verbose_name": "Target Population",
                "verbose_name_plural": "Target Populations",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("payment.paymentplan",),
        ),
    ]
