# Generated by Django 5.2.17 on 2026-09-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0078_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="program",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="program.program"),
        ),
    ]
