# Generated by Django 5.2.17 on 2026-10-02 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0082_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentplangroup",
            name="abort_comment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="paymentplangroup",
            name="closure_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentplangroup",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
