# Generated by Django 5.2.17 on 2026-10-07 23:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0086_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentplan",
            name="export_pdf_file_summary",
        ),
    ]
