# Generated by Django 3.2.25 on 2024-11-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundsCommitment',
            fields=[
                ('rec_serial_number', models.IntegerField(primary_key=True, serialize=False)),
                ('business_area', models.CharField(blank=True, max_length=4, null=True)),
                ('funds_commitment_number', models.CharField(blank=True, max_length=10, null=True)),
                ('document_type', models.CharField(blank=True, max_length=2, null=True)),
                ('document_text', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=5, null=True)),
                ('gl_account', models.CharField(blank=True, max_length=10, null=True)),
                ('commitment_amount_local', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('commitment_amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_open_amount_local', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_open_amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vendor_id', models.CharField(blank=True, max_length=10, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('vision_approval', models.CharField(blank=True, max_length=1, null=True)),
                ('document_reference', models.CharField(max_length=16, null=True)),
                ('fc_status', models.CharField(blank=True, max_length=1, null=True)),
                ('funds_commitment_item', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('wbs_element', models.CharField(blank=True, default='', max_length=24, null=True)),
                ('grant_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('sponsor', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('sponsor_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('fund', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('funds_center', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('office', models.ForeignKey(blank=True, help_text='This can be a business office or a business area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businessarea')),
            ],
        ),
        migrations.CreateModel(
            name='DownPayment',
            fields=[
                ('rec_serial_number', models.IntegerField(primary_key=True, serialize=False)),
                ('business_area', models.CharField(max_length=4)),
                ('down_payment_reference', models.CharField(max_length=20)),
                ('document_type', models.CharField(max_length=10)),
                ('consumed_fc_number', models.CharField(max_length=10)),
                ('consumed_fc_item_number', models.CharField(blank=True, max_length=3, null=True)),
                ('total_down_payment_amount_local', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_down_payment_amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=5, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('doc_year', models.IntegerField(blank=True, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=10, null=True)),
                ('doc_item_number', models.CharField(max_length=3, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('office', models.ForeignKey(blank=True, help_text='This can be a business office or a business area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businessarea')),
            ],
        ),
    ]
