# Generated by Django 3.2.25 on 2024-10-13 19:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_migration'),
        ('vision', '0001_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downpayment',
            name='business_area_obj',
        ),
        migrations.RemoveField(
            model_name='downpayment',
            name='business_office_code',
        ),
        migrations.RemoveField(
            model_name='downpayment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fundscommitment',
            name='business_area_obj',
        ),
        migrations.RemoveField(
            model_name='fundscommitment',
            name='business_office_code',
        ),
        migrations.RemoveField(
            model_name='fundscommitment',
            name='id',
        ),
        migrations.AddField(
            model_name='downpayment',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='downpayment',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='downpayment',
            name='office',
            field=models.ForeignKey(blank=True, help_text='This can be a business office or a business area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businessarea'),
        ),
        migrations.AddField(
            model_name='fundscommitment',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='fundscommitment',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='fundscommitment',
            name='office',
            field=models.ForeignKey(blank=True, help_text='This can be a business office or a business area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businessarea'),
        ),
        migrations.AlterField(
            model_name='downpayment',
            name='rec_serial_number',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundscommitment',
            name='grant_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fundscommitment',
            name='rec_serial_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
