# Generated by Django 3.2.25 on 2024-10-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0004_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='downpayment',
            name='consumed_fc_item_number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
