"""Factories for tests."""

from .account import (
    AdminAreaLimitedToFactory,
    PartnerFactory,
    RoleAssignmentFactory,
    RoleFactory,
    UserFactory,
)
from .accountability import CommunicationMessageFactory, FeedbackFactory, FeedbackMessageFactory, SurveyFactory
from .api import APITokenFactory
from .changelog import ChangelogFactory
from .core import (
    BeneficiaryGroupFactory,
    BusinessAreaFactory,
    CountryCodeMapFactory,
    DataCollectingTypeFactory,
    FileTempFactory,
    FlexibleAttributeChoiceFactory,
    FlexibleAttributeFactory,
    FlexibleAttributeForPDUFactory,
    PeriodicFieldDataFactory,
    XLSXKoboTemplateFactory,
)
from .geo import AreaFactory, AreaTypeFactory, CountryFactory
from .grievance import (
    GrievanceTicketFactory,
    TicketComplaintDetailsFactory,
    TicketIndividualDataUpdateDetailsFactory,
    TicketSensitiveDetailsFactory,
)
from .household import (
    DocumentFactory,
    DocumentTypeFactory,
    EntitlementCardFactory,
    HouseholdFactory,
    IndividualFactory,
    IndividualIdentityFactory,
    IndividualRoleInHouseholdFactory,
)
from .payment import (
    AccountFactory,
    AccountTypeFactory,
    ApprovalFactory,
    ApprovalProcessFactory,
    DeliveryMechanismFactory,
    FinancialInstitutionFactory,
    FinancialServiceProviderFactory,
    FinancialServiceProviderXlsxTemplateFactory,
    FspXlsxTemplatePerDeliveryMechanismFactory,
    PaymentFactory,
    PaymentHouseholdSnapshotFactory,
    PaymentPlanFactory,
    PaymentPlanSplitFactory,
    PaymentPlanSupportingDocumentFactory,
    PaymentVerificationFactory,
    PaymentVerificationPlanFactory,
    PaymentVerificationSummaryFactory,
    WesternUnionInvoiceFactory,
    WesternUnionPaymentPlanReportFactory,
)
from .program import ProgramCycleFactory, ProgramFactory
from .registration_data import ImportDataFactory, RegistrationDataImportFactory
from .steficon import RuleCommitFactory, RuleFactory
from .targeting import TargetingCriteriaRuleFactory
from .vision import FundsCommitmentGroupFactory, FundsCommitmentItemFactory

__all__ = [
    "AdminAreaLimitedToFactory",
    "APITokenFactory",
    "AreaFactory",
    "AreaTypeFactory",
    "BeneficiaryGroupFactory",
    "BusinessAreaFactory",
    "ChangelogFactory",
    "CommunicationMessageFactory",
    "CountryFactory",
    "CountryCodeMapFactory",
    "DataCollectingTypeFactory",
    "FileTempFactory",
    "FeedbackFactory",
    "FeedbackMessageFactory",
    "FlexibleAttributeChoiceFactory",
    "FlexibleAttributeFactory",
    "FlexibleAttributeForPDUFactory",
    "GrievanceTicketFactory",
    "TicketComplaintDetailsFactory",
    "TicketIndividualDataUpdateDetailsFactory",
    "TicketSensitiveDetailsFactory",
    "DocumentFactory",
    "DocumentTypeFactory",
    "EntitlementCardFactory",
    "HouseholdFactory",
    "ImportDataFactory",
    "IndividualFactory",
    "IndividualIdentityFactory",
    "IndividualRoleInHouseholdFactory",
    "AccountFactory",
    "AccountTypeFactory",
    "ApprovalFactory",
    "ApprovalProcessFactory",
    "DeliveryMechanismFactory",
    "FinancialInstitutionFactory",
    "FinancialServiceProviderFactory",
    "FspXlsxTemplatePerDeliveryMechanismFactory",
    "FinancialServiceProviderXlsxTemplateFactory",
    "PartnerFactory",
    "PaymentFactory",
    "PaymentHouseholdSnapshotFactory",
    "PaymentPlanFactory",
    "PaymentPlanSupportingDocumentFactory",
    "PaymentPlanSplitFactory",
    "PaymentVerificationFactory",
    "PaymentVerificationPlanFactory",
    "PaymentVerificationSummaryFactory",
    "PeriodicFieldDataFactory",
    "ProgramCycleFactory",
    "ProgramFactory",
    "RegistrationDataImportFactory",
    "RoleAssignmentFactory",
    "RoleFactory",
    "RuleCommitFactory",
    "RuleFactory",
    "TargetingCriteriaRuleFactory",
    "SurveyFactory",
    "UserFactory",
    "WesternUnionInvoiceFactory",
    "WesternUnionPaymentPlanReportFactory",
    "XLSXKoboTemplateFactory",
    "FundsCommitmentGroupFactory",
    "FundsCommitmentItemFactory",
]
