from smart_env import SmartEnv

DEFAULTS = {
    "ALLOWED_IFRAME_DOMAINS": (
        list,
        [
            "https://localhost:3000",
            "https://dev-hope.unitst.org",
            "https://trn-hope.unitst.org",
            "https://stg-hope.unitst.org",
            "https://hope.unitst.org",
        ],
        "",
        "",
        "List of sites where iframe is allowed",
    ),
    "AURORA_SERVER": (str, ""),
    "AURORA_TOKEN": (str, ""),
    "AURORA_USER": (str, ""),
    "DATABASE_URL": (
        str,
        "sqlite://",
        "",
        "",
        "https://django-environ.readthedocs.io/en/latest/types.html#environ-env-db-url",
    ),
    "REP_DATABASE_URL": (
        str,
        "sqlite://",
        "",
        "",
        "https://django-environ.readthedocs.io/en/latest/types.html#environ-env-db-url",
    ),
    "DEBUG": (bool, False),
    "ENV": (str, "dev"),
    "DOMAIN": (str, "localhost:8000"),
    "DJANGO_ALLOWED_HOSTS": (list, []),
    "HCT_MIS_FRONTEND_HOST": (str, ""),
    "ALERTS_EMAIL": (str, "admin@hct-mis.com"),
    "SECRET_KEY": (str, ""),
    "DATA_VOLUME": (str, "/data"),
    "HCT_MIS_UPLOADS_PATH": (str, ""),
    "DEFAULT_FROM_EMAIL": (str, "HOPE Stage <hope@mail.unicef.org>"),
    "EMAIL_BACKEND": (str, "django.core.mail.backends.smtp.EmailBackend"),
    "EMAIL_HOST": (str, ""),
    "EMAIL_PORT": (str, ""),
    "EMAIL_HOST_USER": (str, ""),
    "EMAIL_HOST_PASSWORD": (str, ""),
    "EMAIL_USE_TLS": (bool, True),
    "DEFAULT_EMAIL": (str, ""),
    "MAILJET_API_KEY": (str, ""),
    "MAILJET_SECRET_KEY": (str, ""),
    "CATCH_ALL_EMAIL": (list, []),
    "DEFAULT_EMAIL_DISPLAY": (str, ""),
    "KOBO_URL": (str, "https://kobo-hope-trn.unitst.org"),
    "KOBO_MASTER_API_TOKEN": (str, "KOBO_TOKEN"),
    "KOBO_PROJECT_VIEWS_ID": (str, ""),
    "AZURE_CLIENT_ID": (str, ""),
    "AZURE_CLIENT_SECRET": (str, ""),
    "AZURE_TENANT_KEY": (str, ""),
    "CONSTANCE_REDIS_CONNECTION": (str, "redis://redis:6379/0"),
    "SANCTION_LIST_CC_MAIL": (str, "dfam-cashassistance@unicef.org"),
    "ELASTICSEARCH_HOST": (str, "http://elasticsearch:9200"),
    "ELASTICSEARCH_INDEX_PREFIX": (str, ""),
    "ELASTICSEARCH_SYNONYMS_FILE": (str, "/app/data/synonyms.txt"),
    "RAPID_PRO_URL": (str, "https://rapidpro.io"),
    "POWER_QUERY_DB_ALIAS": (str, "read_only"),
    "ROOT_ACCESS_TOKEN": (str, ""),
    "SENTRY_DSN": (str, ""),
    "SENTRY_URL": (str, ""),
    "SENTRY_ENVIRONMENT": (str, ""),
    "SENTRY_ENABLE_TRACING": (bool, False),
    "CELERY_BROKER_URL": (str, ""),
    "CELERY_RESULT_BACKEND": (str, ""),
    "CELERY_TASK_ALWAYS_EAGER": (bool, False),
    "ADMIN_PANEL_URL": (str, "unicorn"),
    "SESSION_COOKIE_SECURE": (bool, True),
    "SESSION_COOKIE_HTTPONLY": (bool, True),
    "CSRF_COOKIE_HTTPONLY": (bool, True),
    "CSRF_COOKIE_SECURE": (bool, True),
    "SECURE_CONTENT_TYPE_NOSNIFF": (bool, True),
    "SECURE_REFERRER_POLICY": (str, "same-origin"),
    "SESSION_COOKIE_NAME": (str, "sessionid"),
    "SECURE_HSTS_SECONDS": (int, 3600),
    "FLOWER_ADDRESS": (str, "https://hope.unicef.org/flower"),
    "CACHE_ENABLED": (bool, True),
    "CACHE_LOCATION": (str, "redis://redis:6379/1"),
    "CSP_REPORT_URI": (tuple, ("",)),
    "CSP_REPORT_ONLY": (bool, True),
    "CSP_REPORT_PERCENTAGE": (float, 0.1),
    "CSP_DEFAULT_SRC": (tuple, ("'self'",)),
    "CSP_FRAME_ANCESTORS": (tuple, ("'none'",)),
    "CSP_STYLE_SRC": (
        tuple,
        (
            "'self'",
            "'unsafe-inline'",
            "'unsafe-eval'",
        ),
    ),
    "CSP_MANIFEST_SRC": (tuple, ("'self'",)),
    "CSP_SCRIPT_SRC": (
        tuple,
        (
            "'self'",
            "'unsafe-inline'",
            "'unsafe-eval'",
        ),
    ),
    "CSP_IMG_SRC": (
        tuple,
        (
            "'self'",
            "data:",
        ),
    ),
    "CSP_FONT_SRC": (
        tuple,
        (
            "'self'",
            "data:",
            "fonts.gstatic.com",
            "maxcdn.bootstrapcdn.com",
        ),
    ),
    "CSP_MEDIA_SRC": (tuple, ("'self'",)),
    "CSP_CONNECT_SRC": (
        tuple,
        (
            "gov-bam.nr-data.net",
            "cdn.jsdelivr.net",
        ),
    ),
    "EXCHANGE_RATES_API_KEY": (
        str,
        None,
    ),
    "EXCHANGE_RATES_API_URL": (str, "https://uniapis.unicef.org/biapi/v1/exchangerates"),
    "MATOMO_TRACKER_URL": (
        str,
        "https://unisitetracker.unicef.io/",
    ),
    "MATOMO_SCRIPT_URL": (
        str,
        "",
    ),
    "MATOMO_SITE_ID": (
        str,
        "",
    ),
    "SOCIAL_AUTH_REDIRECT_IS_HTTPS": (bool, True),
    "LOG_LEVEL": (str, "ERROR"),
    "GIT_VERSION": (str, "UNKNOWN"),
    "EXCHANGE_RATE_CACHE_EXPIRY": (int, 60 * 60 * 24),
    "USE_DUMMY_EXCHANGE_RATES": (str, "no"),
    "PROFILING": (str, "off"),
    "STATIC_URL": (str, "/static/"),
    "MEDIA_URL": (str, "/media/"),
    "FILE_STORAGE_STATIC": (
        str,
        "django.core.files.storage.FileSystemStorage",
    ),
    "FILE_STORAGE_MEDIA": (
        str,
        "django.core.files.storage.FileSystemStorage",
    ),
    "STORAGE_AZURE_ACCOUNT_NAME": (str, ""),
    "STORAGE_AZURE_ACCOUNT_KEY": (str, ""),
    "MEDIA_STORAGE_AZURE_ACCOUNT_NAME": (str, ""),
    "MEDIA_STORAGE_AZURE_ACCOUNT_KEY": (str, ""),
    "STATIC_STORAGE_AZURE_ACCOUNT_NAME": (str, ""),
    "STATIC_STORAGE_AZURE_ACCOUNT_KEY": (str, ""),
    "STATIC_LOCATION": (str, "static"),
    "MEDIA_LOCATION": (str, "media"),
    "AZURE_ACCOUNT_NAME": (str, ""),
    "AZURE_ACCOUNT_KEY": (str, ""),
    "GDAL_LIBRARY_PATH": (str, None),
    "GEOS_LIBRARY_PATH": (str, None),
    "WESTERN_UNION_FTP_SERVER": (str, ""),
    "WESTERN_UNION_FTP_PORT": (int, 22),
    "WESTERN_UNION_FTP_USERNAME": (str, ""),
    "WESTERN_UNION_FTP_PASSWORD": (str, ""),
}

env = SmartEnv(**DEFAULTS)
