# Generated by Django 3.2.25 on 2025-01-07 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessarea",
            name="is_payment_plan_applicable",
        ),
    ]
