# Generated by Django 3.2.25 on 2025-10-31 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="periodicfielddata",
            name="rounds_covered",
        ),
    ]
