# Generated by Django 5.2.6 on 2025-11-03 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessarea",
            name="partners",
        ),
        migrations.DeleteModel(
            name="BusinessAreaPartnerThrough",
        ),
    ]
