# Generated by Django 5.2.6 on 2025-10-27 14:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0018_migration"),
        ("core", "0013_migration"),
        ("geo", "0005_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodicfielddata",
            name="rounds_covered",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Number of rounds already used in templates and cannot be used in template creation again.",
            ),
        ),
        migrations.AlterField(
            model_name="periodicfielddata",
            name="rounds_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                default=list,
                size=None,
            ),
        ),
        migrations.AddIndex(
            model_name="businessarea",
            index=models.Index(fields=["active"], name="idx_ba_active"),
        ),
        migrations.AddIndex(
            model_name="businessarea",
            index=models.Index(fields=["slug", "active"], name="idx_ba_slug_active"),
        ),
    ]
