# Generated by Django 5.2.6 on 2025-11-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessarea",
            name="rdi_import_xlsx_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
