# Generated by Django 5.2.11 on 2026-03-31 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0017_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="asyncjob",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="asyncjob",
            name="job_name",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="asyncjob",
            name="object_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="asyncjob",
            index=models.Index(fields=["content_type", "object_id", "job_name"], name="core_asyncj_content_0aa63a_idx"),
        ),
    ]
