# Generated by Django 5.2.11 on 2026-03-31 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncRetryJob",
            fields=[],
            options={
                "verbose_name": "Retry Asynchronous Job",
                "verbose_name_plural": "Retry Asynchronous Jobs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.asyncjob",),
        ),
        migrations.RenameIndex(
            model_name="asyncjob",
            new_name="core_asyncj_content_4eb670_idx",
            old_name="core_asyncj_content_0aa63a_idx",
        ),
    ]
