# Generated by Django 5.2.12 on 2026-04-15 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_asyncjob_queue_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicAsyncJob",
            fields=[],
            options={
                "verbose_name": "Periodic Asynchronous Job",
                "verbose_name_plural": "Periodic Asynchronous Jobs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.asyncjob",),
        ),
        migrations.CreateModel(
            name="PeriodicAsyncRetryJob",
            fields=[],
            options={
                "verbose_name": "Periodic Retry Asynchronous Job",
                "verbose_name_plural": "Periodic Retry Asynchronous Jobs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.asyncretryjob",),
        ),
        migrations.AlterModelOptions(
            name="asyncjob",
            options={
                "permissions": (("debug_job", "Can debug background jobs"),),
                "verbose_name": "Asynchronous Job",
                "verbose_name_plural": "Asynchronous Jobs",
            },
        ),
    ]
