# Generated by Django 5.2.13 on 2026-04-15 12:54

import concurrency.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0022_migration"),
        ("program", "0017_migration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicAsyncJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    concurrency.fields.AutoIncVersionField(default=0, help_text="record revision number"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "curr_async_result_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Current (active) AsyncResult is",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "last_async_result_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Latest executed AsyncResult is",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(auto_now_add=True, help_text="Creation date and time"),
                ),
                (
                    "datetime_queued",
                    models.DateTimeField(
                        blank=True,
                        help_text="Queueing date and time",
                        null=True,
                        verbose_name="Queued At",
                    ),
                ),
                (
                    "repeatable",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Indicate if the job can be repeated as-is",
                    ),
                ),
                (
                    "celery_history",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                (
                    "local_status",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "group_key",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Tasks with the same group key will not run in parallel",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("STANDARD_TASK", "Standard Task"),
                            ("JOB_TASK", "Job Task"),
                        ],
                        max_length=50,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("action", models.CharField(blank=True, max_length=500, null=True)),
                ("sentry_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "object_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "job_name",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                ("errors", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Periodic Asynchronous Job",
                "verbose_name_plural": "Periodic Asynchronous Jobs",
            },
        ),
        migrations.AlterModelOptions(
            name="asyncjob",
            options={
                "permissions": (("recover_missing_async_job", "Can recover missing async jobs"),),
                "verbose_name": "Asynchronous Job",
                "verbose_name_plural": "Asynchronous Jobs",
            },
        ),
        migrations.RemoveIndex(
            model_name="asyncjob",
            name="core_asyncj_content_4eb670_idx",
        ),
        migrations.AlterField(
            model_name="asyncjob",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="program.program",
            ),
        ),
        migrations.AddIndex(
            model_name="asyncjob",
            index=models.Index(fields=["content_type", "object_id", "job_name"], name="core_asyncj_content_0aa63a_idx"),
        ),
        migrations.AddField(
            model_name="periodicasyncjob",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="periodicasyncjob",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="periodicasyncjob",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="program.program",
            ),
        ),
        migrations.AddIndex(
            model_name="periodicasyncjob",
            index=models.Index(fields=["content_type", "object_id", "job_name"], name="core_period_content_10aa74_idx"),
        ),
        migrations.CreateModel(
            name="PeriodicAsyncRetryJob",
            fields=[],
            options={
                "verbose_name": "Periodic Retry Asynchronous Job",
                "verbose_name_plural": "Periodic Retry Asynchronous Jobs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.periodicasyncjob",),
        ),
    ]
