# Generated by Django 5.2.13 on 2026-04-30 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_migration"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="asyncjob",
            new_name="core_asyncj_content_4eb670_idx",
            old_name="core_asyncj_content_0aa63a_idx",
        ),
        migrations.RenameIndex(
            model_name="periodicasyncjob",
            new_name="core_period_content_22b5c0_idx",
            old_name="core_period_content_10aa74_idx",
        ),
    ]
