# Generated by Django 5.2.14 on 2026-05-20 10:24

from django.db import migrations, models


def populate_vision_code(apps, schema_editor):
    Currency = apps.get_model("core", "Currency")
    Currency.objects.filter(vision_code="").update(vision_code=models.F("code"))


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="vision_code",
            field=models.CharField(
                blank=True, default="", help_text="The vision system code for this currency", max_length=5
            ),
        ),
        migrations.RunPython(populate_vision_code, migrations.RunPython.noop),
        migrations.AddField(
            model_name="currency",
            name="active",
            field=models.BooleanField(default=True, help_text="Whether this currency is active"),
        ),
        migrations.AddField(
            model_name="currency",
            name="number_of_decimals",
            field=models.SmallIntegerField(default=2, help_text="Number of decimal places for this currency"),
        ),
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="The currency code following the ISO 4217 standard (e.g. USD, EUR)",
                max_length=5,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(help_text="The full name of the currency", max_length=255),
        ),
    ]
