# Generated by Django 5.2.13 on 2026-04-24 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_migration"),
    ]

    operations = []
