# Generated by Django 5.2.14 on 2026-06-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurprisePageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Photo displayed on the surprise page",
                        upload_to="surprise/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Special Page Configuration",
                "verbose_name_plural": "Special Page Configuration",
            },
        ),
    ]
