# Generated by Django 5.2.15 on 2026-06-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessarea",
            name="ingest_source",
            field=models.CharField(
                choices=[
                    ("COUNTRY_WORKSPACE_ONLY", "Country Workspace only"),
                    ("ALL_EXCEPT_COUNTRY_WORKSPACE", "All except Country Workspace"),
                ],
                default="ALL_EXCEPT_COUNTRY_WORKSPACE",
                max_length=64,
            ),
        ),
    ]
