# Generated by Django 5.2.15 on 2026-07-03 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessarea",
            name="kobo_token",
        ),
        migrations.RemoveField(
            model_name="businessarea",
            name="kobo_url",
        ),
        migrations.RemoveField(
            model_name="businessarea",
            name="kobo_username",
        ),
    ]
