# Generated by Django 5.2 on 2026-08-21

from django.db import migrations
import pytz
import timezone_field.fields

UTC_TIMEZONE_NAME = "UTC"


def populate_business_area_timezones(apps, schema_editor):
    BusinessArea = apps.get_model("core", "BusinessArea")

    for business_area in BusinessArea.objects.select_related("office_country").iterator():
        iso_code2 = business_area.office_country.iso_code2 if business_area.office_country_id else None
        country_timezones = pytz.country_timezones.get(iso_code2.upper(), ()) if iso_code2 else ()
        business_area.timezone = country_timezones[0] if country_timezones else UTC_TIMEZONE_NAME
        business_area.save(update_fields=("timezone",))


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessarea",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(blank=True, null=True),
        ),
        migrations.RunPython(populate_business_area_timezones, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="businessarea",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(
                blank=True,
                help_text="Operational IANA timezone. When omitted, it is initialized from the office country or UTC.",
            ),
        ),
    ]
