# Generated by Django 5.2.16 on 2026-07-29 07:48

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={
                "ordering": ["code", "vision_code"],
                "verbose_name_plural": "currencies",
            },
        ),
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="The currency code following the ISO 4217 standard (e.g. USD, EUR)",
                max_length=5,
            ),
        ),
        migrations.AddConstraint(
            model_name="currency",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                condition=models.Q(("active", True)),
                name="unique_code_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="currency",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("vision_code"),
                name="unique_vision_code",
            ),
        ),
    ]
