# Generated by Django 5.2.15 on 2026-07-28 09:00

from django.db import migrations, models

import hope.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filetemp",
            name="file",
            field=models.FileField(max_length=255, upload_to=hope.models.utils.UniqueUploadPath("file_temp")),
        ),
        migrations.AlterField(
            model_name="storagefile",
            name="file",
            field=models.FileField(max_length=255, upload_to=hope.models.utils.UniqueUploadPath("files")),
        ),
        migrations.AlterField(
            model_name="xlsxkobotemplate",
            name="file",
            field=models.FileField(max_length=255, upload_to=hope.models.utils.UniqueUploadPath("xlsx_kobo_template")),
        ),
    ]
