# Generated by Django 5.2.17 on 2026-09-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessarea",
            name="ingest_source",
            field=models.CharField(
                choices=[
                    ("COUNTRY_WORKSPACE_ONLY", "Country Workspace only"),
                    ("ALL_EXCEPT_COUNTRY_WORKSPACE", "All except Country Workspace"),
                ],
                default="ALL_EXCEPT_COUNTRY_WORKSPACE",
                max_length=64,
            ),
        ),
    ]
