# Generated by Django 3.2.25 on 2024-12-11 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grievance", "0005_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketcomplaintdetails",
            name="payment_content_type",
        ),
        migrations.RemoveField(
            model_name="ticketcomplaintdetails",
            name="payment_object_id",
        ),
        migrations.RemoveField(
            model_name="ticketsensitivedetails",
            name="payment_content_type",
        ),
        migrations.RemoveField(
            model_name="ticketsensitivedetails",
            name="payment_object_id",
        ),
    ]
