# Generated by Django 3.2.25 on 2025-08-20 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grievance", "0009_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grievanceticket",
            name="is_original",
        ),
    ]
