# Generated by Django 5.2.8 on 2026-01-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grievance", "0010_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grievanceticket",
            name="category",
            field=models.IntegerField(
                choices=[
                    (8, "Needs Adjudication"),
                    (1, "Payment Verification"),
                    (9, "System Flagging"),
                    (2, "Data Change"),
                    (4, "Grievance Complaint"),
                    (5, "Negative Feedback"),
                    (7, "Positive Feedback"),
                    (6, "Referral"),
                    (3, "Sensitive Grievance"),
                    (10, "Beneficiary"),
                ],
                verbose_name="Category",
            ),
        ),
    ]
