# Generated by Django 5.2.14 on 2026-06-18 00:10

from django.db import migrations, models

import hope.apps.grievance.constants
import hope.apps.grievance.models
import hope.models.payment_verification


class Migration(migrations.Migration):
    dependencies = [
        ("grievance", "0013_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grievanceticket",
            name="category",
            field=models.IntegerField(
                choices=hope.apps.grievance.models.get_grievance_category_choices,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="grievanceticket",
            name="priority",
            field=models.IntegerField(
                choices=hope.apps.grievance.constants.get_priority_choices,
                default=0,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="grievanceticket",
            name="status",
            field=models.IntegerField(
                choices=hope.apps.grievance.models.get_grievance_status_choices,
                default=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="grievanceticket",
            name="urgency",
            field=models.IntegerField(
                choices=hope.apps.grievance.constants.get_urgency_choices,
                default=0,
                verbose_name="Urgency",
            ),
        ),
        migrations.AlterField(
            model_name="ticketpaymentverificationdetails",
            name="new_status",
            field=models.CharField(
                blank=True,
                choices=hope.models.payment_verification.get_status_choices,
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ticketpaymentverificationdetails",
            name="payment_verification_status",
            field=models.CharField(
                choices=hope.models.payment_verification.get_status_choices,
                max_length=50,
            ),
        ),
    ]
