# Generated by Django 3.2.25 on 2024-12-29 09:42

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetemp',
            name='password',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
