# Generated by Django 3.2.25 on 2025-01-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessarea',
            options={'ordering': ['name'], 'permissions': (('can_split', 'Can split BusinessArea'), ('can_send_doap', 'Can send DOAP matrix'), ('can_reset_doap', 'Can force sync DOAP matrix'), ('can_export_doap', 'Can export DOAP matrix'), ('ping_rapidpro', 'Can test RapidPRO connection'), ("execute_sync_rapid_pro", "Can execute RapidPRO sync"))},
        ),
        migrations.AlterModelOptions(
            name='xlsxkobotemplate',
            options={'ordering': ('-created_at',), 'permissions': (('download_last_valid_file', 'Can download the last valid KOBO template'), ('rerun_kobo_import', 'Can rerun a KOBO import'))},
        ),
    ]
