# Generated by Django 3.2.25 on 2025-01-28 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_migration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MigrationStatus",
        ),
    ]
