# Generated by Django 2.2.8 on 2020-09-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='partner',
            field=models.CharField(choices=[('UNHCR', 'UNHCR'), ('WFP', 'WFP'), ('UNICEF', 'UNICEF')], default='UNICEF', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INVITED', max_length=10),
        ),
    ]
