# Generated by Django 2.2.8 on 2020-09-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_for_export',
            field=models.BooleanField(default=True, help_text='Indicating if User can be exported to CashAssist'),
        ),
    ]
