# Generated by Django 2.2.16 on 2021-01-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('name',)},
        ),
    ]
