# Generated by Django 2.2.16 on 2021-07-13 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='subsystem',
            field=models.CharField(choices=[('HOPE', 'HOPE'), ('KOBO', 'Kobo'), ('CA', 'CashAssist')], default='HOPE', max_length=30),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255), django.core.validators.RegexValidator('\\s{2,}', 'Double spaces characters are not allowed.', code='double_spaces_characters_not_allowed', inverse_match=True), django.core.validators.RegexValidator('(^\\s+)|(\\s+$)', 'Leading or trailing spaces characters are not allowed.', code='leading_trailing_spaces_characters_not_allowed', inverse_match=True), django.core.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'subsystem')},
        ),
    ]
