# Generated by Django 2.2.16 on 2021-07-13 08:09

from django.db import migrations


def create_ca_roles(apps, schema_editor):
    Role = apps.get_model('account', 'Role')
    for role in ['Planner/Preparer', 'Approver', 'Authorizer', 'Releaser', 'Card Issuer',
                 'Reconciler', 'Entitlement Formula ', 'Data Exporter', 'Targeting Reader',
                 'Registration Reader Advanced', 'Cash Assistance Reader', ]:
        Role.objects.create(name=role, subsystem='CA')


def remove_ca_roles(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Role = apps.get_model('account', 'Role')
    Role.objects.exclude(subsystem='HOPE').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0025_migration'),
    ]

    operations = [
        migrations.RunPython(create_ca_roles, remove_ca_roles),
    ]
