# Generated by Django 2.2.16 on 2021-07-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='org',
        ),
        migrations.AddField(
            model_name='user',
            name='doap_hash',
            field=models.TextField(default='', editable=False),
        ),
    ]
