# Generated by Django 3.2.15 on 2022-10-08 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_migration'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0041_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='core.businessarea')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('business_area', 'user', 'group')},
            },
        ),
    ]
