# Generated by Django 2.2.8 on 2020-05-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_datahub', '0002_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='alternative_collector',
            field=models.UUIDField(null=True),
        ),
    ]
