# Generated by Django 2.2.8 on 2020-05-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_datahub', '0003_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='alternative_collector',
            new_name='alternative_id',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='focal_point',
            new_name='head_id',
        ),
        migrations.AddField(
            model_name='household',
            name='alternative_first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='alternative_last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='head_first_name',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='head_last_name',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
