# Generated by Django 2.2.8 on 2020-05-28 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mis_datahub', '0004_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='alternative_first_name',
            new_name='alternative_given_name',
        ),
        migrations.RemoveField(
            model_name='household',
            name='alternative_last_name',
        ),
        migrations.RemoveField(
            model_name='household',
            name='head_first_name',
        ),
        migrations.RemoveField(
            model_name='household',
            name='head_last_name',
        ),
        migrations.AddField(
            model_name='household',
            name='alternative_date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='alternative_estimated_date_of_birth',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='alternative_family_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='alternative_full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='alternative_middle_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='alternative_phone_number',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='alternative_phone_number_alternative',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='alternative_sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='head_date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='head_estimated_date_of_birth',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='head_family_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='head_full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='head_given_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='head_middle_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='head_phone_number',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='head_phone_number_alternative',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='head_sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='phone_number_alternative',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
