# Generated by Django 2.2.8 on 2020-06-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_datahub', '0006_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='country',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
