# Generated by Django 2.2.8 on 2020-07-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_datahub', '0009_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='unicef_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='unicef_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mis_id', models.UUIDField()),
                ('number', models.CharField(max_length=255, null=True)),
                ('individual_mis_id', models.UUIDField(null=True)),
                ('type', models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('DRIVERS_LICENSE', "Driver's License"), ('NATIONAL_ID', 'National ID'), ('NATIONAL_PASSPORT', 'National Passport'), ('ELECTORAL_CARD', 'Electoral Card'), ('OTHER', 'Other')], max_length=50)),
                ('country', models.CharField(max_length=3, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis_datahub.Session')),
            ],
            options={
                'unique_together': {('type', 'number')},
            },
        ),
    ]
