# Generated by Django 2.2.8 on 2020-07-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_datahub', '0010_migration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('type', 'country', 'number')},
        ),
    ]
