# Generated by Django 2.2.8 on 2020-07-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_datahub', '0011_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='individual_data_needed',
            field=models.BooleanField(default=False),
        ),
    ]
