# Generated by Django 2.2.16 on 2021-07-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_datahub', '0033_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('READY', 'Ready'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EMPTY', 'Empty'), ('IGNORED', 'Ignored'), ('LOADING', 'Loading'), ('ERRORED', 'Errored')], max_length=11),
        ),
    ]
