# Generated by Django 2.2.26 on 2022-02-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_datahub', '0035_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='ca_hash_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='ca_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
