# Generated by Django 3.2.15 on 2022-10-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_datahub', '0042_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), (None, None)], max_length=255, null=True),
        ),
    ]
