# Generated by Django 3.2.24 on 2024-03-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_datahub', '0049_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='individual_data_needed',
        ),
    ]
