# Generated by Django 3.2.25 on 2025-01-31 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0002_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="ca_hash_id",
        ),
        migrations.RemoveField(
            model_name="program",
            name="ca_id",
        ),
    ]
