# Generated by Django 3.2.24 on 2024-02-16 05:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def assign_service_providers_based_on_ca_id(apps, schema_editor):
    CashPlan = apps.get_model("program", "CashPlan")
    ServiceProvider = apps.get_model("payment", "ServiceProvider")
    for cash_plan in CashPlan.objects.all():
        if not cash_plan.assistance_through:
            continue
        sp = ServiceProvider.objects.filter(ca_id=cash_plan.assistance_through).first()
        if not sp:
            continue
        cash_plan.service_provider = sp
        cash_plan.save()


def empty_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    replaces = [('program', '0025_migration'), ('program', '0026_migration'), ('program', '0027_migration'), ('program', '0028_migration'), ('program', '0029_migration'), ('program', '0030_migration')]

    dependencies = [
        ('payment', '0010_migration_squashed_0029_migration'),
        ('geo', '0004_migration'),
        ('program', '0024_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashplan',
            name='service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_plans', to='payment.serviceprovider'),
        ),
        migrations.RunPython(assign_service_providers_based_on_ca_id, empty_reverse),
        migrations.AlterField(
            model_name='cashplan',
            name='total_delivered_quantity',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='total_entitled_quantity',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='total_entitled_quantity_revised',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='total_undelivered_quantity',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='ca_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='admin_areas_new',
            field=models.ManyToManyField(blank=True, related_name='programs', to='geo.Area'),
        ),
        migrations.AlterField(
            model_name='program',
            name='frequency_of_payments',
            field=models.CharField(choices=[('ONE_OFF', 'One-off'), ('REGULAR', 'Regular')], max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('FINISHED', 'Finished')], db_index=True, max_length=10),
        ),
    ]
