# Generated by Django 3.2.13 on 2022-06-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0033_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='admin_areas_new',
            new_name='admin_areas',
        ),
    ]
