# Generated by Django 3.2.23 on 2024-02-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0042_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'permissions': [('enroll_beneficiaries', 'Can enroll beneficiaries')],
                     'verbose_name': 'Programme'},
        ),
    ]
