# Generated by Django 3.2.25 on 2024-08-16 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_migration'),
        ('program', '0049_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='data_collecting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='core.datacollectingtype'),
        ),
    ]
