# Generated by Django 3.2.25 on 2024-10-20 15:47

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0053_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryGroup',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('group_label', models.CharField(max_length=255)),
                ('group_label_plural', models.CharField(max_length=255)),
                ('member_label', models.CharField(max_length=255)),
                ('member_label_plural', models.CharField(max_length=255)),
                ('master_detail', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Beneficiary Group',
                'verbose_name_plural': 'Beneficiary Groups',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='program',
            name='beneficiary_group',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='program.beneficiarygroup'),
        ),
    ]
