# Generated by Django 3.2.25 on 2024-11-22 08:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_migration'),
        ('targeting', '0002_migration'),
        ('steficon', '0001_migration'),
        ('payment', '0001_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vulnerability_score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=3, help_text='Written by Steficon', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='build_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('BUILDING', 'Building'), ('FAILED', 'Failed'), ('OK', 'Ok')], db_index=True, default='PENDING', max_length=256),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='built_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='excluded_ids',
            field=models.TextField(blank=True, help_text='Targeting level exclusion'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='internal_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='steficon_rule_targeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_plans_target', to='steficon.rulecommit'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='steficon_targeting_applied_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='storage_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.storagefile'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='targeting_criteria',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_plans', to='targeting.targetingcriteria'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='vulnerability_score_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Written by a tool such as Corticon.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='vulnerability_score_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Written by a tool such as Corticon.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255), django.core.validators.RegexValidator('\\s{2,}', 'Double spaces characters are not allowed.', code='double_spaces_characters_not_allowed', inverse_match=True), django.core.validators.RegexValidator('(^\\s+)|(\\s+$)', 'Leading or trailing spaces characters are not allowed.', code='leading_trailing_spaces_characters_not_allowed', inverse_match=True), django.core.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='status',
            field=django_fsm.FSMField(choices=[('TP_OPEN', 'Open'), ('TP_LOCKED', 'Locked'), ('PROCESSING', 'Processing'), ('STEFICON_WAIT', 'Steficon Wait'), ('STEFICON_RUN', 'Steficon Run'), ('STEFICON_COMPLETED', 'Steficon Completed'), ('STEFICON_ERROR', 'Steficon Error'), ('DRAFT', 'Draft'), ('PREPARING', 'Preparing'), ('OPEN', 'Open'), ('LOCKED', 'Locked'), ('LOCKED_FSP', 'Locked FSP'), ('IN_APPROVAL', 'In Approval'), ('IN_AUTHORIZATION', 'In Authorization'), ('IN_REVIEW', 'In Review'), ('ACCEPTED', 'Accepted'), ('FINISHED', 'Finished')], db_index=True, default='OPEN', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='paymentplan',
            constraint=models.CheckConstraint(check=models.Q(('steficon_rule_targeting__rule__type', 'TARGETING'), ('steficon_rule_targeting__isnull', True), _connector='OR'), name='check_steficon_rule_targeting_type_tp_level'),
        ),
        migrations.AddConstraint(
            model_name='paymentplan',
            constraint=models.CheckConstraint(check=models.Q(('steficon_rule__rule__type', 'PAYMENT_PLAN'), ('steficon_rule__isnull', True), _connector='OR'), name='check_steficon_rule_targeting_type_pp_level'),
        ),
    ]
