# Generated by Django 3.2.25 on 2024-10-23 23:15
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_migration"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="payment_plan_and_household",
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_removed", False), ("is_cash_assist", False)),
                fields=("parent", "household"),
                name="payment_plan_and_household",
            ),
        ),
    ]
