# Generated by Django 3.2.25 on 2024-12-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashPlan',
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
