# Generated by Django 3.2.25 on 2025-02-13 12:10

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0015_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentplan",
            name="target_population",
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("TP_OPEN", "Open"),
                    ("TP_LOCKED", "Locked"),
                    ("PROCESSING", "Processing"),
                    ("STEFICON_WAIT", "Steficon Wait"),
                    ("STEFICON_RUN", "Steficon Run"),
                    ("STEFICON_COMPLETED", "Steficon Completed"),
                    ("STEFICON_ERROR", "Steficon Error"),
                    ("DRAFT", "Draft"),
                    ("PREPARING", "Preparing"),
                    ("OPEN", "Open"),
                    ("LOCKED", "Locked"),
                    ("LOCKED_FSP", "Locked FSP"),
                    ("IN_APPROVAL", "In Approval"),
                    ("IN_AUTHORIZATION", "In Authorization"),
                    ("IN_REVIEW", "In Review"),
                    ("ACCEPTED", "Accepted"),
                    ("FINISHED", "Finished"),
                ],
                db_index=True,
                default="TP_OPEN",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="targeting_criteria",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_plan",
                to="targeting.targetingcriteria",
            ),
        ),
    ]
