# Generated by Django 3.2.25 on 2025-05-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialinstitution',
            name='code',
        ),
        migrations.RenameField(
            model_name="financialinstitution",
            old_name="description",
            new_name="name",
        ),
        migrations.AlterField(
            model_name='financialinstitution',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='financialinstitution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
