# Generated by Django 3.2.25 on 2025-02-27 20:04

from django.db import migrations, models


# set account type and store only field_name (phone) / value in .data json
def migrate_delivery_mechanism_data(apps, schema_editor):
    AccountType = apps.get_model("payment", "AccountType")
    DeliveryMechanismData = apps.get_model("payment", "DeliveryMechanismData")

    AccountType.objects.get_or_create(
        key="mobile",
        defaults=dict(
            label="Mobile",
            unique_fields=["number"] # TODO fields???
        )
    )

    for dmd in DeliveryMechanismData.objects.filter(
        delivery_mechanism__code="mobile_money"
    ).iterator(chunk_size=1000):
        data = dmd.data
        dmd.data = {
            "service_provider_code": data.get("service_provider_code__mobile_money", ""),
            "number": data.get("delivery_phone_number__mobile_money", ""),
            "provider": data.get("provider__mobile_money", ""),
        } # TODO field names???


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_migration'),
    ]

    operations = [
        migrations.RunPython(migrate_delivery_mechanism_data, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='deliverymechanismdata',
            name='delivery_mechanism',
        ),
    ]
