# Generated by Django 3.2.25 on 2025-03-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='payment_gateway_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
