# Generated by Django 3.2.25 on 2025-04-04 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_migration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliverymechanismdata',
            name='unique_individual_delivery_mechanism',
        ),
    ]
