# Generated by Django 3.2.25 on 2025-04-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_migration'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='deliverymechanismdata',
                    name='unique_individual_delivery_mechanism',
                )
            ]
        )
    ]
