# Generated by Django 3.2.25 on 2025-04-15 10:49

import uuid

import django.db.models.deletion
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstitutionMapping',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=30)),
                ('financial_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.financialinstitution')),
                ('financial_service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.financialserviceprovider')),
            ],
            options={
                'unique_together': {('financial_service_provider', 'financial_institution')},
            },
        ),
    ]
