# Generated by Django 3.2.25 on 2025-04-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_migration'),
    ]

    operations = [
    ]
