# Generated by Django 3.2.25 on 2025-05-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinstitution',
            name='code',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.RunSQL(
            sql="""
                CREATE SEQUENCE financialinstitution_code_seq OWNED BY payment_financialinstitution.code;
                ALTER TABLE payment_financialinstitution
                ALTER COLUMN code SET DEFAULT nextval('financialinstitution_code_seq');
            """,
            reverse_sql="""
                ALTER TABLE payment_financialinstitution
                ALTER COLUMN code DROP DEFAULT;
                DROP SEQUENCE IF EXISTS financialinstitution_code_seq;
            """
        ),
        migrations.CreateModel(
            name='PaymentDataCollector',
            fields=[
            ],
            options={
                'verbose_name': 'Payment Data Collector',
                'verbose_name_plural': 'Payment Data Collectors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payment.account',),
        ),
        migrations.RenameField(
            model_name="financialinstitution",
            old_name="description",
            new_name="name",
        ),
        migrations.AlterField(
            model_name='financialinstitution',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
