# Generated by Django 3.2.25 on 2025-06-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDataCollector',
            fields=[
            ],
            options={
                'verbose_name': 'Payment Data Collector',
                'verbose_name_plural': 'Payment Data Collectors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payment.account',),
        ),
        migrations.RemoveConstraint(
            model_name='paymentplan',
            name='name_unique_per_program',
        ),
        migrations.AlterField(
            model_name='deliverymechanismperpaymentplan',
            name='payment_plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_mechanism_per_payment_plan', to='payment.paymentplan'),
        ),
    ]
