# Generated by Django 3.2.25 on 2025-07-31 10:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0038_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True, decimal_places=8, help_text="Exchange Rate [sys]", max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="total_delivered_quantity",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                help_text="Total Delivered Quantity [sys]",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal(0))],
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="total_delivered_quantity_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total Delivered Quantity USD [sys]",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal(0))],
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="total_entitled_quantity",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                help_text="Total Entitled Quantity [sys]",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal(0))],
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="total_entitled_quantity_revised",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                help_text="Total Entitled Quantity Revised [sys]",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal(0))],
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="total_entitled_quantity_revised_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total Entitled Quantity Revised USD [sys]",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal(0))],
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="total_entitled_quantity_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total Entitled Quantity USD [sys]",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal(0))],
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="total_undelivered_quantity",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                help_text="Total Undelivered Quantity [sys]",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal(0))],
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="total_undelivered_quantity_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total Undelivered Quantity USD [sys]",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal(0))],
            ),
        ),
    ]
