# Generated by Django 3.2.18 on 2023-05-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0097_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='exclusion_reason',
            field=models.TextField(blank=True),
        ),
    ]
