# Generated by Django 3.2.25 on 2024-05-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0129_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplansplit',
            name='split_type',
            field=models.CharField(choices=[('BY_RECORDS', 'By Records'), ('BY_COLLECTOR', 'By Collector'), ('BY_ADMIN_AREA1', 'By Admin Area 1'), ('BY_ADMIN_AREA2', 'By Admin Area 2'), ('BY_ADMIN_AREA3', 'By Admin Area 3')], max_length=24),
        ),
    ]
