# Generated by Django 3.2.25 on 2024-08-09 13:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0137_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialserviceproviderxlsxtemplate',
            name='flex_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, size=None),
        ),
    ]
