# Generated by Django 3.2.25 on 2024-09-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0143_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymechanismdata',
            name='delivery_mechanism_choice',
            field=models.CharField(blank=True, choices=[('Cardless cash withdrawal', 'Cardless cash withdrawal'), ('Cash', 'Cash'), ('Cash by FSP', 'Cash by FSP'), ('Cheque', 'Cheque'), ('Deposit to Card', 'Deposit to Card'), ('Mobile Money', 'Mobile Money'), ('Pre-paid card', 'Pre-paid card'), ('Referral', 'Referral'), ('Transfer', 'Transfer'), ('Transfer to Account', 'Transfer to Account'), ('Voucher', 'Voucher'), ('ATM Card', 'ATM Card'), ('Cash over the counter', 'Cash over the counter'), ('Transfer to Digital Wallet', 'Transfer to Digital Wallet')], max_length=255, null=True, verbose_name='Delivery Mechanism'),
        ),
    ]
