# Generated by Django 3.2.25 on 2024-10-23 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0053_migration'),
        ('payment', '0147_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymechanismdata',
            name='delivery_mechanism_choice',
        ),
        migrations.RemoveField(
            model_name='deliverymechanismperpaymentplan',
            name='delivery_mechanism_choice',
        ),
        migrations.RemoveField(
            model_name='financialserviceprovider',
            name='delivery_mechanisms_choices',
        ),
        migrations.RemoveField(
            model_name='fspxlsxtemplateperdeliverymechanism',
            name='delivery_mechanism_choice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='delivery_type_choice',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='program',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='delivery_type_choice',
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='program_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='program.programcycle'),
        ),
    ]
