# Generated by Django 2.2.8 on 2020-09-30 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('household', '0025_migration'),
        ('core', '0005_migration'),
        ('payment', '0016_migration'),
        ('grievance', '0003_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceTicket',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_modified', models.DateTimeField(blank=True, help_text='Date this ticket was most recently changed.', verbose_name='Modified')),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Reopened'), (3, 'Resolved'), (4, 'Closed'), (5, 'Duplicate')], default=1, verbose_name='Status')),
                ('type', models.IntegerField(choices=[(1, 'Payment Verification'), (2, 'Data Change'), (3, 'Sensitive Grievance'), (4, 'Grievance Complaint'), (5, 'Negative Feedback'), (6, 'Referral'), (7, 'Positive Feedback'), (8, 'Deduplication')], verbose_name='Type')),
                ('description', models.TextField(blank=True, help_text='The content of the customers query.', null=True, verbose_name='Description')),
                ('admin', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=250)),
                ('consent', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('business_area', models.ForeignKey(on_delete='tickets', to='core.BusinessArea')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketPaymentVerificationDetails',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_details', to='payment.PaymentVerification')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_verification_details', to='grievance.GrievanceTicket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketNotes',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='The content of the customers query.', null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_notes', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketDeduplicationDetails',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicated_individuals', models.ManyToManyField(related_name='duplicates_ticket_details', to='household.Individual')),
                ('individual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_details', to='household.Individual')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deduplication_details', to='grievance.GrievanceTicket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
