# Generated by Django 2.2.16 on 2020-11-03 15:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0029_migration'),
        ('grievance', '0004_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketIndividualDataUpdateDetails',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('individual_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('individual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_data_update_ticket_details', to='household.Individual')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_data_update_ticket_details', to='grievance.GrievanceTicket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
