# Generated by Django 2.2.16 on 2020-11-03 20:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0029_migration'),
        ('grievance', '0005_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAddIndividualDetails',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('individual_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('household', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_individual_ticket_details', to='household.Household')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='add_individual_ticket_details', to='grievance.GrievanceTicket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
