# Generated by Django 2.2.16 on 2020-11-10 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grievance', '0011_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketNote',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='The content of the customers query.', verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_notes', to='grievance.GrievanceTicket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TicketNotes',
        ),
    ]
