# Generated by Django 2.2.16 on 2020-12-16 17:36

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_migration'),
        ('grievance', '0015_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPaymentVerificationDetails',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_verification_status', models.CharField(choices=[('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('NOT_RECEIVED', 'NOT RECEIVED'), ('RECEIVED_WITH_ISSUES', 'RECEIVED WITH ISSUES')], max_length=50)),
                ('payment_verifications', models.ManyToManyField(related_name='ticket_details', to='payment.PaymentVerification')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_verification_ticket_details', to='grievance.GrievanceTicket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
