# Generated by Django 3.2.12 on 2022-04-07 13:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0044_migration'),
        ('grievance', '0037_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpaymentverificationdetails',
            name='approve_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketpaymentverificationdetails',
            name='new_received_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='ticketpaymentverificationdetails',
            name='new_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('NOT_RECEIVED', 'NOT RECEIVED'), ('RECEIVED_WITH_ISSUES', 'RECEIVED WITH ISSUES')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticketpaymentverificationdetails',
            name='payment_verification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_detail', to='payment.paymentverification'),
        ),
    ]
