# Generated by Django 3.2.12 on 2022-04-28 11:19
# Generated by Django 3.2.12 on 2022-05-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0039_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketneedsadjudicationdetails',
            name='score_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ticketneedsadjudicationdetails',
            name='score_min',
            field=models.FloatField(default=0.0),
        ),
    ]
