# Generated by Django 3.2.12 on 2022-04-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0104_migration'),
        ('grievance', '0039_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketneedsadjudicationdetails',
            name='is_multiple_duplicates_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketneedsadjudicationdetails',
            name='possible_duplicates',
            field=models.ManyToManyField(related_name='ticket_duplicates', to='household.Individual'),
        ),
        migrations.AddField(
            model_name='ticketneedsadjudicationdetails',
            name='selected_individuals',
            field=models.ManyToManyField(related_name='ticket_selected', to='household.Individual'),
        ),
    ]
