# Generated by Django 3.2.12 on 2022-05-11 13:05

from django.db import migrations

from hct_mis_api.apps.grievance.common import _get_min_max_score


def update_min_max_score(apps, schema_editor):
    TicketNeedsAdjudicationDetails = apps.get_model("grievance", "TicketNeedsAdjudicationDetails")

    db_alias = schema_editor.connection.alias
    tickets = TicketNeedsAdjudicationDetails.objects.using(db_alias).all()
    for ticket in tickets:
        score_min, score_max = _get_min_max_score(ticket.extra_data.get("golden_records", []))

        ticket.score_min = score_min
        ticket.score_max = score_max

    TicketNeedsAdjudicationDetails.objects.bulk_update(tickets, ["score_min", "score_max"])


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0040_migration'),
    ]

    operations = [
        migrations.RunPython(update_min_max_score, migrations.RunPython.noop),
    ]
