# Generated by Django 3.2.13 on 2022-07-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievance", "0049_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="grievanceticket",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "Critical"), (2, "High"), (3, "Medium"), (4, "Low")], default=4, verbose_name="Priority"
            ),
        ),
    ]
