<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-08-22 13:25

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.2.15 on 2023-01-12 18:41

from django.db import migrations, models
>>>>>>> origin


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("account", "0038_migration"),
        ("grievance", "0053_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="grievanceticket",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "High"), (2, "Medium"), (3, "Low")], default=3, verbose_name="Priority"
            ),
        ),
        migrations.AddField(
            model_name="grievanceticket",
            name="urgency",
            field=models.IntegerField(
                choices=[(1, "Very urgent"), (2, "Urgent"), (3, "Not urgent")], default=3, verbose_name="Urgency"
            ),
        ),
        migrations.AddField(
            model_name="grievanceticket",
            name="partner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="account.partner"
            ),
=======
        ('grievance', '0053_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievanceticket',
            name='category',
            field=models.IntegerField(choices=[(8, 'Needs Adjudication'), (1, 'Payment Verification'), (9, 'System Flagging'), (2, 'Data Change'), (4, 'Grievance Complaint'), (5, 'Negative Feedback'), (7, 'Positive Feedback'), (6, 'Referral'), (3, 'Sensitive Grievance')], verbose_name='Category'),
>>>>>>> origin
        ),
    ]
