<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-08-25 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid
=======
# Generated by Django 3.2.15 on 2023-02-27 13:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
>>>>>>> origin


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("program", "0034_migration"),
        ("grievance", "0054_migration"),
=======
        ('grievance', '0054_migration'),
>>>>>>> origin
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="grievanceticket",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grievanceticket",
            name="programme",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="program.program"
            ),
        ),
        migrations.CreateModel(
            name="GrievanceDocument",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
                ("file_size", models.IntegerField(null=True)),
                ("content_type", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grievance_ticket",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_documents",
                        to="grievance.grievanceticket",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
=======
            model_name='ticketpaymentverificationdetails',
            name='old_received_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
>>>>>>> origin
        ),
    ]
