# Generated by Django 3.2.18 on 2023-04-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('grievance', '0056_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomplaintdetails',
            name='payment_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ticketcomplaintdetails',
            name='payment_object_id',
            field=models.UUIDField(default=None),
        ),
    ]
