# Generated by Django 3.2.22 on 2023-12-05 08:57

from django.db import migrations, models
from django.utils.timezone import now


def populate_migrated_at(apps, schema_editor):
    GrievanceTicket = apps.get_model("grievance", "GrievanceTicket")

    GrievanceTicket.objects.filter(migrated_at__isnull=True, is_migration_handled=True).update(migrated_at=now())


class Migration(migrations.Migration):

    dependencies = [
        ("grievance", "0064_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="grievanceticket",
            name="migrated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(populate_migrated_at, migrations.RunPython.noop),
    ]
