# Generated by Django 3.2.22 on 2023-11-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0066_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketneedsadjudicationdetails',
            name='is_cross_area',
            field=models.BooleanField(default=False),
        ),
    ]
