# Generated by Django 2.2.8 on 2020-07-12 15:46

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sanction_list', '0004_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionListIndividualAliasName',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sanctionlistindividual',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='sanctionlistindividual',
            name='second_year_of_birth',
        ),
        migrations.RemoveField(
            model_name='sanctionlistindividual',
            name='year_of_birth',
        ),
        migrations.AddField(
            model_name='sanctionlistindividual',
            name='fourth_name',
            field=models.CharField(blank=True, default='', max_length=85),
        ),
        migrations.AddField(
            model_name='sanctionlistindividual',
            name='second_date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sanctionlistindividual',
            name='alias_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanction_list.SanctionListIndividualAliasName'),
        ),
        migrations.AddField(
            model_name='sanctionlistindividualaliasname',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_names', to='sanction_list.SanctionListIndividual'),
        ),
    ]
