# Generated by Django 2.2.8 on 2020-07-12 17:59

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sanction_list', '0005_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanctionlistindividual',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='sanctionlistindividual',
            name='second_date_of_birth',
        ),
        migrations.CreateModel(
            name='SanctionListIndividualDateOfBirth',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates_of_birth', to='sanction_list.SanctionListIndividual')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
