# Generated by Django 2.2.16 on 2020-12-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanction_list', '0007_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanctionlistindividual',
            name='alias_name',
        ),
    ]
