# Generated by Django 3.2.13 on 2022-06-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanction_list', '0010_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanctionlistindividualcountries',
            name='country',
        ),
    ]
