# Generated by Django 3.2.13 on 2022-06-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanction_list', '0012_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanctionlistindividualnationalities',
            name='nationality',
        ),
    ]
