# Generated by Django 3.2.25 on 2025-01-15 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0007_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="individual",
            options={
                "permissions": (("update_individual_iban", "Can update individual IBAN"),),
                "verbose_name": "Individual",
            },
        ),
    ]
