# Generated by Django 3.2.25 on 2025-08-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0024_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualroleinhousehold",
            name="role",
            field=models.CharField(
                choices=[("ALTERNATE", "Alternate collector"), ("PRIMARY", "Primary collector")], max_length=255
            ),
        ),
    ]
