# Generated by Django 5.2.6 on 2025-10-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0027_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualroleinhousehold",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ALTERNATE", "Alternate collector"),
                    ("PRIMARY", "Primary collector"),
                ],
                max_length=255,
            ),
        ),
    ]
