# Generated by Django 5.2.8 on 2026-01-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0029_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="originating_id",
            field=models.CharField(
                blank=True,
                help_text="A unified external reference with a fixed-length source prefix (XLS, KOB, or AUR) \n                     and a source-specific identifier separated by '#', e.g., 'KOB#321#123'.",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="originating_id",
            field=models.CharField(
                blank=True,
                help_text="A unified external reference with a fixed-length source prefix (XLS, KOB, or AUR) \n                     and a source-specific identifier separated by '#', e.g., 'KOB#321#123'.",
                max_length=150,
                null=True,
            ),
        ),
    ]
