# Generated by Django 5.2.11 on 2026-02-27 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0030_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="household",
            name="collision_flag",
        ),
    ]
