# Generated by Django 5.2.12 on 2026-03-16 18:01

import django.db.models.deletion
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_migration"),
        ("geo", "0006_migration"),
        ("household", "0033_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Facility or Organization name", max_length=255
                    ),
                ),
                (
                    "admin_area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin area",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facilities",
                        to="geo.area",
                    ),
                ),
                (
                    "business_area",
                    models.ForeignKey(
                        help_text="Business area",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="core.businessarea",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Facilities",
                "ordering": ("business_area", "name"),
            },
        ),
        migrations.AddField(
            model_name="household",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="households",
                to="household.facility",
            ),
        ),
        migrations.AddConstraint(
            model_name="facility",
            constraint=models.UniqueConstraint(
                fields=("name", "business_area"),
                name="unique_for_ba_name_and_admin_area",
            ),
        ),
    ]
