# Generated by Django 5.2.11 on 2026-03-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_migration"),
        ("geo", "0006_migration"),
        ("household", "0035_migration"),
        ("program", "0017_migration"),
        ("registration_data", "0012_migration"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="household",
            index=models.Index(
                condition=models.Q(("is_removed", False)),
                fields=["program", "rdi_merge_status"],
                name="idx_hh_prog_rdi_status",
            ),
        ),
        migrations.AddIndex(
            model_name="individual",
            index=models.Index(
                condition=models.Q(("is_removed", False)),
                fields=["program", "rdi_merge_status"],
                name="idx_hi_prog_rdi_status",
            ),
        ),
    ]
