# Generated by Django 5.2.12 on 2026-04-07 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0036_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="household",
            options={
                "ordering": ("id",),
                "permissions": (
                    ("can_withdrawn", "Can withdrawn Household"),
                    ("sanity_check", "Sanity check Household"),
                    ("gdpr_remove", "GDPR remove Household data"),
                    ("logical_delete", "Logical delete Household"),
                    ("can_see_linked_objects", "Can see Linked Objects"),
                    ("reset_sync_date", "Can reset sync date"),
                    ("reset_sync_date_single", "Can reset sync date single"),
                ),
                "verbose_name": "Household",
            },
        ),
        migrations.AlterModelOptions(
            name="individual",
            options={
                "ordering": ("id",),
                "permissions": (
                    ("update_individual_iban", "Can update individual IBAN"),
                    ("individual_sanity_check", "Can check individual sanity"),
                    ("can_see_linked_objects", "Can see linked objects"),
                    ("reset_sync_date", "Can reset sync date"),
                    ("reset_sync_date_single", "Can reset sync date single"),
                ),
                "verbose_name": "Individual",
            },
        ),
        migrations.AlterModelOptions(
            name="individualroleinhousehold",
            options={
                "ordering": ("-role", "id"),
                "permissions": (
                    ("reset_sync_date", "Can reset sync date"),
                    ("reset_sync_date_single", "Can reset sync date single"),
                ),
            },
        ),
    ]
