# Generated by Django 5.2.12 on 2026-04-16 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0038_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="individual",
            name="family_name_local",
            field=models.CharField(
                blank=True,
                db_collation="und-ci-det",
                db_index=True,
                help_text="Last local name of the Beneficiary",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="full_name_local",
            field=models.CharField(
                blank=True,
                db_collation="und-ci-det",
                db_index=True,
                help_text="Full Local Name of the Beneficiary",
                max_length=500,
                null=True,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="given_name_local",
            field=models.CharField(
                blank=True,
                db_collation="und-ci-det",
                db_index=True,
                help_text="First local name of the Beneficiary",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="middle_name_local",
            field=models.CharField(
                blank=True,
                db_collation="und-ci-det",
                db_index=True,
                help_text="Middle local name of the Beneficiary",
                max_length=150,
                null=True,
            ),
        ),
    ]
