# Generated by Django 5.2.12 on 2026-04-19 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0038_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="individual",
            name="family_name_local",
            field=models.CharField(
                blank=True,
                db_collation="und-ci-det",
                db_index=True,
                help_text="Last local name of the Beneficiary",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="full_name_local",
            field=models.CharField(
                blank=True,
                db_collation="und-ci-det",
                db_index=True,
                help_text="Full Local Name of the Beneficiary",
                max_length=500,
                null=True,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="given_name_local",
            field=models.CharField(
                blank=True,
                db_collation="und-ci-det",
                db_index=True,
                help_text="First local name of the Beneficiary",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="middle_name_local",
            field=models.CharField(
                blank=True,
                db_collation="und-ci-det",
                db_index=True,
                help_text="Middle local name of the Beneficiary",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="family_name",
            field=models.CharField(
                blank=True,
                db_collation="und-ci-det",
                db_index=True,
                help_text="Last name of the Beneficiary",
                max_length=85,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_name",
                        message="Only ASCII letters, spaces, hyphens, and apostrophes are allowed.",
                        regex="^[A-Za-z]+(?:[ '-][A-Za-z]+)*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="full_name",
            field=models.CharField(
                db_collation="und-ci-det",
                db_index=True,
                help_text="Full Name of the Beneficiary",
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        code="invalid_name",
                        message="Only ASCII letters, spaces, hyphens, and apostrophes are allowed.",
                        regex="^[A-Za-z]+(?:[ '-][A-Za-z]+)*$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="given_name",
            field=models.CharField(
                blank=True,
                db_collation="und-ci-det",
                db_index=True,
                help_text="First name of the Beneficiary",
                max_length=85,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_name",
                        message="Only ASCII letters, spaces, hyphens, and apostrophes are allowed.",
                        regex="^[A-Za-z]+(?:[ '-][A-Za-z]+)*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="middle_name",
            field=models.CharField(
                blank=True,
                db_collation="und-ci-det",
                db_index=True,
                help_text="Middle name of the Beneficiary",
                max_length=85,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_name",
                        message="Only ASCII letters, spaces, hyphens, and apostrophes are allowed.",
                        regex="^[A-Za-z]+(?:[ '-][A-Za-z]+)*$",
                    )
                ],
            ),
        ),
    ]
