# Generated by Django 5.2.13 on 2026-04-16 21:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0006_migration"),
        ("household", "0038_migration"),
        ("program", "0017_migration"),
        ("registration_data", "0013_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="program.program",
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="child_hoh",
            field=models.BooleanField(blank=True, help_text="Child headed household flag", null=True),
        ),
        migrations.AlterField(
            model_name="household",
            name="collect_type",
            field=models.CharField(
                blank=True,
                choices=[("STANDARD", "Standard"), ("SINGLE", "Single")],
                default="STANDARD",
                help_text="Household collect type [sys]",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="consent",
            field=models.BooleanField(blank=True, help_text="Household consent", null=True),
        ),
        migrations.AlterField(
            model_name="household",
            name="consent_sharing",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("GOVERNMENT_PARTNER", "Government partners"),
                    ("HUMANITARIAN_PARTNER", "Humanitarian partners"),
                    ("PRIVATE_PARTNER", "Private partners"),
                    ("UNICEF", "UNICEF"),
                ],
                default="",
                help_text="Household consent sharing",
                max_length=63,
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="fchild_hoh",
            field=models.BooleanField(blank=True, help_text="Female child headed household flag", null=True),
        ),
        migrations.AlterField(
            model_name="household",
            name="head_of_household",
            field=models.OneToOneField(
                blank=True,
                help_text="Household head of household",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="heading_household",
                to="household.individual",
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="household_collection",
            field=models.ForeignKey(
                blank=True,
                help_text="Collection of household representations",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="households",
                to="household.householdcollection",
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="kobo_submission_uuid",
            field=models.UUIDField(
                blank=True,
                default=None,
                help_text="Household Kobo submission uuid [sys]",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="org_enumerator",
            field=models.CharField(
                blank=True,
                choices=[("", "None"), ("PARTNER", "Partner"), ("UNICEF", "UNICEF")],
                default="",
                help_text="Household org enumerator [sys]",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="registration_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("COMMUNITY", "Community-level Registration"),
                    ("HH_REGISTRATION", "Household Registration"),
                ],
                default="",
                help_text="Household registration method [sys]",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="returnee",
            field=models.BooleanField(blank=True, help_text="Household returnee status", null=True),
        ),
        migrations.AlterField(
            model_name="individual",
            name="enrolled_in_nutrition_programme",
            field=models.BooleanField(blank=True, help_text="Enrolled in nutrition program [sys]", null=True),
        ),
        migrations.AlterField(
            model_name="individual",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("DIVORCED", "Divorced"),
                    ("MARRIED", "Married"),
                    ("SEPARATED", "Separated"),
                    ("SINGLE", "Single"),
                    ("WIDOWED", "Widowed"),
                ],
                db_index=True,
                default="",
                help_text="Beneficiary marital status",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="phone_no_alternative_valid",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                help_text="Beneficiary phone number alternative valid [sys]",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="phone_no_valid",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                help_text="Beneficiary phone number valid [sys]",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="pregnant",
            field=models.BooleanField(blank=True, help_text="Pregnant status", null=True),
        ),
        migrations.AlterField(
            model_name="individualidentity",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.country",
            ),
        ),
        migrations.AlterField(
            model_name="xlsxupdatefile",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="program.program",
            ),
        ),
        migrations.AlterField(
            model_name="xlsxupdatefile",
            name="rdi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="registration_data.registrationdataimport",
            ),
        ),
        migrations.AlterField(
            model_name="xlsxupdatefile",
            name="xlsx_match_columns",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
