# Generated by Django 5.2.13 on 2026-05-04 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0040_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="household",
            name="currency_old",
        ),
    ]
