# Generated by Django 5.2.13 on 2026-05-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0040_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="household",
            name="residence_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("IDP", "Displaced  |  Internally Displaced People"),
                    (
                        "IDP_RETURNEE",
                        "Displaced  |  Internally Displaced People Returnee",
                    ),
                    ("REFUGEE", "Displaced  |  Refugee / Asylum Seeker"),
                    ("OTHERS_OF_CONCERN", "Displaced  |  Others of Concern"),
                    ("HOST", "Non-displaced  |   Host"),
                    ("NON_HOST", "Non-displaced  |   Non-host"),
                    ("RETURNEE", "Displaced  |   Refugee Returnee"),
                ],
                help_text="Household residence status",
                max_length=254,
            ),
        ),
    ]
