# Generated by Django 5.2.14 on 2026-06-17 23:58

from django.db import migrations, models
import multiselectfield.db.fields

import hope.apps.core.languages
import hope.apps.household.const
import hope.models.document
import hope.models.entitlement_card
import hope.models.household
import hope.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0044_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="rdi_merge_status",
            field=models.CharField(
                blank=True,
                choices=hope.models.utils.get_merge_status_choices,
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                blank=True,
                choices=hope.models.document.get_document_status_choices,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="entitlementcard",
            name="status",
            field=models.CharField(
                choices=hope.models.entitlement_card.get_status_choices,
                default="ACTIVE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="collect_type",
            field=models.CharField(
                blank=True,
                choices=hope.models.household.Household.CollectType.get_choices,
                default="STANDARD",
                help_text="Household collect type [sys]",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="consent_sharing",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=hope.apps.household.const.get_data_sharing_choices,
                default="",
                help_text="Household consent sharing",
                max_length=63,
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="org_enumerator",
            field=models.CharField(
                blank=True,
                choices=hope.apps.household.const.get_org_enumerator_choices,
                default="",
                help_text="Household org enumerator [sys]",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="rdi_merge_status",
            field=models.CharField(
                blank=True,
                choices=hope.models.utils.get_merge_status_choices,
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="registration_method",
            field=models.CharField(
                blank=True,
                choices=hope.apps.household.const.get_registration_method_choices,
                default="",
                help_text="Household registration method [sys]",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="residence_status",
            field=models.CharField(
                blank=True,
                choices=hope.apps.household.const.get_residence_status_choices,
                help_text="Household residence status",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="biometric_deduplication_batch_status",
            field=models.CharField(
                choices=hope.apps.household.const.get_deduplication_batch_status_choices,
                db_index=True,
                default="NOT_PROCESSED",
                help_text="Deduplication batch status [sys]",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="biometric_deduplication_golden_record_status",
            field=models.CharField(
                choices=hope.apps.household.const.get_deduplication_golden_record_status_choices,
                db_index=True,
                default="NOT_PROCESSED",
                help_text="Deduplication golden record status [sys]",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="comms_disability",
            field=models.CharField(
                blank=True,
                choices=hope.apps.household.const.get_severity_of_disability_choices,
                help_text="Comms disability",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="deduplication_batch_status",
            field=models.CharField(
                choices=hope.apps.household.const.get_deduplication_batch_status_choices,
                db_index=True,
                default="UNIQUE_IN_BATCH",
                help_text="Deduplication batch status [sys]",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="deduplication_golden_record_status",
            field=models.CharField(
                choices=hope.apps.household.const.get_deduplication_golden_record_status_choices,
                db_index=True,
                default="UNIQUE",
                help_text="Deduplication golden record status [sys]",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="disability",
            field=models.CharField(
                choices=hope.apps.household.const.get_disability_choices,
                default="not disabled",
                help_text="Disability status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="hearing_disability",
            field=models.CharField(
                blank=True,
                choices=hope.apps.household.const.get_severity_of_disability_choices,
                help_text="Hearing disability",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=hope.apps.household.const.get_marital_status_choices,
                db_index=True,
                default="",
                help_text="Beneficiary marital status",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="memory_disability",
            field=models.CharField(
                blank=True,
                choices=hope.apps.household.const.get_severity_of_disability_choices,
                help_text="Memory disability",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="observed_disability",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=hope.apps.household.const.get_observed_disability_choices,
                default="NONE",
                help_text="Observed disability status",
                max_length=58,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="physical_disability",
            field=models.CharField(
                blank=True,
                choices=hope.apps.household.const.get_severity_of_disability_choices,
                help_text="Physical disability",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=hope.apps.core.languages.Languages.get_tuple,
                help_text="Preferred language",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="rdi_merge_status",
            field=models.CharField(
                blank=True,
                choices=hope.models.utils.get_merge_status_choices,
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="relationship",
            field=models.CharField(
                blank=True,
                choices=hope.apps.household.const.get_relationship_choices,
                help_text="This represents the MEMBER relationship. can be blank\n            as well if household is null!",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="seeing_disability",
            field=models.CharField(
                blank=True,
                choices=hope.apps.household.const.get_severity_of_disability_choices,
                help_text="Seeing disability",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="selfcare_disability",
            field=models.CharField(
                blank=True,
                choices=hope.apps.household.const.get_severity_of_disability_choices,
                help_text="Selfcare disability",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="sex",
            field=models.CharField(
                choices=hope.apps.household.const.get_sex_choices,
                db_index=True,
                help_text="Beneficiary gender",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="work_status",
            field=models.CharField(
                blank=True,
                choices=hope.apps.household.const.get_work_status_choices,
                default="NOT_PROVIDED",
                help_text="Work status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="individualidentity",
            name="rdi_merge_status",
            field=models.CharField(
                blank=True,
                choices=hope.models.utils.get_merge_status_choices,
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="individualroleinhousehold",
            name="rdi_merge_status",
            field=models.CharField(
                blank=True,
                choices=hope.models.utils.get_merge_status_choices,
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="individualroleinhousehold",
            name="role",
            field=models.CharField(
                blank=True,
                choices=hope.apps.household.const.get_role_choices,
                max_length=255,
            ),
        ),
    ]
