# Generated by Django 5.2.15 on 2026-07-06 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0045_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individual",
            name="blockchain_name",
        ),
        migrations.RemoveField(
            model_name="individual",
            name="wallet_address",
        ),
        migrations.RemoveField(
            model_name="individual",
            name="wallet_name",
        ),
    ]
