# Generated by Django 5.2.16 on 2026-08-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_migration"),
        ("household", "0047_migration"),
        ("program", "0021_disable_biometric_dedup_for_non_cw"),
        ("registration_data", "0017_migration"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="individual",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_removed", False),
                    ("withdrawn", False),
                    ("country_workspace_id__isnull", False),
                ),
                fields=("business_area", "country_workspace_id"),
                name="country_workspace_id_ind_unique_constraint",
            ),
        ),
    ]
