# Generated by opencode on 2026-09-14

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("household", "0048_migration"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="individual",
            index=models.Index(
                fields=["program_registration_id"],
                name="idx_individual_program_reg_id",
            ),
        ),
    ]
