# Generated by Django 5.2.17 on 2026-09-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0049_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individual",
            name="program_registration_id",
            field=models.CharField(
                blank=True,
                db_collation="und-ci-det",
                db_index=True,
                help_text="Beneficiary Program Registration ID [sys]",
                max_length=100,
                null=True,
                verbose_name="Beneficiary Program Registration Id",
            ),
        ),
    ]
