trigger: none
pr: none
resources:
  pipelines:
  - pipeline: ci-hope
    source: '[CI] HOPE'
    trigger: 
      branches:
      - feature/payment-module


variables:
  # ========================================================================
  #                          Mandatory variables 
  # ========================================================================
  Kubernetes.serviceConnection: "aks-hope-pm-azure-devops-sa"
  Kubernetes.namespace: "ictd-hope-pm"
  Docker.backend.repository: "hope-backend"
  Docker.frontend.repository: "hope-frontend"
  Docker.registry: "uniappsakshopedev.azurecr.io"

stages:
  - stage: deploy
    displayName: DEPLOY
    jobs:
      - job: deploy_hope
        pool:
          vmImage: 'ubuntu-latest'
        displayName: "[HOPE] Deployment"
        steps:
          - task: HelmDeploy@0
            displayName: "Update Chart dependencies"
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: $(Kubernetes.serviceConnection)     
              command: package
              updatedependency: true
              chartPath: '**/deployment/hope'
          - task: HelmDeploy@0
            displayName: "DEPLOY"
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: $(Kubernetes.serviceConnection)
              namespace: $(Kubernetes.namespace)
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '**/deployment/hope'
              releaseName: 'hope-pm'
              install: true
              waitForExecution: false
              failOnStderr: false
              valueFile: '**/deployment/aks-values.yaml'
              arguments: "--timeout 600s"
              overrideValues: "
                global.env=staging,\
                global.storageClass=default,\
                backend.image=$(Docker.registry)/$(Docker.backend.repository):$(Build.SourceVersion),\
                celery.image=$(Docker.registry)/$(Docker.backend.repository):$(Build.SourceVersion),\
                backend.config.STORAGE_AZURE_ACCOUNT_NAME=$(STORAGE_AZURE_ACCOUNT_NAME),\
                backend.config.AZURE_CLIENT_ID=$(AZURE_CLIENT_ID),\
                backend.secret.SECRET_KEY=$(SECRET_KEY),\
                backend.secret.STORAGE_AZURE_ACCOUNT_KEY=$(STORAGE_AZURE_ACCOUNT_KEY),\
                backend.secret.AZURE_CLIENT_SECRET=$(AZURE_CLIENT_SECRET),\
                backend.secret.AZURE_TENANT_KEY=$(AZURE_TENANT_KEY),\
                backend.secret.SENTRY_DSN=$(SENTRY_DSN),\
                backend.secret.EMAIL_HOST=$(EMAIL_HOST),\
                backend.secret.EMAIL_USE_TLS=$(EMAIL_USE_TLS),\
                backend.secret.KOBO_API_URL=$(KOBO_API_URL),\
                backend.secret.KOBO_MASTER_API_TOKEN=$(KOBO_MASTER_API_TOKEN),\
                backend.secret.EXCHANGE_RATES_API_KEY=$(EXCHANGE_RATES_API_KEY),\
                frontend.secret.SENTRY_FRONTEND_DSN=$(SENTRY_FRONTEND_DSN),\
                backend.secret.DATAMART_USER=$(DATAMART_USER),\
                backend.secret.DATAMART_PASSWORD=$(DATAMART_PASSWORD),\
                backend.secret.DATAMART_URL=$(DATAMART_URL),\
                backend.secret.KOBO_KF_URL=$(KOBO_KF_URL),\
                backend.secret.KOBO_KC_URL=$(KOBO_KC_URL),\
                backend.secret.KOBO_APP_API_TOKEN=$(KOBO_APP_API_TOKEN),\
                backend.secret.ROOT_ACCESS_TOKEN=$(ROOT_ACCESS_TOKEN),\
                frontend.image=$(Docker.registry)/$(Docker.frontend.repository):$(Build.SourceVersion),\
                ingress.host=pm-hope-dev.unitst.org,\
                ingress.tls=true,\
                postgresql.postgresqlPassword=hope-pm,\
                registrationdatahubpostgresql.postgresqlPassword=hope-pm,\
                cashassistdatahubpostgresql.postgresqlPassword=hope-pm,\
                celeryflower.secret.FLOWER_BASIC_AUTH=$(FLOWER_BASIC_AUTH),\
                backend.replicaCount=1,\
                celery.replicaCount=1,"
