# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot


snapshots = Snapshot()

snapshots["TestSchema::test_get_areas_tree 1"] = {
    "data": {
        "allAreasTree": [
            {
                "areas": [
                    {
                        "areas": [
                            {"areas": [], "level": 3, "name": "Aromatnenska", "pCode": "UA0102003"},
                            {"areas": [], "level": 3, "name": "Bakhchysaraiska", "pCode": "UA0102005"},
                            {"areas": [], "level": 3, "name": "Dolynnenska", "pCode": "UA0102015"},
                            {"areas": [], "level": 3, "name": "Holubynska", "pCode": "UA0102013"},
                            {"areas": [], "level": 3, "name": "Kashtanivska", "pCode": "UA0102025"},
                            {"areas": [], "level": 3, "name": "Krasnomatska", "pCode": "UA0102027"},
                            {"areas": [], "level": 3, "name": "Kuibyshevska", "pCode": "UA0102029"},
                            {"areas": [], "level": 3, "name": "Pishchanivska", "pCode": "UA0102033"},
                            {"areas": [], "level": 3, "name": "Plodivska", "pCode": "UA0102035"},
                            {"areas": [], "level": 3, "name": "Poshtivska", "pCode": "UA0102037"},
                            {"areas": [], "level": 3, "name": "Sevastopilska", "pCode": "UA0102000"},
                            {"areas": [], "level": 3, "name": "Skalystivska", "pCode": "UA0102039"},
                            {"areas": [], "level": 3, "name": "Tabachnenska", "pCode": "UA0102041"},
                            {"areas": [], "level": 3, "name": "Tinystivska", "pCode": "UA0102045"},
                            {"areas": [], "level": 3, "name": "Uhlivska", "pCode": "UA0102047"},
                            {"areas": [], "level": 3, "name": "Verkhorichenska", "pCode": "UA0102009"},
                            {"areas": [], "level": 3, "name": "Vilinska", "pCode": "UA0102011"},
                            {"areas": [], "level": 3, "name": "Zaliznychnenska", "pCode": "UA0102017"},
                            {"areas": [], "level": 3, "name": "Zelenivska", "pCode": "UA0102019"},
                        ],
                        "level": 2,
                        "name": "Bakhchysaraiskyi",
                        "pCode": "UA0102",
                    },
                    {
                        "areas": [
                            {"areas": [], "level": 3, "name": "Aromatnivska", "pCode": "UA0104001"},
                            {"areas": [], "level": 3, "name": "Bahativska", "pCode": "UA0104003"},
                            {"areas": [], "level": 3, "name": "Bilohirska", "pCode": "UA0104005"},
                            {"areas": [], "level": 3, "name": "Chkalovska", "pCode": "UA0104071"},
                            {"areas": [], "level": 3, "name": "Chornopilska", "pCode": "UA0104073"},
                            {"areas": [], "level": 3, "name": "Drofynska", "pCode": "UA0104011"},
                            {"areas": [], "level": 3, "name": "Ivanivska", "pCode": "UA0104027"},
                            {"areas": [], "level": 3, "name": "Izobilnenska", "pCode": "UA0104029"},
                            {"areas": [], "level": 3, "name": "Kistochkivska", "pCode": "UA0104031"},
                            {"areas": [], "level": 3, "name": "Krymskorozivska", "pCode": "UA0104033"},
                            {"areas": [], "level": 3, "name": "Krynychnenska", "pCode": "UA0104035"},
                            {"areas": [], "level": 3, "name": "Kurska", "pCode": "UA0104037"},
                            {"areas": [], "level": 3, "name": "Lystvynska", "pCode": "UA0104039"},
                            {"areas": [], "level": 3, "name": "Melnychna", "pCode": "UA0104041"},
                            {"areas": [], "level": 3, "name": "Michurinska", "pCode": "UA0104047"},
                            {"areas": [], "level": 3, "name": "Muromska", "pCode": "UA0104049"},
                            {"areas": [], "level": 3, "name": "Mykhailivska", "pCode": "UA0104045"},
                            {"areas": [], "level": 3, "name": "Mytrofanivska", "pCode": "UA0104043"},
                            {"areas": [], "level": 3, "name": "Novohryhorivska", "pCode": "UA0104053"},
                            {"areas": [], "level": 3, "name": "Novozhylivska", "pCode": "UA0104055"},
                            {"areas": [], "level": 3, "name": "Nyzhnohirska", "pCode": "UA0104051"},
                            {"areas": [], "level": 3, "name": "Okhotska", "pCode": "UA0104059"},
                            {"areas": [], "level": 3, "name": "Omelianivska", "pCode": "UA0104057"},
                            {"areas": [], "level": 3, "name": "Pshenychnenska", "pCode": "UA0104061"},
                            {"areas": [], "level": 3, "name": "Rusakivska", "pCode": "UA0104063"},
                            {"areas": [], "level": 3, "name": "Sadova", "pCode": "UA0104065"},
                            {"areas": [], "level": 3, "name": "Tsvitochnenska", "pCode": "UA0104069"},
                            {"areas": [], "level": 3, "name": "Uvarivska", "pCode": "UA0104067"},
                            {"areas": [], "level": 3, "name": "Vasylivska", "pCode": "UA0104007"},
                            {"areas": [], "level": 3, "name": "Vyshenska", "pCode": "UA0104009"},
                            {"areas": [], "level": 3, "name": "Yakymivska", "pCode": "UA0104075"},
                            {"areas": [], "level": 3, "name": "Zelenohirska", "pCode": "UA0104017"},
                            {"areas": [], "level": 3, "name": "Zemlianychnenska", "pCode": "UA0104019"},
                            {"areas": [], "level": 3, "name": "Zheliabovska", "pCode": "UA0104013"},
                            {"areas": [], "level": 3, "name": "Zhemchuzhynska", "pCode": "UA0104015"},
                            {"areas": [], "level": 3, "name": "Zorkinska", "pCode": "UA0104023"},
                            {"areas": [], "level": 3, "name": "Zuiska", "pCode": "UA0104025"},
                            {"areas": [], "level": 3, "name": "Zybynska", "pCode": "UA0104021"},
                        ],
                        "level": 2,
                        "name": "Bilohirskyi",
                        "pCode": "UA0104",
                    },
                    {
                        "areas": [
                            {"areas": [], "level": 3, "name": "Azovska", "pCode": "UA0106001"},
                            {"areas": [], "level": 3, "name": "Chaikynska", "pCode": "UA0106051"},
                            {"areas": [], "level": 3, "name": "Dzhankoiska", "pCode": "UA0106005"},
                            {"areas": [], "level": 3, "name": "Izumrudnivska", "pCode": "UA0106013"},
                            {"areas": [], "level": 3, "name": "Kindrativska", "pCode": "UA0106015"},
                            {"areas": [], "level": 3, "name": "Krymkivska", "pCode": "UA0106017"},
                            {"areas": [], "level": 3, "name": "Lobanivska", "pCode": "UA0106019"},
                            {"areas": [], "level": 3, "name": "Luhanska", "pCode": "UA0106021"},
                            {"areas": [], "level": 3, "name": "Maiska", "pCode": "UA0106023"},
                            {"areas": [], "level": 3, "name": "Maslivska", "pCode": "UA0106025"},
                            {"areas": [], "level": 3, "name": "Medvedivska", "pCode": "UA0106027"},
                            {"areas": [], "level": 3, "name": "Myrnivska", "pCode": "UA0106029"},
                            {"areas": [], "level": 3, "name": "Novokrymska", "pCode": "UA0106031"},
                            {"areas": [], "level": 3, "name": "Pakharivska", "pCode": "UA0106033"},
                            {"areas": [], "level": 3, "name": "Pobiednenska", "pCode": "UA0106035"},
                            {"areas": [], "level": 3, "name": "Prostornenska", "pCode": "UA0106037"},
                            {"areas": [], "level": 3, "name": "Roshchynska", "pCode": "UA0106041"},
                            {"areas": [], "level": 3, "name": "Rozkishnenska", "pCode": "UA0106039"},
                            {"areas": [], "level": 3, "name": "Stalnenska", "pCode": "UA0106045"},
                            {"areas": [], "level": 3, "name": "Svitlivska", "pCode": "UA0106043"},
                            {"areas": [], "level": 3, "name": "Tabachnenska", "pCode": "UA0106047"},
                            {"areas": [], "level": 3, "name": "Tsilynna", "pCode": "UA0106049"},
                            {"areas": [], "level": 3, "name": "Vilnenska", "pCode": "UA0106003"},
                            {"areas": [], "level": 3, "name": "Yarkivska", "pCode": "UA0106053"},
                            {"areas": [], "level": 3, "name": "Yarkopolenska", "pCode": "UA0106055"},
                            {"areas": [], "level": 3, "name": "Yasnopolianska", "pCode": "UA0106057"},
                            {"areas": [], "level": 3, "name": "Yermakivska", "pCode": "UA0106007"},
                            {"areas": [], "level": 3, "name": "Zarichnenska", "pCode": "UA0106011"},
                            {"areas": [], "level": 3, "name": "Zavito-Leninska", "pCode": "UA0106009"},
                        ],
                        "level": 2,
                        "name": "Dzhankoiskyi",
                        "pCode": "UA0106",
                    },
                    {"areas": [], "level": 2, "name": "Feodosiiskyi", "pCode": "UA0118"},
                    {
                        "areas": [
                            {"areas": [], "level": 3, "name": "Baherivska", "pCode": "UA0110001"},
                            {"areas": [], "level": 3, "name": "Batalnenska", "pCode": "UA0110003"},
                            {"areas": [], "level": 3, "name": "Bielinska", "pCode": "UA0110005"},
                            {"areas": [], "level": 3, "name": "Cheliadinivska", "pCode": "UA0110051"},
                            {"areas": [], "level": 3, "name": "Chystopilska", "pCode": "UA0110053"},
                            {"areas": [], "level": 3, "name": "Hlazivska", "pCode": "UA0110011"},
                            {"areas": [], "level": 3, "name": "Hornostaivska", "pCode": "UA0110013"},
                            {"areas": [], "level": 3, "name": "Illichivska", "pCode": "UA0110017"},
                            {"areas": [], "level": 3, "name": "Kalynivska", "pCode": "UA0110019"},
                            {"areas": [], "level": 3, "name": "Kerchenska", "pCode": "UA0110021"},
                            {"areas": [], "level": 3, "name": "Kirovska", "pCode": "UA0110023"},
                            {"areas": [], "level": 3, "name": "Krasnohirska", "pCode": "UA0110025"},
                            {"areas": [], "level": 3, "name": "Leninska", "pCode": "UA0110027"},
                            {"areas": [], "level": 3, "name": "Leninska", "pCode": "UA0110029"},
                            {"areas": [], "level": 3, "name": "Luhivska", "pCode": "UA0110031"},
                            {"areas": [], "level": 3, "name": "Marfivska", "pCode": "UA0110035"},
                            {"areas": [], "level": 3, "name": "Marivska", "pCode": "UA0110033"},
                            {"areas": [], "level": 3, "name": "Mysivska", "pCode": "UA0110037"},
                            {"areas": [], "level": 3, "name": "Novomykolaivska", "pCode": "UA0110039"},
                            {"areas": [], "level": 3, "name": "Oktiabrska", "pCode": "UA0110041"},
                            {"areas": [], "level": 3, "name": "Ostaninska", "pCode": "UA0110043"},
                            {"areas": [], "level": 3, "name": "Pryozernivska", "pCode": "UA0110045"},
                            {"areas": [], "level": 3, "name": "Semysotska", "pCode": "UA0110047"},
                            {"areas": [], "level": 3, "name": "Shcholkinska", "pCode": "UA0110055"},
                            {"areas": [], "level": 3, "name": "Uvarivska", "pCode": "UA0110049"},
                            {"areas": [], "level": 3, "name": "Voikovska", "pCode": "UA0110009"},
                            {"areas": [], "level": 3, "name": "Vynohradnenska", "pCode": "UA0110007"},
                            {"areas": [], "level": 3, "name": "Zavitnenska", "pCode": "UA0110015"},
                        ],
                        "level": 2,
                        "name": "Kerchynskyi",
                        "pCode": "UA0110",
                    },
                    {
                        "areas": [
                            {"areas": [], "level": 3, "name": "Abrykosivska", "pCode": "UA0112001"},
                            {"areas": [], "level": 3, "name": "Amurska", "pCode": "UA0112003"},
                            {"areas": [], "level": 3, "name": "Chernovska", "pCode": "UA0112071"},
                            {"areas": [], "level": 3, "name": "Hryshynska", "pCode": "UA0112011"},
                            {"areas": [], "level": 3, "name": "Hvardiiska", "pCode": "UA0112009"},
                            {"areas": [], "level": 3, "name": "Kalininska", "pCode": "UA0112015"},
                            {"areas": [], "level": 3, "name": "Kalininska", "pCode": "UA0112017"},
                            {"areas": [], "level": 3, "name": "Klepyninska", "pCode": "UA0112019"},
                            {"areas": [], "level": 3, "name": "Kolodiazianska", "pCode": "UA0112021"},
                            {"areas": [], "level": 3, "name": "Kormivska", "pCode": "UA0112023"},
                            {"areas": [], "level": 3, "name": "Kotelnykivska", "pCode": "UA0112025"},
                            {"areas": [], "level": 3, "name": "Krasnohvardiiska", "pCode": "UA0112027"},
                            {"areas": [], "level": 3, "name": "Krasnoznamianska", "pCode": "UA0112029"},
                            {"areas": [], "level": 3, "name": "Krestianivska", "pCode": "UA0112031"},
                            {"areas": [], "level": 3, "name": "Leninska", "pCode": "UA0112033"},
                            {"areas": [], "level": 3, "name": "Marianivska", "pCode": "UA0112035"},
                            {"areas": [], "level": 3, "name": "Naidonivska", "pCode": "UA0112037"},
                            {"areas": [], "level": 3, "name": "Novopokrovska", "pCode": "UA0112039"},
                            {"areas": [], "level": 3, "name": "Oktiabrska", "pCode": "UA0112041"},
                            {"areas": [], "level": 3, "name": "Oktiabrska", "pCode": "UA0112043"},
                            {"areas": [], "level": 3, "name": "Oleksandrivska", "pCode": "UA0112045"},
                            {"areas": [], "level": 3, "name": "Oleksiivska", "pCode": "UA0112047"},
                            {"areas": [], "level": 3, "name": "Ostrovska", "pCode": "UA0112049"},
                            {"areas": [], "level": 3, "name": "Pervomaiska", "pCode": "UA0112053"},
                            {"areas": [], "level": 3, "name": "Petrivska", "pCode": "UA0112055"},
                            {"areas": [], "level": 3, "name": "Piatykhatska", "pCode": "UA0112051"},
                            {"areas": [], "level": 3, "name": "Poltavska", "pCode": "UA0112057"},
                            {"areas": [], "level": 3, "name": "Pravdivska", "pCode": "UA0112059"},
                            {"areas": [], "level": 3, "name": "Rivnivska", "pCode": "UA0112061"},
                            {"areas": [], "level": 3, "name": "Sarybashivska", "pCode": "UA0112063"},
                            {"areas": [], "level": 3, "name": "Stakhanovska", "pCode": "UA0112065"},
                            {"areas": [], "level": 3, "name": "Stepnivska", "pCode": "UA0112067"},
                            {"areas": [], "level": 3, "name": "Susaninska", "pCode": "UA0112069"},
                            {"areas": [], "level": 3, "name": "Voikovska", "pCode": "UA0112005"},
                            {"areas": [], "level": 3, "name": "Voskhodnenska", "pCode": "UA0112007"},
                            {"areas": [], "level": 3, "name": "Yantarnenska", "pCode": "UA0112073"},
                            {"areas": [], "level": 3, "name": "Zernivska", "pCode": "UA0112013"},
                        ],
                        "level": 2,
                        "name": "Kurmanskyi",
                        "pCode": "UA0112",
                    },
                    {
                        "areas": [
                            {"areas": [], "level": 3, "name": "Armianska", "pCode": "UA0114001"},
                            {"areas": [], "level": 3, "name": "Berezivska", "pCode": "UA0114003"},
                            {"areas": [], "level": 3, "name": "Botanichna", "pCode": "UA0114005"},
                            {"areas": [], "level": 3, "name": "Bratska", "pCode": "UA0114007"},
                            {"areas": [], "level": 3, "name": "Chernyshivska", "pCode": "UA0114053"},
                            {"areas": [], "level": 3, "name": "Filativska", "pCode": "UA0114051"},
                            {"areas": [], "level": 3, "name": "Illinska", "pCode": "UA0114015"},
                            {"areas": [], "level": 3, "name": "Ishunska", "pCode": "UA0114017"},
                            {"areas": [], "level": 3, "name": "Kovylnivska", "pCode": "UA0114019"},
                            {"areas": [], "level": 3, "name": "Krasnoarmiiska", "pCode": "UA0114021"},
                            {"areas": [], "level": 3, "name": "Krasnoperekopska", "pCode": "UA0114023"},
                            {"areas": [], "level": 3, "name": "Kukushkinska", "pCode": "UA0114025"},
                            {"areas": [], "level": 3, "name": "Mahazynska", "pCode": "UA0114027"},
                            {"areas": [], "level": 3, "name": "Novopavlivska", "pCode": "UA0114029"},
                            {"areas": [], "level": 3, "name": "Novoselivska", "pCode": "UA0114031"},
                            {"areas": [], "level": 3, "name": "Orlivska", "pCode": "UA0114033"},
                            {"areas": [], "level": 3, "name": "Pochetnenska", "pCode": "UA0114035"},
                            {"areas": [], "level": 3, "name": "Rozdolnenska", "pCode": "UA0114037"},
                            {"areas": [], "level": 3, "name": "Ruchivska", "pCode": "UA0114039"},
                            {"areas": [], "level": 3, "name": "Serebrianska", "pCode": "UA0114041"},
                            {"areas": [], "level": 3, "name": "Slavnivska", "pCode": "UA0114043"},
                            {"areas": [], "level": 3, "name": "Slovianska", "pCode": "UA0114045"},
                            {"areas": [], "level": 3, "name": "Sovkhoznenska", "pCode": "UA0114047"},
                            {"areas": [], "level": 3, "name": "Suvorovska", "pCode": "UA0114049"},
                            {"areas": [], "level": 3, "name": "Voinska", "pCode": "UA0114011"},
                            {"areas": [], "level": 3, "name": "Vyshnivska", "pCode": "UA0114009"},
                            {"areas": [], "level": 3, "name": "Zymynska", "pCode": "UA0114013"},
                        ],
                        "level": 2,
                        "name": "Perekopskyi",
                        "pCode": "UA0114",
                    },
                    {
                        "areas": [
                            {"areas": [], "level": 3, "name": "Dobrivska", "pCode": "UA0116005"},
                            {"areas": [], "level": 3, "name": "Donska", "pCode": "UA0116007"},
                            {"areas": [], "level": 3, "name": "Hresivska", "pCode": "UA0116003"},
                            {"areas": [], "level": 3, "name": "Hvardiiska", "pCode": "UA0116001"},
                            {"areas": [], "level": 3, "name": "Kolchuhynska", "pCode": "UA0116011"},
                            {"areas": [], "level": 3, "name": "Mazanska", "pCode": "UA0116013"},
                            {"areas": [], "level": 3, "name": "Molodizhnenska", "pCode": "UA0116019"},
                            {"areas": [], "level": 3, "name": "Mykolaivska", "pCode": "UA0116015"},
                            {"areas": [], "level": 3, "name": "Myrnivska", "pCode": "UA0116017"},
                            {"areas": [], "level": 3, "name": "Novoandriivska", "pCode": "UA0116021"},
                            {"areas": [], "level": 3, "name": "Novoselivska", "pCode": "UA0116023"},
                            {"areas": [], "level": 3, "name": "Perovska", "pCode": "UA0116027"},
                            {"areas": [], "level": 3, "name": "Pervomaiska", "pCode": "UA0116025"},
                            {"areas": [], "level": 3, "name": "Pozharska", "pCode": "UA0116029"},
                            {"areas": [], "level": 3, "name": "Rodnykivska", "pCode": "UA0116031"},
                            {"areas": [], "level": 3, "name": "Skvortsivska", "pCode": "UA0116035"},
                            {"areas": [], "level": 3, "name": "Trudivska", "pCode": "UA0116037"},
                            {"areas": [], "level": 3, "name": "Ukromnivska", "pCode": "UA0116039"},
                            {"areas": [], "level": 3, "name": "Urozhainivska", "pCode": "UA0116041"},
                            {"areas": [], "level": 3, "name": "Zhuravlivska", "pCode": "UA0116009"},
                        ],
                        "level": 2,
                        "name": "Simferopolskyi",
                        "pCode": "UA0116",
                    },
                    {"areas": [], "level": 2, "name": "Yaltynskyi", "pCode": "UA0120"},
                    {
                        "areas": [
                            {"areas": [], "level": 3, "name": "Chornomorska", "pCode": "UA0108077"},
                            {"areas": [], "level": 3, "name": "Dalekivska", "pCode": "UA0108011"},
                            {"areas": [], "level": 3, "name": "Dobrushynska", "pCode": "UA0108013"},
                            {"areas": [], "level": 3, "name": "Frunzenska", "pCode": "UA0108075"},
                            {"areas": [], "level": 3, "name": "Heroiska", "pCode": "UA0108009"},
                            {"areas": [], "level": 3, "name": "Ivanivska", "pCode": "UA0108021"},
                            {"areas": [], "level": 3, "name": "Kirovska", "pCode": "UA0108023"},
                            {"areas": [], "level": 3, "name": "Koltsovska", "pCode": "UA0108025"},
                            {"areas": [], "level": 3, "name": "Krainenska", "pCode": "UA0108027"},
                            {"areas": [], "level": 3, "name": "Krasnoiarska", "pCode": "UA0108031"},
                            {"areas": [], "level": 3, "name": "Krasnopolianska", "pCode": "UA0108029"},
                            {"areas": [], "level": 3, "name": "Krymska", "pCode": "UA0108033"},
                            {"areas": [], "level": 3, "name": "Lisnivska", "pCode": "UA0108035"},
                            {"areas": [], "level": 3, "name": "Medvedivska", "pCode": "UA0108037"},
                            {"areas": [], "level": 3, "name": "Mizhvodnenska", "pCode": "UA0108043"},
                            {"areas": [], "level": 3, "name": "Molochnenska", "pCode": "UA0108045"},
                            {"areas": [], "level": 3, "name": "Myrnivska", "pCode": "UA0108039"},
                            {"areas": [], "level": 3, "name": "Mytiaivska", "pCode": "UA0108041"},
                            {"areas": [], "level": 3, "name": "Novofedorivska", "pCode": "UA0108053"},
                            {"areas": [], "level": 3, "name": "Novoivanivska", "pCode": "UA0108047"},
                            {"areas": [], "level": 3, "name": "Novoozernivska", "pCode": "UA0108049"},
                            {"areas": [], "level": 3, "name": "Novosilska", "pCode": "UA0108051"},
                            {"areas": [], "level": 3, "name": "Okhotnykivska", "pCode": "UA0108061"},
                            {"areas": [], "level": 3, "name": "Okunivska", "pCode": "UA0108055"},
                            {"areas": [], "level": 3, "name": "Olenivska", "pCode": "UA0108057"},
                            {"areas": [], "level": 3, "name": "Orikhivska", "pCode": "UA0108059"},
                            {"areas": [], "level": 3, "name": "Romashkinska", "pCode": "UA0108063"},
                            {"areas": [], "level": 3, "name": "Sakska", "pCode": "UA0108065"},
                            {"areas": [], "level": 3, "name": "Shtormivska", "pCode": "UA0108079"},
                            {"areas": [], "level": 3, "name": "Stovpivska", "pCode": "UA0108069"},
                            {"areas": [], "level": 3, "name": "Suvorovska", "pCode": "UA0108071"},
                            {"areas": [], "level": 3, "name": "Syzivska", "pCode": "UA0108067"},
                            {"areas": [], "level": 3, "name": "Uiutnenska", "pCode": "UA0108073"},
                            {"areas": [], "level": 3, "name": "Veresaievska", "pCode": "UA0108001"},
                            {"areas": [], "level": 3, "name": "Veselivska", "pCode": "UA0108003"},
                            {"areas": [], "level": 3, "name": "Vorobiovska", "pCode": "UA0108007"},
                            {"areas": [], "level": 3, "name": "Vynohradivska", "pCode": "UA0108005"},
                            {"areas": [], "level": 3, "name": "Yevpatoriiska", "pCode": "UA0108015"},
                            {"areas": [], "level": 3, "name": "Zaozernenska", "pCode": "UA0108017"},
                            {"areas": [], "level": 3, "name": "Zernivska", "pCode": "UA0108019"},
                        ],
                        "level": 2,
                        "name": "Yevpatoriiskyi",
                        "pCode": "UA0108",
                    },
                ],
                "level": 1,
                "name": "Avtonomna Respublika Krym",
                "pCode": "UA01",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Cherkaskyi", "pCode": "UA7108"},
                    {"areas": [], "level": 2, "name": "Umanskyi", "pCode": "UA7106"},
                    {"areas": [], "level": 2, "name": "Zolotoniskyi", "pCode": "UA7104"},
                    {"areas": [], "level": 2, "name": "Zvenyhorodskyi", "pCode": "UA7102"},
                ],
                "level": 1,
                "name": "Cherkaska",
                "pCode": "UA71",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Chernihivskyi", "pCode": "UA7410"},
                    {"areas": [], "level": 2, "name": "Koriukivskyi", "pCode": "UA7402"},
                    {"areas": [], "level": 2, "name": "Nizhynskyi", "pCode": "UA7404"},
                    {"areas": [], "level": 2, "name": "Novhorod-Siverskyi", "pCode": "UA7406"},
                    {"areas": [], "level": 2, "name": "Prylutskyi", "pCode": "UA7408"},
                ],
                "level": 1,
                "name": "Chernihivska",
                "pCode": "UA74",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Cnernivetskyi", "pCode": "UA7306"},
                    {"areas": [], "level": 2, "name": "Dnistrovskyi", "pCode": "UA7304"},
                    {"areas": [], "level": 2, "name": "Vyzhnytskyi", "pCode": "UA7302"},
                ],
                "level": 1,
                "name": "Chernivetska",
                "pCode": "UA73",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Dniprovskyi", "pCode": "UA1202"},
                    {"areas": [], "level": 2, "name": "Kamianskyi", "pCode": "UA1204"},
                    {"areas": [], "level": 2, "name": "Kryvorizkyi", "pCode": "UA1206"},
                    {"areas": [], "level": 2, "name": "Nikopolskyi", "pCode": "UA1208"},
                    {"areas": [], "level": 2, "name": "Novomoskovskyi", "pCode": "UA1210"},
                    {"areas": [], "level": 2, "name": "Pavlohradskyi", "pCode": "UA1212"},
                    {"areas": [], "level": 2, "name": "Synelnykivskyi", "pCode": "UA1214"},
                ],
                "level": 1,
                "name": "Dnipropetrovska",
                "pCode": "UA12",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Bakhmutskyi", "pCode": "UA1402"},
                    {"areas": [], "level": 2, "name": "Donetskyi", "pCode": "UA1408"},
                    {"areas": [], "level": 2, "name": "Horlivskyi", "pCode": "UA1406"},
                    {"areas": [], "level": 2, "name": "Kalmiuskyi", "pCode": "UA1410"},
                    {"areas": [], "level": 2, "name": "Kramatorskyi", "pCode": "UA1412"},
                    {"areas": [], "level": 2, "name": "Mariupolskyi", "pCode": "UA1414"},
                    {"areas": [], "level": 2, "name": "Pokrovskyi", "pCode": "UA1416"},
                    {"areas": [], "level": 2, "name": "Volnovaskyi", "pCode": "UA1404"},
                ],
                "level": 1,
                "name": "Donetska",
                "pCode": "UA14",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Ivano-Frankivskyi", "pCode": "UA2604"},
                    {"areas": [], "level": 2, "name": "Kaluskyi", "pCode": "UA2606"},
                    {"areas": [], "level": 2, "name": "Kolomyiskyi", "pCode": "UA2608"},
                    {"areas": [], "level": 2, "name": "Kosivskyi", "pCode": "UA2610"},
                    {"areas": [], "level": 2, "name": "Nadvirnianskyi", "pCode": "UA2612"},
                    {"areas": [], "level": 2, "name": "Verkhovynskyi", "pCode": "UA2602"},
                ],
                "level": 1,
                "name": "Ivano-Frankivska",
                "pCode": "UA26",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Bohodukhivskyi", "pCode": "UA6302"},
                    {"areas": [], "level": 2, "name": "Chuhuivskyi", "pCode": "UA6314"},
                    {"areas": [], "level": 2, "name": "Iziumskyi", "pCode": "UA6304"},
                    {"areas": [], "level": 2, "name": "Kharkivskyi", "pCode": "UA6312"},
                    {"areas": [], "level": 2, "name": "Krasnohradskyi", "pCode": "UA6306"},
                    {"areas": [], "level": 2, "name": "Kupianskyi", "pCode": "UA6308"},
                    {"areas": [], "level": 2, "name": "Lozivskyi", "pCode": "UA6310"},
                ],
                "level": 1,
                "name": "Kharkivska",
                "pCode": "UA63",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Beryslavskyi", "pCode": "UA6502"},
                    {"areas": [], "level": 2, "name": "Henicheskyi", "pCode": "UA6504"},
                    {"areas": [], "level": 2, "name": "Kakhovskyi", "pCode": "UA6506"},
                    {"areas": [], "level": 2, "name": "Khersonskyi", "pCode": "UA6510"},
                    {"areas": [], "level": 2, "name": "Skadovskyi", "pCode": "UA6508"},
                ],
                "level": 1,
                "name": "Khersonska",
                "pCode": "UA65",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Kamianets-Podilskyi", "pCode": "UA6802"},
                    {"areas": [], "level": 2, "name": "Khmelnytskyi", "pCode": "UA6804"},
                    {"areas": [], "level": 2, "name": "Shepetivskyi", "pCode": "UA6806"},
                ],
                "level": 1,
                "name": "Khmelnytska",
                "pCode": "UA68",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Holovanivskyi", "pCode": "UA3502"},
                    {"areas": [], "level": 2, "name": "Kropyvnytskyi", "pCode": "UA3504"},
                    {"areas": [], "level": 2, "name": "Novoukrainskyi", "pCode": "UA3506"},
                    {"areas": [], "level": 2, "name": "Oleksandriiskyi", "pCode": "UA3508"},
                ],
                "level": 1,
                "name": "Kirovohradska",
                "pCode": "UA35",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Bilotserkivskyi", "pCode": "UA3202"},
                    {"areas": [], "level": 2, "name": "Boryspilskyi", "pCode": "UA3204"},
                    {"areas": [], "level": 2, "name": "Brovarskyi", "pCode": "UA3206"},
                    {"areas": [], "level": 2, "name": "Buchanskyi", "pCode": "UA3208"},
                    {"areas": [], "level": 2, "name": "Chornobylska zona vidchuzhennia", "pCode": "UA3200"},
                    {"areas": [], "level": 2, "name": "Fastivskyi", "pCode": "UA3214"},
                    {"areas": [], "level": 2, "name": "Obukhivskyi", "pCode": "UA3212"},
                    {"areas": [], "level": 2, "name": "Vyshhorodskyi", "pCode": "UA3210"},
                ],
                "level": 1,
                "name": "Kyivska",
                "pCode": "UA32",
            },
            {
                "areas": [{"areas": [], "level": 2, "name": "Kyivska", "pCode": "UA8000"}],
                "level": 1,
                "name": "Kyivska",
                "pCode": "UA80",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Alchevskyi", "pCode": "UA4402"},
                    {"areas": [], "level": 2, "name": "Dovzhanskyi", "pCode": "UA4404"},
                    {"areas": [], "level": 2, "name": "Luhanskyi", "pCode": "UA4406"},
                    {"areas": [], "level": 2, "name": "Rovenkivskyi", "pCode": "UA4408"},
                    {"areas": [], "level": 2, "name": "Shchastynskyi", "pCode": "UA4416"},
                    {"areas": [], "level": 2, "name": "Sievierodonetskyi", "pCode": "UA4412"},
                    {"areas": [], "level": 2, "name": "Starobilskyi", "pCode": "UA4414"},
                    {"areas": [], "level": 2, "name": "Svativskyi", "pCode": "UA4410"},
                ],
                "level": 1,
                "name": "Luhanska",
                "pCode": "UA44",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Chervonohradskyi", "pCode": "UA4612"},
                    {"areas": [], "level": 2, "name": "Drohobytskyi", "pCode": "UA4602"},
                    {"areas": [], "level": 2, "name": "Lvivskyi", "pCode": "UA4606"},
                    {"areas": [], "level": 2, "name": "Sambirskyi", "pCode": "UA4608"},
                    {"areas": [], "level": 2, "name": "Stryiskyi", "pCode": "UA4610"},
                    {"areas": [], "level": 2, "name": "Yavorivskyi", "pCode": "UA4614"},
                    {"areas": [], "level": 2, "name": "Zolochivskyi", "pCode": "UA4604"},
                ],
                "level": 1,
                "name": "Lvivska",
                "pCode": "UA46",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Bashtanskyi", "pCode": "UA4802"},
                    {"areas": [], "level": 2, "name": "Mykolaivskyi", "pCode": "UA4806"},
                    {"areas": [], "level": 2, "name": "Pervomaiskyi", "pCode": "UA4808"},
                    {"areas": [], "level": 2, "name": "Voznesenskyi", "pCode": "UA4804"},
                ],
                "level": 1,
                "name": "Mykolaivska",
                "pCode": "UA48",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Berezivskyi", "pCode": "UA5102"},
                    {"areas": [], "level": 2, "name": "Bilhorod-Dnistrovskyi", "pCode": "UA5104"},
                    {"areas": [], "level": 2, "name": "Bolhradskyi", "pCode": "UA5106"},
                    {"areas": [], "level": 2, "name": "Izmailskyi", "pCode": "UA5108"},
                    {"areas": [], "level": 2, "name": "Odeskyi", "pCode": "UA5110"},
                    {"areas": [], "level": 2, "name": "Podilskyi", "pCode": "UA5112"},
                    {"areas": [], "level": 2, "name": "Rozdilnianskyi", "pCode": "UA5114"},
                ],
                "level": 1,
                "name": "Odeska",
                "pCode": "UA51",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Kremenchutskyi", "pCode": "UA5302"},
                    {"areas": [], "level": 2, "name": "Lubenskyi", "pCode": "UA5304"},
                    {"areas": [], "level": 2, "name": "Myrhorodskyi", "pCode": "UA5306"},
                    {"areas": [], "level": 2, "name": "Poltavskyi", "pCode": "UA5308"},
                ],
                "level": 1,
                "name": "Poltavska",
                "pCode": "UA53",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Dubenskyi", "pCode": "UA5604"},
                    {"areas": [], "level": 2, "name": "Rivnenskyi", "pCode": "UA5606"},
                    {"areas": [], "level": 2, "name": "Sarnenskyi", "pCode": "UA5608"},
                    {"areas": [], "level": 2, "name": "Varaskyi", "pCode": "UA5602"},
                ],
                "level": 1,
                "name": "Rivnenska",
                "pCode": "UA56",
            },
            {
                "areas": [{"areas": [], "level": 2, "name": "Sevastopilska", "pCode": "UA8500"}],
                "level": 1,
                "name": "Sevastopilska",
                "pCode": "UA85",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Konotopskyi", "pCode": "UA5902"},
                    {"areas": [], "level": 2, "name": "Okhtyrskyi", "pCode": "UA5904"},
                    {"areas": [], "level": 2, "name": "Romenskyi", "pCode": "UA5906"},
                    {"areas": [], "level": 2, "name": "Shostkynskyi", "pCode": "UA5910"},
                    {"areas": [], "level": 2, "name": "Sumskyi", "pCode": "UA5908"},
                ],
                "level": 1,
                "name": "Sumska",
                "pCode": "UA59",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Chortkivskyi", "pCode": "UA6106"},
                    {"areas": [], "level": 2, "name": "Kremenetskyi", "pCode": "UA6102"},
                    {"areas": [], "level": 2, "name": "Ternopilskyi", "pCode": "UA6104"},
                ],
                "level": 1,
                "name": "Ternopilska",
                "pCode": "UA61",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Haisynskyi", "pCode": "UA0504"},
                    {"areas": [], "level": 2, "name": "Khmilnytskyi", "pCode": "UA0512"},
                    {"areas": [], "level": 2, "name": "Mohyliv-Podilskyi", "pCode": "UA0508"},
                    {"areas": [], "level": 2, "name": "Tulchynskyi", "pCode": "UA0510"},
                    {"areas": [], "level": 2, "name": "Vinnytskyi", "pCode": "UA0502"},
                    {"areas": [], "level": 2, "name": "Zhmerynskyi", "pCode": "UA0506"},
                ],
                "level": 1,
                "name": "Vinnytska",
                "pCode": "UA05",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Kamin-Kashyrskyi", "pCode": "UA0704"},
                    {"areas": [], "level": 2, "name": "Kovelskyi", "pCode": "UA0706"},
                    {"areas": [], "level": 2, "name": "Lutskyi", "pCode": "UA0708"},
                    {"areas": [], "level": 2, "name": "Volodymyr-Volynskyi", "pCode": "UA0702"},
                ],
                "level": 1,
                "name": "Volynska",
                "pCode": "UA07",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Berehivskyi", "pCode": "UA2102"},
                    {"areas": [], "level": 2, "name": "Khustskyi", "pCode": "UA2112"},
                    {"areas": [], "level": 2, "name": "Mukachivskyi", "pCode": "UA2104"},
                    {"areas": [], "level": 2, "name": "Rakhivskyi", "pCode": "UA2106"},
                    {"areas": [], "level": 2, "name": "Tiachivskyi", "pCode": "UA2108"},
                    {"areas": [], "level": 2, "name": "Uzhhorodskyi", "pCode": "UA2110"},
                ],
                "level": 1,
                "name": "Zakarpatska",
                "pCode": "UA21",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Berdianskyi", "pCode": "UA2302"},
                    {"areas": [], "level": 2, "name": "Melitopolskyi", "pCode": "UA2308"},
                    {"areas": [], "level": 2, "name": "Polohivskyi", "pCode": "UA2310"},
                    {"areas": [], "level": 2, "name": "Vasylivskyi", "pCode": "UA2304"},
                    {"areas": [], "level": 2, "name": "Zaporizkyi", "pCode": "UA2306"},
                ],
                "level": 1,
                "name": "Zaporizka",
                "pCode": "UA23",
            },
            {
                "areas": [
                    {"areas": [], "level": 2, "name": "Berdychivskyi", "pCode": "UA1802"},
                    {"areas": [], "level": 2, "name": "Korostenskyi", "pCode": "UA1806"},
                    {"areas": [], "level": 2, "name": "Novohrad-Volynskyi", "pCode": "UA1808"},
                    {"areas": [], "level": 2, "name": "Zhytomyrskyi", "pCode": "UA1804"},
                ],
                "level": 1,
                "name": "Zhytomyrska",
                "pCode": "UA18",
            },
        ]
    }
}
