# Generated by Django 5.2.17 on 2026-09-16 12:03

from django.db import migrations, models
import django.db.models.deletion

TRIGGER_FUNCTION = """
CREATE OR REPLACE FUNCTION funds_commitment_trigger_function()
RETURNS TRIGGER AS $$
DECLARE
    fc_group_id INT;
    office_id UUID;

BEGIN
    -- Check if FundsCommitmentGroup exists, if not create it
    SELECT id INTO fc_group_id FROM vision_fundscommitmentgroup
    WHERE funds_commitment_number = NEW.funds_commitment_number;

    IF fc_group_id IS NULL THEN
        INSERT INTO vision_fundscommitmentgroup (
            funds_commitment_number,
            business_area,
            document_type,
            posting_date,
            currency_code,
            vendor_id,
            gl_account
        )
        VALUES (
            NEW.funds_commitment_number,
            NEW.business_area,
            NEW.document_type,
            NEW.posting_date,
            NEW.currency_code,
            NEW.vendor_id,
            NEW.gl_account
        )
        RETURNING id INTO fc_group_id;
    ELSE
        UPDATE vision_fundscommitmentgroup
        SET business_area = NEW.business_area,
            document_type = NEW.document_type,
            posting_date = NEW.posting_date,
            currency_code = NEW.currency_code,
            vendor_id = NEW.vendor_id,
            gl_account = NEW.gl_account
        WHERE id = fc_group_id;
    END IF;

    -- Try to get BusinessArea.id using the business_area code
    SELECT id INTO office_id FROM core_businessarea
    WHERE code = NEW.business_area
    LIMIT 1;

    -- Insert into FundsCommitmentItem
    INSERT INTO vision_fundscommitmentitem (
        funds_commitment_group_id,
        funds_commitment_item,
        rec_serial_number,
        vision_approval,
        document_reference,
        fc_status,
        wbs_element,
        grant_number,
        document_text,
        commitment_amount_local,
        commitment_amount_usd,
        total_open_amount_local,
        total_open_amount_usd,
        sponsor,
        sponsor_name,
        fund,
        funds_center,
        percentage,
        create_date,
        created_by,
        update_date,
        updated_by,
        office_id
    )
    VALUES (
        fc_group_id,
        NEW.funds_commitment_item,
        NEW.rec_serial_number,
        NEW.vision_approval,
        NEW.document_reference,
        NEW.fc_status,
        NEW.wbs_element,
        NEW.grant_number,
        NEW.document_text,
        NEW.commitment_amount_local,
        NEW.commitment_amount_usd,
        NEW.total_open_amount_local,
        NEW.total_open_amount_usd,
        NEW.sponsor,
        NEW.sponsor_name,
        NEW.fund,
        NEW.funds_center,
        NEW.percentage,
        NEW.create_date,
        NEW.created_by,
        NEW.update_date,
        NEW.updated_by,
        office_id
    );

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

TRIGGER_DELETION = """
DROP TRIGGER IF EXISTS funds_commitment_insert_trigger ON vision_fundscommitment;
DROP FUNCTION IF EXISTS funds_commitment_trigger_function;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0077_migration"),
        ("vision", "0003_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fundscommitmentitem",
            name="business_area",
        ),
        migrations.RemoveField(
            model_name="fundscommitmentitem",
            name="currency_code",
        ),
        migrations.RemoveField(
            model_name="fundscommitmentitem",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="fundscommitmentitem",
            name="gl_account",
        ),
        migrations.RemoveField(
            model_name="fundscommitmentitem",
            name="payment_plan",
        ),
        migrations.RemoveField(
            model_name="fundscommitmentitem",
            name="posting_date",
        ),
        migrations.RemoveField(
            model_name="fundscommitmentitem",
            name="vendor_id",
        ),
        migrations.AddField(
            model_name="fundscommitmentgroup",
            name="business_area",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="fundscommitmentgroup",
            name="currency_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="fundscommitmentgroup",
            name="document_type",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="fundscommitmentgroup",
            name="gl_account",
            field=models.CharField(blank=True, help_text="General Ledger Account", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="fundscommitmentgroup",
            name="payment_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funds_commitments",
                to="payment.paymentplan",
            ),
        ),
        migrations.AddField(
            model_name="fundscommitmentgroup",
            name="posting_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundscommitmentgroup",
            name="vendor_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="fundscommitmentitem",
            name="funds_center",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cost center",
                max_length=16,
                null=True,
            ),
        ),
        migrations.RunSQL(
            TRIGGER_FUNCTION,
            TRIGGER_DELETION,
        ),
    ]
