# Generated by Django 5.2.17 on 2026-09-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vision", "0004_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundscommitment",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ZA", "Direct Cash Transfer"),
                    ("ZB", "Reimbursement Cash Transfer"),
                    ("ZC", "Direct Payment Cash Transfer"),
                    ("ZD", "HQ/RO Cash Transfer"),
                    ("ZE", "UN IAP (Joint Programming)"),
                    ("ZF", "UN IAP (Common Services)"),
                    ("ZG", "UN IAP (Joint UN Activities)"),
                    ("ZH", "UN IAP (Non-JP Programmatic Ac"),
                    ("ZJ", "CBT Advance"),
                    ("ZK", "CBT Reimbursement"),
                    ("ZL", "CBT Controlled Account"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fundscommitment",
            name="fund",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GA", "RR Allotment for Overexpenditure"),
                    ("GC", "RR Allotment for Country Programme"),
                    ("GE", "Emergency Programme Fund (EPF)"),
                    ("GF", "Allotment for Central/Shared Services"),
                    ("GG", "Net Revenue - Product Sales"),
                    ("GI", "RR Allot. for Global and Regional Progr."),
                    ("GP", "RR Allotment for Unfunder OR"),
                    ("SC", "OR Allotment for Country Programme"),
                    ("SG", "Direct Contributions for Mgmt Results"),
                    ("SH", "OR Develop Allot for Emergency Appeals"),
                    ("SI", "OR Allotment for Inter-Country Programme"),
                    ("SLD", "Salary Fund Temporary Deficit"),
                    ("SLF", "Salary Fund"),
                    ("SM", "OR Allotment for Emergency Appeals"),
                    ("SP", "OR allotment for PSFR"),
                ],
                default="",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fundscommitmentgroup",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ZA", "Direct Cash Transfer"),
                    ("ZB", "Reimbursement Cash Transfer"),
                    ("ZC", "Direct Payment Cash Transfer"),
                    ("ZD", "HQ/RO Cash Transfer"),
                    ("ZE", "UN IAP (Joint Programming)"),
                    ("ZF", "UN IAP (Common Services)"),
                    ("ZG", "UN IAP (Joint UN Activities)"),
                    ("ZH", "UN IAP (Non-JP Programmatic Ac"),
                    ("ZJ", "CBT Advance"),
                    ("ZK", "CBT Reimbursement"),
                    ("ZL", "CBT Controlled Account"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fundscommitmentitem",
            name="fund",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GA", "RR Allotment for Overexpenditure"),
                    ("GC", "RR Allotment for Country Programme"),
                    ("GE", "Emergency Programme Fund (EPF)"),
                    ("GF", "Allotment for Central/Shared Services"),
                    ("GG", "Net Revenue - Product Sales"),
                    ("GI", "RR Allot. for Global and Regional Progr."),
                    ("GP", "RR Allotment for Unfunder OR"),
                    ("SC", "OR Allotment for Country Programme"),
                    ("SG", "Direct Contributions for Mgmt Results"),
                    ("SH", "OR Develop Allot for Emergency Appeals"),
                    ("SI", "OR Allotment for Inter-Country Programme"),
                    ("SLD", "Salary Fund Temporary Deficit"),
                    ("SLF", "Salary Fund"),
                    ("SM", "OR Allotment for Emergency Appeals"),
                    ("SP", "OR allotment for PSFR"),
                ],
                default="",
                max_length=10,
                null=True,
            ),
        ),
    ]
