# Generated by Django 3.2.15 on 2023-01-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_module", "0003_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcycle",
            name="unicef_id",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
