# Generated by Django 3.2.25 on 2025-01-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanction_list', '0001_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanctionlistindividual',
            options={'ordering': ['-listed_on']},
        ),
    ]
