# Generated by Django 3.2.20 on 2023-09-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targeting', '0039_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdselection',
            name='is_migration_handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='householdselection',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
    ]
