# Generated by Django 3.2.25 on 2024-10-03 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0053_migration'),
        ('targeting', '0047_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetpopulation',
            name='program_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_populations', to='program.programcycle'),
        ),
    ]
