# Generated by Django 3.2.25 on 2025-02-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0007_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievanceticket',
            name='is_original',
        ),
    ]
