# Generated by Django 3.2.24 on 2024-02-16 06:13

from django.db import migrations, models
from django.core.paginator import Paginator
import django.db.models.deletion


def update_status_for_not_assigned_tickets(apps, schema_editor):
    from hct_mis_api.apps.grievance.models import GrievanceTicket

    GrievanceTicket.default_for_migrations_fix.filter(status=GrievanceTicket.STATUS_ASSIGNED, assigned_to=None).update(status=GrievanceTicket.STATUS_NEW)


def migrate_old_tickets_m2m_program(apps, schema_editor):
    GrievanceTicket = apps.get_model("grievance", "GrievanceTicket")

    qs_tickets = GrievanceTicket.objects.filter(programme__isnull=False)

    paginator = Paginator(qs_tickets, 500)
    for page in paginator.page_range:
        for ticket in paginator.page(page).object_list:
            ticket.programs.add(ticket.programme)


class Migration(migrations.Migration):

    replaces = [('grievance', '0062_migration'), ('grievance', '0063_migration'), ('grievance', '0064_migration'), ('grievance', '0065_migration'), ('grievance', '0066_migration'), ('grievance', '0067_migration'), ('grievance', '0068_migration'), ('grievance', '0069_migration')]

    dependencies = [
        ('grievance', '0055_migration_squashed_0061_migration'),
        ('program', '0038_migration'),
    ]

    operations = [
        migrations.RunPython(update_status_for_not_assigned_tickets, migrations.RunPython.noop),
        migrations.AddField(
            model_name='grievanceticket',
            name='copied_from',
            field=models.ForeignKey(blank=True, help_text='If this object was copied from another, this field will contain the object it was copied from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_to', to='grievance.grievanceticket'),
        ),
        migrations.AddField(
            model_name='grievanceticket',
            name='is_migration_handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grievanceticket',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grievanceticket',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='grievance_tickets', to='program.Program'),
        ),
        migrations.AlterModelOptions(
            name='ticketaddindividualdetails',
            options={'verbose_name_plural': 'Ticket Add Individual Details'},
        ),
        migrations.AlterModelOptions(
            name='ticketcomplaintdetails',
            options={'verbose_name_plural': 'Ticket Complaint Details'},
        ),
        migrations.AlterModelOptions(
            name='ticketdeletehouseholddetails',
            options={'verbose_name_plural': 'Ticket Delete Household Details'},
        ),
        migrations.AlterModelOptions(
            name='ticketdeleteindividualdetails',
            options={'verbose_name_plural': 'Ticket Delete Individual Details'},
        ),
        migrations.AlterModelOptions(
            name='tickethouseholddataupdatedetails',
            options={'verbose_name_plural': 'Ticket Household Data Update Details'},
        ),
        migrations.AlterModelOptions(
            name='ticketindividualdataupdatedetails',
            options={'verbose_name_plural': 'Ticket Individual Data Update Details'},
        ),
        migrations.AlterModelOptions(
            name='ticketneedsadjudicationdetails',
            options={'verbose_name_plural': 'Ticket Needs Adjudication Details'},
        ),
        migrations.AlterModelOptions(
            name='ticketnegativefeedbackdetails',
            options={'verbose_name_plural': 'Ticket Negative Feedback Details'},
        ),
        migrations.AlterModelOptions(
            name='ticketpaymentverificationdetails',
            options={'verbose_name_plural': 'Ticket Payment Verification Details'},
        ),
        migrations.AlterModelOptions(
            name='ticketpositivefeedbackdetails',
            options={'verbose_name_plural': 'Ticket Positive Feedback Details'},
        ),
        migrations.AlterModelOptions(
            name='ticketreferraldetails',
            options={'verbose_name_plural': 'Ticket Referral Details'},
        ),
        migrations.AlterModelOptions(
            name='ticketsensitivedetails',
            options={'verbose_name_plural': 'Ticket Sensitive Details'},
        ),
        migrations.AlterModelOptions(
            name='ticketsystemflaggingdetails',
            options={'verbose_name_plural': 'Ticket System Flagging Details'},
        ),
        migrations.AddField(
            model_name='grievanceticket',
            name='migrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_old_tickets_m2m_program, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='grievanceticket',
            name='programme',
        ),
        migrations.AddField(
            model_name='ticketneedsadjudicationdetails',
            name='is_cross_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grievanceticket',
            name='is_original',
            field=models.BooleanField(default=False),
        ),
    ]
