# Generated by Django 3.2.23 on 2023-12-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0068_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievanceticket',
            name='is_original',
            field=models.BooleanField(default=False),
        ),
    ]
