# Generated by Django 3.2.25 on 2024-09-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0072_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketneedsadjudicationdetails',
            name='dedup_engine_similarity_pair',
        ),
    ]
