#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE "$POSTGRES_CASHASSIST_DATAHUB_DB";
        CREATE EXTENSION IF NOT EXISTS POSTGIS;
	GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_CASHASSIST_DATAHUB_DB" TO "$POSTGRES_USER";
	CREATE DATABASE "$POSTGRES_REGISTRATION_DATAHUB_DB";
	GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_REGISTRATION_DATAHUB_DB" TO "$POSTGRES_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_CASHASSIST_DATAHUB_DB" <<-EOSQL
        CREATE EXTENSION IF NOT EXISTS POSTGIS;
        CREATE SCHEMA IF NOT EXISTS mis;
        CREATE SCHEMA IF NOT EXISTS erp;
        CREATE SCHEMA IF NOT EXISTS ca;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_REGISTRATION_DATAHUB_DB" <<-EOSQL
        CREATE EXTENSION IF NOT EXISTS POSTGIS;
EOSQL
