# Generated by Django 3.2.25 on 2025-06-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sanction_list", "0003_migration"),
        ("program", "0004_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="sanction_lists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Program sanction lists",
                related_name="programs",
                to="sanction_list.SanctionList",
            ),
        ),
    ]
