# Generated by Django 5.2.6 on 2025-09-24 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # ensure CREATE COLLATION can run outside transaction

    dependencies = [
        ("program", "0009_migration"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE COLLATION IF NOT EXISTS "und-ci-det"
            (provider = icu, locale = 'und-u-ks-level2', deterministic = true);
            """,
            """
            DROP COLLATION IF EXISTS "und-ci-det";
            """,
        ),
        migrations.AlterField(
            model_name="program",
            name="name",
            field=models.CharField(
                db_collation="und-ci-det",
                db_index=True,
                help_text="Program name",
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(255),
                    django.core.validators.RegexValidator(
                        "\\s{2,}",
                        "Double spaces characters are not allowed.",
                        code="double_spaces_characters_not_allowed",
                        inverse_match=True,
                    ),
                    django.core.validators.RegexValidator(
                        "(^\\s+)|(\\s+$)",
                        "Leading or trailing spaces characters are not allowed.",
                        code="leading_trailing_spaces_characters_not_allowed",
                        inverse_match=True,
                    ),
                    django.core.validators.ProhibitNullCharactersValidator(),
                ],
            ),
        ),
    ]
