# Generated by Django 5.2.6 on 2025-11-17 11:41

from django.db import migrations
import strategy_field.fields

import hope.apps.program.collision_detectors


def populate_noop_collision_detector(apps, schema_editor):
    Program = apps.get_model("program", "Program")
    programs_to_update = []
    Program.objects.filter(collision_detector__isnull=True).update(
        collision_detector=hope.apps.program.collision_detectors.NoopCollisionDetector
    )

    Program.objects.bulk_update(programs_to_update, ["collision_detector"])


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0011_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="collision_detection_enabled",
        ),
        migrations.RunPython(populate_noop_collision_detector, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="program",
            name="collision_detector",
            field=strategy_field.fields.StrategyField(
                default=hope.apps.program.collision_detectors.NoopCollisionDetector,
                help_text="Object which detects collisions",
            ),
        ),
    ]
