# Generated by Django 5.2.11 on 2026-03-04 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0015_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="program",
            options={
                "ordering": ("id",),
                "permissions": [
                    ("enroll_beneficiaries", "Can enroll beneficiaries"),
                    (
                        "can_bulk_upload_individual_photos",
                        "Can bulk upload Individual photos",
                    ),
                ],
                "verbose_name": "Programme",
            },
        ),
    ]
