# Generated by Django 5.2.11 on 2026-02-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_migration"),
        ("program", "0015_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisation or facility",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.facility",
            ),
        ),
    ]
