# Generated by Django 5.2.12 on 2026-03-13 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_migration"),
        ("program", "0016_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisation or facility",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.facility",
            ),
        ),
    ]
