# Generated by Django 5.2.11 on 2026-03-31 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_log", "0002_migration"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0017_migration"),
        ("program", "0017_migration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="logentry",
            index=models.Index(fields=["business_area", "-timestamp"], name="idx_le_ba_ts"),
        ),
    ]
