# Generated by Django 5.2.13 on 2026-04-16 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("activity_log", "0003_migration"),
        ("core", "0021_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="business_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.businessarea",
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="changes",
            field=models.JSONField(blank=True, null=True, verbose_name="change message"),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="object_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
