# Generated by Django 5.2.17 on 2026-10-01 14:17

from django.db import migrations, models

import hope.models.log_entry
import hope.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("activity_log", "0005_migration"),
    ]

    operations = [
        # State only: the indexes already exist under these names, db_index=True created them.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="logentry",
                    name="action",
                    field=models.CharField(
                        choices=hope.models.log_entry.get_log_entry_action_choices,
                        max_length=100,
                        verbose_name="action",
                    ),
                ),
                migrations.AlterField(
                    model_name="logentry",
                    name="object_id",
                    field=models.UUIDField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name="logentry",
                    name="timestamp",
                    field=models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
                migrations.AddIndex(
                    model_name="logentry",
                    index=hope.models.utils.LongNameIndex(
                        fields=["object_id"], name="activity_log_logentry_object_id_d7af1d06"
                    ),
                ),
                migrations.AddIndex(
                    model_name="logentry",
                    index=hope.models.utils.LongNameIndex(
                        fields=["action"], name="activity_log_logentry_action_7b504b2d"
                    ),
                ),
                migrations.AddIndex(
                    model_name="logentry",
                    index=hope.models.utils.LongNameIndex(
                        fields=["action"],
                        name="activity_log_logentry_action_7b504b2d_like",
                        opclasses=["varchar_pattern_ops"],
                    ),
                ),
                migrations.AddIndex(
                    model_name="logentry",
                    index=hope.models.utils.LongNameIndex(
                        fields=["timestamp"], name="activity_log_logentry_timestamp_62c98ec4"
                    ),
                ),
            ],
        ),
    ]
