# Generated by Django 3.2.25 on 2024-11-05 17:49
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('household', '0002_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccountinfo',
            name='is_migration_handled',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='bankaccountinfo',
                    name='bank_account_number',
                    field=models.CharField(db_index=True, max_length=64),
                ),
            ],
            database_operations=[
                AddIndexConcurrently(
                    model_name="bankaccountinfo",
                    index=models.Index(
                        fields=["bank_account_number"], name="bank_account_number_idx"
                    )
                ),
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='bankaccountinfo',
                    name='debit_card_number',
                    field=models.CharField(blank=True, db_index=True, default='', max_length=255),
                ),
            ],
            database_operations=[
                AddIndexConcurrently(
                    model_name="bankaccountinfo",
                    index=models.Index(
                        fields=["debit_card_number"], name="debit_card_number_idx"
                    )
                ),
            ]
        )
    ]