# Generated by Django 3.2.25 on 2025-01-24 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0009_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="household",
            name="collect_individual_data",
        ),
    ]
