# Generated by Django 3.2.25 on 2025-02-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0011_migration'),
        ('program', '0003_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='programs',
        ),
        migrations.AlterField(
            model_name='household',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs',
                                    to='program.program'),
        ),
    ]
