# Generated by Django 3.2.25 on 2025-02-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0012_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_migration_handled',
        ),
        migrations.RemoveField(
            model_name='household',
            name='is_migration_handled',
        ),
        migrations.RemoveField(
            model_name='household',
            name='migrated_at',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='is_migration_handled',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='migrated_at',
        ),
        migrations.RemoveField(
            model_name='individualidentity',
            name='is_migration_handled',
        ),
        migrations.RemoveField(
            model_name='individualroleinhousehold',
            name='is_migration_handled',
        ),
        migrations.RemoveField(
            model_name='individualroleinhousehold',
            name='migrated_at',
        ),
    ]
