# Generated by Django 3.2.25 on 2025-02-20 13:34

from django.db import migrations, models

def migrate_registration_id_to_detail_id(apps, schema_editor):
    Household = apps.get_model("household", "Household")
    Individual = apps.get_model("household", "Individual")

    Individual.objects.filter(registration_id__isnull=False, detail_id__isnull=True).update(detail_id=models.F("registration_id"))
    Household.objects.filter(registration_id__isnull=False, detail_id__isnull=True).update(detail_id=models.F("registration_id"))


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0013_migration'),
    ]

    operations = [
        migrations.RunPython(migrate_registration_id_to_detail_id, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='household',
            name='registration_id',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='registration_id',
        ),
        migrations.AlterField(
            model_name='household',
            name='detail_id',
            field=models.CharField(blank=True, help_text='Kobo asset ID, Xlsx row ID, Aurora registration ID', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='detail_id',
            field=models.CharField(blank=True, help_text='Kobo asset ID, Xlsx row ID, Aurora registration ID', max_length=150, null=True),
        ),
    ]
