# Generated by Django 3.2.25 on 2025-03-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0016_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Household latitude [sys]', null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Household longitude [sys]', null=True),
        ),
    ]
