# Generated by Django 3.2.25 on 2025-03-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0017_migration'),
    ]

    operations = [
    ]
