# Generated by Django 3.2.25 on 2025-07-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0020_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='identification_key',
            field=models.CharField(blank=True, help_text='Key used to identify Collisions in the system', max_length=255, null=True),
        ),
    ]
