# Generated by Django 3.2.25 on 2025-07-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0021_migration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='household',
            name='identification_key_unique_constraint',
        ),
        migrations.AddConstraint(
            model_name='household',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False), ('identification_key__isnull', False), ('rdi_merge_status', 'MERGED')), fields=('identification_key', 'program'), name='identification_key_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='individual',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False), ('identification_key__isnull', False), ('rdi_merge_status', 'MERGED')), fields=('identification_key', 'program'), name='identification_key_ind_unique_constraint'),
        ),
    ]
