# Generated by Django 3.2.20 on 2023-07-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0151_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='age_at_registration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
