# Generated by Django 5.2.11 on 2026-03-31 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_migration"),
        ("periodic_data_update", "0004_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pduonlineedit",
            name="celery_tasks_results_ids",
        ),
    ]
