# Generated by Django 5.2.12 on 2026-04-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodic_data_update', '0006_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pduxlsxtemplate',
            options={'ordering': ('-created_at',), 'permissions': (('restart_export_task', 'Can restart export task'),)},
        ),
    ]
