# Generated by Django 5.2.17 on 2026-09-09 12:24

from django.db import migrations, models

import hope.apps.core.upload_paths


class Migration(migrations.Migration):
    dependencies = [
        ("periodic_data_update", "0008_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pduxlsxupload",
            name="file",
            field=models.FileField(max_length=255, upload_to=hope.apps.core.upload_paths.upload_path),
        ),
    ]
