# Generated by Django 5.2.17 on 2026-10-02 09:27

from django.conf import settings
from django.db import migrations, models

import hope.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_migration"),
        ("periodic_data_update", "0008_migration"),
        ("program", "0022_migration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pduonlineedit",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pduonlineedit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="pduonlineeditsentbackcomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pduonlineeditsentbackcomment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="pduxlsxtemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pduxlsxtemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="pduxlsxupload",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pduxlsxupload",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="pduonlineedit",
            index=hope.models.utils.LongNameIndex(
                fields=["created_at"],
                name="periodic_data_update_pduonlineedit_created_at_cbf512a8",
            ),
        ),
        migrations.AddIndex(
            model_name="pduonlineedit",
            index=hope.models.utils.LongNameIndex(
                fields=["updated_at"],
                name="periodic_data_update_pduonlineedit_updated_at_416e7971",
            ),
        ),
        migrations.AddIndex(
            model_name="pduonlineeditsentbackcomment",
            index=hope.models.utils.LongNameIndex(
                fields=["created_at"],
                name="periodic_data_update_pduon_created_at_b2b09a3c",
            ),
        ),
        migrations.AddIndex(
            model_name="pduonlineeditsentbackcomment",
            index=hope.models.utils.LongNameIndex(
                fields=["updated_at"],
                name="periodic_data_update_pduon_updated_at_e57014b4",
            ),
        ),
        migrations.AddIndex(
            model_name="pduxlsxtemplate",
            index=hope.models.utils.LongNameIndex(
                fields=["created_at"],
                name="periodic_data_update_pduxlsxtemplate_created_at_0ed2662a",
            ),
        ),
        migrations.AddIndex(
            model_name="pduxlsxtemplate",
            index=hope.models.utils.LongNameIndex(
                fields=["updated_at"],
                name="periodic_data_update_pduxlsxtemplate_updated_at_e370f5c5",
            ),
        ),
        migrations.AddIndex(
            model_name="pduxlsxupload",
            index=hope.models.utils.LongNameIndex(
                fields=["created_at"],
                name="periodic_data_update_pduxlsxupload_created_at_5ad6c4ee",
            ),
        ),
        migrations.AddIndex(
            model_name="pduxlsxupload",
            index=hope.models.utils.LongNameIndex(
                fields=["updated_at"],
                name="periodic_data_update_pduxlsxupload_updated_at_fa057243",
            ),
        ),
    ]
