# Generated by Django 3.2.20 on 2023-09-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0008_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='copied_from',
            field=models.ForeignKey(blank=True, help_text='If this object was copied from another, this field will contain the object it was copied from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_to', to='accountability.feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_migration_handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='copied_from',
            field=models.ForeignKey(blank=True, help_text='If this object was copied from another, this field will contain the object it was copied from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_to', to='accountability.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_migration_handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
    ]
