# Generated by Django 2.2.8 on 2020-04-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_migration'),
        ('targeting', '0001_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashplan',
            name='target_population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_plans', to='targeting.TargetPopulation'),
        ),
    ]
