# Generated by Django 2.2.8 on 2020-01-14 12:42

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashplan',
            name='currency',
            field=models.CharField(default='Indian Rupee', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashplan',
            name='dispersion_date',
            field=models.DateField(default=datetime.date(2020, 1, 14)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashplan',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('STARTED', 'STARTED'), ('COMPLETE', 'COMPLETE')], default='STARTED', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashplan',
            name='total_delivered_quantity',
            field=models.DecimalField(decimal_places=2, default=120000.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashplan',
            name='total_entitled_quantity',
            field=models.DecimalField(decimal_places=2, default=30000.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashplan',
            name='total_undelivered_quantity',
            field=models.DecimalField(decimal_places=2, default=20000.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='cash_plus',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='frequency_of_payments',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('ONE_OFF', 'One-off')], default='REGULAR', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='population_goal',
            field=models.PositiveIntegerField(default=500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='scope',
            field=models.CharField(choices=[('FULL', 'Full'), ('PARTIAL', 'Partial'), ('NO_INTEGRATION', 'No Integration')], default='FULL', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='sector',
            field=models.CharField(choices=[('CHILD', 'Child'), ('PROTECTION', 'Protection'), ('EDUCATION', 'Education'), ('GENDER', 'Gender'), ('HEALTH', 'Health'), ('HIV_AIDS', 'HIV / AIDS'), ('MULTI_PURPOSE', 'Multi Purpose'), ('NUTRITION', 'Nutrition'), ('SOCIAL_POLICY', 'Social Policy'), ('WASH', 'WASH')], default='EDUCATION', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
