# Generated by Django 2.2.8 on 2020-01-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashplan',
            name='assistanceThrough',
            field=models.CharField(default='Cairo Amman Bank', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashplan',
            name='deliveryType',
            field=models.CharField(default='Deposit to Card', max_length=255),
            preserve_default=False,
        ),
    ]
