# Generated by Django 2.2.8 on 2020-01-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='administrative_areas_of_implementation',
            field=models.CharField(default='Lorem Ipsum', max_length=255),
            preserve_default=False,
        ),
    ]
