# Generated by Django 2.2.8 on 2020-02-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashplan',
            old_name='assistanceThrough',
            new_name='assistance_through',
        ),
        migrations.RenameField(
            model_name='cashplan',
            old_name='deliveryType',
            new_name='delivery_type',
        ),
    ]
