# Generated by Django 2.2.8 on 2020-02-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(),
        ),
    ]
