# Generated by Django 2.2.8 on 2020-06-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashplan',
            name='last_sync_at',
            field=models.DateTimeField(null=True),
        ),
    ]
