# Generated by Django 2.2.8 on 2020-09-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashplan',
            name='comments',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
