# Generated by Django 2.2.16 on 2021-01-21 13:39

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0017_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
    ]
