# Generated by Django 2.2.16 on 2021-02-16 13:11

from decimal import Decimal
import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0021_migration'),
        ('steficon', '0002_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashplan',
            name='assistance_measurement',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='assistance_through',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='delivery_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('DEPOSIT_TO_CARD', 'Deposit to Card'), ('TRANSFER', 'Transfer')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='end_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='start_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='status',
            field=models.CharField(choices=[('Distribution Completed', 'Distribution Completed'), ('Distribution Completed with Errors', 'Distribution Completed with Errors'), ('Transaction Completed', 'Transaction Completed'), ('Transaction Completed with Errors', 'Transaction Completed with Errors')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='total_delivered_quantity',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='total_entitled_quantity',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='total_entitled_quantity_revised',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='total_persons_covered',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='total_persons_covered_revised',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='total_undelivered_quantity',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cashplan',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='program',
            name='budget',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='program',
            name='ca_hash_id',
            field=django.contrib.postgres.fields.citext.CICharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='ca_id',
            field=django.contrib.postgres.fields.citext.CICharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='program',
            name='sector',
            field=models.CharField(choices=[('CHILD_PROTECTION', 'Child Protection'), ('EDUCATION', 'Education'), ('HEALTH', 'Health'), ('MULTI_PURPOSE', 'Multi Purpose'), ('NUTRITION', 'Nutrition'), ('SOCIAL_POLICY', 'Social Policy'), ('WASH', 'WASH')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
