# Generated by Django 2.2.26 on 2022-02-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0030_migration'),
        ('payment', '0035_migration'),

    ]

    operations = [
        migrations.RemoveField(
            model_name='cashplan',
            name='verification_status',
        ),
    ]
