# Generated by Django 3.2.13 on 2022-07-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0034_migration"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[migrations.AlterModelTable("CashPlan", "payment_cashplan")],
        )
    ]
