# Generated by Django 3.2.15 on 2023-01-13 11:03

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0135_migration'),
        ('program', '0034_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPopulationThrough',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('eligible', models.BooleanField(default=False)),
                ('vulnerability_score', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_to_household_through', to='household.household')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_to_household_through', to='program.program')),
            ],
            options={
                'verbose_name': 'Program to Household',
                'ordering': ['created_at'],
                'unique_together': {('program', 'household')},
            },
        ),
        migrations.AddField(
            model_name='program',
            name='program_population',
            field=models.ManyToManyField(blank=True, related_name='programs', through='program.ProgramPopulationThrough', to='household.Household'),
        ),
    ]
