# Generated by Django 3.2.15 on 2023-01-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0135_migration"),
        ("program", "0035_migration"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProgramPopulationThrough",
            new_name="HouseholdProgramPopulationThrough",
        ),
        migrations.RemoveField(
            model_name="program",
            name="program_population",
        ),
        migrations.AddField(
            model_name="program",
            name="household_program_population",
            field=models.ManyToManyField(
                blank=True,
                related_name="programs",
                through="program.HouseholdProgramPopulationThrough",
                to="household.Household",
            ),
        ),
    ]
