# Generated by Django 3.2.18 on 2023-05-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0037_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programcycle',
            options={'ordering': ['program', 'iteration'], 'verbose_name': 'ProgrammeCycle'},
        ),
        migrations.AlterField(
            model_name='program',
            name='individual_data_needed',
            field=models.BooleanField(default=False, help_text="\n        This boolean decides whether the target population sync will send\n        all individuals of a household that's part of the population or only\n        the relevant ones (collectors etc.)"),
        ),
    ]
