# Generated by Django 3.2.20 on 2023-08-22 17:37

import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0038_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcycle',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(default='Default Program Cycle', max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255), django.core.validators.RegexValidator('\\s{2,}', 'Double spaces characters are not allowed.', code='double_spaces_characters_not_allowed', inverse_match=True), django.core.validators.RegexValidator('(^\\s+)|(\\s+$)', 'Leading or trailing spaces characters are not allowed.', code='leading_trailing_spaces_characters_not_allowed', inverse_match=True), django.core.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterUniqueTogether(
            name='programcycle',
            unique_together={('iteration', 'program'), ('name', 'program')},
        ),
        migrations.RemoveField(
            model_name='programcycle',
            name='description',
        ),
    ]
