# Generated by Django 3.2.20 on 2023-10-02 15:00

import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0040_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programcycle',
            options={'ordering': ['start_date'], 'verbose_name': 'ProgrammeCycle'},
        ),
        migrations.AddField(
            model_name='programcycle',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(default='Default Program Cycle', max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255), django.core.validators.RegexValidator('\\s{2,}', 'Double spaces characters are not allowed.', code='double_spaces_characters_not_allowed', inverse_match=True), django.core.validators.RegexValidator('(^\\s+)|(\\s+$)', 'Leading or trailing spaces characters are not allowed.', code='leading_trailing_spaces_characters_not_allowed', inverse_match=True), django.core.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AddField(
            model_name='programcycle',
            name='unicef_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programcycle',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished')], db_index=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='programcycle',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='programcycle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False)), fields=('name', 'program', 'is_removed'), name='program_cycle_name_unique_if_not_removed'),
        ),
        migrations.RemoveField(
            model_name='programcycle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='programcycle',
            name='iteration',
        ),
    ]
