# Generated by Django 3.2.23 on 2024-01-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0042_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='household_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='program',
            name='individual_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
