# Generated by Django 3.2.25 on 2024-04-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0047_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpartnerthrough',
            name='full_area_access',
            field=models.BooleanField(default=False),
        ),
    ]
