# Generated by Django 3.2.25 on 2024-04-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0048_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='partner_access',
            field=models.CharField(choices=[('ALL_PARTNERS_ACCESS', 'All partners access'), ('NONE_PARTNERS_ACCESS', 'None partners access'), ('SELECTED_PARTNERS_ACCESS', 'Selected partners access')], default='SELECTED_PARTNERS_ACCESS', max_length=50),
        ),
    ]
