# Generated by Django 3.2.25 on 2024-09-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0051_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programcycle',
            options={'ordering': ['start_date'], 'verbose_name': 'Programme Cycle'},
        ),
        migrations.RemoveConstraint(
            model_name='programcycle',
            name='program_cycle_name_unique_if_not_removed',
        ),
        migrations.RemoveField(
            model_name='programcycle',
            name='is_removed',
        ),
        migrations.AddConstraint(
            model_name='programcycle',
            constraint=models.UniqueConstraint(fields=('title', 'program'), name='program_cycle_title_unique_per_program'),
        ),
    ]
