# Generated by Django 5.2.11 on 2026-03-04 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sanction_list", "0003_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sanctionlistindividualaliasname",
            options={
                "ordering": ("name",),
                "verbose_name": "Alias",
                "verbose_name_plural": "Aliases",
            },
        ),
        migrations.AlterModelOptions(
            name="sanctionlistindividualcountries",
            options={
                "ordering": ("id",),
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.AlterModelOptions(
            name="sanctionlistindividualdateofbirth",
            options={"ordering": ("id",), "verbose_name": "Birthday"},
        ),
        migrations.AlterModelOptions(
            name="sanctionlistindividualdocument",
            options={
                "ordering": ("id",),
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="sanctionlistindividualnationalities",
            options={
                "ordering": ("id",),
                "verbose_name": "Nationality",
                "verbose_name_plural": "Nationalities",
            },
        ),
    ]
