# Generated by Django 5.2.12 on 2026-04-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sanction_list", "0004_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sanctionlist",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("refresh", "Can Refresh Sanction List"),
                    ("empty", "Can Empty Sanction List"),
                ),
            },
        ),
    ]
