# Generated by Django 5.2.15 on 2026-07-28 09:00

from django.db import migrations, models

import hope.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("sanction_list", "0007_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedxlsxfile",
            name="file",
            field=models.FileField(
                max_length=255, upload_to=hope.models.utils.UniqueUploadPath("sanction_list_upload")
            ),
        ),
    ]
