# Generated by Django 3.2.25 on 2025-01-22 18:59
from django.db import migrations

from hct_mis_api.apps.account.migration_utils import migrate_user_roles_logic, migrate_partner_roles_and_access_logic, migrate_unicef_partners_logic


def migrate_user_roles(apps, schema_editor):
    """
    Handle migration of user roles.
    UserRole model was replaced with RoleAssignment model, which includes a program field.
    After model update, existing UserRoles would have program=null, granting users access to all programs by default.
    This migration will fetch the programs for specific Business Areas from UserRole
    and create RoleAssignment entries for each program to preserve the original access.
    """
    migrate_user_roles_logic(apps)


def migrate_partner_roles_and_access(apps, schema_editor):
    """
    Handle migration of partner roles and access.
    ProgramPartnerThrough and BusinessAreaPartnerThrough models need to be migrated into RoleAssignment model.
    For each combination of role in the BusinessAreaPartnerThrough and a program in the ProgramPartnerThrough,
    that partner has access to within the BA of the role -> the RoleAssignment entry needs to be created.

    Additionally, area access defined on areas filed in ProgramPartnerThrough needs to be moved to
    AdminAreaLimitedTo model and the logic needs changing - create records in the AdminAreaLimitedTo only
    if this is NOT a full-area-access - so if there are area limits applied.
    """
    migrate_partner_roles_and_access_logic(apps)


def migrate_unicef_partners(apps, schema_editor):
    """
    Handle migration of UNICEF partner into UNICEF HQ and UNICEF Partners per BusinessArea.
    UNICEF partner will become parent Partner for UNICEF HQ and UNICEF Partners per BusinessArea.

    UNICEF HQ will hold "Role with all permissions" for all Business Areas (with program=None so whole BA access)
    UNICEF Partners per BusinessArea will hold role with permissions specified in DEFAULT_PERMISSIONS_IS_UNICEF_PARTNER
    within the Business Area specific for them. Within this BA they will have access to all programs.

    Users currently assigned to UNICEF partner will be assigned to UNICEF HQ and UNICEF Partners per BusinessArea based on their roles.
    If user holds roles in multiple Business Areas, they will be assigned to UNICEF HQ.
    """
    migrate_unicef_partners_logic(apps)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_migration'),
    ]

    operations = [
        migrations.RunPython(migrate_user_roles, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(migrate_partner_roles_and_access, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(migrate_unicef_partners, reverse_code=migrations.RunPython.noop),
    ]

