# Generated by Django 3.2.25 on 2025-01-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_migration'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('program__isnull', True), ('user__isnull', False)), fields=('user', 'role', 'business_area'), name='unique_user_role_business_area_no_program'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('partner__isnull', False), ('program__isnull', True)), fields=('partner', 'role', 'business_area'), name='unique_partner_role_business_area_no_program'),
        ),
    ]
