# Generated by Django 3.2.25 on 2025-01-30 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available_for_export',
        ),
        migrations.AlterField(
            model_name='user',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.partner'),
        ),
    ]
