# Generated by Django 3.2.24 on 2024-02-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='After expiry date this User Role will be ignored.', null=True),
        ),
    ]
