# Generated by Django 3.2.23 on 2024-02-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='After expiry date this User Role will be inactive.', null=True),
        ),
    ]
