# Generated by Django 3.2.25 on 2024-03-17 00:36

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_migration'),
        ('account', '0065_migration'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='partner',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='allowed_business_areas',
            field=models.ManyToManyField(to='core.BusinessArea'),
        ),
    ]
