# Generated by Django 3.2.18 on 2023-06-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0001_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.IntegerField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('storage', models.BinaryField(blank=True, null=True)),
                ('ignored', models.BooleanField(blank=True, db_index=True, default=False, null=True)),
                ('source_id', models.IntegerField(db_index=True)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('TO_IMPORT', 'To import'), ('IMPORTED', 'Imported'), ('ERROR', 'Error')], max_length=16, null=True)),
                ('unique_field', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('counters', models.JSONField(blank=True, null=True)),
                ('fields', models.JSONField(blank=True, null=True)),
                ('files', models.BinaryField(blank=True, null=True)),
                ('index1', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('index2', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('index3', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'swappable': 'AURORA_RECORD_MODEL',
            },
        ),
    ]
