# Generated by Django 3.2.18 on 2023-05-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("power_query", "0007_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="last_run",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formatter",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("csv", "text/csv"),
                    ("html", "text/html"),
                    ("json", "application/json"),
                    ("txt", "text/plain"),
                    ("xls", "application/vnd.ms-excel"),
                    ("xml", "application/xml"),
                    ("yaml", "text/yaml"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="reportdocument",
            name="content_type",
            field=models.CharField(choices=[], max_length=5),
        ),
    ]
