# Generated by Django 2.2.5 on 2019-12-12 13:51

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('cash_assist_id', models.CharField(max_length=255)),
                ('delivery_type', models.CharField(choices=[('DELIVERED', 'Delivered'), ('IN_PROGRESS', 'In Progress')], max_length=255)),
                ('cash_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='program.CashPlan')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='household.Household')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
