# Generated by Django 3.2.19 on 2023-06-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_migration'),
        ('program', '0001_migration'),
        ('household', '0002_migration'),
        ('targeting', '0001_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecordverification',
            name='verification_process',
        ),
        migrations.DeleteModel(
            name='PaymentEntitlement',
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
        migrations.DeleteModel(
            name='PaymentRecordVerification',
        ),
        migrations.DeleteModel(
            name='VerificationProcess',
        ),
    ]
