# Generated by Django 3.2.19 on 2023-06-11 10:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0003_migration_squashed_0086_migration'),
        ('core', '0002_migration_squashed_0006_migration'),
        ('program', '0002_migration_squashed_0020_migration'),
        ('targeting', '0006_migration'),
        ('payment', '0002_migration_squashed_0003_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ca_id', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=3)),
                ('vision_id', models.CharField(max_length=255)),
                ('business_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.businessarea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Sucess'), ('PENDING', 'Pending'), ('ERROR', 'Error')], max_length=255)),
                ('status_date', models.DateTimeField()),
                ('ca_id', models.CharField(max_length=255, null=True)),
                ('ca_hash_id', models.UUIDField(null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('total_persons_covered', models.IntegerField()),
                ('distribution_modality', models.CharField(max_length=255)),
                ('target_population_cash_assist_id', models.CharField(max_length=255)),
                ('entitlement_card_number', models.CharField(max_length=255)),
                ('entitlement_card_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('entitlement_card_issue_date', models.DateField()),
                ('delivery_type', models.CharField(choices=[('CASH', 'Cash'), ('DEPOSIT_TO_CARD', 'Deposit to Card'), ('TRANSFER', 'Transfer')], default='ACTIVE', max_length=20)),
                ('currency', models.CharField(max_length=4)),
                ('entitlement_quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('delivered_quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('delivery_date', models.DateTimeField()),
                ('business_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.businessarea')),
                ('cash_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='program.cashplan')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='household.household')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='payment.serviceprovider')),
                ('target_population', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='targeting.targetpopulation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashPlanPaymentVerification',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished')], default='PENDING', max_length=50)),
                ('sampling', models.CharField(choices=[('FULL_LIST', 'Full list'), ('RANDOM', 'Draft')], max_length=50)),
                ('verification_method', models.CharField(choices=[('RAPIDPRO', 'RAPIDPRO'), ('XLSX', 'XLSX'), ('MANUAL', 'MANUAL')], max_length=50)),
                ('sample_size', models.PositiveIntegerField(null=True)),
                ('responded_count', models.PositiveIntegerField(null=True)),
                ('received_count', models.PositiveIntegerField(null=True)),
                ('not_received_count', models.PositiveIntegerField(null=True)),
                ('received_with_problems_count', models.PositiveIntegerField(null=True)),
                ('cash_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='program.cashplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentVerification',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('NOT_RECEIVED', 'NOT RECEIVED'), ('RECEIVED_WITH_ISSUES', 'RECEIVED WITH ISSUES')], default='DRAFT', max_length=50)),
                ('status_date', models.DateField(null=True)),
                ('cash_plan_payment_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_record_verifications', to='payment.cashplanpaymentverification')),
                ('payment_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='payment.paymentrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
