# Generated by Django 2.2.8 on 2020-05-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0003_migration'),
        ('payment', '0004_migration'),
        ('program', '0005_migration'),
        ('targeting', '0006_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='cash_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='program.CashPlan'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='household.Household'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='payment.ServiceProvider'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='target_population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='targeting.TargetPopulation'),
        ),
    ]
