# Generated by Django 2.2.8 on 2020-07-14 11:48

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_migration'),
        ('payment', '0008_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPlanPaymentVerification',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished')], default='PENDING', max_length=50)),
                ('sampling', models.CharField(choices=[('FULL_LIST', 'Full list'), ('RANDOM', 'Draft')], max_length=50)),
                ('verification_method', models.CharField(choices=[('RAPIDPRO', 'RAPIDPRO'), ('XLSX', 'XLSX'), ('MANUAL', 'MANUAL')], max_length=50)),
                ('sample_size', models.PositiveIntegerField(null=True)),
                ('responded_count', models.PositiveIntegerField(null=True)),
                ('received_count', models.PositiveIntegerField(null=True)),
                ('not_received_count', models.PositiveIntegerField(null=True)),
                ('received_with_problems_count', models.PositiveIntegerField(null=True)),
                ('cash_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='program.CashPlan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentVerification',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('NOT_RECEIVED', 'NOT RECEIVED'), ('RECEIVED_WITH_ISSUES', 'RECEIVED WITH ISSUES')], default='DRAFT', max_length=50)),
                ('status_date', models.DateField(null=True)),
                ('cash_plan_payment_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_record_verifications', to='payment.CashPlanPaymentVerification')),
                ('payment_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='payment.PaymentRecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
