# Generated by Django 2.2.8 on 2020-07-09 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashplanpaymentverification',
            name='cash_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='program.CashPlan'),
        ),
    ]
