# Generated by Django 2.2.8 on 2020-07-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashplanpaymentverification',
            name='sampling',
            field=models.CharField(choices=[('FULL_LIST', 'Full list'), ('RANDOM', 'Random sampling')], max_length=50),
        ),
    ]
