# Generated by Django 2.2.8 on 2020-08-27 09:00

from django.db import migrations

def change_all_rapidpro_to_pending(apps, schema_editor):
    CashPlanPaymentVerification = apps.get_model("payment", "CashPlanPaymentVerification")
    CashPlanPaymentVerification.objects.filter(
        verification_method="RAPIDPRO",
    ).update(status="PENDING")

def empty_reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_migration'),
    ]

    operations = [
        migrations.RunPython(change_all_rapidpro_to_pending, empty_reverse),
    ]
