# Generated by Django 2.2.16 on 2021-02-01 19:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


def populate_existing_payment_record_usd_amount(apps, schema_editor):
    PaymentRecord = apps.get_model("payment", "PaymentRecord")
    all_payment_records = PaymentRecord.objects.all()

    for payment_record in all_payment_records:
        exchange_rate = payment_record.cash_plan.exchange_rate if payment_record.cash_plan else None
        if exchange_rate:
            payment_record.delivered_quantity_usd = Decimal(payment_record.delivered_quantity * exchange_rate).quantize(
                Decimal(".01")
            )
    PaymentRecord.objects.bulk_update(all_payment_records, ["delivered_quantity_usd"])


def empty_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("payment", "0019_migration"), ("program", "0019_migration")]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="delivered_quantity_usd",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.RunPython(populate_existing_payment_record_usd_amount, empty_reverse),
    ]
