# Generated by Django 2.2.16 on 2022-01-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='short_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='vision_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
