# Generated by Django 3.2 on 2022-02-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashplanpaymentverification',
            name='age_filter',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='cashplanpaymentverification',
            name='excluded_admin_areas_filter',
            field=models.JSONField(null=True),
        ),
    ]
