# Generated by Django 2.2.26 on 2022-02-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0041_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashplanpaymentverification',
            old_name='verification_method',
            new_name='verification_channel',
        ),
    ]
