# Generated by Django 3.2.12 on 2022-04-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0043_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashplanpaymentverificationsummary',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('FINISHED', 'Finished'), ('PENDING', 'Pending')], db_index=True, default='PENDING', max_length=50, verbose_name='Verification status'),
        ),
    ]
