# Generated by Django 3.2.13 on 2022-08-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0053_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='dispersion_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='dispersion_start_date',
            field=models.DateField(),
        ),
    ]
