# Generated by Django 3.2.13 on 2022-08-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0057_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='unicef_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='unicef_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
