# Generated by Django 3.2.13 on 2022-08-31 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0061_migration'),
        ('payment', '0062_migration'),
    ]

    operations = [
    ]
