# Generated by Django 3.2.15 on 2022-09-13 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0119_migration'),
        ('core', '0059_migration'),
        ('payment', '0068_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentplan',
            old_name='xlsx_file_imported_date',
            new_name='imported_file_date',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='export_per_fsp_zip_file',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='export_xlsx_file',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='imported_xlsx_file',
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='export_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.filetemp'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='imported_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.filetemp'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='assigned_payment_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.paymentchannel'),
        ),
        migrations.AlterField(
            model_name='paymentchannel',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_channels', to='household.individual'),
        ),
    ]
