# Generated by Django 3.2.15 on 2022-09-18 16:00

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0069_migration'),
    ]

    operations = [
        migrations.RenameModel('CashPlanPaymentVerification', 'PaymentVerificationPlan'),
        migrations.RenameModel('XlsxCashPlanPaymentVerificationFile', 'XlsxPaymentVerificationPlanFile'),
        migrations.RenameModel('CashPlanPaymentVerificationSummary', 'PaymentVerificationSummary'),
        migrations.RenameField(
            model_name='xlsxpaymentverificationplanfile',
            old_name='cash_plan_payment_verification',
            new_name='payment_verification_plan',
        ),
        migrations.RenameField(
            model_name='paymentverification',
            old_name='cash_plan_payment_verification',
            new_name='payment_verification_plan',
        ),
        migrations.AlterField(
            model_name='paymentverificationplan',
            name='cash_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='verification_plans', to='payment.cashplan'),
        ),
        migrations.AlterField(
            model_name='paymentverificationsummary',
            name='cash_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='payment_verification_summary', to='payment.cashplan'),
        ),
        migrations.AlterField(
            model_name='xlsxpaymentverificationplanfile',
            name='payment_verification_plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='xlsx_verification_file', to='payment.paymentverificationplan'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='status',
            field=django_fsm.FSMField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('LOCKED_FSP', 'Locked FSP'),
                                               ('IN_APPROVAL', 'In Approval'), ('IN_AUTHORIZATION', 'In Authorization'),
                                               ('IN_REVIEW', 'In Review'), ('ACCEPTED', 'Accepted'),
                                               ('RECONCILED', 'Reconciled')], db_index=True, default='OPEN',
                                      max_length=50),
        ),
    ]
