# Generated by Django 3.2.15 on 2022-09-23 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0071_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentverificationplan',
            name='payment_plan_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='paymentverificationplan',
            name='payment_plan_object_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentverificationsummary',
            name='payment_plan_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='paymentverificationsummary',
            name='payment_plan_object_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
