# Generated by Django 3.2.15 on 2022-10-04 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0074_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentverificationplan',
            name='cash_plan',
        ),
        migrations.RemoveField(
            model_name='paymentverificationsummary',
            name='cash_plan',
        ),
        migrations.AddField(
            model_name='paymentverification',
            name='payment_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='paymentverification',
            name='payment_object_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='paymentverification',
            constraint=models.UniqueConstraint(fields=('payment_content_type', 'payment_object_id'), name='payment_content_type_and_payment_id'),
        ),
        migrations.AddConstraint(
            model_name='paymentverificationsummary',
            constraint=models.UniqueConstraint(fields=('payment_plan_content_type', 'payment_plan_object_id'), name='payment_plan_content_type_and_payment_plan_id'),
        ),
    ]
