# Generated by Django 3.2.15 on 2023-02-10 15:07

from decimal import Decimal
import django.contrib.postgres.fields.ranges
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import psycopg2.extras
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_migration'),
        ('payment', '0085_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceProcessThreshold',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('payments_range_usd', django.contrib.postgres.fields.ranges.IntegerRangeField(default=psycopg2.extras.NumericRange(0, None, '[)'), validators=[django.contrib.postgres.validators.RangeMinValueValidator(0)])),
                ('approval_number_required', models.PositiveIntegerField(default=1)),
                ('authorization_number_required', models.PositiveIntegerField(default=1)),
                ('finance_review_number_required', models.PositiveIntegerField(default=1)),
                ('business_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptance_process_thresholds', to='core.businessarea')),
            ],
            options={
                'ordering': ('payments_range_usd',),
            },
        ),
    ]
