# Generated by Django 3.2.15 on 2023-02-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0087_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalprocess',
            name='approval_number_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='approvalprocess',
            name='authorization_number_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='approvalprocess',
            name='finance_release_number_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Distribution Successful', 'Distribution Successful'), ('Not Distributed', 'Not Distributed'), ('Transaction Successful', 'Transaction Successful'), ('Transaction Erroneous', 'Transaction Erroneous'), ('Force failed', 'Force failed'), ('Partially Distributed', 'Partially Distributed'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('Distribution Successful', 'Distribution Successful'), ('Not Distributed', 'Not Distributed'), ('Transaction Successful', 'Transaction Successful'), ('Transaction Erroneous', 'Transaction Erroneous'), ('Force failed', 'Force failed'), ('Partially Distributed', 'Partially Distributed'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
    ]
