# Generated by Django 3.2.18 on 2023-03-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0090_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='female_adults_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='female_children_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='male_adults_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='male_children_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='total_households_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='total_individuals_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
