# Generated by Django 3.2.18 on 2023-03-23 21:56

from django.db import migrations, models
import django.db.models.deletion


def remove_payment_plan_old_export_file(apps, schema_editor):
    PaymentPlan = apps.get_model("payment", "PaymentPlan")

    for pp in PaymentPlan.objects.exclude(export_file__isnull=True):
        pp.export_file.file.delete(save=False)
        pp.export_file.delete()
        pp.export_file = None
        pp.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_migration"),
        ("payment", "0091_migration"),
    ]

    operations = [
        migrations.RunSQL("SET CONSTRAINTS ALL IMMEDIATE;"),
        migrations.RunPython(remove_payment_plan_old_export_file, migrations.RunPython.noop),
        migrations.RunSQL("SET CONSTRAINTS ALL DEFERRED;"),
        migrations.RenameField(
            model_name="paymentplan",
            old_name="export_file",
            new_name="export_file_entitlement",
        ),
        migrations.AddField(
            model_name="paymentplan",
            name="export_file_per_fsp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.filetemp",
            ),
        ),
    ]
