<<<<<<< HEAD
# Generated by Django 3.2.18 on 2023-04-17 11:41
=======
# Generated by Django 3.2.18 on 2023-04-25 07:13
>>>>>>> origin/followup-pp

from django.db import migrations, models
import django.db.models.deletion


<<<<<<< HEAD
def populate_program_cycles(apps, schema_editor):
    PaymentPlan = apps.get_model("payment", "PaymentPlan")
    payment_plans = []
    for pp in PaymentPlan.objects.all():
        pp.program_cycle = pp.program.cycles.first()
        payment_plans.append(pp)

    PaymentPlan.objects.bulk_update(payment_plans, ['program_cycle'])


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0037_migration'),
=======
class Migration(migrations.Migration):

    dependencies = [
>>>>>>> origin/followup-pp
        ('payment', '0095_migration'),
    ]

    operations = [
<<<<<<< HEAD
        migrations.AddField(
            model_name='paymentplan',
            name='program_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.programcycle'),
        ),
        migrations.RunPython(populate_program_cycles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='paymentplan',
            name='program_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programcycle'),
=======
        migrations.RenameField(
            model_name='payment',
            old_name='excluded',
            new_name='conflicted',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='source_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='is_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='source_payment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='payment.paymentplan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='excluded',
            field=models.BooleanField(default=False),
>>>>>>> origin/followup-pp
        ),
    ]
