# Generated by Django 3.2.18 on 2023-04-17 11:41

from django.db import migrations, models
import django.db.models.deletion


def populate_program_cycles(apps, schema_editor):
    PaymentPlan = apps.get_model("payment", "PaymentPlan")
    payment_plans = []
    for pp in PaymentPlan.objects.all():
        pp.program_cycle = pp.program.cycles.first()
        payment_plans.append(pp)

    PaymentPlan.objects.bulk_update(payment_plans, ['program_cycle'])


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0037_migration'),
        ('payment', '0096_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='program_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.programcycle'),
        ),
        migrations.RunPython(populate_program_cycles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='paymentplan',
            name='program_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programcycle'),
        ),
    ]
