# Generated by Django 3.2.18 on 2023-05-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0101_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='exclude_household_error',
            field=models.TextField(blank=True),
        ),
    ]
