# Generated by Django 3.2.19 on 2023-07-07 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_migration_squashed_0067_migration'),
        ('payment', '0103_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='export_pdf_file_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.filetemp'),
        ),
    ]
