# Generated by Django 3.2.23 on 2024-02-21 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0117_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True,
                                   validators=[django.core.validators.MinLengthValidator(3),
                                               django.core.validators.MaxLengthValidator(255)]),
        ),
    ]
