# Generated by Django 3.2.25 on 2024-09-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_migration'),
        ('payment', '0143_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialserviceprovider',
            name='allowed_business_areas',
            field=models.ManyToManyField(blank=True, to='core.BusinessArea'),
        ),
    ]
