# Generated by Django 3.2.12 on 2022-03-18 09:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('household', '0002_migration'), ('household', '0003_migration'), ('household', '0004_migration'), ('household', '0005_migration'), ('household', '0006_migration'), ('household', '0007_migration'), ('household', '0008_migration'), ('household', '0009_migration'), ('household', '0010_migration'), ('household', '0011_migration')]

    dependencies = [
        ('household', '0001_migration'),
        ('program', '0001_migration'),
        ('registration_data', '0001_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='households', to='program.Program'),
        ),
        migrations.AddField(
            model_name='household',
            name='registration_data_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='registration_data.registrationdataimport'),
        ),
        migrations.AddField(
            model_name='entitlementcard',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlement_cards', to='household.household'),
        ),
        migrations.AddField(
            model_name='documentvalidator',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validators', to='household.documenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='household.individual'),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='household.documenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='individualidentity',
            unique_together={('agency', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('type', 'document_number')},
        ),
        migrations.AddField(
            model_name='documenttype',
            name='type',
            field=models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('DRIVERS_LICENSE', "Driver's License"), ('NATIONAL_ID', 'National ID'), ('NATIONAL_PASSPORT', 'National Passport'), ('ELECTORAL_CARD', 'Electoral Card'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='documenttype',
            unique_together={('country', 'type')},
        ),
        migrations.AlterField(
            model_name='agency',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='household',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='individual',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='last_sync_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='last_sync_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='administration_of_rutf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='enrolled_in_nutrition_programme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='work_status',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NOT_PROVIDED', 'Not provided')], default='NOT_PROVIDED', max_length=20),
        ),
        migrations.RemoveField(
            model_name='household',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='household',
            name='first_registration_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 14, 13, 42, 33, 98340)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='last_registration_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 14, 13, 42, 42, 836944)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='first_registration_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 14, 13, 42, 49, 586301)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='last_registration_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 14, 13, 42, 54, 763979)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='unicef_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='individual',
            name='unicef_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
