# Generated by Django 2.2.8 on 2020-05-12 13:01

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Concat


def remove_duplicates(apps, schema_editor):
    DocumentType = apps.get_model("household", "DocumentType")

    master_qs_types = DocumentType.objects.annotate(
        concat_country_label=Concat(
            F("label"), F("country"), output_field=models.CharField(),
        ),
    ).distinct("concat_country_label")

    for master in master_qs_types:
        DocumentType.objects.filter(
            country=master.country, label=master.label
        ).exclude(pk=master.pk).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("household", "0002_migration"),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
    ]
