# Generated by Django 2.2.8 on 2020-05-12 13:01

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Concat





class Migration(migrations.Migration):
    dependencies = [
        ("household", "0002_migration"),
    ]

    operations = [
    ]
