# Generated by Django 2.2.8 on 2020-05-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0004_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
