# Generated by Django 2.2.8 on 2020-02-18 08:06

import django.core.validators
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0004_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='consent',
            field=sorl.thumbnail.fields.ImageField(upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='individual',
            name='first_name',
            field=models.CharField(max_length=125, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(125)]),
        ),
        migrations.AlterField(
            model_name='individual',
            name='full_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='individual',
            name='last_name',
            field=models.CharField(max_length=125, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(125)]),
        ),
    ]
