# Generated by Django 2.2.8 on 2020-06-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0006_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='last_sync_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='last_sync_at',
            field=models.DateTimeField(null=True),
        ),
    ]
