# Generated by Django 2.2.8 on 2020-02-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0007_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='disability',
            field=models.CharField(choices=[('NO', 'No'), ('SEEING', 'Difficulty seeing (even if wearing glasses)'), ('HEARING', 'Difficulty hearing (even if using a hearing aid)'), ('WALKING', 'Difficulty walking or climbing steps'), ('MEMORY', 'Difficulty remembering or concentrating'), ('SELF_CARE', 'Difficulty with self care (washing, dressing)'), ('COMMUNICATING', 'Difficulty communicating (e.g understanding or being understood)')], default='NO', max_length=30),
        ),
    ]
