# Generated by Django 2.2.8 on 2020-07-10 12:00

from django.db import migrations, models
import household.models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0009_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='unicef_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='household',
            name='unicef_id_index',
            field=household.models.SerialField(),
        ),
        migrations.AddField(
            model_name='individual',
            name='unicef_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='individual',
            name='unicef_id_index',
            field=household.models.SerialField(),
        ),
    ]
