# Generated by Django 2.2.8 on 2020-03-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_migration'),
        ('household', '0009_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='households', to='program.Program'),
        ),
    ]
