# Generated by Django 2.2.8 on 2020-04-08 11:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0012_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='flex_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='individual',
            name='flex_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
