# Generated by Django 2.2.8 on 2020-08-07 09:31

from django.db import migrations, models
import django.db.models.deletion




class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_migration"),
        ("household", "0014_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="business_area",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.BusinessArea",
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="business_area",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.BusinessArea",
            ),
        ),
    ]
