# Generated by Django 2.2.8 on 2020-04-22 14:37

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0018_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='birth_certificate_no',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='birth_certificate_photo',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='drivers_license_no',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='drivers_license_photo',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='electoral_card_no',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='electoral_card_photo',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='national_passport',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='national_passport_photo',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='other_id_no',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='other_id_photo',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='other_id_type',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='scope_id_no',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='scope_id_photo',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='unhcr_id_no',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='unhcr_id_photo',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('id_type', models.CharField(choices=[('NA', 'N/A'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('DRIVING_LICENSE', 'Driving License'), ('UNHCR_ID_CARD', 'UNHCR ID card'), ('NATIONAL_ID', 'National ID'), ('NATIONAL_PASSPORT', 'National Passport')], max_length=255)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='household.Individual')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
