# Generated by Django 2.2.8 on 2020-04-23 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_migration'),
        ('household', '0020_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='admin_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.AdminArea'),
        ),
    ]
