# Generated by Django 2.2.8 on 2020-08-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0022_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='deduplication_status',
            field=models.CharField(choices=[('UNIQUE', 'Unique'), ('DUPLICATE', 'Duplicate'), ('NEEDS_ADJUDICATION', 'Needs Adjudication'), ('NOT_PROCESSED', 'Not Processed')], default='UNIQUE', max_length=50),
        ),
    ]
