# Generated by Django 2.2.8 on 2020-09-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0025_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='sanction_list_last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
