# Generated by Django 2.2.8 on 2020-04-24 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0025_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='individual',
            name='administration_of_rutf',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='age_first_married',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='enrolled_in_nutrition_programme',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='enrolled_in_school',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='estimated_birth_date',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='minutes_to_school',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='school_attendance',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='school_type',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='serious_illness',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='work_status',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='years_in_school',
        ),
        migrations.AlterField(
            model_name='individual',
            name='disability',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=255)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='household.Agency')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='household.Individual')),
            ],
        ),
    ]
