# Generated by Django 2.2.8 on 2020-10-08 10:45

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0026_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='child_hoh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='household',
            name='consent_sign',
            field=sorl.thumbnail.fields.ImageField(default='image.png', upload_to='', validators=[django.core.validators.validate_image_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='deviceid',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='household',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='fchild_hoh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='household',
            name='name_enumerator',
            field=models.CharField(default='Default Enumerator', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='org_enumerator',
            field=models.CharField(choices=[('UNICEF', 'UNICEF'), ('PARTNER', 'Partner')], default='UNICEF', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='org_name_enumerator',
            field=models.CharField(default='TEST', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='village',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='individual',
            name='comms_disability',
            field=models.CharField(blank=True, choices=[('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AddField(
            model_name='individual',
            name='hearing_disability',
            field=models.CharField(blank=True, choices=[('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AddField(
            model_name='individual',
            name='memory_disability',
            field=models.CharField(blank=True, choices=[('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AddField(
            model_name='individual',
            name='observed_disability',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NONE', 'None'), ('SEEING', 'Difficulty seeing (even if wearing glasses)'), ('HEARING', 'Difficulty hearing (even if using a hearing aid)'), ('WALKING', 'Difficulty walking or climbing steps'), ('MEMORY', 'Difficulty remembering or concentrating'), ('SELF_CARE', 'Difficulty with self care (washing, dressing)'), ('COMMUNICATING', 'Difficulty communicating (e.g understanding or being understood)')], default='NONE', max_length=58),
        ),
        migrations.AddField(
            model_name='individual',
            name='physical_disability',
            field=models.CharField(blank=True, choices=[('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AddField(
            model_name='individual',
            name='seeing_disability',
            field=models.CharField(blank=True, choices=[('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AddField(
            model_name='individual',
            name='selfcare_disability',
            field=models.CharField(blank=True, choices=[('SOME_DIFFICULTY', 'Some difficulty'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all')], max_length=50),
        ),
        migrations.AddField(
            model_name='individual',
            name='who_answers_alt_phone',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='individual',
            name='who_answers_phone',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='household',
            name='consent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='residence_status',
            field=models.CharField(choices=[('IDP', 'Displaced  |  Internally Displaced People'), ('REFUGEE', 'Displaced  |  Refugee / Asylum Seeker'), ('OTHERS_OF_CONCERN', 'Displaced  |  Others of Concern'), ('HOST', 'Non-displaced  |   Host'), ('NON_HOST', 'Non-displaced  |   Non-host')], max_length=255),
        ),
        migrations.AlterField(
            model_name='individual',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated')], max_length=255),
        ),
    ]
