# Generated by Django 2.2.8 on 2020-10-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0026_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOW', 'Widow'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated')], max_length=255),
        ),
    ]
