# Generated by Django 2.2.8 on 2020-10-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0027_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='consent',
            field=models.BooleanField(default=True),
        ),
    ]
