# Generated by Django 2.2.16 on 2020-11-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0030_migration'),
    ]


    operations = [
    ]
