# Generated by Django 2.2.16 on 2020-12-11 10:48

from django.db import migrations

def fix_relationship(apps, schema_editor):
    Individual = apps.get_model("household", "Individual")
    Individual.objects.filter(relationship="").update(relationship="UNKNOWN")

def empty_reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('household', '0035_migration'),
    ]

    operations = [
        migrations.RunPython(fix_relationship, empty_reverse),
    ]
