# Generated by Django 2.2.8 on 2020-04-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0036_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='unhcr_case_id',
        ),
    ]
