# Generated by Django 2.2.16 on 2020-12-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0038_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='business_area',
            field=models.ForeignKey(null=False, on_delete=models.deletion.CASCADE, to='core.BusinessArea'),
        ),
    ]
