# Generated by Django 2.2.16 on 2020-12-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0040_migration'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='individual',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='household',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
