# Generated by Django 2.2.16 on 2020-12-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0043_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='deviceid',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='household',
            name='name_enumerator',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='household',
            name='org_name_enumerator',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='household',
            name='unhcr_id',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='household',
            name='unicef_id',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='household',
            name='village',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
