# Generated by Django 3.2.12 on 2022-03-18 10:37

import django.contrib.postgres.fields.citext
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    replaces = [('household', '0054_migration'), ('household', '0055_migration'), ('household', '0056_migration'), ('household', '0057_migration'), ('household', '0058_migration'), ('household', '0059_migration'), ('household', '0060_migration'), ('household', '0061_migration'), ('household', '0062_migration'), ('household', '0063_migration'), ('household', '0064_migration'), ('household', '0065_migration'), ('household', '0066_migration'), ('household', '0067_migration'), ('household', '0068_migration'), ('household', '0069_migration'), ('household', '0070_migration'), ('household', '0071_migration'), ('household', '0072_migration'), ('household', '0073_migration'), ('household', '0074_migration'), ('household', '0075_migration'), ('household', '0076_migration'), ('household', '0077_migration'), ('household', '0078_migration'), ('household', '0079_migration'), ('household', '0080_migration'), ('household', '0081_migration'), ('household', '0082_migration'), ('household', '0083_migration'), ('household', '0084_migration'), ('household', '0085_migration'), ('household', '0086_migration')]

    dependencies = [
        ('household', '0053_migration'),
        ('geo', '0003_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='documentvalidator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='documentvalidator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='entitlementcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='entitlementcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='country',
            field=django_countries.fields.CountryField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='household',
            name='country_origin',
            field=django_countries.fields.CountryField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='household',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='size',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='unhcr_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='household',
            name='unicef_id',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='household',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='withdrawn',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='household',
            name='withdrawn_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='birth_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='duplicate',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='individual',
            name='family_name',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, db_index=True, max_length=85),
        ),
        migrations.AlterField(
            model_name='individual',
            name='full_name',
            field=django.contrib.postgres.fields.citext.CICharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='individual',
            name='given_name',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, db_index=True, max_length=85),
        ),
        migrations.AlterField(
            model_name='individual',
            name='marital_status',
            field=models.CharField(choices=[('', 'None'), ('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated')], db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='individual',
            name='middle_name',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, db_index=True, max_length=85),
        ),
        migrations.AlterField(
            model_name='individual',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='individual',
            name='unicef_id',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='individual',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='withdrawn',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='individualroleinhousehold',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='individualroleinhousehold',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='sanction_list_confirmed_match',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_if_not_removed',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='VALID', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('is_removed', False), ('status', 'VALID'))), fields=('document_number', 'type'), name='unique_if_not_removed_and_valid'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('NEED_INVESTIGATION', 'Need Investigation'), ('INVALID', 'Invalid')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='agency',
            name='type',
            field=models.CharField(choices=[('WFP', 'WFP'), ('UNHCR', 'UNHCR')], max_length=100),
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(fields=('type', 'country'), name='unique_type_and_country'),
        ),
        migrations.AddField(
            model_name='individual',
            name='user_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='agency',
            name='type',
            field=models.CharField(choices=[('UNHCR', 'UNHCR'), ('WFP', 'WFP')], max_length=100),
        ),
        migrations.AlterField(
            model_name='individual',
            name='disability',
            field=models.CharField(choices=[('disabled', 'disabled'), ('not disabled', 'not disabled')], default='not disabled', max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='user_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='country',
            field=django_countries.fields.CountryField(default='U', max_length=2),
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
        migrations.AddField(
            model_name='individual',
            name='child_hoh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='fchild_hoh',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='household',
            name='admin_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adminarea'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='deduplication_batch_results',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='individual',
            name='deduplication_golden_record_results',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='individual',
            name='imported_individual_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='household',
            old_name='female_age_group_0_5_count',
            new_name='female_age_group_0_4_count',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='female_age_group_0_5_disabled_count',
            new_name='female_age_group_0_4_disabled_count',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='female_age_group_12_17_count',
            new_name='female_age_group_13_17_count',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='female_age_group_12_17_disabled_count',
            new_name='female_age_group_13_17_disabled_count',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='female_age_group_6_11_count',
            new_name='female_age_group_5_12_count',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='female_age_group_6_11_disabled_count',
            new_name='female_age_group_5_12_disabled_count',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='male_age_group_0_5_count',
            new_name='male_age_group_0_4_count',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='male_age_group_0_5_disabled_count',
            new_name='male_age_group_0_4_disabled_count',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='male_age_group_12_17_count',
            new_name='male_age_group_13_17_count',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='male_age_group_12_17_disabled_count',
            new_name='male_age_group_13_17_disabled_count',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='male_age_group_6_11_count',
            new_name='male_age_group_5_12_count',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='male_age_group_6_11_disabled_count',
            new_name='male_age_group_5_12_disabled_count',
        ),
        migrations.AddField(
            model_name='agency',
            name='country_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.country'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='country_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.country'),
        ),
        migrations.AddField(
            model_name='household',
            name='country_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.country'),
        ),
        migrations.AddField(
            model_name='household',
            name='country_origin_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.country'),
        ),
    ]
