# Generated by Django 2.2.16 on 2021-03-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0058_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='type',
            field=models.CharField(choices=[('WFP', 'WFP'), ('UNHCR', 'UNHCR')], max_length=100),
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(fields=('type', 'country'), name='unique_type_and_country'),
        ),
    ]
