# Generated by Django 2.2.16 on 2021-05-04 13:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0060_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='user_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='agency',
            name='type',
            field=models.CharField(choices=[('WFP', 'WFP'), ('UNHCR', 'UNHCR')], max_length=100),
        ),
    ]
