# Generated by Django 2.2.16 on 2021-05-24 13:28

from django.db import migrations




class Migration(migrations.Migration):

    dependencies = [
        ('household', '0063_migration'),
    ]

    operations = [
    ]
