# Generated by Django 2.2.16 on 2021-06-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0075_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='disability',
            field=models.CharField(choices=[('disabled', 'disabled'), ('not disabled', 'not disabled')], default='not disabled', max_length=20),
        ),
    ]
