# Generated by Django 2.2.16 on 2021-06-30 12:27

from django.db import migrations
from django.db.models import Case, When, Q, Value

from hct_mis_api.apps.household.models import NOT_DISABLED, DISABLED, LOT_DIFFICULTY, CANNOT_DO




def empty_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0076_migration'),
    ]

    operations = [
    ]
