# Generated by Django 2.2.16 on 2021-05-04 11:57
from itertools import zip_longest

from django.db import migrations




def empty_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0077_migration"),
    ]

    operations = [
    ]
