# Generated by Django 2.2.16 on 2021-09-13 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0081_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='admin_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.AdminArea'),
        ),
    ]
