# Generated by Django 2.2.16 on 2021-09-23 11:48

from django.db import migrations

from hct_mis_api.apps.core.core_fields_attributes import TYPE_DECIMAL
from hct_mis_api.apps.core.utils import serialize_flex_attributes, fix_flex_type_fields



class Migration(migrations.Migration):

    dependencies = [
        ('household', '0084_migration'),
    ]

    operations = [
    ]
