# Generated by Django 2.2.16 on 2021-12-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0090_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='kobo_asset_id',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
