# Generated by Django 3.2.12 on 2022-03-17 17:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0094_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['country', 'label']},
        ),
        migrations.AlterModelOptions(
            name='individualidentity',
            options={'verbose_name_plural': 'Individual Identities'},
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='type',
            field=models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('DRIVERS_LICENSE', "Driver's License"), ('ELECTORAL_CARD', 'Electoral Card'), ('NATIONAL_ID', 'National ID'), ('NATIONAL_PASSPORT', 'National Passport'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='household',
            name='consent_sharing',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', 'None'), ('GOVERNMENT_PARTNER', 'Government partners'), ('HUMANITARIAN_PARTNER', 'Humanitarian partners'), ('PRIVATE_PARTNER', 'Private partners'), ('UNICEF', 'UNICEF')], default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='household',
            name='org_enumerator',
            field=models.CharField(choices=[('', 'None'), ('PARTNER', 'Partner'), ('UNICEF', 'UNICEF')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='household',
            name='registration_method',
            field=models.CharField(choices=[('', 'None'), ('COMMUNITY', 'Community-level Registration'), ('HH_REGISTRATION', 'Household Registration')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='individual',
            name='comms_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all'), ('SOME_DIFFICULTY', 'Some difficulty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='individual',
            name='deduplication_batch_status',
            field=models.CharField(choices=[('DUPLICATE_IN_BATCH', 'Duplicate in batch'), ('NOT_PROCESSED', 'Not Processed'), ('SIMILAR_IN_BATCH', 'Similar in batch'), ('UNIQUE_IN_BATCH', 'Unique in batch')], default='UNIQUE_IN_BATCH', max_length=50),
        ),
        migrations.AlterField(
            model_name='individual',
            name='deduplication_golden_record_status',
            field=models.CharField(choices=[('DUPLICATE', 'Duplicate'), ('NEEDS_ADJUDICATION', 'Needs Adjudication'), ('NOT_PROCESSED', 'Not Processed'), ('UNIQUE', 'Unique')], default='UNIQUE', max_length=50),
        ),
        migrations.AlterField(
            model_name='individual',
            name='hearing_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all'), ('SOME_DIFFICULTY', 'Some difficulty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='individual',
            name='marital_status',
            field=models.CharField(choices=[('', 'None'), ('DIVORCED', 'Divorced'), ('MARRIED', 'Married'), ('SEPARATED', 'Separated'), ('SINGLE', 'Single'), ('WIDOWED', 'Widowed')], db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='individual',
            name='memory_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all'), ('SOME_DIFFICULTY', 'Some difficulty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='individual',
            name='physical_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all'), ('SOME_DIFFICULTY', 'Some difficulty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='individual',
            name='relationship',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'Unknown'), ('AUNT_UNCLE', 'Aunt / Uncle'), ('BROTHER_SISTER', 'Brother / Sister'), ('COUSIN', 'Cousin'), ('DAUGHTERINLAW_SONINLAW', 'Daughter-in-law / Son-in-law'), ('GRANDDAUGHER_GRANDSON', 'Granddaughter / Grandson'), ('GRANDMOTHER_GRANDFATHER', 'Grandmother / Grandfather'), ('HEAD', 'Head of household (self)'), ('MOTHER_FATHER', 'Mother / Father'), ('MOTHERINLAW_FATHERINLAW', 'Mother-in-law / Father-in-law'), ('NEPHEW_NIECE', 'Nephew / Niece'), ('NON_BENEFICIARY', 'Not a Family Member. Can only act as a recipient.'), ('SISTERINLAW_BROTHERINLAW', 'Sister-in-law / Brother-in-law'), ('SON_DAUGHTER', 'Son / Daughter'), ('WIFE_HUSBAND', 'Wife / Husband')], help_text='This represents the MEMBER relationship. can be blank\n            as well if household is null!', max_length=255),
        ),
        migrations.AlterField(
            model_name='individual',
            name='seeing_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all'), ('SOME_DIFFICULTY', 'Some difficulty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='individual',
            name='selfcare_disability',
            field=models.CharField(blank=True, choices=[('', 'None'), ('LOT_DIFFICULTY', 'A lot of difficulty'), ('CANNOT_DO', 'Cannot do at all'), ('SOME_DIFFICULTY', 'Some difficulty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='individualroleinhousehold',
            name='role',
            field=models.CharField(blank=True, choices=[('NO_ROLE', 'None'), ('ALTERNATE', 'Alternate collector'), ('PRIMARY', 'Primary collector')], max_length=255),
        ),
    ]
