# Generated by Django 3.2.12 on 2022-04-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0096_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='individual',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
