# Generated by Django 3.2.12 on 2022-04-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0102_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='sanction_list_last_check',
        ),
        migrations.AlterField(
            model_name='individual',
            name='sanction_list_confirmed_match',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='individual',
            name='sanction_list_possible_match',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
