# Generated by Django 3.2.12 on 2022-04-26 17:07

from django.db import migrations, models
import hct_mis_api.apps.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0103_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='individual',
            name='phone_no',
            field=hct_mis_api.apps.utils.models.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='individual',
            name='phone_no_alternative',
            field=hct_mis_api.apps.utils.models.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None),
        ),
    ]
