# Generated by Django 3.2.13 on 2022-06-09 11:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0106_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='individual',
            name='phone_no_alternative',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None),
        ),
    ]
