# Generated by Django 3.2.13 on 2022-06-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0108_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='deduplication_golden_record_status',
            field=models.CharField(choices=[('DUPLICATE', 'Duplicate'), ('NEEDS_ADJUDICATION', 'Needs Adjudication'), ('NOT_PROCESSED', 'Not Processed'), ('POSTPONE', 'Postpone'), ('UNIQUE', 'Unique')], default='UNIQUE', max_length=50),
        ),
    ]
