# Generated by Django 3.2.24 on 2024-02-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('household', '0114_migration'), ('household', '0115_migration'), ('household', '0116_migration'), ('household', '0117_migration'), ('household', '0118_migration'), ('household', '0119_migration')]

    dependencies = [
        ('geo', '0007_migration'),
        ('household', '0113_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['country_new', 'label']},
        ),
        migrations.AlterUniqueTogether(
            name='documenttype',
            unique_together={('country_new', 'type')},
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='country',
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['country', 'label']},
        ),
        migrations.RenameField(
            model_name='documenttype',
            old_name='country_new',
            new_name='country',
        ),
        migrations.AlterUniqueTogether(
            name='documenttype',
            unique_together={('country', 'type')},
        ),
        migrations.RemoveConstraint(
            model_name='agency',
            name='unique_type_and_country',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='country',
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(fields=('type', 'country_new'), name='unique_type_and_country'),
        ),
        migrations.RemoveConstraint(
            model_name='agency',
            name='unique_type_and_country',
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='country_new',
            new_name='country',
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(fields=('type', 'country'), name='unique_type_and_country'),
        ),
        migrations.RemoveField(
            model_name='household',
            name='admin_area',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='admin_area_new',
            new_name='admin_area',
        ),
    ]
