# Generated by Django 3.2.15 on 2022-09-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0120_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='size',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
    ]
