# Generated by Django 3.2.15 on 2022-11-04 14:17
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0129_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="individual",
            name="phone_no_alternative_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="individual",
            name="phone_no_valid",
            field=models.BooleanField(default=False),
        ),
    ]
