# Generated by Django 3.2.15 on 2023-02-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0137_migration"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS household_household_composite_default_page_idx ON household_household (business_area_id, is_removed, unicef_id);"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS household_individual_composite_default_page_idx ON household_individual (business_area_id, is_removed, unicef_id);"
        ),
    ]
