# Generated by Django 3.2.18 on 2023-04-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0142_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
