# Generated by Django 3.2.18 on 2023-04-04 09:35

from django.db import migrations, models
from django.db.models.functions import Lower


def update_document_type_keys(apps, schema_editor):
    DocumentType = apps.get_model("household", "DocumentType")
    DocumentType.objects.all().update(key=Lower("key"))


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0142_migration"),
    ]

    operations = [
        migrations.RenameField("DocumentType", "type", "key"),
        migrations.RunPython(update_document_type_keys, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="documenttype",
            name="key",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
