# Generated by Django 3.2.18 on 2023-04-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0142_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
