# Generated by Django 3.2.18 on 2023-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('household', '0147_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='issuance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql="CREATE INDEX CONCURRENTLY IF NOT EXISTS household_document_expiry_date ON household_document(expiry_date);",
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS household_document_expiry_date"
        )
    ]
