# Generated by Django 3.2.18 on 2023-05-17 11:04
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('household', '0147_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='issuance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='document',
                    name='expiry_date',
                    field=models.DateTimeField(db_index=True),
                )
            ],
            database_operations=[
                AddIndexConcurrently(
                    model_name="document",
                    index=models.Index(
                        fields=["expiry_date"], name="household_document_expiry_date_idx"
                    )
                ),
            ]
        )
    ]
