<<<<<<< HEAD
# Generated by Django 3.2.20 on 2023-09-26 10:13

from django.db import migrations, models
import django.db.models.expressions
=======
# Generated by Django 3.2.20 on 2023-10-05 11:43

from django.db import migrations, models
>>>>>>> 1320d7b3c06f4b8cc0506fbb6d09aaac676921bd


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0157_migration'),
    ]

    operations = [
<<<<<<< HEAD
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_for_individual_if_not_removed_and_valid',
        ),
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_if_not_removed_and_valid',
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('is_removed', False), ('status', 'VALID'), django.db.models.expressions.Func(django.db.models.expressions.F('type_id'), django.db.models.expressions.Value(True), function='check_unique_document_for_individual', output_field=models.BooleanField()))), fields=('type', 'country', 'program'), name='unique_for_individual_if_not_removed_and_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('is_removed', False), ('status', 'VALID'), django.db.models.expressions.Func(django.db.models.expressions.F('type_id'), django.db.models.expressions.Value(False), function='check_unique_document_for_individual', output_field=models.BooleanField()))), fields=('document_number', 'type', 'country', 'program'), name='unique_if_not_removed_and_valid'),
=======
        migrations.AlterField(
            model_name='individual',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en-us', 'English | English'), ('ar-ae', ' | عربيArabic'), ('cs-cz', 'čeština | Czech'), ('de-de', 'Deutsch'), ('es-es', 'Español | Spanish'), ('fr-fr', 'Français | French'), ('hu-hu', 'Magyar | Hungarian'), ('it-it', 'Italiano'), ('pl-pl', 'Polskie | Polish'), ('pt-pt', 'Português'), ('ro-ro', 'Română'), ('ru-ru', 'Русский | Russian'), ('si-si', 'සිංහල | Sinhala'), ('ta-ta', 'தமிழ் | Tamil'), ('uk-ua', 'український | Ukrainian'), ('hi-hi', 'हिंदी')], max_length=6, null=True),
>>>>>>> 1320d7b3c06f4b8cc0506fbb6d09aaac676921bd
        ),
    ]
