# Generated by Django 3.2.22 on 2023-11-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0160_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='is_identity_document',
            field=models.BooleanField(default=True, help_text='Document type is used for deduplication'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='valid_for_deduplication',
            field=models.BooleanField(default=False, help_text='The document type id added to the signature'),
        ),
    ]
