# Generated by Django 3.2.22 on 2023-12-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0161_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="migrated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="individual",
            name="migrated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="individualroleinhousehold",
            name="migrated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
