# Generated by Django 3.2.25 on 2024-04-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0173_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountinfo',
            name='rdi_merge_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MERGED', 'Merged')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rdi_merge_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MERGED', 'Merged')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='rdi_merge_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MERGED', 'Merged')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='rdi_merge_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MERGED', 'Merged')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='individualidentity',
            name='rdi_merge_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MERGED', 'Merged')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='individualroleinhousehold',
            name='rdi_merge_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MERGED', 'Merged')], max_length=10, null=True),
        ),
    ]
