# Generated by Django 3.2.25 on 2024-04-23 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0175_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='head_of_household',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heading_household', to='household.individual'),
        ),
    ]
