# Generated by Django 3.2.25 on 2024-06-11 14:49

from django.db import migrations,  models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0176_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='kobo_asset_id',
        ),
        migrations.RemoveField(
            model_name='household',
            name='row_id',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='kobo_asset_id',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='row_id',
        ),
        migrations.AlterField(
            model_name='household',
            name='head_of_household',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='heading_household', to='household.individual'),
        ),
    ]
