# Generated by Django 3.2.25 on 2024-06-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0177_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='kobo_submission_uuid',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
