# Generated by Django 3.2.25 on 2024-06-19 14:41

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0114_migration'),
        ('household', '0178_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountinfo',
            name='rdi_merge_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MERGED', 'Merged')], default='PENDING', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='rdi_merge_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MERGED', 'Merged')], default='PENDING', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='flex_registrations_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='registration_datahub.record'),
        ),
        migrations.AlterField(
            model_name='household',
            name='rdi_merge_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MERGED', 'Merged')], default='PENDING', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='registration_id',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Aurora Registration Id'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='rdi_merge_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MERGED', 'Merged')], default='PENDING', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='individualidentity',
            name='rdi_merge_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MERGED', 'Merged')], default='PENDING', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='individualroleinhousehold',
            name='rdi_merge_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MERGED', 'Merged')], default='PENDING', max_length=10, null=True),
        ),
    ]
