# Generated by Django 3.2.25 on 2024-06-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0180_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingBankAccountInfo',
            fields=[
            ],
            options={
                'verbose_name': 'Imported Bank Account Info',
                'verbose_name_plural': 'Imported Bank Account Infos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('household.bankaccountinfo',),
        ),
    ]
