# Generated by Django 3.2.25 on 2024-06-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0180_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='enumerator_rec_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
