# Generated by Django 3.2.25 on 2024-08-16 11:24

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Count


def assign_individual_to_rdi(apps, schema_editor):
    RegistrationDataImport = apps.get_model("registration_data", "RegistrationDataImport")
    Individual = apps.get_model("household", "Individual")
    Program = apps.get_model("program", "Program")

    for program in Program.objects.all():
        # create RDI only if exists any individual without RDI
        individual_qs = Individual.objects.filter(program=program, registration_data_import__isnull=True)

        if individual_qs.exists():
            rdi = RegistrationDataImport(
                name="RDI for Individuals [data migration]",
                status="MERGED",
                imported_by=None,
                data_source="XLS",
                number_of_individuals=individual_qs.count(),
                number_of_households=individual_qs.aggregate(household_count=Count("household", distinct=True))["household_count"],
                business_area=program.business_area,
                program_id=program.id,
                import_data=None,
            )
            rdi.save()
            individual_qs.update(registration_data_import_id=rdi.id)


class Migration(migrations.Migration):

    dependencies = [
        ('registration_data', '0038_migration'),
        ('household', '0184_migration'),
    ]

    operations = [
        migrations.RunPython(assign_individual_to_rdi, migrations.RunPython.noop,),
        migrations.AlterField(
            model_name='individual',
            name='registration_data_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='registration_data.registrationdataimport'),
        ),
    ]
