# Generated by Django 3.2.15 on 2022-10-24 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0034_migration'),
        ('core', '0055_migration'),
        ('targeting', '0034_migration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('household', '0124_migration'),
        ('accountability', '0004_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('unicef_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=60)),
                ('body', models.TextField(max_length=1000, blank=True, null=True)),
                ('category', models.CharField(choices=[('RAPID_PRO', 'Survey with RapidPro'), ('SMS', 'Survey with SMS'), ('MANUAL', 'Survey with manual process')], max_length=16)),
                ('number_of_recipients', models.PositiveIntegerField(default=0)),
                ('sampling_type', models.CharField(choices=[('FULL_LIST', 'Full list'), ('RANDOM', 'Random')], default='FULL_LIST', max_length=50)),
                ('full_list_arguments', models.JSONField(blank=True, null=True)),
                ('random_sampling_arguments', models.JSONField(blank=True, null=True)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('business_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.businessarea')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='program.program')),
                ('recipients', models.ManyToManyField(blank=True, related_name='surveys', to='household.Household')),
                ('target_population', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='targeting.targetpopulation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
