apiVersion: batch/v1
kind: Job
metadata:
  name: es-copy-job
  namespace: ictd-hope-eph-1
  labels: {rehearsal: copy}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels: {rehearsal: copy}
    spec:
      restartPolicy: Never
      serviceAccountName: core
      containers:
        - name: copy
          image: unicef/hope-support-images:core-62c6b84092b74eec335918fb5f80586c31c0180a
          command: ["bash", "-c", "cd /scripts && python3 es_migrate.py"]
          env:
            - {name: SRC, value: "http://hope-elasticsearch:9200"}
            - {name: DST, value: "http://hope-es-search-master:9200"}
            - {name: CONC, value: "6"}
            - {name: SCROLL_SIZE, value: "2000"}
            - {name: INDEX_GLOB, value: "households_*,individuals_*"}
          volumeMounts:
            - {name: scripts, mountPath: /scripts}
          resources:
            requests: {cpu: 100m, memory: 512Mi}
            limits: {cpu: "2", memory: 1536Mi}
      volumes:
        - name: scripts
          configMap: {name: mig-scripts}
