# Generated by Django 2.2.16 on 2022-01-13 17:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_query', '0001_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_args',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='query_args',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
