# Generated by Django 3.2.19 on 2023-07-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_query', '0001_migration_squashed_0014_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
