# Generated by Django 2.2.16 on 2022-01-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_query', '0005_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatter',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
