# Generated by Django 3.2.19 on 2023-06-03 06:21

from django.db import migrations, models
import hct_mis_api.apps.power_query.json


class Migration(migrations.Migration):

    dependencies = [
        ('power_query', '0012_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='celery_task',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='celery_task',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='reportdocument',
            name='arguments',
            field=models.JSONField(default=dict, encoder=hct_mis_api.apps.power_query.json.PQJSONEncoder),
        ),
    ]
