# Generated by Django 3.2.19 on 2023-06-03 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('power_query', '0013_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrizer',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='power_query.query'),
        ),
    ]
