# Generated by Django 3.2.18 on 2023-03-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0002_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ('date',)},
        ),
    ]
