# Generated by Django 3.2.15 on 2022-12-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0002_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ('date',)},
        ),
    ]
