<<<<<<< HEAD
# Generated by Django 3.2.20 on 2023-08-23 11:33
=======
# Generated by Django 3.2.20 on 2023-09-05 06:22
>>>>>>> 082307486845f95851a374b96d3b4c6ad227fb07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0003_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ('-date',)},
        ),
    ]
