# Generated by Django 3.2.19 on 2023-06-10 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hct_mis_api.apps.account.fields


class Migration(migrations.Migration):

    replaces = [('api', '0001_migration'), ('api', '0002_migration'), ('api', '0003_migration')]

    dependencies = [
        ('core', '0054_migration'),
        ('core', '0053_migration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Key')),
                ('allowed_ips', models.CharField(blank=True, max_length=200, null=True, verbose_name='IPs')),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('valid_for', models.ManyToManyField(to='core.BusinessArea')),
                ('grants', hct_mis_api.apps.account.fields.ChoiceArrayField(base_field=models.CharField(choices=[('API_READ_ONLY', 'API_READ_ONLY'), ('API_RDI_UPLOAD', 'API_RDI_UPLOAD'), ('API_RDI_CREATE', 'API_RDI_CREATE'), ('API_PROGRAM_CREATE', 'API_PROGRAM_CREATE')], max_length=255), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='APILogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField()),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.apitoken')),
            ],
        ),
    ]
