# Generated by Django 2.2.16 on 2021-10-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_migration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('name', 'p_code')},
        ),
    ]
