# Generated by Django 3.2.23 on 2024-02-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration_datahub', '0110_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedhousehold',
            name='program_registration_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
