# Generated by Django 3.2.25 on 2024-06-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_datahub', '0115_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportedDeliveryMechanismData',
        ),
    ]
