from typing import Dict, List, Optional

from django.db import transaction

from hct_mis_api.apps.geo.models import Country
from hct_mis_api.apps.payment.models import (
    DeliveryMechanismData,
    FinancialInstitution,
    FinancialInstitutionMapping,
    FinancialServiceProvider,
)
from hct_mis_api.apps.registration_data.models import RegistrationDataImport

mapping: List[Dict[str, Optional[str]]] = [
    {
        "uba_institution_name": "3line Card Management Limited",
        "uba_code": "110005",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "78 FINANCE COMPANY LIMITED",
        "uba_code": "110072",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "9 PAYMENT SERVICE BANK",
        "uba_code": "120001",
        "moneygram_code": "100003",
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "9JAPAY MICROFINANCE BANK",
        "uba_code": "090629",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "AAA FINANCE", "uba_code": "050005", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "AB Microfinance bank",
        "uba_code": "090270",
        "moneygram_code": "100011",
        "ecobank_code": None,
    },
    {"uba_institution_name": "ABBEY MORTGAGE BANK", "uba_code": "070010", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Above Only Microfinance bank",
        "uba_code": "090260",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ABSU MICROFINANCE BANK",
        "uba_code": "090640",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ABU Microfinance bank",
        "uba_code": "090197",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ABUCOOP MICROFINANCE BANK",
        "uba_code": "090424",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ABULESORO MICROFINANCE BANK LTD",
        "uba_code": "090545",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Accelerex network", "uba_code": "090202", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Access Bank", "uba_code": "000014", "moneygram_code": "000014", "ecobank_code": "044"},
    {"uba_institution_name": "Access Money", "uba_code": "100013", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Access Yello", "uba_code": "100052", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "ACCION MFB", "uba_code": "090134", "moneygram_code": "100008", "ecobank_code": None},
    {"uba_institution_name": "ADA MFB", "uba_code": "090483", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Addosser MFBB", "uba_code": "090160", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Adeyemi College Staff Microfinance bank",
        "uba_code": "090268",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Advans LaFayette MFB",
        "uba_code": "090155",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Afekhafe Microfinance Bank",
        "uba_code": "090292",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Afemai Microfinance Bank",
        "uba_code": "090518",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "AG Mortgage Bank Plc",
        "uba_code": "100028",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Agosasa MICROFINANCE BANK",
        "uba_code": "090371",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "AKPO MICROFINANCE BANK",
        "uba_code": "090608",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "AKU MICROFINANCE BANK",
        "uba_code": "090531",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "AKUCHUCKWU MICROFINANCE BANK",
        "uba_code": "090561",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Akuchukwu MFB", "uba_code": "090561", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Akwa savings and Loans Limited",
        "uba_code": "070025",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "AL-BARKAH MFB", "uba_code": "090133", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Alekun Microfinance bank",
        "uba_code": "090259",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Alert MFB", "uba_code": "090297", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "AL-HAYAT MICROFINANCE BANK",
        "uba_code": "090277",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "ALLWORKERS MFB", "uba_code": "090131", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "ALLY MICROFINANCE BANK",
        "uba_code": "090548",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Alpha Kapital Mfb Ltd",
        "uba_code": "090169",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ALTERNATIVE BANK LIMITED",
        "uba_code": "000037",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ALVANA MICROFINANCE BANK",
        "uba_code": "090489",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Amac Microfinance Bank",
        "uba_code": "090394",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "AMJU UNIQUE MICROFINANCE BANK",
        "uba_code": "090180",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "AMML MFB", "uba_code": "090116", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "AMOYE MICROFINANCE BANK",
        "uba_code": "090610",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "AMUCHA MICROFINANCE BANK",
        "uba_code": "090645",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Anchorage MFB", "uba_code": "090476", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Aniocha MFB", "uba_code": "090469", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "APEKS Microfinance Bank",
        "uba_code": "090143",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "APPLE MICROFINANCE BANK",
        "uba_code": "090376",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ARAMOKO MICROFINANCE BANK",
        "uba_code": "090307",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ARCA PAYMENTS COMPANY LIMITED",
        "uba_code": "110011",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Arise MFB", "uba_code": "090282", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "ASOSavings", "uba_code": "090001", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "ASPIRE MICROFINANCE BANK LTD",
        "uba_code": "090544",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Assets Matrix MFB", "uba_code": "090287", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "ASSETS Microfinance Bank",
        "uba_code": "090473",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Astrapolis MFB", "uba_code": "090172", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "ATBU Microfinance Bank",
        "uba_code": "090451",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Auchi Microfinance bank",
        "uba_code": "090264",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "AVE MARIA MICROFINANCE BANK LTD",
        "uba_code": "090600",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Avuenegbe MFB", "uba_code": "090478", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "AWACASH MICROFINANCE BANK",
        "uba_code": "090633",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Awesome Microfinance Bank",
        "uba_code": "090662",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Aztec Microfinance Bank",
        "uba_code": "090540",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BABURA MICROFINANCE BANK",
        "uba_code": "090625",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BAINES CREDIT MICROFINANCE BANK",
        "uba_code": "090188",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Balogun Fulani Microfinance Bank",
        "uba_code": "090181",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BALOGUN GAMBARI MICROFINANCE BANK",
        "uba_code": "090326",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BAM MICROFINANCE BANK",
        "uba_code": "090651",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BANC CORP MICROFINANCE BANK LTD",
        "uba_code": "090581",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Banex Microfinance Bank",
        "uba_code": "090425",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Bankly Microfinance Bank",
        "uba_code": "090529",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BAOBAB MICROFINANCE BANK",
        "uba_code": "090136",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Bayero MICROFINANCE BANK",
        "uba_code": "090316",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "BC Kash MFB", "uba_code": "090127", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "BELLBANK Microfinance Bank",
        "uba_code": "090672",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BENYSTA MICROFINANCE BANK",
        "uba_code": "090413",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "BESTSTAR MFB", "uba_code": "090615", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "BESTSTAR MICROFINANCE BANK",
        "uba_code": "090615",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BETHEL MICROFINANCE BANK",
        "uba_code": "090683",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BIPC MICROFINANCE BANK",
        "uba_code": "090336",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Blue Investments Microfinance Bank",
        "uba_code": "090538",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Bluewhales Microfinance Bank",
        "uba_code": "090431",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Boctrust Microfinance Bank Limited",
        "uba_code": "090117",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BOI Microfinance Bank",
        "uba_code": "090444",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BOJIÂ BOJIÂ MICROFINANCE BANK",
        "uba_code": "090494",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "BOKKOS MFB", "uba_code": "090703", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Bonghe Microfinance Bank",
        "uba_code": "090319",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BORGU MICROFINANCE BANK",
        "uba_code": "090395",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Borno Renaissance Microfinance Bank",
        "uba_code": "090508",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Boromu Microfinance Bank",
        "uba_code": "090501",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Borstal Microfinance Bank",
        "uba_code": "090454",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Bosak MFB", "uba_code": "090176", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Bowen MFB", "uba_code": "090148", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Branch International Financial Services",
        "uba_code": "050006",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Brent Mortgage Bank", "uba_code": "070015", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "BRETHREN MICROFINANCE BANK",
        "uba_code": "090293",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Bridgeway Microfinance Bank",
        "uba_code": "090393",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Brightway MFB", "uba_code": "090308", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "BRIYTH-COVENANT MICROFINANCE BANK",
        "uba_code": "090636",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BROADVIEW MICROFINANCE BANK",
        "uba_code": "090568",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BUBAYERO MICORFINANCE BANK",
        "uba_code": "090512",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Bud infrastructure Limited",
        "uba_code": "110021",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BUILD MICROFINANCE BANK",
        "uba_code": "090613",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BUNDI MICROFINANCE BANK",
        "uba_code": "090661",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BUNKURE MICROFINANCE BANK",
        "uba_code": "090655",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Business SupportMicrofinance Bank",
        "uba_code": "090406",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BUYPOWER MICROFINANACE BANK",
        "uba_code": "090682",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Calabar Microfinance Bank",
        "uba_code": "090415",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "CANAAN MICROFINANCE BANK",
        "uba_code": "090647",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "CAPITALMETRIQ SWIFT MICROFINANCE BANK",
        "uba_code": "090509",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Capricorn Digital", "uba_code": "110023", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "CAPSTONE Microfinance Bank",
        "uba_code": "090445",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Carbon MFB", "uba_code": "100026", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Cardinalstone Finance",
        "uba_code": "050017",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "CARETAKER Microfinance Bank",
        "uba_code": "090472",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "CASHBRIDGE MICROFINANCE BANK",
        "uba_code": "090634",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Cashconnect MICROFINANCE BANK",
        "uba_code": "090360",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "CATLANDÂ MICROFINANCE BANK",
        "uba_code": "090498",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Cellulant PSSP", "uba_code": "110012", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "CEMCS MFB", "uba_code": "090154", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Central Bank of Nigeria",
        "uba_code": "000028",
        "moneygram_code": None,
        "ecobank_code": "001",
    },
    {"uba_institution_name": "CHANELLE MFB", "uba_code": "090397", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Changan RTS Microfinance Bank",
        "uba_code": "090470",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Chase Microfinance Bank",
        "uba_code": "090523",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Cherish Microfinance Bank",
        "uba_code": "090440",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "CHIBUEZE MFB", "uba_code": "090416", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Chikum Microfinance Bank",
        "uba_code": "090141",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Chukwunenye Microfinance Bank",
        "uba_code": "090490",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "CINTRUST MFB", "uba_code": "090480", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Citi Bank", "uba_code": "000009", "moneygram_code": "000009", "ecobank_code": "023"},
    {"uba_institution_name": "Citizen Trust Â MFB", "uba_code": "090343", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "CITYCODE MORTGAGE BANK",
        "uba_code": "070027",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Clover Leaf Microfinance Bank",
        "uba_code": "090511",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "CoalCamp Microfinance Bank",
        "uba_code": "090254",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Coastline MICROFINANCE BANK",
        "uba_code": "090374",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "CONFIDENCE MICROFINANCE BANK LTD",
        "uba_code": "090530",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "CONSUMER MFB", "uba_code": "090130", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Coop Mortgage Bank", "uba_code": "070021", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Corestep MICROFINANCE BANK",
        "uba_code": "090365",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Coronation Merchant Bank",
        "uba_code": "060001",
        "moneygram_code": None,
        "ecobank_code": "559",
    },
    {"uba_institution_name": "Covenant", "uba_code": "070006", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Credit Afrique MFB", "uba_code": "090159", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Creditville MFB", "uba_code": "090611", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "CRESCENT MICROFINANCE BANK",
        "uba_code": "090526",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "CrossRiver Microfinance Bank",
        "uba_code": "090429",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "CROWDFORCE", "uba_code": "110017", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "CRUST MICROFINANCE BANK",
        "uba_code": "090560",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Crutech Microfinance Bank",
        "uba_code": "090414",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "CSD MFB", "uba_code": "090686", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Cyberspace Limited", "uba_code": "110014", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "DAL MICROFINANCE BANK",
        "uba_code": "090596",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "DAVENPORT MICROFINANCE BANK",
        "uba_code": "090673",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Davodani Microfinance Bank",
        "uba_code": "090391",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Daylight Microfinance Bank",
        "uba_code": "090167",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "DELTA TRUST MORTGAGE BANK",
        "uba_code": "070023",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Dignity Finance", "uba_code": "050013", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "DIOBU MICROFINANCE BANK",
        "uba_code": "090643",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "DOJE Microfinance Bank Limited",
        "uba_code": "090404",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Eagle Flight MFB", "uba_code": "090294", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Earnwell MICROFINANCE BANK",
        "uba_code": "090674",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Eartholeum", "uba_code": "100021", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "e-BARCs MFB", "uba_code": "090156", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "EBSU MFB", "uba_code": "090427", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Ecobank Bank", "uba_code": "000010", "moneygram_code": "000010", "ecobank_code": "050"},
    {"uba_institution_name": "EcoMobile", "uba_code": "100008", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Edfin MFB", "uba_code": "090310", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "E-FINANCE", "uba_code": "050016", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "EGWAFIN MICROFINANCE BANK",
        "uba_code": "090556",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "EKIMOGUN MICROFINANCE BANK",
        "uba_code": "090552",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "EKONDO MICROFINANCE BANK",
        "uba_code": "090097",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "EK-Reliable Microfinance Bank",
        "uba_code": "090389",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Emeralds MFB", "uba_code": "090273", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "EMPIRE MFB", "uba_code": "090114", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "e-Naira", "uba_code": "000033", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "ENCO FINANCE COMPANY LTD",
        "uba_code": "050012",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Enterprise Bank", "uba_code": "000019", "moneygram_code": "100001", "ecobank_code": None},
    {
        "uba_institution_name": "ENTITY MICROFINANCE BANK",
        "uba_code": "090656",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Esan Microfinance Bank",
        "uba_code": "090189",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Eso-E Microfinance Bank",
        "uba_code": "090166",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "eTranzact", "uba_code": "100006", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Evangel MFB", "uba_code": "090304", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Evergreen MICROFINANCE BANK",
        "uba_code": "090332",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "EWT Microfinance Bank",
        "uba_code": "090572",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "EXCEL MICROFINANCE BANK",
        "uba_code": "090678",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "EXCELLENT MICROFINANCE BANK",
        "uba_code": "090541",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "EYOWO MFB", "uba_code": "090328", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "FAIRMONEY MICROFINANCE BANK LTD",
        "uba_code": "090551",
        "moneygram_code": "100006",
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "FAME Microfinance Bank",
        "uba_code": "090330",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "FAST CREDIT", "uba_code": "050009", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "FAST MICROFINANCE BANK",
        "uba_code": "090179",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "FBNQuest Merchant bank",
        "uba_code": "060002",
        "moneygram_code": None,
        "ecobank_code": "011",
    },
    {"uba_institution_name": "FCMB", "uba_code": "000003", "moneygram_code": "000003", "ecobank_code": "214"},
    {"uba_institution_name": "FCMB BETA", "uba_code": "090409", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "FCMB MOBILE", "uba_code": "100031", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "FCT MFB", "uba_code": "090290", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "FEDERAL POLYTECHNIC NEKEDE MICROFINANCE BANK",
        "uba_code": "090398",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "FEDERAL UNIVERSITY DUTSE MICROFINANCE BANK",
        "uba_code": "090318",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "FederalPoly NasarawaMFB",
        "uba_code": "090298",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "FEDETH MFB", "uba_code": "090482", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "FETS", "uba_code": "100001", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "FEWCHORE FINANCE COMPANY LIMITED",
        "uba_code": "050002",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "FFS Microfinance Bank",
        "uba_code": "090153",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "FHA MORTGAGE BANK LTD",
        "uba_code": "070026",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Fidelity Bank", "uba_code": "000007", "moneygram_code": "000007", "ecobank_code": "070"},
    {"uba_institution_name": "Fidelity Mobile", "uba_code": "100019", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "FidFund MFB", "uba_code": "090126", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "FIMS MICROFINANCE BANK",
        "uba_code": "090507",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "FinaTrust Microfinance Bank",
        "uba_code": "090111",
        "moneygram_code": "100010",
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Finca Microfinance Bank",
        "uba_code": "090400",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Firmus MFB", "uba_code": "090366", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "First Apple Limited", "uba_code": "110004", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "First Bank of Nigeria",
        "uba_code": "000016",
        "moneygram_code": "000016",
        "ecobank_code": "011",
    },
    {
        "uba_institution_name": "First Generation Mortgage Bank",
        "uba_code": "070014",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "First Heritage MFB", "uba_code": "090479", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "First Mortgage Limited",
        "uba_code": "090107",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "First Multiple MFB", "uba_code": "090163", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "First Option MFB", "uba_code": "090285", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "First Royal Microfinance Bank",
        "uba_code": "090164",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "FIRSTMIDAS MICROFINANCE BANK LTD",
        "uba_code": "090575",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "FirstMonie Wallet", "uba_code": "100014", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Flourish MFB", "uba_code": "090614", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Flutterwave Technology solutions Limited",
        "uba_code": "110002",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Foresight Microfinance Bank",
        "uba_code": "090521",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Fortis Microfinance Bank",
        "uba_code": "070002",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "FortisMobile", "uba_code": "100016", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Fotress Microfinance Bank",
        "uba_code": "090486",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "FSDH", "uba_code": "400001", "moneygram_code": None, "ecobank_code": "501"},
    {"uba_institution_name": "Full range MFB", "uba_code": "090145", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "FUNDQUEST FINANCIAL SERVICES LTD",
        "uba_code": "050010",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Futminna Microfinance Bank",
        "uba_code": "090438",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "FUTO MFB", "uba_code": "090158", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "GABASAWA MICROFINANCE BANK",
        "uba_code": "090582",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GABSYN MICROFINANCE BANK",
        "uba_code": "090591",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "GARKI MFB", "uba_code": "090484", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Garun Mallam MFB", "uba_code": "090691", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Gashua Microfinance Bank",
        "uba_code": "090168",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GATEWAY MORTGAGE BANK",
        "uba_code": "070009",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GBEDE MICROFINANCE BANK",
        "uba_code": "090579",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "GDL FINANCE", "uba_code": "050026", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "GIDAUNIYAR ALHERI MICROFINANCE BANK",
        "uba_code": "090621",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Giginya MFB", "uba_code": "090411", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Girei MFB", "uba_code": "090186", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Giwa Microfinance Bank",
        "uba_code": "090441",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GLOBAL INITIATIVE MICROFINANCE BANK",
        "uba_code": "090639",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Globus Bank", "uba_code": "000027", "moneygram_code": "000027", "ecobank_code": "103"},
    {
        "uba_institution_name": "Glory Microfinance Bank",
        "uba_code": "090278",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GMB Microfinance Bank",
        "uba_code": "090408",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GOLDMAN MICROFINANCE BANK LTD",
        "uba_code": "090574",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GOMBE MICROFINANCE BANK LTD",
        "uba_code": "090586",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "GOMONEY", "uba_code": "100022", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Good Neighbours Microfinance Bank",
        "uba_code": "090467",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GOOD SHEPHERD MICROFINANCE BANK",
        "uba_code": "090664",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GOODNEWS MICROFINANCE BANK",
        "uba_code": "090495",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "GOSIFECHUKWU MFB", "uba_code": "090687", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "GOWANS MFB", "uba_code": "090122", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Grant Microfinance Bank",
        "uba_code": "090335",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GREEN ENERGY MICROFINANCE BANK LTD",
        "uba_code": "090550",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GREENACRES MICROFINANCE BANK LTD",
        "uba_code": "090599",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "GreenBank MFB", "uba_code": "090178", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Greenville Microfinance bank",
        "uba_code": "090269",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GREENWICH MERCHANT BANK",
        "uba_code": "060004",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Grooming Microfinance bank",
        "uba_code": "090195",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "GTBank Plc", "uba_code": "000013", "moneygram_code": "000013", "ecobank_code": "058"},
    {
        "uba_institution_name": "GTI Microfinance Bank",
        "uba_code": "090385",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "GTMobile", "uba_code": "100009", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "GWONG MICROFINANCE BANK",
        "uba_code": "090500",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Habaripay", "uba_code": "110059", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Hackman Microfinance Bank",
        "uba_code": "090147",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "HAGGAI MORTGAGE BANK LIMITED",
        "uba_code": "070017",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Hala MFB", "uba_code": "090291", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Halo Microfinance Bank",
        "uba_code": "090539",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "HASAL MFB", "uba_code": "090121", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Headway MFB", "uba_code": "090363", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Hedonmark", "uba_code": "100017", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Heritage", "uba_code": "000020", "moneygram_code": "000020", "ecobank_code": "030"},
    {
        "uba_institution_name": "HIGHLAND MICROFINANCE BANK",
        "uba_code": "090418",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "HomeBase Mortgage Bank",
        "uba_code": "070024",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Hope Payment Service Bank",
        "uba_code": "120002",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IBA Microfinance Bank",
        "uba_code": "090598",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IBETO MICROFINANCE BANK",
        "uba_code": "090439",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Ibile Microfinance Bank Limited",
        "uba_code": "090118",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IBOLO MICORFINANCE BANK LTD",
        "uba_code": "090532",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Ibom fadama Microfinance Bank",
        "uba_code": "090519",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IBU-AJE MICROFINANCE BANK",
        "uba_code": "090488",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IC GLOBALMicrofinance Bank",
        "uba_code": "090520",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IJEBU-IFE MICROFINANCE BANK LTD",
        "uba_code": "090546",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "IKENNE MFB", "uba_code": "090324", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Ikire MFB", "uba_code": "090279", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "IKOYI ILE MICROFINANCEBANK",
        "uba_code": "090681",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IKOYI-OSUN MICROFINANCE BANK",
        "uba_code": "090536",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Ilasan MICROFINANCE BANK",
        "uba_code": "090370",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Illorin Microfinance Bank",
        "uba_code": "090350",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Ilora Microfinance Bank",
        "uba_code": "090430",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Imo Microfinance bank",
        "uba_code": "090258",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Imowo Microfinance Bank",
        "uba_code": "090417",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Imperial Homes Mortgage Bank",
        "uba_code": "100024",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IMSU MICROFINANCE BANK",
        "uba_code": "090670",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Infinity MFB", "uba_code": "090157", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Infinity trust Mortgage Bank",
        "uba_code": "070016",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Innovectives Kesh", "uba_code": "100029", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Insight Microfinance Bank",
        "uba_code": "090434",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Intellifin", "uba_code": "100027", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Interland MFB", "uba_code": "090386", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Interswitch Financial Inclusion ServicesIFIS",
        "uba_code": "110010",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Interswitch Limited", "uba_code": "110003", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "IPERUÂ MICROFINANCE BANK",
        "uba_code": "090493",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IRL Microfinance Bank",
        "uba_code": "090149",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ISALEOYO MICROFINANCE BANK",
        "uba_code": "090377",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Ishie Microfinance Bank",
        "uba_code": "090428",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ISLAND MICROFINANCE BANK LTD",
        "uba_code": "090584",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Isuofia MFB", "uba_code": "090353", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Itex Integrated Services Limited",
        "uba_code": "090211",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IWADE MICROFINANCE BANK LTD",
        "uba_code": "090578",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IYAMOYE MICROFINANCE BANK",
        "uba_code": "090570",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IYERU OKIN MICROFINANCE BANK LTD",
        "uba_code": "090337",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Izon Microfinance Bank",
        "uba_code": "090421",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "JAIZ Bank", "uba_code": "000006", "moneygram_code": "000006", "ecobank_code": "301"},
    {
        "uba_institution_name": "JESSEFIELD MICROFINANCE",
        "uba_code": "090352",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "JubileeLife", "uba_code": "090003", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Kadick Integration Limited",
        "uba_code": "110008",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Kadpoly MICROFINANCE BANK",
        "uba_code": "090320",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "KADUPE MICROFINANCE BANK",
        "uba_code": "090669",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "KANOPOLY MICROFINANCE BANK LIMITED",
        "uba_code": "090592",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "KAYI MICROFINANCE BANK",
        "uba_code": "090667",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Kayvee Microfinance Bank",
        "uba_code": "090554",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "KC MICROFINANCE BANK",
        "uba_code": "090549",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "KCMB MFB", "uba_code": "090191", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "KEGOWCHAMSMOBILE", "uba_code": "100036", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "KENECHUKWU MICROFINANCE BANK",
        "uba_code": "090602",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Keystone Bank", "uba_code": "000002", "moneygram_code": "000002", "ecobank_code": "082"},
    {
        "uba_institution_name": "KINGDOM COLLEGE MICROFINANCE BANK",
        "uba_code": "090487",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "KKU Microfinance Bank",
        "uba_code": "090606",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "KongaPay", "uba_code": "100025", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Kontagora MFB", "uba_code": "090299", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "KOPO KOPE MICROFINANCE BANK",
        "uba_code": "090617",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Koraypay", "uba_code": "110022", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "KREDI MONEY MICROFINANCE BANK",
        "uba_code": "090380",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Kuda Microfinance Bank",
        "uba_code": "090267",
        "moneygram_code": "100004",
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "KWASU Microfinance Bank",
        "uba_code": "090450",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "LANDGOLD MICROFINANCE BANK",
        "uba_code": "090422",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Lapo MFB", "uba_code": "090177", "moneygram_code": "100007", "ecobank_code": None},
    {
        "uba_institution_name": "Lavender Microfinance bank",
        "uba_code": "090271",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "LBIC Mortgage Bank", "uba_code": "070012", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "LEADCITY MICROFINANCE BANK",
        "uba_code": "090650",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "LEADREMIT LIMITED", "uba_code": "110044", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Legend MICROFINANCE BANK",
        "uba_code": "090372",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Light Microfinance Bank",
        "uba_code": "090477",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "LINKS MICROFINANCE BANK",
        "uba_code": "090435",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Lobrem Microfinance Bank",
        "uba_code": "090537",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "LOMA MFB", "uba_code": "090620", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "LOTUS BANK", "uba_code": "000029", "moneygram_code": "000029", "ecobank_code": "303"},
    {
        "uba_institution_name": "Lovonus Microfinance bank",
        "uba_code": "090265",
        "moneygram_code": "100013",
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Ltshego Microfinance Bank",
        "uba_code": "090420",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "LUKEFIELD FINANCE COMPANY LIMITED",
        "uba_code": "050015",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "M&M MFB", "uba_code": "090685", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "M36", "uba_code": "100035", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "MAB ALLIANZ MICROFINANCE BANK",
        "uba_code": "090623",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MABINAS MICROFINANCE BANK",
        "uba_code": "090630",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Macrod MFB", "uba_code": "090603", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "MADOBI MICROFINANCE BANK",
        "uba_code": "090605",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MAINLAND MICROFINANCE BANK",
        "uba_code": "090323",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MAINSTREET MICROFINANCE BANK",
        "uba_code": "090171",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Maintrust MFB", "uba_code": "090465", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "MALACHY MICROFINANCE BANK",
        "uba_code": "090174",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Manny MFB", "uba_code": "090383", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "MARITIME MICROFINANCE BANK",
        "uba_code": "090410",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Mautech Microfinance Bank",
        "uba_code": "090423",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Mayfair MFB", "uba_code": "090321", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "MayFresh Mortgage Bank",
        "uba_code": "070019",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Medef MFB", "uba_code": "090612", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Megapraise Microfinance Bank",
        "uba_code": "090280",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MEMPHIS MICROFINANCE BANK",
        "uba_code": "090432",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MERCURY MICROFINANCE BANK",
        "uba_code": "090589",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Meridian MFB", "uba_code": "090275", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Mgbidi Microfinance Bank",
        "uba_code": "090528",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Microbiz MFB", "uba_code": "090587", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Microsystems Investment and Development Limited",
        "uba_code": "110018",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MICROVIS MICROFINANCE BANK",
        "uba_code": "090113",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Midland MFB", "uba_code": "090192", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "MINJIBIR MICROFINANCE BANK",
        "uba_code": "090607",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MINT-FINEX MICROFINANCE",
        "uba_code": "090281",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MKOBO MICROFINANCE BANK LTD",
        "uba_code": "090455",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Mkudi", "uba_code": "100011", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "MOLUSI MFB", "uba_code": "090362", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Momo Payment services Bank",
        "uba_code": "120003",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Monarch Microfinance Bank",
        "uba_code": "090462",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Money Master PSB", "uba_code": "120005", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "MoneyBox", "uba_code": "100020", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "MONEYFIELD MICROFINANCE BANK",
        "uba_code": "090144",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "MONEYTRUST MFB", "uba_code": "090129", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Moniepoint MFB", "uba_code": "090405", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Moyofade MF Bank", "uba_code": "090448", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "MOZFIN MICROFINANCE BANK",
        "uba_code": "090392",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MUTUAL ALLIANCE MORTGAGE BANK",
        "uba_code": "070028",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "MUTUAL BENEFIT MFB", "uba_code": "090190", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Mutual Trust Microfinance Bank",
        "uba_code": "090151",
        "moneygram_code": "100009",
        "ecobank_code": None,
    },
    {"uba_institution_name": "Nargata MFB", "uba_code": "090152", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "NDDC MICROFINANCE BANK",
        "uba_code": "090679",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Ndiorah MFB", "uba_code": "090128", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Neptune MFB", "uba_code": "090329", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "NET MFB", "uba_code": "090675", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "NetApps Technology Limited",
        "uba_code": "110025",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "New Dawn Microfinance Bank",
        "uba_code": "090205",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "NEW GOLDEN PASTURES MICROFINANCE BANK",
        "uba_code": "090378",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "New Prudential Bank", "uba_code": "090108", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "NEWEDGE FINANCE LTD", "uba_code": "050004", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "NEXIM BANK", "uba_code": "030001", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "NIBSSUSSD PAYMENTS", "uba_code": "110019", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "NICE Microfinance Bank",
        "uba_code": "090459",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "NIGERIAN NAVY MICROFINANCE BANK",
        "uba_code": "090263",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "NIGERIAN PRISONS MICROFINANCE BANK",
        "uba_code": "090505",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "NIP Virtual Bank", "uba_code": "999999", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "NIRSAL MICROFINANCE BANK",
        "uba_code": "090194",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Nomba financial services Limited",
        "uba_code": "110028",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "NOVA MERCHANT BANK", "uba_code": "060003", "moneygram_code": None, "ecobank_code": "561"},
    {"uba_institution_name": "NowNowModification", "uba_code": "100032", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "NPF MicroFinance Bank",
        "uba_code": "070001",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "NSEHE MICROFINANCE BANK",
        "uba_code": "090628",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "NSUK MICROFINANCE BANK",
        "uba_code": "090491",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "NUGGETS MFB", "uba_code": "090676", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Numo Microfinance Bank",
        "uba_code": "090516",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Nuture MFB", "uba_code": "090364", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Nwannegadi MFB", "uba_code": "090399", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Oakland Microfinance Bank",
        "uba_code": "090437",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OAU MICROFINANCE BANK",
        "uba_code": "090345",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OCHE MICROFINANCE BANK",
        "uba_code": "090333",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OCTOPUS MICROFINANCE BANK",
        "uba_code": "090576",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ODOAKPU MICROFINANCE BANK LIMITED",
        "uba_code": "090654",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "OHAFIA MFB", "uba_code": "090119", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "OHHA MICROFINANCE BANK",
        "uba_code": "090626",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OJOKORO MICROFINANCE BANK",
        "uba_code": "090527",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OK MICROFINANCE BANK",
        "uba_code": "090567",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OKENGWE MICROFINANCE BANK",
        "uba_code": "090646",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Okpoga MFB", "uba_code": "090161", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "OLABISI ONABANJO UNIVERSITY MICROFINANCE BANK",
        "uba_code": "090272",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "OLIVE MFB", "uba_code": "090696", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "OLOFIN OWENA Microfinance Bank",
        "uba_code": "090468",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OLUCHUKWU Microfinance Bank",
        "uba_code": "090471",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Omiye MFB", "uba_code": "090295", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Omoluabi", "uba_code": "070077", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Omoluabi", "uba_code": "070077", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "OPAY DIGITAL SERVICES LIMITED",
        "uba_code": "100004",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Optimus Bank", "uba_code": "000036", "moneygram_code": "000036", "ecobank_code": None},
    {
        "uba_institution_name": "Oraukwu Microfinance Bank",
        "uba_code": "090492",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ORISUN MICROFINANCE BANK",
        "uba_code": "090588",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ORITA-BASORUN Microfinance Bank",
        "uba_code": "090460",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OROKAM MICROFINANCE BANK",
        "uba_code": "090567",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Oscotech MFB", "uba_code": "090396", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Ospoly Microfinance Bank",
        "uba_code": "090456",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OTECH MICROFINANCE BANK LTD",
        "uba_code": "090580",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OTUO MICROFINANCE BANK LTD",
        "uba_code": "090542",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OYAN MICROFINANCE BANK",
        "uba_code": "090635",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Pagatech", "uba_code": "100002", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Page MFBank", "uba_code": "070008", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "PALMCOAST MICROFINANCE BANK",
        "uba_code": "090497",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "PALMPAY", "uba_code": "100033", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "PARALLEX BANK", "uba_code": "000030", "moneygram_code": "000030", "ecobank_code": None},
    {"uba_institution_name": "Parkway MF Bank", "uba_code": "090390", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Parkway-ReadyCash", "uba_code": "100003", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Parralex Microfinance bank",
        "uba_code": "090004",
        "moneygram_code": None,
        "ecobank_code": "104",
    },
    {
        "uba_institution_name": "PATHFINDER MICROFINANACE BANK LIMITED",
        "uba_code": "090680",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "PATRICKGOLD MICROFINANCE BANK",
        "uba_code": "090317",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "PayAttitude Online", "uba_code": "110001", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Paystack Payments", "uba_code": "110006", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Paystack-Titan", "uba_code": "100039", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Peace Microfinance Bank",
        "uba_code": "090402",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Pecan Trust Microfinance Bank",
        "uba_code": "090137",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "PENIEL MICORFINANCE BANK LTD",
        "uba_code": "090379",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Pennywise Microfinance bank",
        "uba_code": "090196",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Personal Trust Microfinance Bank",
        "uba_code": "090135",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "PETRA MICROFINANCE BANK PLC",
        "uba_code": "090165",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "PFI FINANCE COMPANY LIMITED",
        "uba_code": "050021",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Pillar MFB", "uba_code": "090289", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "PLATINUM MORTGAGE BANK",
        "uba_code": "070013",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "POLARIS BANK", "uba_code": "000008", "moneygram_code": "000008", "ecobank_code": "076"},
    {
        "uba_institution_name": "Polyibadan Microfinance Bank",
        "uba_code": "090534",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Polyuwanna MFB", "uba_code": "090296", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Preeminent Microfinance Bank",
        "uba_code": "090412",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "PremiumTrust Bank",
        "uba_code": "000031",
        "moneygram_code": "000031",
        "ecobank_code": "105",
    },
    {
        "uba_institution_name": "Prestige Microfinance bank",
        "uba_code": "090274",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "PRISCO MFB", "uba_code": "090481", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Pristine Divitis MFB",
        "uba_code": "090499",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "PROJECTS MICROFINANCE BANK",
        "uba_code": "090503",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "PROSPECTS MFB", "uba_code": "090689", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "PROSPERITY MICROFINANCE BANK",
        "uba_code": "090642",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Providus Bank", "uba_code": "000023", "moneygram_code": "000023", "ecobank_code": "101"},
    {
        "uba_institution_name": "PRUDENT MICROFINANCE BANK",
        "uba_code": "090690",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Purplemoney MFB", "uba_code": "090303", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "PYRAMID MICROFINANCE BANK",
        "uba_code": "090657",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "QR Payments", "uba_code": "110013", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "QUBE MICROFINANCE BANK LTD",
        "uba_code": "090569",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "QuickFund Microfinance bank",
        "uba_code": "090261",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Rahama MFB", "uba_code": "090170", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Rand Merchant Bank", "uba_code": "000024", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "RANDALPHA MFB", "uba_code": "090496", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "RAYYAN MICROFINANCE BANK",
        "uba_code": "090616",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Refuge Mortgage Bank",
        "uba_code": "070011",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "REGENT MFB", "uba_code": "090125", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Rehoboth Microfinance Bank",
        "uba_code": "090463",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Reliance MFB", "uba_code": "090173", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "RENMONEY MICROFINANCE BANK",
        "uba_code": "090198",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Rephidim MICROFINANCE BANK",
        "uba_code": "090322",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Resident Fintech Limited",
        "uba_code": "110024",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "REVELATION MICROFINANCE BANK",
        "uba_code": "090666",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "REX MICROFINANCE BANK",
        "uba_code": "090449",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "RICHWAY MFB", "uba_code": "090132", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "RIGO MICROFINANCE BANK",
        "uba_code": "090433",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "RIMA GROWTH PATHWAY MICROFINANCE BANK",
        "uba_code": "090515",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "RIMA Microfinance Bank",
        "uba_code": "090443",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ROCKSHIELD MICROFINANCE BANK",
        "uba_code": "090547",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Royal Exchange Microfinance Bank",
        "uba_code": "090138",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "RSU MICROFINANCE BANK",
        "uba_code": "090535",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "RUBIES MICROFINANCE BANK",
        "uba_code": "090175",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Safe Haven MFB", "uba_code": "090286", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Safegate Microfinance Bank",
        "uba_code": "090485",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Safetrust Mortage", "uba_code": "090006", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Sagamu Microfinance Bank",
        "uba_code": "090140",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "SageGrey Finace Limited",
        "uba_code": "050003",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "SEAP Microfinance Bank",
        "uba_code": "090513",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Seed Capital Microfinance Bank",
        "uba_code": "090112",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "SEEDVEST MICROFINANCE BANK",
        "uba_code": "090369",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "SHALOM MICROFINACE BANK",
        "uba_code": "090502",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Shepherd Trust Microfinance Bank",
        "uba_code": "090401",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "SHIELD MICROFINANCE BANK",
        "uba_code": "090559",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Shield Microfinance Bank",
        "uba_code": "090559",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Signature Bank", "uba_code": "000034", "moneygram_code": "000034", "ecobank_code": None},
    {
        "uba_institution_name": "SIMPLE FINANCE LIMITED",
        "uba_code": "050008",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "SMARTCASH PAYMENT SERVICE BANK",
        "uba_code": "120004",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "SNOW MFB", "uba_code": "090573", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "SOLID ALLIANZE MICROFINANCE BANK",
        "uba_code": "090506",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Solidrock Microfinance Bank",
        "uba_code": "090524",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "SOURCE MICROFINANCE BANK",
        "uba_code": "090641",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Sparkle", "uba_code": "090325", "moneygram_code": "100012", "ecobank_code": None},
    {"uba_institution_name": "SPAY Business", "uba_code": "110026", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Spectrum Microfinance Bank",
        "uba_code": "090436",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Stanbic IBTC @ease Wallet",
        "uba_code": "100007",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "StanbicIBTC Bank",
        "uba_code": "000012",
        "moneygram_code": "000012",
        "ecobank_code": "221",
    },
    {
        "uba_institution_name": "Standard Microfinance Bank",
        "uba_code": "090182",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "StandardChartered",
        "uba_code": "000021",
        "moneygram_code": "000021",
        "ecobank_code": "068",
    },
    {"uba_institution_name": "Stanford MFB", "uba_code": "090162", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "STATESIDE MFB", "uba_code": "090583", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "STB MORTGAGE BANK", "uba_code": "070022", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Stellas Microfinance bank",
        "uba_code": "090262",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Sterling Bank", "uba_code": "000001", "moneygram_code": "000001", "ecobank_code": "232"},
    {
        "uba_institution_name": "Stockcorp Microfinance Bank",
        "uba_code": "090340",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Sulsap MFB", "uba_code": "090305", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Sunbeam Microfinance Bank",
        "uba_code": "090302",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "SUNTOP MICROFINANCE BANK",
        "uba_code": "090644",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Suntrust Bank", "uba_code": "000022", "moneygram_code": "000022", "ecobank_code": "100"},
    {"uba_institution_name": "Support MF Bank", "uba_code": "090446", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "SUPREME MICROFINANCE BANK",
        "uba_code": "090564",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "TagpayVisual Ict", "uba_code": "100023", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Taj Bank", "uba_code": "000026", "moneygram_code": "100002", "ecobank_code": "302"},
    {"uba_institution_name": "TAJ_PINSPAY", "uba_code": "080002", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "TANGALE MICROFINANCE BANK",
        "uba_code": "090638",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "TANGERINE MONEY", "uba_code": "090426", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "TASUED MICROFINANCE BANK",
        "uba_code": "090593",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "TCF Microfinance Bank Limited",
        "uba_code": "090115",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Team APT", "uba_code": "110007", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "TeasyMobile", "uba_code": "100010", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Tekla Finance Ltd", "uba_code": "050007", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "TF MICROFINANCE BANK",
        "uba_code": "090373",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "THRIVE MFB", "uba_code": "090283", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "TITAN TRUST BANK",
        "uba_code": "000025",
        "moneygram_code": "000025",
        "ecobank_code": "102",
    },
    {
        "uba_institution_name": "TREASURES MICROFINANCE BANK",
        "uba_code": "090663",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Trident Microfinance Bank",
        "uba_code": "090146",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "TRINITY FINANCIAL", "uba_code": "050014", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Triple A Microfinance Bank",
        "uba_code": "090525",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "TRIVES FINANCE COMPANY LTD",
        "uba_code": "050023",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Trust MFB", "uba_code": "090327", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "TrustBanc J6 Microfinance Bank Limited",
        "uba_code": "090123",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Trustbond Mortgage Bank Plc",
        "uba_code": "090005",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Trustfund Microfinance Bank",
        "uba_code": "090276",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "U AND C Microfinance Bank",
        "uba_code": "090315",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "UDA Microfinance Bank",
        "uba_code": "090403",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Uhuru Microfinance Bank",
        "uba_code": "090517",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Ummah Microfinance Bank",
        "uba_code": "090609",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Umuchinemere Procredit Microfinance Bank",
        "uba_code": "090514",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "UMUCHUKWU MICROFINANCE BANK",
        "uba_code": "090652",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Umunnachi Microfinance Bank",
        "uba_code": "090510",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "UNAAB MFB", "uba_code": "090331", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Uniben Microfinance bank",
        "uba_code": "090266",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Unical MFB", "uba_code": "090193", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "UNIFUND MICROFINANCE BANK LIMITED",
        "uba_code": "090637",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "UNIIBADAN Microfinance Bank",
        "uba_code": "090461",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Unilag Microfinance Bank",
        "uba_code": "090452",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Unilorin Microfinance Bank",
        "uba_code": "090341",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Unimaid Microfinance Bank",
        "uba_code": "090464",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Union Bank", "uba_code": "000018", "moneygram_code": "000018", "ecobank_code": "032"},
    {
        "uba_institution_name": "United Bank for Africa",
        "uba_code": "000004",
        "moneygram_code": "000004",
        "ecobank_code": "033",
    },
    {"uba_institution_name": "Unity Bank", "uba_code": "000011", "moneygram_code": "000011", "ecobank_code": "215"},
    {
        "uba_institution_name": "UniUyo Microfinance Bank",
        "uba_code": "090338",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "UNN MFB", "uba_code": "090251", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "URE MICROFINANCE BANK",
        "uba_code": "090619",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Uzondu MF Bank", "uba_code": "090453", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "VALE FINANCE LIMITED",
        "uba_code": "050020",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Vas2nets Limited", "uba_code": "110015", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Venture Garden Nigeria Limited",
        "uba_code": "110009",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "VFD MICROFINANCE BANK",
        "uba_code": "090110",
        "moneygram_code": "100005",
        "ecobank_code": None,
    },
    {"uba_institution_name": "Virtue MFB", "uba_code": "090150", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Visa Microfinance Bank",
        "uba_code": "090139",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "VTNetworks", "uba_code": "100012", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "WAYA MICROFINANCE BANK LTD",
        "uba_code": "090590",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Wema Bank", "uba_code": "000017", "moneygram_code": "000017", "ecobank_code": "035"},
    {"uba_institution_name": "WESLEY MFB", "uba_code": "090699", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "WETLAND MFB", "uba_code": "090120", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "WinView Bank", "uba_code": "090419", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Woven Finance", "uba_code": "110029", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "WRA MFB", "uba_code": "090631", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Xpress Payments", "uba_code": "090201", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "XPRESS WALLET", "uba_code": "100040", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "XSLNCE Microfinance Bank",
        "uba_code": "090124",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Yello Digital financial services",
        "uba_code": "110027",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Yes MFB", "uba_code": "090142", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Yobe MFB", "uba_code": "090252", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Zenith Bank", "uba_code": "000015", "moneygram_code": "000015", "ecobank_code": "057"},
    {"uba_institution_name": "ZENITH EAZY WALLET", "uba_code": "100034", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "ZenithMobile", "uba_code": "100018", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "ZIKORA MICROFINANCE BANK",
        "uba_code": "090504",
        "moneygram_code": None,
        "ecobank_code": None,
    },
]


@transaction.atomic
def migrate_account_service_provider_codes() -> None:
    nigeria = Country.objects.get(iso_code2="NG")
    uba_fsp = FinancialServiceProvider.objects.get(name="United Bank for Africa - Nigeria")
    moneygram_fsp = FinancialServiceProvider.objects.get(name="Moneygram")
    ecobank_fsp = FinancialServiceProvider.objects.get(name="Nigeria - Eco Bank")

    created_uba_bank_codes = []
    created_eco_bank_codes = []
    created_moneygram_codes = []
    used_hope_mappings = []

    nigeria_uba_rdis = RegistrationDataImport.objects.filter(
        business_area__slug="nigeria", data_source="Flex Registration"
    )
    for rdi in nigeria_uba_rdis:
        for ind in rdi.individuals.filter(delivery_mechanisms_data__isnull=False):
            for account in ind.delivery_mechanisms_data.all():
                ubabank_code = account.data.get("bank_code__transfer_to_account")
                bank_name = account.data.get("bank_name__transfer_to_account")

                if ubabank_code and ubabank_code not in created_uba_bank_codes:
                    created_uba_bank_codes.append(ubabank_code)
                    fi = FinancialInstitution.objects.create(
                        name=bank_name,
                        type="bank",
                        country=nigeria,
                    )
                    FinancialInstitutionMapping.objects.create(
                        code=ubabank_code, financial_service_provider=uba_fsp, financial_institution=fi
                    )
                    # check if other mappings can be created
                    hope_mapping = next((entry for entry in mapping if entry["uba_code"] == ubabank_code), None)
                    if hope_mapping:
                        used_hope_mappings.append(hope_mapping)
                        if moneygram_code := hope_mapping.get("moneygram_code"):
                            if moneygram_code not in created_moneygram_codes:
                                FinancialInstitutionMapping.objects.create(
                                    code=moneygram_code,
                                    financial_service_provider=moneygram_fsp,
                                    financial_institution=fi,
                                )
                                created_moneygram_codes.append(moneygram_code)
                        if ecobank_code := hope_mapping.get("ecobank_code"):
                            if ecobank_code not in created_eco_bank_codes:
                                FinancialInstitutionMapping.objects.create(
                                    code=ecobank_code, financial_service_provider=ecobank_fsp, financial_institution=fi
                                )
                                created_eco_bank_codes.append(ecobank_code)
                    else:
                        print(f"No HOPE mapping for uba_bank_code: {ubabank_code} [{bank_name}]")

    accounts_to_update = []
    nigeria_eco_rdis = RegistrationDataImport.objects.filter(business_area__slug="nigeria", data_source="Excel")
    for rdi in nigeria_eco_rdis:
        for ind in rdi.individuals.filter(delivery_mechanisms_data__isnull=False):
            for account in ind.delivery_mechanisms_data.all():
                data = account.data
                ecobank_code = data.get("bank_code__transfer_to_account")
                data["bank_code_eco__transfer_to_account"] = ecobank_code
                bank_name = data.get("bank_name__transfer_to_account")

                if ecobank_code:
                    hope_mapping = next((entry for entry in mapping if entry["ecobank_code"] == ecobank_code), None)
                    if hope_mapping:
                        used_hope_mappings.append(hope_mapping)

                        ubabank_code = hope_mapping.get("uba_code")
                        data["bank_code__transfer_to_account"] = ubabank_code

                        account.data = data
                        accounts_to_update.append(account)

                        if ubabank_code not in created_uba_bank_codes:
                            created_uba_bank_codes.append(ubabank_code)
                            fi = FinancialInstitution.objects.create(
                                name=bank_name,
                                type="bank",
                                country=nigeria,
                            )
                            FinancialInstitutionMapping.objects.create(
                                code=ubabank_code, financial_service_provider=uba_fsp, financial_institution=fi
                            )

                            # check if other mappings can be created
                            if moneygram_code := hope_mapping.get("moneygram_code"):
                                if moneygram_code not in created_moneygram_codes:
                                    FinancialInstitutionMapping.objects.create(
                                        code=moneygram_code,
                                        financial_service_provider=moneygram_fsp,
                                        financial_institution=fi,
                                    )
                                    created_moneygram_codes.append(moneygram_code)

                            # check if other mappings can be created
                            if ecobank_code := hope_mapping.get("ecobank_code"):
                                if ecobank_code not in created_eco_bank_codes:
                                    FinancialInstitutionMapping.objects.create(
                                        code=ecobank_code,
                                        financial_service_provider=ecobank_fsp,
                                        financial_institution=fi,
                                    )
                                    created_eco_bank_codes.append(ecobank_code)

                    else:
                        print(f"No HOPE mapping for eco_bank_code: {ecobank_code} [{bank_name}]")

    if accounts_to_update:
        DeliveryMechanismData.objects.bulk_update(accounts_to_update, ["data"])
        print(f"Updated {len(accounts_to_update)} ECO BANK accounts \n\n")

    print(f"Used {len(used_hope_mappings)} HOPE mappings: {used_hope_mappings} \n\n")
    print(f"Created {len(created_uba_bank_codes)} UBA FSP mappings: {created_uba_bank_codes} \n\n")
    print(f"Created {len(created_eco_bank_codes)} ECO FSP mappings: {created_eco_bank_codes} \n\n")
    print(f"Created {len(created_moneygram_codes)} MONEYGRAM FSP mappings: {created_moneygram_codes} \n\n")
