from typing import Dict, List, Optional

from django.db import transaction

from hct_mis_api.apps.geo.models import Country
from hct_mis_api.apps.payment.models import (
    DeliveryMechanismData,
    FinancialInstitution,
    FinancialInstitutionMapping,
    FinancialServiceProvider,
)
from hct_mis_api.apps.registration_data.models import RegistrationDataImport

mapping: List[Dict[str, Optional[str]]] = [
    {
        "uba_institution_name": "3line Card Management Limited",
        "uba_code": "110005",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "78 FINANCE COMPANY LIMITED",
        "uba_code": "110072",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "9 PAYMENT SERVICE BANK",
        "uba_code": "120001",
        "moneygram_code": "100003",
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "9JAPAY MICROFINANCE BANK",
        "uba_code": "90629",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "AAA FINANCE", "uba_code": "50005", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "AB Microfinance bank",
        "uba_code": "90270",
        "moneygram_code": "100011",
        "ecobank_code": None,
    },
    {"uba_institution_name": "ABBEY MORTGAGE BANK", "uba_code": "70010", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Above Only Microfinance bank",
        "uba_code": "90260",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ABSU MICROFINANCE BANK",
        "uba_code": "90640",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ABU Microfinance bank",
        "uba_code": "90197",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ABUCOOP MICROFINANCE BANK",
        "uba_code": "90424",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ABULESORO MICROFINANCE BANK LTD",
        "uba_code": "90545",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Accelerex network", "uba_code": "90202", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Access Bank", "uba_code": "14", "moneygram_code": "14", "ecobank_code": "44"},
    {"uba_institution_name": "Access Money", "uba_code": "100013", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Access Yello", "uba_code": "100052", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "ACCION MFB", "uba_code": "90134", "moneygram_code": "100008", "ecobank_code": None},
    {"uba_institution_name": "ADA MFB", "uba_code": "90483", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Addosser MFBB", "uba_code": "90160", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Adeyemi College Staff Microfinance bank",
        "uba_code": "90268",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Advans LaFayette MFB", "uba_code": "90155", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Afekhafe Microfinance Bank",
        "uba_code": "90292",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Afemai Microfinance Bank",
        "uba_code": "90518",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "AG Mortgage Bank Plc",
        "uba_code": "100028",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Agosasa MICROFINANCE BANK",
        "uba_code": "90371",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "AKPO MICROFINANCE BANK",
        "uba_code": "90608",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "AKU MICROFINANCE BANK",
        "uba_code": "90531",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "AKUCHUCKWU MICROFINANCE BANK",
        "uba_code": "90561",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Akuchukwu MFB", "uba_code": "90561", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Akwa savings and Loans Limited",
        "uba_code": "70025",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "AL-BARKAH MFB", "uba_code": "90133", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Alekun Microfinance bank",
        "uba_code": "90259",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Alert MFB", "uba_code": "90297", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "AL-HAYAT MICROFINANCE BANK",
        "uba_code": "90277",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "ALLWORKERS MFB", "uba_code": "90131", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "ALLY MICROFINANCE BANK",
        "uba_code": "90548",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Alpha Kapital Mfb Ltd",
        "uba_code": "90169",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ALTERNATIVE BANK LIMITED",
        "uba_code": "37",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ALVANA MICROFINANCE BANK",
        "uba_code": "90489",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Amac Microfinance Bank",
        "uba_code": "90394",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "AMJU UNIQUE MICROFINANCE BANK",
        "uba_code": "90180",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "AMML MFB", "uba_code": "90116", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "AMOYE MICROFINANCE BANK",
        "uba_code": "90610",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "AMUCHA MICROFINANCE BANK",
        "uba_code": "90645",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Anchorage MFB", "uba_code": "90476", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Aniocha MFB", "uba_code": "90469", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "APEKS Microfinance Bank",
        "uba_code": "90143",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "APPLE MICROFINANCE BANK",
        "uba_code": "90376",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ARAMOKO MICROFINANCE BANK",
        "uba_code": "90307",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ARCA PAYMENTS COMPANY LIMITED",
        "uba_code": "110011",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Arise MFB", "uba_code": "90282", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "ASOSavings", "uba_code": "90001", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "ASPIRE MICROFINANCE BANK LTD",
        "uba_code": "90544",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Assets Matrix MFB", "uba_code": "90287", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "ASSETS Microfinance Bank",
        "uba_code": "90473",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Astrapolis MFB", "uba_code": "90172", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "ATBU Microfinance Bank",
        "uba_code": "90451",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Auchi Microfinance bank",
        "uba_code": "90264",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "AVE MARIA MICROFINANCE BANK LTD",
        "uba_code": "90600",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Avuenegbe MFB", "uba_code": "90478", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "AWACASH MICROFINANCE BANK",
        "uba_code": "90633",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Awesome Microfinance Bank",
        "uba_code": "90662",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Aztec Microfinance Bank",
        "uba_code": "90540",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BABURA MICROFINANCE BANK",
        "uba_code": "90625",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BAINES CREDIT MICROFINANCE BANK",
        "uba_code": "90188",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Balogun Fulani Microfinance Bank",
        "uba_code": "90181",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BALOGUN GAMBARI MICROFINANCE BANK",
        "uba_code": "90326",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BAM MICROFINANCE BANK",
        "uba_code": "90651",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BANC CORP MICROFINANCE BANK LTD",
        "uba_code": "90581",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Banex Microfinance Bank",
        "uba_code": "90425",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Bankly Microfinance Bank",
        "uba_code": "90529",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BAOBAB MICROFINANCE BANK",
        "uba_code": "90136",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Bayero MICROFINANCE BANK",
        "uba_code": "90316",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "BC Kash MFB", "uba_code": "90127", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "BELLBANK Microfinance Bank",
        "uba_code": "90672",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BENYSTA MICROFINANCE BANK",
        "uba_code": "90413",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "BESTSTAR MFB", "uba_code": "90615", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "BESTSTAR MICROFINANCE BANK",
        "uba_code": "90615",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BETHEL MICROFINANCE BANK",
        "uba_code": "90683",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BIPC MICROFINANCE BANK",
        "uba_code": "90336",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Blue Investments Microfinance Bank",
        "uba_code": "90538",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Bluewhales Microfinance Bank",
        "uba_code": "90431",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Boctrust Microfinance Bank Limited",
        "uba_code": "90117",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BOI Microfinance Bank",
        "uba_code": "90444",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BOJIÂ BOJIÂ MICROFINANCE BANK",
        "uba_code": "90494",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "BOKKOS MFB", "uba_code": "90703", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Bonghe Microfinance Bank",
        "uba_code": "90319",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BORGU MICROFINANCE BANK",
        "uba_code": "90395",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Borno Renaissance Microfinance Bank",
        "uba_code": "90508",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Boromu Microfinance Bank",
        "uba_code": "90501",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Borstal Microfinance Bank",
        "uba_code": "90454",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Bosak MFB", "uba_code": "90176", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Bowen MFB", "uba_code": "90148", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Branch International Financial Services",
        "uba_code": "50006",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Brent Mortgage Bank", "uba_code": "70015", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "BRETHREN MICROFINANCE BANK",
        "uba_code": "90293",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Bridgeway Microfinance Bank",
        "uba_code": "90393",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Brightway MFB", "uba_code": "90308", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "BRIYTH-COVENANT MICROFINANCE BANK",
        "uba_code": "90636",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BROADVIEW MICROFINANCE BANK",
        "uba_code": "90568",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BUBAYERO MICORFINANCE BANK",
        "uba_code": "90512",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Bud infrastructure Limited",
        "uba_code": "110021",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BUILD MICROFINANCE BANK",
        "uba_code": "90613",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BUNDI MICROFINANCE BANK",
        "uba_code": "90661",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BUNKURE MICROFINANCE BANK",
        "uba_code": "90655",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Business SupportMicrofinance Bank",
        "uba_code": "90406",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "BUYPOWER MICROFINANACE BANK",
        "uba_code": "90682",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Calabar Microfinance Bank",
        "uba_code": "90415",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "CANAAN MICROFINANCE BANK",
        "uba_code": "90647",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "CAPITALMETRIQ SWIFT MICROFINANCE BANK",
        "uba_code": "90509",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Capricorn Digital", "uba_code": "110023", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "CAPSTONE Microfinance Bank",
        "uba_code": "90445",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Carbon MFB", "uba_code": "100026", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Cardinalstone Finance",
        "uba_code": "50017",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "CARETAKER Microfinance Bank",
        "uba_code": "90472",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "CASHBRIDGE MICROFINANCE BANK",
        "uba_code": "90634",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Cashconnect MICROFINANCE BANK",
        "uba_code": "90360",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "CATLANDÂ MICROFINANCE BANK",
        "uba_code": "90498",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Cellulant PSSP", "uba_code": "110012", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "CEMCS MFB", "uba_code": "90154", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Central Bank of Nigeria", "uba_code": "28", "moneygram_code": None, "ecobank_code": "1"},
    {"uba_institution_name": "CHANELLE MFB", "uba_code": "90397", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Changan RTS Microfinance Bank",
        "uba_code": "90470",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Chase Microfinance Bank",
        "uba_code": "90523",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Cherish Microfinance Bank",
        "uba_code": "90440",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "CHIBUEZE MFB", "uba_code": "90416", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Chikum Microfinance Bank",
        "uba_code": "90141",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Chukwunenye Microfinance Bank",
        "uba_code": "90490",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "CINTRUST MFB", "uba_code": "90480", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Citi Bank", "uba_code": "9", "moneygram_code": "9", "ecobank_code": "23"},
    {"uba_institution_name": "Citizen Trust Â MFB", "uba_code": "90343", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "CITYCODE MORTGAGE BANK",
        "uba_code": "70027",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Clover Leaf Microfinance Bank",
        "uba_code": "90511",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "CoalCamp Microfinance Bank",
        "uba_code": "90254",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Coastline MICROFINANCE BANK",
        "uba_code": "90374",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "CONFIDENCE MICROFINANCE BANK LTD",
        "uba_code": "90530",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "CONSUMER MFB", "uba_code": "90130", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Coop Mortgage Bank", "uba_code": "70021", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Corestep MICROFINANCE BANK",
        "uba_code": "90365",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Coronation Merchant Bank",
        "uba_code": "60001",
        "moneygram_code": None,
        "ecobank_code": "559",
    },
    {"uba_institution_name": "Covenant", "uba_code": "70006", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Credit Afrique MFB", "uba_code": "90159", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Creditville MFB", "uba_code": "90611", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "CRESCENT MICROFINANCE BANK",
        "uba_code": "90526",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "CrossRiver Microfinance Bank",
        "uba_code": "90429",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "CROWDFORCE", "uba_code": "110017", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "CRUST MICROFINANCE BANK",
        "uba_code": "90560",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Crutech Microfinance Bank",
        "uba_code": "90414",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "CSD MFB", "uba_code": "90686", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Cyberspace Limited", "uba_code": "110014", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "DAL MICROFINANCE BANK",
        "uba_code": "90596",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "DAVENPORT MICROFINANCE BANK",
        "uba_code": "90673",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Davodani Microfinance Bank",
        "uba_code": "90391",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Daylight Microfinance Bank",
        "uba_code": "90167",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "DELTA TRUST MORTGAGE BANK",
        "uba_code": "70023",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Dignity Finance", "uba_code": "50013", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "DIOBU MICROFINANCE BANK",
        "uba_code": "90643",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "DOJE Microfinance Bank Limited",
        "uba_code": "90404",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Eagle Flight MFB", "uba_code": "90294", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Earnwell MICROFINANCE BANK",
        "uba_code": "90674",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Eartholeum", "uba_code": "100021", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "e-BARCs MFB", "uba_code": "90156", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "EBSU MFB", "uba_code": "90427", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Ecobank Bank", "uba_code": "10", "moneygram_code": "10", "ecobank_code": "50"},
    {"uba_institution_name": "EcoMobile", "uba_code": "100008", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Edfin MFB", "uba_code": "90310", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "E-FINANCE", "uba_code": "50016", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "EGWAFIN MICROFINANCE BANK",
        "uba_code": "90556",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "EKIMOGUN MICROFINANCE BANK",
        "uba_code": "90552",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "EKONDO MICROFINANCE BANK",
        "uba_code": "90097",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "EK-Reliable Microfinance Bank",
        "uba_code": "90389",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Emeralds MFB", "uba_code": "90273", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "EMPIRE MFB", "uba_code": "90114", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "e-Naira", "uba_code": "33", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "ENCO FINANCE COMPANY LTD",
        "uba_code": "50012",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Enterprise Bank", "uba_code": "19", "moneygram_code": "100001", "ecobank_code": None},
    {
        "uba_institution_name": "ENTITY MICROFINANCE BANK",
        "uba_code": "90656",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Esan Microfinance Bank",
        "uba_code": "90189",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Eso-E Microfinance Bank",
        "uba_code": "90166",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "eTranzact", "uba_code": "100006", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Evangel MFB", "uba_code": "90304", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Evergreen MICROFINANCE BANK",
        "uba_code": "90332",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "EWT Microfinance Bank",
        "uba_code": "90572",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "EXCEL MICROFINANCE BANK",
        "uba_code": "90678",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "EXCELLENT MICROFINANCE BANK",
        "uba_code": "90541",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "EYOWO MFB", "uba_code": "90328", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "FAIRMONEY MICROFINANCE BANK LTD",
        "uba_code": "90551",
        "moneygram_code": "100006",
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "FAME Microfinance Bank",
        "uba_code": "90330",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "FAST CREDIT", "uba_code": "50009", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "FAST MICROFINANCE BANK",
        "uba_code": "90179",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "FBNQuest Merchant bank",
        "uba_code": "60002",
        "moneygram_code": None,
        "ecobank_code": "11",
    },
    {"uba_institution_name": "FCMB", "uba_code": "3", "moneygram_code": "3", "ecobank_code": "214"},
    {"uba_institution_name": "FCMB BETA", "uba_code": "90409", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "FCMB MOBILE", "uba_code": "100031", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "FCT MFB", "uba_code": "90290", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "FEDERAL POLYTECHNIC NEKEDE MICROFINANCE BANK",
        "uba_code": "90398",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "FEDERAL UNIVERSITY DUTSE MICROFINANCE BANK",
        "uba_code": "90318",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "FederalPoly NasarawaMFB",
        "uba_code": "90298",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "FEDETH MFB", "uba_code": "90482", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "FETS", "uba_code": "100001", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "FEWCHORE FINANCE COMPANY LIMITED",
        "uba_code": "50002",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "FFS Microfinance Bank",
        "uba_code": "90153",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "FHA MORTGAGE BANK LTD",
        "uba_code": "70026",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Fidelity Bank", "uba_code": "7", "moneygram_code": "7", "ecobank_code": "70"},
    {"uba_institution_name": "Fidelity Mobile", "uba_code": "100019", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "FidFund MFB", "uba_code": "90126", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "FIMS MICROFINANCE BANK",
        "uba_code": "90507",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "FinaTrust Microfinance Bank",
        "uba_code": "90111",
        "moneygram_code": "100010",
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Finca Microfinance Bank",
        "uba_code": "90400",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Firmus MFB", "uba_code": "90366", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "First Apple Limited", "uba_code": "110004", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "First Bank of Nigeria", "uba_code": "16", "moneygram_code": "16", "ecobank_code": "11"},
    {
        "uba_institution_name": "First Generation Mortgage Bank",
        "uba_code": "70014",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "First Heritage MFB", "uba_code": "90479", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "First Mortgage Limited",
        "uba_code": "90107",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "First Multiple MFB", "uba_code": "90163", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "First Option MFB", "uba_code": "90285", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "First Royal Microfinance Bank",
        "uba_code": "90164",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "FIRSTMIDAS MICROFINANCE BANK LTD",
        "uba_code": "90575",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "FirstMonie Wallet", "uba_code": "100014", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Flourish MFB", "uba_code": "90614", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Flutterwave Technology solutions Limited",
        "uba_code": "110002",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Foresight Microfinance Bank",
        "uba_code": "90521",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Fortis Microfinance Bank",
        "uba_code": "70002",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "FortisMobile", "uba_code": "100016", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Fotress Microfinance Bank",
        "uba_code": "90486",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "FSDH", "uba_code": "400001", "moneygram_code": None, "ecobank_code": "501"},
    {"uba_institution_name": "Full range MFB", "uba_code": "90145", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "FUNDQUEST FINANCIAL SERVICES LTD",
        "uba_code": "50010",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Futminna Microfinance Bank",
        "uba_code": "90438",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "FUTO MFB", "uba_code": "90158", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "GABASAWA MICROFINANCE BANK",
        "uba_code": "90582",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GABSYN MICROFINANCE BANK",
        "uba_code": "90591",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "GARKI MFB", "uba_code": "90484", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Garun Mallam MFB", "uba_code": "90691", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Gashua Microfinance Bank",
        "uba_code": "90168",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GATEWAY MORTGAGE BANK",
        "uba_code": "70009",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GBEDE MICROFINANCE BANK",
        "uba_code": "90579",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "GDL FINANCE", "uba_code": "50026", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "GIDAUNIYAR ALHERI MICROFINANCE BANK",
        "uba_code": "90621",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Giginya MFB", "uba_code": "90411", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Girei MFB", "uba_code": "90186", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Giwa Microfinance Bank",
        "uba_code": "90441",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GLOBAL INITIATIVE MICROFINANCE BANK",
        "uba_code": "90639",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Globus Bank", "uba_code": "27", "moneygram_code": "27", "ecobank_code": "103"},
    {
        "uba_institution_name": "Glory Microfinance Bank",
        "uba_code": "90278",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GMB Microfinance Bank",
        "uba_code": "90408",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GOLDMAN MICROFINANCE BANK LTD",
        "uba_code": "90574",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GOMBE MICROFINANCE BANK LTD",
        "uba_code": "90586",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "GOMONEY", "uba_code": "100022", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Good Neighbours Microfinance Bank",
        "uba_code": "90467",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GOOD SHEPHERD MICROFINANCE BANK",
        "uba_code": "90664",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GOODNEWS MICROFINANCE BANK",
        "uba_code": "90495",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "GOSIFECHUKWU MFB", "uba_code": "90687", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "GOWANS MFB", "uba_code": "90122", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Grant Microfinance Bank",
        "uba_code": "90335",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GREEN ENERGY MICROFINANCE BANK LTD",
        "uba_code": "90550",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GREENACRES MICROFINANCE BANK LTD",
        "uba_code": "90599",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "GreenBank MFB", "uba_code": "90178", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Greenville Microfinance bank",
        "uba_code": "90269",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "GREENWICH MERCHANT BANK",
        "uba_code": "60004",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Grooming Microfinance bank",
        "uba_code": "90195",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "GTBank Plc", "uba_code": "13", "moneygram_code": "13", "ecobank_code": "58"},
    {
        "uba_institution_name": "GTI Microfinance Bank",
        "uba_code": "90385",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "GTMobile", "uba_code": "100009", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "GWONG MICROFINANCE BANK",
        "uba_code": "90500",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Habaripay", "uba_code": "110059", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Hackman Microfinance Bank",
        "uba_code": "90147",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "HAGGAI MORTGAGE BANK LIMITED",
        "uba_code": "70017",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Hala MFB", "uba_code": "90291", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Halo Microfinance Bank",
        "uba_code": "90539",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "HASAL MFB", "uba_code": "90121", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Headway MFB", "uba_code": "90363", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Hedonmark", "uba_code": "100017", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Heritage", "uba_code": "20", "moneygram_code": "20", "ecobank_code": "30"},
    {
        "uba_institution_name": "HIGHLAND MICROFINANCE BANK",
        "uba_code": "90418",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "HomeBase Mortgage Bank",
        "uba_code": "70024",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Hope Payment Service Bank",
        "uba_code": "120002",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IBA Microfinance Bank",
        "uba_code": "90598",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IBETO MICROFINANCE BANK",
        "uba_code": "90439",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Ibile Microfinance Bank Limited",
        "uba_code": "90118",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IBOLO MICORFINANCE BANK LTD",
        "uba_code": "90532",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Ibom fadama Microfinance Bank",
        "uba_code": "90519",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IBU-AJE MICROFINANCE BANK",
        "uba_code": "90488",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IC GLOBALMicrofinance Bank",
        "uba_code": "90520",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IJEBU-IFE MICROFINANCE BANK LTD",
        "uba_code": "90546",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "IKENNE MFB", "uba_code": "90324", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Ikire MFB", "uba_code": "90279", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "IKOYI ILE MICROFINANCEBANK",
        "uba_code": "90681",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IKOYI-OSUN MICROFINANCE BANK",
        "uba_code": "90536",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Ilasan MICROFINANCE BANK",
        "uba_code": "90370",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Illorin Microfinance Bank",
        "uba_code": "90350",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Ilora Microfinance Bank",
        "uba_code": "90430",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Imo Microfinance bank",
        "uba_code": "90258",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Imowo Microfinance Bank",
        "uba_code": "90417",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Imperial Homes Mortgage Bank",
        "uba_code": "100024",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IMSU MICROFINANCE BANK",
        "uba_code": "90670",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Infinity MFB", "uba_code": "90157", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Infinity trust Mortgage Bank",
        "uba_code": "70016",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Innovectives Kesh", "uba_code": "100029", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Insight Microfinance Bank",
        "uba_code": "90434",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Intellifin", "uba_code": "100027", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Interland MFB", "uba_code": "90386", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Interswitch Financial Inclusion ServicesIFIS",
        "uba_code": "110010",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Interswitch Limited", "uba_code": "110003", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "IPERUÂ MICROFINANCE BANK",
        "uba_code": "90493",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IRL Microfinance Bank",
        "uba_code": "90149",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ISALEOYO MICROFINANCE BANK",
        "uba_code": "90377",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Ishie Microfinance Bank",
        "uba_code": "90428",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ISLAND MICROFINANCE BANK LTD",
        "uba_code": "90584",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Isuofia MFB", "uba_code": "90353", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Itex Integrated Services Limited",
        "uba_code": "90211",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IWADE MICROFINANCE BANK LTD",
        "uba_code": "90578",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IYAMOYE MICROFINANCE BANK",
        "uba_code": "90570",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "IYERU OKIN MICROFINANCE BANK LTD",
        "uba_code": "90337",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Izon Microfinance Bank",
        "uba_code": "90421",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "JAIZ Bank", "uba_code": "6", "moneygram_code": "6", "ecobank_code": "301"},
    {
        "uba_institution_name": "JESSEFIELD MICROFINANCE",
        "uba_code": "90352",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "JubileeLife", "uba_code": "90003", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Kadick Integration Limited",
        "uba_code": "110008",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Kadpoly MICROFINANCE BANK",
        "uba_code": "90320",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "KADUPE MICROFINANCE BANK",
        "uba_code": "90669",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "KANOPOLY MICROFINANCE BANK LIMITED",
        "uba_code": "90592",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "KAYI MICROFINANCE BANK",
        "uba_code": "90667",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Kayvee Microfinance Bank",
        "uba_code": "90554",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "KC MICROFINANCE BANK", "uba_code": "90549", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "KCMB MFB", "uba_code": "90191", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "KEGOWCHAMSMOBILE", "uba_code": "100036", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "KENECHUKWU MICROFINANCE BANK",
        "uba_code": "90602",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Keystone Bank", "uba_code": "2", "moneygram_code": "2", "ecobank_code": "82"},
    {
        "uba_institution_name": "KINGDOM COLLEGE MICROFINANCE BANK",
        "uba_code": "90487",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "KKU Microfinance Bank",
        "uba_code": "90606",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "KongaPay", "uba_code": "100025", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Kontagora MFB", "uba_code": "90299", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "KOPO KOPE MICROFINANCE BANK",
        "uba_code": "90617",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Koraypay", "uba_code": "110022", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "KREDI MONEY MICROFINANCE BANK",
        "uba_code": "90380",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Kuda Microfinance Bank",
        "uba_code": "90267",
        "moneygram_code": "100004",
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "KWASU Microfinance Bank",
        "uba_code": "90450",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "LANDGOLD MICROFINANCE BANK",
        "uba_code": "90422",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Lapo MFB", "uba_code": "90177", "moneygram_code": "100007", "ecobank_code": None},
    {
        "uba_institution_name": "Lavender Microfinance bank",
        "uba_code": "90271",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "LBIC Mortgage Bank", "uba_code": "70012", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "LEADCITY MICROFINANCE BANK",
        "uba_code": "90650",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "LEADREMIT LIMITED", "uba_code": "110044", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Legend MICROFINANCE BANK",
        "uba_code": "90372",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Light Microfinance Bank",
        "uba_code": "90477",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "LINKS MICROFINANCE BANK",
        "uba_code": "90435",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Lobrem Microfinance Bank",
        "uba_code": "90537",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "LOMA MFB", "uba_code": "90620", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "LOTUS BANK", "uba_code": "29", "moneygram_code": "29", "ecobank_code": "303"},
    {
        "uba_institution_name": "Lovonus Microfinance bank",
        "uba_code": "90265",
        "moneygram_code": "100013",
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Ltshego Microfinance Bank",
        "uba_code": "90420",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "LUKEFIELD FINANCE COMPANY LIMITED",
        "uba_code": "50015",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "M&M MFB", "uba_code": "90685", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "M36", "uba_code": "100035", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "MAB ALLIANZ MICROFINANCE BANK",
        "uba_code": "90623",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MABINAS MICROFINANCE BANK",
        "uba_code": "90630",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Macrod MFB", "uba_code": "90603", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "MADOBI MICROFINANCE BANK",
        "uba_code": "90605",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MAINLAND MICROFINANCE BANK",
        "uba_code": "90323",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MAINSTREET MICROFINANCE BANK",
        "uba_code": "90171",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Maintrust MFB", "uba_code": "90465", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "MALACHY MICROFINANCE BANK",
        "uba_code": "90174",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Manny MFB", "uba_code": "90383", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "MARITIME MICROFINANCE BANK",
        "uba_code": "90410",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Mautech Microfinance Bank",
        "uba_code": "90423",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Mayfair MFB", "uba_code": "90321", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "MayFresh Mortgage Bank",
        "uba_code": "70019",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Medef MFB", "uba_code": "90612", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Megapraise Microfinance Bank",
        "uba_code": "90280",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MEMPHIS MICROFINANCE BANK",
        "uba_code": "90432",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MERCURY MICROFINANCE BANK",
        "uba_code": "90589",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Meridian MFB", "uba_code": "90275", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Mgbidi Microfinance Bank",
        "uba_code": "90528",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Microbiz MFB", "uba_code": "90587", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Microsystems Investment and Development Limited",
        "uba_code": "110018",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MICROVIS MICROFINANCE BANK",
        "uba_code": "90113",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Midland MFB", "uba_code": "90192", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "MINJIBIR MICROFINANCE BANK",
        "uba_code": "90607",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MINT-FINEX MICROFINANCE",
        "uba_code": "90281",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MKOBO MICROFINANCE BANK LTD",
        "uba_code": "90455",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Mkudi", "uba_code": "100011", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "MOLUSI MFB", "uba_code": "90362", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Momo Payment services Bank",
        "uba_code": "120003",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Monarch Microfinance Bank",
        "uba_code": "90462",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Money Master PSB", "uba_code": "120005", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "MoneyBox", "uba_code": "100020", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "MONEYFIELD MICROFINANCE BANK",
        "uba_code": "90144",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "MONEYTRUST MFB", "uba_code": "90129", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Moniepoint MFB", "uba_code": "90405", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Moyofade MF Bank", "uba_code": "90448", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "MOZFIN MICROFINANCE BANK",
        "uba_code": "90392",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "MUTUAL ALLIANCE MORTGAGE BANK",
        "uba_code": "70028",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "MUTUAL BENEFIT MFB", "uba_code": "90190", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Mutual Trust Microfinance Bank",
        "uba_code": "90151",
        "moneygram_code": "100009",
        "ecobank_code": None,
    },
    {"uba_institution_name": "Nargata MFB", "uba_code": "90152", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "NDDC MICROFINANCE BANK",
        "uba_code": "90679",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Ndiorah MFB", "uba_code": "90128", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Neptune MFB", "uba_code": "90329", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "NET MFB", "uba_code": "90675", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "NetApps Technology Limited",
        "uba_code": "110025",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "New Dawn Microfinance Bank",
        "uba_code": "90205",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "NEW GOLDEN PASTURES MICROFINANCE BANK",
        "uba_code": "90378",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "New Prudential Bank", "uba_code": "90108", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "NEWEDGE FINANCE LTD", "uba_code": "50004", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "NEXIM BANK", "uba_code": "30001", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "NIBSSUSSD PAYMENTS", "uba_code": "110019", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "NICE Microfinance Bank",
        "uba_code": "90459",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "NIGERIAN NAVY MICROFINANCE BANK",
        "uba_code": "90263",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "NIGERIAN PRISONS MICROFINANCE BANK",
        "uba_code": "90505",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "NIP Virtual Bank", "uba_code": "999999", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "NIRSAL MICROFINANCE BANK",
        "uba_code": "90194",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Nomba financial services Limited",
        "uba_code": "110028",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "NOVA MERCHANT BANK", "uba_code": "60003", "moneygram_code": None, "ecobank_code": "561"},
    {"uba_institution_name": "NowNowModification", "uba_code": "100032", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "NPF MicroFinance Bank",
        "uba_code": "70001",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "NSEHE MICROFINANCE BANK",
        "uba_code": "90628",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "NSUK MICROFINANCE BANK",
        "uba_code": "90491",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "NUGGETS MFB", "uba_code": "90676", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Numo Microfinance Bank",
        "uba_code": "90516",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Nuture MFB", "uba_code": "90364", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Nwannegadi MFB", "uba_code": "90399", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Oakland Microfinance Bank",
        "uba_code": "90437",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OAU MICROFINANCE BANK",
        "uba_code": "90345",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OCHE MICROFINANCE BANK",
        "uba_code": "90333",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OCTOPUS MICROFINANCE BANK",
        "uba_code": "90576",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ODOAKPU MICROFINANCE BANK LIMITED",
        "uba_code": "90654",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "OHAFIA MFB", "uba_code": "90119", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "OHHA MICROFINANCE BANK",
        "uba_code": "90626",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OJOKORO MICROFINANCE BANK",
        "uba_code": "90527",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "OK MICROFINANCE BANK", "uba_code": "90567", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "OKENGWE MICROFINANCE BANK",
        "uba_code": "90646",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Okpoga MFB", "uba_code": "90161", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "OLABISI ONABANJO UNIVERSITY MICROFINANCE BANK",
        "uba_code": "90272",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "OLIVE MFB", "uba_code": "90696", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "OLOFIN OWENA Microfinance Bank",
        "uba_code": "90468",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OLUCHUKWU Microfinance Bank",
        "uba_code": "90471",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Omiye MFB", "uba_code": "90295", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Omoluabi", "uba_code": "70077", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Omoluabi", "uba_code": "70077", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "OPAY DIGITAL SERVICES LIMITED",
        "uba_code": "100004",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Optimus Bank", "uba_code": "36", "moneygram_code": "36", "ecobank_code": None},
    {
        "uba_institution_name": "Oraukwu Microfinance Bank",
        "uba_code": "90492",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ORISUN MICROFINANCE BANK",
        "uba_code": "90588",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ORITA-BASORUN Microfinance Bank",
        "uba_code": "90460",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OROKAM MICROFINANCE BANK",
        "uba_code": "90567",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Oscotech MFB", "uba_code": "90396", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Ospoly Microfinance Bank",
        "uba_code": "90456",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OTECH MICROFINANCE BANK LTD",
        "uba_code": "90580",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OTUO MICROFINANCE BANK LTD",
        "uba_code": "90542",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "OYAN MICROFINANCE BANK",
        "uba_code": "90635",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Pagatech", "uba_code": "100002", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Page MFBank", "uba_code": "70008", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "PALMCOAST MICROFINANCE BANK",
        "uba_code": "90497",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "PALMPAY", "uba_code": "100033", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "PARALLEX BANK", "uba_code": "30", "moneygram_code": "30", "ecobank_code": None},
    {"uba_institution_name": "Parkway MF Bank", "uba_code": "90390", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Parkway-ReadyCash", "uba_code": "100003", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Parralex Microfinance bank",
        "uba_code": "90004",
        "moneygram_code": None,
        "ecobank_code": "104",
    },
    {
        "uba_institution_name": "PATHFINDER MICROFINANACE BANK LIMITED",
        "uba_code": "90680",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "PATRICKGOLD MICROFINANCE BANK",
        "uba_code": "90317",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "PayAttitude Online", "uba_code": "110001", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Paystack Payments", "uba_code": "110006", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Paystack-Titan", "uba_code": "100039", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Peace Microfinance Bank",
        "uba_code": "90402",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Pecan Trust Microfinance Bank",
        "uba_code": "90137",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "PENIEL MICORFINANCE BANK LTD",
        "uba_code": "90379",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Pennywise Microfinance bank",
        "uba_code": "90196",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Personal Trust Microfinance Bank",
        "uba_code": "90135",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "PETRA MICROFINANCE BANK PLC",
        "uba_code": "90165",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "PFI FINANCE COMPANY LIMITED",
        "uba_code": "50021",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Pillar MFB", "uba_code": "90289", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "PLATINUM MORTGAGE BANK",
        "uba_code": "70013",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "POLARIS BANK", "uba_code": "8", "moneygram_code": "8", "ecobank_code": "76"},
    {
        "uba_institution_name": "Polyibadan Microfinance Bank",
        "uba_code": "90534",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Polyuwanna MFB", "uba_code": "90296", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Preeminent Microfinance Bank",
        "uba_code": "90412",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "PremiumTrust Bank", "uba_code": "31", "moneygram_code": "31", "ecobank_code": "105"},
    {
        "uba_institution_name": "Prestige Microfinance bank",
        "uba_code": "90274",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "PRISCO MFB", "uba_code": "90481", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Pristine Divitis MFB", "uba_code": "90499", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "PROJECTS MICROFINANCE BANK",
        "uba_code": "90503",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "PROSPECTS MFB", "uba_code": "90689", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "PROSPERITY MICROFINANCE BANK",
        "uba_code": "90642",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Providus Bank", "uba_code": "23", "moneygram_code": "23", "ecobank_code": "101"},
    {
        "uba_institution_name": "PRUDENT MICROFINANCE BANK",
        "uba_code": "90690",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Purplemoney MFB", "uba_code": "90303", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "PYRAMID MICROFINANCE BANK",
        "uba_code": "90657",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "QR Payments", "uba_code": "110013", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "QUBE MICROFINANCE BANK LTD",
        "uba_code": "90569",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "QuickFund Microfinance bank",
        "uba_code": "90261",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Rahama MFB", "uba_code": "90170", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Rand Merchant Bank", "uba_code": "24", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "RANDALPHA MFB", "uba_code": "90496", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "RAYYAN MICROFINANCE BANK",
        "uba_code": "90616",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Refuge Mortgage Bank", "uba_code": "70011", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "REGENT MFB", "uba_code": "90125", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Rehoboth Microfinance Bank",
        "uba_code": "90463",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Reliance MFB", "uba_code": "90173", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "RENMONEY MICROFINANCE BANK",
        "uba_code": "90198",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Rephidim MICROFINANCE BANK",
        "uba_code": "90322",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Resident Fintech Limited",
        "uba_code": "110024",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "REVELATION MICROFINANCE BANK",
        "uba_code": "90666",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "REX MICROFINANCE BANK",
        "uba_code": "90449",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "RICHWAY MFB", "uba_code": "90132", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "RIGO MICROFINANCE BANK",
        "uba_code": "90433",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "RIMA GROWTH PATHWAY MICROFINANCE BANK",
        "uba_code": "90515",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "RIMA Microfinance Bank",
        "uba_code": "90443",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "ROCKSHIELD MICROFINANCE BANK",
        "uba_code": "90547",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Royal Exchange Microfinance Bank",
        "uba_code": "90138",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "RSU MICROFINANCE BANK",
        "uba_code": "90535",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "RUBIES MICROFINANCE BANK",
        "uba_code": "90175",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Safe Haven MFB", "uba_code": "90286", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Safegate Microfinance Bank",
        "uba_code": "90485",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Safetrust Mortage", "uba_code": "90006", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Sagamu Microfinance Bank",
        "uba_code": "90140",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "SageGrey Finace Limited",
        "uba_code": "50003",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "SEAP Microfinance Bank",
        "uba_code": "90513",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Seed Capital Microfinance Bank",
        "uba_code": "90112",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "SEEDVEST MICROFINANCE BANK",
        "uba_code": "90369",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "SHALOM MICROFINACE BANK",
        "uba_code": "90502",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Shepherd Trust Microfinance Bank",
        "uba_code": "90401",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "SHIELD MICROFINANCE BANK",
        "uba_code": "90559",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Shield Microfinance Bank",
        "uba_code": "90559",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Signature Bank", "uba_code": "34", "moneygram_code": "34", "ecobank_code": None},
    {
        "uba_institution_name": "SIMPLE FINANCE LIMITED",
        "uba_code": "50008",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "SMARTCASH PAYMENT SERVICE BANK",
        "uba_code": "120004",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "SNOW MFB", "uba_code": "90573", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "SOLID ALLIANZE MICROFINANCE BANK",
        "uba_code": "90506",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Solidrock Microfinance Bank",
        "uba_code": "90524",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "SOURCE MICROFINANCE BANK",
        "uba_code": "90641",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Sparkle", "uba_code": "90325", "moneygram_code": "100012", "ecobank_code": None},
    {"uba_institution_name": "SPAY Business", "uba_code": "110026", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Spectrum Microfinance Bank",
        "uba_code": "90436",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Stanbic IBTC @ease Wallet",
        "uba_code": "100007",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "StanbicIBTC Bank", "uba_code": "12", "moneygram_code": "12", "ecobank_code": "221"},
    {
        "uba_institution_name": "Standard Microfinance Bank",
        "uba_code": "90182",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "StandardChartered", "uba_code": "21", "moneygram_code": "21", "ecobank_code": "68"},
    {"uba_institution_name": "Stanford MFB", "uba_code": "90162", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "STATESIDE MFB", "uba_code": "90583", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "STB MORTGAGE BANK", "uba_code": "70022", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Stellas Microfinance bank",
        "uba_code": "90262",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Sterling Bank", "uba_code": "1", "moneygram_code": "1", "ecobank_code": "232"},
    {
        "uba_institution_name": "Stockcorp Microfinance Bank",
        "uba_code": "90340",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Sulsap MFB", "uba_code": "90305", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Sunbeam Microfinance Bank",
        "uba_code": "90302",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "SUNTOP MICROFINANCE BANK",
        "uba_code": "90644",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Suntrust Bank", "uba_code": "22", "moneygram_code": "22", "ecobank_code": "100"},
    {"uba_institution_name": "Support MF Bank", "uba_code": "90446", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "SUPREME MICROFINANCE BANK",
        "uba_code": "90564",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "TagpayVisual Ict", "uba_code": "100023", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Taj Bank", "uba_code": "26", "moneygram_code": "100002", "ecobank_code": "302"},
    {"uba_institution_name": "TAJ_PINSPAY", "uba_code": "80002", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "TANGALE MICROFINANCE BANK",
        "uba_code": "90638",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "TANGERINE MONEY", "uba_code": "90426", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "TASUED MICROFINANCE BANK",
        "uba_code": "90593",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "TCF Microfinance Bank Limited",
        "uba_code": "90115",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Team APT", "uba_code": "110007", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "TeasyMobile", "uba_code": "100010", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Tekla Finance Ltd", "uba_code": "50007", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "TF MICROFINANCE BANK", "uba_code": "90373", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "THRIVE MFB", "uba_code": "90283", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "TITAN TRUST BANK", "uba_code": "25", "moneygram_code": "25", "ecobank_code": "102"},
    {
        "uba_institution_name": "TREASURES MICROFINANCE BANK",
        "uba_code": "90663",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Trident Microfinance Bank",
        "uba_code": "90146",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "TRINITY FINANCIAL", "uba_code": "50014", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Triple A Microfinance Bank",
        "uba_code": "90525",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "TRIVES FINANCE COMPANY LTD",
        "uba_code": "50023",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Trust MFB", "uba_code": "90327", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "TrustBanc J6 Microfinance Bank Limited",
        "uba_code": "90123",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Trustbond Mortgage Bank Plc",
        "uba_code": "90005",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Trustfund Microfinance Bank",
        "uba_code": "90276",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "U AND C Microfinance Bank",
        "uba_code": "90315",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "UDA Microfinance Bank",
        "uba_code": "90403",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Uhuru Microfinance Bank",
        "uba_code": "90517",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Ummah Microfinance Bank",
        "uba_code": "90609",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Umuchinemere Procredit Microfinance Bank",
        "uba_code": "90514",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "UMUCHUKWU MICROFINANCE BANK",
        "uba_code": "90652",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Umunnachi Microfinance Bank",
        "uba_code": "90510",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "UNAAB MFB", "uba_code": "90331", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Uniben Microfinance bank",
        "uba_code": "90266",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Unical MFB", "uba_code": "90193", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "UNIFUND MICROFINANCE BANK LIMITED",
        "uba_code": "90637",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "UNIIBADAN Microfinance Bank",
        "uba_code": "90461",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Unilag Microfinance Bank",
        "uba_code": "90452",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Unilorin Microfinance Bank",
        "uba_code": "90341",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Unimaid Microfinance Bank",
        "uba_code": "90464",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Union Bank", "uba_code": "18", "moneygram_code": "18", "ecobank_code": "32"},
    {"uba_institution_name": "United Bank for Africa", "uba_code": "4", "moneygram_code": "4", "ecobank_code": "33"},
    {"uba_institution_name": "Unity Bank", "uba_code": "11", "moneygram_code": "11", "ecobank_code": "215"},
    {
        "uba_institution_name": "UniUyo Microfinance Bank",
        "uba_code": "90338",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "UNN MFB", "uba_code": "90251", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "URE MICROFINANCE BANK",
        "uba_code": "90619",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Uzondu MF Bank", "uba_code": "90453", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "VALE FINANCE LIMITED", "uba_code": "50020", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Vas2nets Limited", "uba_code": "110015", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Venture Garden Nigeria Limited",
        "uba_code": "110009",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "VFD MICROFINANCE BANK",
        "uba_code": "90110",
        "moneygram_code": "100005",
        "ecobank_code": None,
    },
    {"uba_institution_name": "Virtue MFB", "uba_code": "90150", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "Visa Microfinance Bank",
        "uba_code": "90139",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "VTNetworks", "uba_code": "100012", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "WAYA MICROFINANCE BANK LTD",
        "uba_code": "90590",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Wema Bank", "uba_code": "17", "moneygram_code": "17", "ecobank_code": "35"},
    {"uba_institution_name": "WESLEY MFB", "uba_code": "90699", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "WETLAND MFB", "uba_code": "90120", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "WinView Bank", "uba_code": "90419", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Woven Finance", "uba_code": "110029", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "WRA MFB", "uba_code": "90631", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Xpress Payments", "uba_code": "90201", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "XPRESS WALLET", "uba_code": "100040", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "XSLNCE Microfinance Bank",
        "uba_code": "90124",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {
        "uba_institution_name": "Yello Digital financial services",
        "uba_code": "110027",
        "moneygram_code": None,
        "ecobank_code": None,
    },
    {"uba_institution_name": "Yes MFB", "uba_code": "90142", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Yobe MFB", "uba_code": "90252", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "Zenith Bank", "uba_code": "15", "moneygram_code": "15", "ecobank_code": "57"},
    {"uba_institution_name": "ZENITH EAZY WALLET", "uba_code": "100034", "moneygram_code": None, "ecobank_code": None},
    {"uba_institution_name": "ZenithMobile", "uba_code": "100018", "moneygram_code": None, "ecobank_code": None},
    {
        "uba_institution_name": "ZIKORA MICROFINANCE BANK",
        "uba_code": "90504",
        "moneygram_code": None,
        "ecobank_code": None,
    },
]


@transaction.atomic
def migrate_account_service_provider_codes() -> None:
    """
    For each delivery mechanism data from Nigeria and imported through aurora

        Does Mapping with code and UBA?

        If doesn’t exist:
            Create Financial Institution based on the name bank_name__transfer_to_account
            Get or Create mapping
                The retrieved/created financial institution:
                UBA as FSP
                Code -> bank_code__transfer_to_account


    For each delivery mechanism data from Nigeria and imported through xls (ECO BANK)
    "bank_code__transfer_to_account" ->  "bank_code_eco__transfer_to_account"
    "bank_code__transfer_to_account" should be migrated according to mapping file (UBA code)

     Create mapping
     FSP = ECOBank
     Financial Institution from mapping
     Code = old code
    """
    nigeria = Country.objects.get(iso_code2="NG")
    uba_fsp = FinancialServiceProvider.objects.get(name="United Bank for Africa - Nigeria")
    moneygram_fsp = FinancialServiceProvider.objects.get(name="Moneygram")
    ecobank_fsp = FinancialServiceProvider.objects.get(name="Nigeria - Eco Bank")

    created_uba_bank_codes = []
    created_eco_bank_codes = []
    created_moneygram_codes = []
    used_hope_mappings = []

    nigeria_uba_rdis = RegistrationDataImport.objects.filter(
        business_area__slug="nigeria", data_source="Flex Registration"
    )
    for rdi in nigeria_uba_rdis:
        for ind in rdi.individuals.filter(delivery_mechanisms_data__isnull=False):
            for account in ind.delivery_mechanisms_data.all():
                ubabank_code = account.data.get("bank_code__transfer_to_account")
                bank_name = account.data.get("bank_name__transfer_to_account")

                if ubabank_code and ubabank_code not in created_uba_bank_codes:
                    created_uba_bank_codes.append(ubabank_code)
                    fi = FinancialInstitution.objects.create(
                        name=bank_name,
                        type="bank",
                        country=nigeria,
                    )
                    FinancialInstitutionMapping.objects.create(
                        code=ubabank_code, financial_service_provider=uba_fsp, financial_institution=fi
                    )
                    # check if other mappings can be created
                    hope_mapping = next((entry for entry in mapping if entry["uba_code"] == ubabank_code), None)
                    if hope_mapping:
                        used_hope_mappings.append(hope_mapping)
                        if moneygram_code := hope_mapping.get("moneygram_code"):
                            if moneygram_code not in created_moneygram_codes:
                                FinancialInstitutionMapping.objects.create(
                                    code=moneygram_code,
                                    financial_service_provider=moneygram_fsp,
                                    financial_institution=fi,
                                )
                                created_moneygram_codes.append(moneygram_code)
                        if ecobank_code := hope_mapping.get("ecobank_code"):
                            if ecobank_code not in created_eco_bank_codes:
                                FinancialInstitutionMapping.objects.create(
                                    code=ecobank_code, financial_service_provider=ecobank_fsp, financial_institution=fi
                                )
                                created_eco_bank_codes.append(ecobank_code)
                    else:
                        print(f"No HOPE mapping for uba_bank_code: {ubabank_code} [{bank_name}]")

    accounts_to_update = []
    nigeria_eco_rdis = RegistrationDataImport.objects.filter(business_area__slug="nigeria", data_source="Excel")
    for rdi in nigeria_eco_rdis:
        for ind in rdi.individuals.filter(delivery_mechanisms_data__isnull=False):
            for account in ind.delivery_mechanisms_data.all():
                data = account.data
                ecobank_code = data.get("bank_code__transfer_to_account")
                data["bank_code_eco__transfer_to_account"] = ecobank_code
                bank_name = data.get("bank_name__transfer_to_account")

                if ecobank_code:
                    hope_mapping = next((entry for entry in mapping if entry["ecobank_code"] == ecobank_code), None)
                    if hope_mapping:
                        used_hope_mappings.append(hope_mapping)

                        ubabank_code = hope_mapping.get("uba_code")
                        data["bank_code__transfer_to_account"] = ubabank_code

                        account.data = data
                        accounts_to_update.append(account)

                        if ubabank_code not in created_uba_bank_codes:
                            created_uba_bank_codes.append(ubabank_code)
                            fi = FinancialInstitution.objects.create(
                                name=bank_name,
                                type="bank",
                                country=nigeria,
                            )
                            FinancialInstitutionMapping.objects.create(
                                code=ubabank_code, financial_service_provider=uba_fsp, financial_institution=fi
                            )

                            # check if other mappings can be created
                            if moneygram_code := hope_mapping.get("moneygram_code"):
                                if moneygram_code not in created_moneygram_codes:
                                    FinancialInstitutionMapping.objects.create(
                                        code=moneygram_code,
                                        financial_service_provider=moneygram_fsp,
                                        financial_institution=fi,
                                    )
                                    created_moneygram_codes.append(moneygram_code)

                            # check if other mappings can be created
                            if ecobank_code := hope_mapping.get("ecobank_code"):
                                if ecobank_code not in created_eco_bank_codes:
                                    FinancialInstitutionMapping.objects.create(
                                        code=ecobank_code,
                                        financial_service_provider=ecobank_fsp,
                                        financial_institution=fi,
                                    )
                                    created_eco_bank_codes.append(ecobank_code)

                    else:
                        print(f"No HOPE mapping for eco_bank_code: {ecobank_code} [{bank_name}]")

    if accounts_to_update:
        DeliveryMechanismData.objects.bulk_update(accounts_to_update, ["data"])
        print(f"Updated {len(accounts_to_update)} ECO BANK accounts \n\n")

    print(f"Used {len(used_hope_mappings)} HOPE mappings: {used_hope_mappings} \n\n")
    print(f"Created {len(created_uba_bank_codes)} UBA FSP mappings: {created_uba_bank_codes} \n\n")
    print(f"Created {len(created_eco_bank_codes)} ECO FSP mappings: {created_eco_bank_codes} \n\n")
    print(f"Created {len(created_moneygram_codes)} MONEYGRAM FSP mappings: {created_moneygram_codes} \n\n")
