class ProgrammeManagement:

    buttonNewProgram = '[data-cy="button-new-program"]'
    pageHeaderTitle = 'h5[data-cy="page-header-title"]'
    dialogTitle = '[data-cy="page-header-title"]'
    inputProgrammeName = 'div[data-cy="input-programme-name"]'
    inputCashAssistScope = 'div[data-cy="input-cash-assist-scope"]'
    selectOptionUnicef = 'li[data-cy="select-option-Unicef"]'
    selectOptionForPartners = 'li[data-cy="select-option-For partners"]'
    inputSector = 'div[data-cy="input-sector"]'
    selectOptionX = 'li[data-cy="select-option-'
    inputStartDate = 'div[data-cy="input-start-date"]'
    inputEndDate = 'div[data-cy="input-end-date"]'
    inputDescription = 'div[data-cy="input-description"]'
    inputBudget = 'input[data-cy="input-budget"]'
    inputAdminArea = 'div[data-cy="input-admin-area"]'
    inputPopulationGoal = 'div[data-cy="input-population-goal"]'
    inputDataCollectingType = 'div[data-cy="input-data-collecting-type"]'
    buttonSave = 'button[data-cy="button-save"]'
    buttonNext = 'button[data-cy="button-next"]'
    statusFilter = 'div[data-cy="filters-status"]'
    option = ' li[role = "option"]'
    buttonApply = 'button[data-cy="button-filters-apply"]'
    statusContainer = 'div[data-cy="status-container"]'
    tableRowX = 'tr[data-cy="table-row-'
    inputFrequencyOfPayment = 'div[data-cy="input-frequency-of-payment"]'
    inputCashPlus = 'span[data-cy="input-cashPlus"]'
    inputIndividualDataNeeded = 'div[data-cy="input-individual-data-needed"]'
    selectDataCollectingTypeCode = 'input[data-cy="select-dataCollectingTypeCode"]'