name: CI
run-name: CI/CD RUN ${{ github.ref_name }}
on:
  push:
    branches:
    - develop
    - staging
    - master
    - ephemeral-*
    - feature/development-improvements

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    uses: ./.github/workflows/frontend-checks.yml
  lint:
    uses: ./.github/workflows/lint.yml
  tests:
    uses: ./.github/workflows/tests.yml
  build:
    needs:
      - lint
      - tests
      - frontend
    uses: ./.github/workflows/build-and-push.yml
    secrets: inherit
  deploy:
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    needs:
      - build