name: CI
run-name: CI/CD RUN ${{ github.ref_name }}
on:
  push:
    branches:
    - develop
    - staging
    - master
    - ephemeral-*

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    uses: ./.github/workflows/frontend-checks.yml
  lint:
    uses: ./.github/workflows/lint.yml
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
  build:
    needs:
      - lint
      - tests
      - frontend
    uses: ./.github/workflows/build-and-push.yml
    secrets: inherit
  trivy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run Trivy vulnerability scanner
        continue-on-error: true # due to getting TOOMANYREQUESTS
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ vars.DOCKERHUB_ORGANIZATION }}/hope-support-images:core-${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  deploy:
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    needs:
      - build
