name: CI
run-name: CI/CD RUN ${{ github.ref_name }}
on:
  push:
    branches:
    - develop
    - staging
    - master
    - ephemeral-*
    - feature/development-improvements

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/ci-pr.yml
    secrets: inherit
  deploy:
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    needs: checks