name: CI-PR
run-name: "PR CHECK #${{ github.event.pull_request.number }}- ${{ github.event.pull_request.title }}"
on:
  pull_request:
    branches:
    - develop
    - staging
    - master
    - ephemeral-*
    - long-term/*
  workflow_call:


concurrency:
  group: CI-PR-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  tests:
    uses: ./.github/workflows/tests.yml
  build:
    needs:
      - lint
      - tests
    uses: ./.github/workflows/build.yml
    secrets: inherit