from faker import Faker

from extras.test_utils.factories import DataCollectingTypeFactory
from hope.models import BusinessArea, Country, CountryCodeMap, Currency, DataCollectingType

faker = Faker()


business_area_short_name_code_map = {
    "Analysis,Planning & Monitoring": "456C",
    "Timor-Leste": "7060",
    "Morocco": "2910",
    "Zambia": "4980",
    "Public Partnerships Division": "456I",
    "Malaysia": "2700",
    "Paraguay": "3360",
    "Nicaragua": "3120",
    "Kazakhstan": "2390",
    "Kosovo": "8971",
    "Kenya": "2400",
    "Cote D'Ivoire": "2250",
    "Albania": "0090",
    "Guinea": "1770",
    "Rep of Uzbekistan": "4630",
    "Dominican Republic": "1260",
    "Saudi Arabia": "3780",
    "Denmark": "1200",
    "EAPRO, Thailand": "420R",
    "Thailand": "4200",
    "Armenia": "0260",
    "Ecuador": "1350",
    "Liberia": "2550",
    "Democratic Republic of Congo": "0990",
    "Barbados": "0420",
    "Lebanon": "2490",
    "Angola": "6810",
    "Nepal": "2970",
    "Tajikistan": "4150",
    "El Salvador": "1380",
    "Costa Rica": "1020",
    "Evaluation Office": "456O",
    "Gabon": "1530",
    "GSSC Project": "456Q",
    "Division of Human Resources": "456K",
    "Research Division": "456E",
    "Chad": "0810",
    "Mongolia": "2880",
    "Syria": "4140",
    "LACRO, Panama": "333R",
    "Sudan": "4020",
    "Republic of Montenegro": "8950",
    "OSEB": "456S",
    "Republic of Mozambique": "6890",
    "Ukraine": "4410",
    "Yemen": "4920",
    "Turkey": "4350",
    "Division of Communication": "456G",
    "United Rep. of Tanzania": "4550",
    "Off of Global Insight & Policy": "456R",
    "Venezuela": "4710",
    "Bulgaria": "0570",
    "Executive Director's Office": "456B",
    "Croatia": "1030",
    "Belize": "6110",
    "Eswatini": "4030",
    "Azerbaijan": "0310",
    "Sierra Leone": "3900",
    "Switzerland": "5750",
    "Cambodia": "0660",
    "Mali": "2760",
    "Sri Lanka": "0780",
    "Romania": "3660",
    "Benin": "1170",
    "Georgia": "1600",
    "ROSA, Nepal": "297R",
    "Info & Comm Technology Div": "456L",
    "Oman": "6350",
    "Guinea Bissau": "6850",
    "Argentina": "0240",
    "Madagascar": "2670",
    "Office of Global Innovation": "240B",
    "Jordan": "2340",
    "Rwanda": "3750",
    "Central African Republic": "0750",
    "Lesotho": "2520",
    "Sao Tome & Principe": "6830",
    "Senegal": "3810",
    "ECARO, Switzerland": "575R",
    "Egypt": "4500",
    "Niger": "3180",
    "Somalia": "3920",
    "Nigeria": "3210",
    "Field Sup & Coordination Off": "456P",
    "Office of Research, Italy": "2220",
    "Zimbabwe": "6260",
    "Chile": "0840",
    "Malawi": "2690",
    "Botswana": "0520",
    "Eritrea": "1420",
    "Lao People's Dem Rep.": "2460",
    "Belarus": "0630",
    "Republic of Cameroon": "0690",
    "Namibia": "6980",
    "Moldova": "5640",
    "Iraq": "2130",
    "Office of Emergency Prog.": "456F",
    "Iran": "2100",
    "Papua New Guinea": "6490",
    "Maldives": "2740",
    "Burundi": "0610",
    "Panama": "3330",
    "China": "0860",
    "Mexico": "2850",
    "Vietnam": "5200",
    "Turkmenistan": "4360",
    "ESARO, Kenya": "240R",
    "Equatorial Guinea": "1390",
    "Indonesia": "2070",
    "Procurement Services": "120X",
    "India": "2040",
    "Czech Republic": "BOCZ",
    "Colombia": "0930",
    "Mauritania": "2820",
    "Bhutan": "0490",
    "Comoros": "6620",
    "Global Shared Services Centre": "1950",
    "Ethiopia": "1410",
    "Int. Audit & Invest (OIAI)": "456N",
    "Programme Division": "456D",
    "Gov. & Multilateral Affairs": "456H",
    "WCARO, Senegal": "381R",
    "Brazil": "0540",
    "DP Republic of Korea": "5150",
    "Pakistan": "3300",
    "MENA, Jordan": "234R",
    "Bangladesh": "5070",
    "Div. of Finance & Admin Mgmt": "456J",
    "Cabo Verde": "6820",
    "Jamaica": "2280",
    "Cuba": "1050",
    "Afghanistan": "0060",
    "Haiti": "1830",
    "Gambia": "1560",
    "UNICEF Hosted Funds": "456T",
    "Djibouti": "6690",
    "Tunisia": "4320",
    "South Africa": "3930",
    "Togo": "4230",
    "South Sudan": "4040",
    "Peru": "3390",
    "Bolivia": "0510",
    "Guyana": "1800",
    "Myanmar": "0600",
    "Uganda": "4380",
    "Honduras": "1860",
    "Fiji (Pacific Islands)": "1430",
    "Libya": "2580",
    "Global": "GLOBAL",
    "Palestine, State of": "7050",
    "North Macedonia": "2660",
    "Ghana": "1620",
    "Serbia": "8970",
    "Geneva Common Services": "575C",
    "Algeria": "0120",
    "Republic of Kyrgyzstan": "2450",
    "Bosnia and Herzegovina": "0530",
    "Congo": "3380",
    "Philippines": "3420",
    "Burkina Faso": "4590",
    "Russia": "3700",
    "Guatemala": "1680",
    "Uruguay": "4620",
}


CURRENCIES = [
    ("AED", "United Arab Emirates dirham", False),
    ("AFN", "Afghan afghani", False),
    ("ALL", "Albanian lek", False),
    ("AMD", "Armenian dram", False),
    ("ANG", "Netherlands Antillean guilder", False),
    ("AOA", "Angolan kwanza", False),
    ("ARS", "Argentine peso", False),
    ("AUD", "Australian dollar", False),
    ("AWG", "Aruban florin", False),
    ("AZN", "Azerbaijani manat", False),
    ("BAM", "Bosnia and Herzegovina convertible mark", False),
    ("BBD", "Barbados dollar", False),
    ("BDT", "Bangladeshi taka", False),
    ("BGN", "Bulgarian lev", False),
    ("BHD", "Bahraini dinar", False),
    ("BIF", "Burundian franc", False),
    ("BMD", "Bermudian dollar", False),
    ("BND", "Brunei dollar", False),
    ("BOB", "Boliviano", False),
    ("BOV", "Bolivian Mvdol (funds code)", False),
    ("BRL", "Brazilian real", False),
    ("BSD", "Bahamian dollar", False),
    ("BTN", "Bhutanese ngultrum", False),
    ("BWP", "Botswana pula", False),
    ("BYN", "Belarusian ruble", False),
    ("BZD", "Belize dollar", False),
    ("CAD", "Canadian dollar", False),
    ("CDF", "Congolese franc", False),
    ("CHF", "Swiss franc", False),
    ("CLP", "Chilean peso", False),
    ("CNY", "Chinese yuan", False),
    ("COP", "Colombian peso", False),
    ("CRC", "Costa Rican colon", False),
    ("CUC", "Cuban convertible peso", False),
    ("CUP", "Cuban peso", False),
    ("CVE", "Cape Verdean escudo", False),
    ("CZK", "Czech koruna", False),
    ("DJF", "Djiboutian franc", False),
    ("DKK", "Danish krone", False),
    ("DOP", "Dominican peso", False),
    ("DZD", "Algerian dinar", False),
    ("EGP", "Egyptian pound", False),
    ("ERN", "Eritrean nakfa", False),
    ("ETB", "Ethiopian birr", False),
    ("EUR", "Euro", False),
    ("FJD", "Fiji dollar", False),
    ("FKP", "Falkland Islands pound", False),
    ("GBP", "Pound sterling", False),
    ("GEL", "Georgian lari", False),
    ("GHS", "Ghanaian cedi", False),
    ("GIP", "Gibraltar pound", False),
    ("GMD", "Gambian dalasi", False),
    ("GNF", "Guinean franc", False),
    ("GTQ", "Guatemalan quetzal", False),
    ("GYD", "Guyanese dollar", False),
    ("HKD", "Hong Kong dollar", False),
    ("HNL", "Honduran lempira", False),
    ("HRK", "Croatian kuna", False),
    ("HTG", "Haitian gourde", False),
    ("HUF", "Hungarian forint", False),
    ("IDR", "Indonesian rupiah", False),
    ("ILS", "Israeli new shekel", False),
    ("INR", "Indian rupee", False),
    ("IQD", "Iraqi dinar", False),
    ("IRR", "Iranian rial", False),
    ("ISK", "Icelandic króna", False),
    ("JMD", "Jamaican dollar", False),
    ("JOD", "Jordanian dinar", False),
    ("JPY", "Japanese yen", False),
    ("KES", "Kenyan shilling", False),
    ("KGS", "Kyrgyzstani som", False),
    ("KHR", "Cambodian riel", False),
    ("KMF", "Comoro franc", False),
    ("KPW", "North Korean won", False),
    ("KRW", "South Korean won", False),
    ("KWD", "Kuwaiti dinar", False),
    ("KYD", "Cayman Islands dollar", False),
    ("KZT", "Kazakhstani tenge", False),
    ("LAK", "Lao kip", False),
    ("LBP", "Lebanese pound", False),
    ("LKR", "Sri Lankan rupee", False),
    ("LRD", "Liberian dollar", False),
    ("LSL", "Lesotho loti", False),
    ("LYD", "Libyan dinar", False),
    ("MAD", "Moroccan dirham", False),
    ("MDL", "Moldovan leu", False),
    ("MGA", "Malagasy ariary", False),
    ("MKD", "Macedonian denar", False),
    ("MMK", "Myanmar kyat", False),
    ("MNT", "Mongolian tögrög", False),
    ("MOP", "Macanese pataca", False),
    ("MRU", "Mauritanian ouguiya", False),
    ("MUR", "Mauritian rupee", False),
    ("MVR", "Maldivian rufiyaa", False),
    ("MWK", "Malawian kwacha", False),
    ("MXN", "Mexican peso", False),
    ("MYR", "Malaysian ringgit", False),
    ("MZN", "Mozambican metical", False),
    ("NAD", "Namibian dollar", False),
    ("NGN", "Nigerian naira", False),
    ("NIO", "Nicaraguan córdoba", False),
    ("NOK", "Norwegian krone", False),
    ("NPR", "Nepalese rupee", False),
    ("NZD", "New Zealand dollar", False),
    ("OMR", "Omani rial", False),
    ("PAB", "Panamanian balboa", False),
    ("PEN", "Peruvian sol", False),
    ("PGK", "Papua New Guinean kina", False),
    ("PHP", "Philippine peso", False),
    ("PKR", "Pakistani rupee", False),
    ("PLN", "Polish złoty", False),
    ("PYG", "Paraguayan guaraní", False),
    ("QAR", "Qatari riyal", False),
    ("RON", "Romanian leu", False),
    ("RSD", "Serbian dinar", False),
    ("RUB", "Russian ruble", False),
    ("RWF", "Rwandan franc", False),
    ("SAR", "Saudi riyal", False),
    ("SBD", "Solomon Islands dollar", False),
    ("SCR", "Seychelles rupee", False),
    ("SDG", "Sudanese pound", False),
    ("SEK", "Swedish krona/kronor", False),
    ("SGD", "Singapore dollar", False),
    ("SHP", "Saint Helena pound", False),
    ("SLE", "Sierra Leonean leone", False),
    ("SOS", "Somali shilling", False),
    ("SRD", "Surinamese dollar", False),
    ("SSP", "South Sudanese pound", False),
    ("STN", "São Tomé and Príncipe dobra", False),
    ("SVC", "Salvadoran colón", False),
    ("SYP", "Syrian pound Old", False),
    ("SYP01", "Syrian pound", False),
    ("SZL", "Swazi lilangeni", False),
    ("THB", "Thai baht", False),
    ("TJS", "Tajikistani somoni", False),
    ("TMT", "Turkmenistan manat", False),
    ("TND", "Tunisian dinar", False),
    ("TOP", "Tongan paʻanga", False),
    ("TRY", "Turkish lira", False),
    ("TTD", "Trinidad and Tobago dollar", False),
    ("TWD", "New Taiwan dollar", False),
    ("TZS", "Tanzanian shilling", False),
    ("UAH", "Ukrainian hryvnia", False),
    ("UGX", "Ugandan shilling", False),
    ("USD", "United States dollar", False),
    ("USDC", "USD Coin", True),
    ("UYU", "Uruguayan peso", False),
    ("UYW", "Unidad previsional[14]", False),
    ("UZS", "Uzbekistan som", False),
    ("VES", "Venezuelan bolívar soberano", False),
    ("VND", "Vietnamese đồng", False),
    ("VUV", "Vanuatu vatu", False),
    ("WST", "Samoan tala", False),
    ("XAF", "CFA franc BEAC", False),
    ("XAG", "Silver (one troy ounce)", False),
    ("XAU", "Gold (one troy ounce)", False),
    ("XCD", "East Caribbean dollar", False),
    ("XOF", "CFA franc BCEAO", False),
    ("XPF", "CFP franc (franc Pacifique)", False),
    ("YER", "Yemeni rial", False),
    ("ZAR", "South African rand", False),
    ("ZMW", "Zambian kwacha", False),
    ("ZWL", "Zimbabwean dollar", False),
]


def generate_country_codes() -> None:
    for country in Country.objects.all():
        CountryCodeMap.objects.get_or_create(country=country, defaults={"ca_code": country.iso_code3})


def generate_business_areas() -> None:
    for country_name, ba_code in business_area_short_name_code_map.items():
        if country := Country.objects.filter(short_name=country_name).first():
            business_area, _ = BusinessArea.objects.get_or_create(
                code=ba_code,
                defaults={
                    "name": country.short_name,
                    "long_name": country.name,
                    "region_code": country.iso_num,
                    "region_name": country.iso_code3,
                    "has_data_sharing_agreement": True,
                    "active": True,
                    "is_accountability_applicable": True,
                },
            )
            business_area.countries.add(country)

    # create Global
    BusinessArea.objects.get_or_create(
        code="GLOBAL",
        defaults={
            "name": "Global",
            "long_name": "Global Business Area",
            "region_code": "GLOBAL",
            "region_name": "GLOBAL",
            "has_data_sharing_agreement": True,
        },
    )


def generate_data_collecting_types() -> None:
    all_ba_id_list = BusinessArea.objects.all().values_list("id", flat=True)
    data_collecting_types = [
        {
            "label": "Partial",
            "code": "partial_individuals",
            "description": "Partial individuals collected",
            "type": DataCollectingType.Type.SOCIAL.value,
        },
        {
            "label": "Full",
            "code": "full_collection",
            "description": "Full individual collected",
            "type": DataCollectingType.Type.STANDARD.value,
        },
        {
            "label": "Size only",
            "code": "size_only",
            "description": "Size only collected",
            "type": DataCollectingType.Type.STANDARD.value,
        },
        {
            "label": "size/age/gender disaggregated",
            "code": "size_age_gender_disaggregated",
            "description": "No individual data",
            "type": DataCollectingType.Type.SOCIAL.value,
        },
    ]

    for data_dict in data_collecting_types:
        dct = DataCollectingTypeFactory(
            label=data_dict["label"],
            code=data_dict["code"],
            type=data_dict["type"],
            household_filters_available=bool(data_dict["type"] == DataCollectingType.Type.STANDARD.value),
        )
        dct.limit_to.add(*all_ba_id_list)


def generate_currencies() -> None:
    currencies = [
        Currency(code=code, vision_code=code, name=name, is_crypto=is_crypto) for code, name, is_crypto in CURRENCIES
    ]
    Currency.objects.bulk_create(currencies)
