# Generated by Django 3.2.25 on 2025-01-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardreport',
            name='year',
            field=models.PositiveSmallIntegerField(default=2025),
        ),
    ]
